### ISSUE TITLE
Problem z cda.pl

### ISSUE THREAD

**Issue by mrknow** [mrknow/filmkodi#1]
Witam mam takie pytanko czy jest taka mozliwosc zeby poprwaic dzialanie cda.pl w mr know moj problem polega na tym ze nie moge przejsc do nastepnej strony w zakladce filmy najnowsze
Generalnie cda.pl to jedna z najlepszych stron tylko ludzie wrzucaja duzo smieci i jak sie chce obejrzec jakis film to ciezko cos znalezc bo pelno bzdur i seriali kiedys bylo swietnie bo mozna bylo przezucac strony i wybor byl wiekszy natomiat teraz jak wrzuca 20 seriali to lipa
moze mozna by bylo wstawic ustawienia tak jak na stronie zeby pomijac filmy krotsze niz 60 minut.
Serdecznie pozdrawiam i mam na dzieje ze nie truje moimi sugestjami.

**Comment by xxcriticxx** [comment]
proponuje zrobienia plugin do freedisc.pl jest hyba lepsza niz cda.pl

**Comment by xxcriticxx** [comment]
tutaj jest exemplarz najnowszej wtyczki

Repozytorium wtyczek Phantom-a, zawiera obsługę serwisu cda.pl

http://mods-kodi.pl/viewpage.php?page_id=53

**Comment by xxcriticxx** [comment]
tutaj jest dobry program do cda.pl

http://cdax.pl/

O aplikacji
CDAx to aplikacja pozwalająca na dostęp do tysięcy darmowych filmów znajdujących się w zasobach portalu cda.pl.
Email: cdax.pl@gmail.com

**Comment by mrknow** [comment]
Poprawiłem przed chwilą wtyczkę. Serwis cda.pl - powinien już działać prawidłowo
