### ISSUE TITLE
alltube seriale

### ISSUE THREAD

**Issue by xxcriticxx** [mrknow/filmkodi#101]
cos sie hyba pozmienialao z openload.co zadne odcinki nie startuja

**Comment by mrknow** [comment]
potrzebuję około 3 godzin aby to poprawić. Dzisiaj wrzuce poprawkę

**Comment by mrknow** [comment]
ok openload działa już na mojej wersji developerskiej, teraz sprawdze pozostałe serwisy ...

**Comment by mrknow** [comment]
Nowa wersja juz na serwerach. Poprawiłem działanie openload
