### ISSUE TITLE
poprawki do tv 

### ISSUE THREAD

**Issue by xxcriticxx** [mrknow/filmkodi#102]
NO STREAMS AVAILABLE

**Comment by mrknow** [comment]
ale gdzie? cda i openload ?

**Comment by mrknow** [comment]
Jest w tytule że TV. OK, zaraz zacznę weryfikację  ....

**Comment by xxcriticxx** [comment]
iklub i typer napewno wszystko dziala przez strone ale nie dziala przez plugin

**Comment by plumers** [comment]
nie ma looknijTV - możesz dać mojefilmy-tk z opcją rejestracji i premium users ... 
DZIAŁA:
Telewizjada 
Typer
Iklub
reszta portali wywala w/w problem ze źródłem,,,

pozdrawiam

**Comment by mrknow** [comment]
powinno być lepiej
