### ISSUE TITLE
TV and Movie sections not working..

### ISSUE THREAD

**Issue by dilldogs** [mrknow/filmkodi#103]
Ok, I went into spectro and clicked on movie the went to year. Clicked on all years and wont let me in. same with TV Shows. a Couple categories is working. but thats it... Just a heads up

**Comment by Beckles83** [comment]
Mine is doing the same. I did a fresh start and reinstalled my digiwizard thinking it was a glitch in my system. Sort of glad it's not just me, but not loving that I cannot search for anything anymore or browse years. Those are my two favorite ways to find movies. Help anyone?

**Comment by zurahk** [comment]
Agreed Same issue, Genre wont work, Years won't work.

**Comment by mrknow** [comment]
OK 
TMDB API Expired, Today I fix this issue. I need 3 hours

**Comment by N3tPirat3** [comment]
Hey mrknow, I just wanted to THANK YOU for working on this project and for your time and helping the users here with support! Your Specto project means the WORLD to me and many other users I'm certain! I just came in to see if the sections problem was just me or if others were having the same trouble. Thank you again for working on this project! Do you have a way to donate to your cause?

**Comment by bblankier** [comment]
Hell MrKnow. I wanted to thank you and your team for taking on this project and bringing Genesis back to life in the form of Specto. I updated to the latest version of Specto with the TMDB API  fix, but am still encountering the same issues with the categories as I did before. They cannot be accessed. Any suggestions?

**Comment by bblankier** [comment]
To be more specific, it's happening to categories under TV Shows such as Networks, Most Popular, Airing Today, and others relying on the TMDB API I believe.

**Comment by zurahk** [comment]
@bblankier yeah it happens under Movies as I believe. I haven't messed with it much since my earlier post. But thats the section i was under when making the list of what works.

**Comment by zurahk** [comment]
@bblankier So same issue that WAS (now working) happening with Movies is now happening with TV SHows

**Comment by mrknow** [comment]
TMDB API Expired, 
Fixed in 2015.02.17.2
