### ISSUE TITLE
Specto - categories dot showing up

### ISSUE THREAD

**Issue by azgal** [mrknow/filmkodi#109]
Hello,  

First off thank you Mr.Know for taking over "G", appreciate your work!
I installed Specto and it does come up however when I click movies and am taking to next page where the list starts with Genres, year, people and so on, when I click on Genres, people, certificates, featured, most popular, most voted, in theaters, or favorites, working comes up but then nothing happens, doesn't go to next page of that category like it use to.

I'm wondering if I did something wrong when I installed to make this happen?
I can get the year, people watching and latest pages to come up but none of the others.

I think I read in another post that someone said they installed the plugin as well, I'm not sure if I installed plugin, I followed instructions and don't remember anything being said about a plugin.

Look forward to hearing back and hopefully helping to figure out what's wrong.

Thanks,
KD

**Comment by mrknow** [comment]
in a few hours try to install new version. My tmdb api was revoked.

**Comment by azgal** [comment]
I think it's downloading now but if this download doesn't work I'll try 
later.

Thank you so much, I'm new to this and learning as I go and you've been 
a blessing!

Thanks,
Kelly

**Comment by mrknow** [comment]
Today I installed openelec on ​​my old laptop , and for me there was no problem
OK, please give me more info
1. witch version ov kodi do you have
2. witch version of add-on
3. Do you you set English as regional settings in kodi ?

**Comment by mrknow** [comment]
can you send me error logs ? Here you have instructions http://kodi.wiki/view/Log_file/Easy

**Comment by mrknow** [comment]
Now problem is solved
