### ISSUE TITLE
Problem z mrknow - nie działa

### ISSUE THREAD

**Issue by marsik2008** [mrknow/filmkodi#11]
Witam, mam problem z wtyczką MrKnow, od paru dni nie działa po aktualizacji próbowałem się z tym ''bawić'' ale nic z tego... w czym problem, pomoże mi ktoś?
http://i.imgur.com/IqIFpOI.png

**Comment by adaski8** [comment]
https://github.com/mrknow/filmkodi/issues/5

**Comment by ip5d** [comment]
```
sdcard/android/data/org.xbmc.kodi/files/.kodi/addons/script.module.xbmcfilm/lib/
```
zmienic nazwe *parser.py* na *parser.py.***bak** 

oraz  

*parser.pyo* na *parser.pyo.***bak**

**Comment by marsik2008** [comment]
Trzeba mieć root? Czy można te nazwy zmienić tym: Total Commander

**Comment by Jan111** [comment]
chcę się połączyć programem FlashFXP ale nie daję rady, umie ktoś mi pomóc albo potrzebuję inny program ?

**Comment by marsik2008** [comment]
ip5d Dzięki wielkie. Wzystko dziala po zmianie tych nazw !! :)

**Comment by mrknow** [comment]
Mam nadzieje że ostatecznie poprawione w wersji 2016.01.03. w razie co prześlij logi za (tu instrukcja https://github.com/mrknow/filmkodi/wiki/Jak-przes%C5%82a%C4%87-logi-z-kodi)
