### ISSUE TITLE
Stworzenie wtyczki z mojej kolekcji filmów na cda.pl

### ISSUE THREAD

**Issue by Seico** [mrknow/filmkodi#111]
Witam serdecznie
Mam pytanko , posiadam dość pokaźną kolekcje filmów HD (ok.1400 filmów (i cały czas rosnie) - 1080p- 720p- 3/4 z dzwiękiem 5,1 ukrytą na swoim koncie cda.pl premium , czy byłby ktoś w stanie stworzyć bezpieczną wtyczkę aby była ona dostępna w kodi dla "normalnych" użytkowników - tak aby mogli oni tylko oglądać filmy a nie mogli mieć dostepu do pliku źródłowego. Dodam ze każdy film ma swoją kopie i w razie czego jest możliwy szybki reupload.

**Comment by xxcriticxx** [comment]
super pomysl

moze bys zrobil kopie na freedisc.pl?

**Comment by mrknow** [comment]
Nie chciał bym robić nic niezgodnego z regulaminem cda.pl, a podejrzewam że to było by niezgodne i szybko by zbanowali twoje konto.

Wstępnie  mam 2 pomysły, ale nie wiem czy o to ci chodzi. 

**Pomysł nr 1** - Strona XBMCFILM obsługuje katalogi
    Publiczny - każdy może zobaczyć linki
    Hasło - potrzebujesz hasła aby podejrzeć linki.
    Prywatny - tylko ty możesz oglądać linki w katalogu
Dzięki temu wrzucając film do określonego katalogu użytkownicy mieli by dostęp do określonego filmu. Tutaj dodał bym logowanie dla kont premium i dzięki temu wszyscy którzy mają premium mogli by oglądać te filmy (tak przynajmniej mi się wydaje - musiał bym to sprawdzić)  

Pomysł nr 2 - wrzucasz filmy na openload.io - tu info https://openload.co/ nawet coś można zarobić https://openload.co/money i na xbmcfilm.com lub innej własnej strony

**Comment by mrknow** [comment]
Jeżeli moje pomysły są nie trafione - to resztę możemy omówić na wykopie napisz mi PW mój nick to mrknow

**Comment by Seico** [comment]
Poszło PW na wykopie
