### ISSUE TITLE
Solution to My Specto jpg not showing

### ISSUE THREAD

**Issue by bjgood** [mrknow/filmkodi#114]
Mr Know,
If you want the My Specto icon to show in Specto then change the name of resources>media>4orbs, g0ne, metro, etc>mygenesis.jpg to myspecto.jpg. Then the icon will show in the navigator. In resources>lib>indexers>navigator.py...line 83 points to myspecto.jpg yet that name doesn't exist in media themes.

Hope this helps.

Bob

**Comment by mrknow** [comment]
OK , thanks for the solution.
Today, I fix it and patch will be available in the next update .

**Comment by xxcriticxx** [comment]
@bjgood if you program we can use you here
