### ISSUE TITLE
dizilab i dizigold (gvideo)

### ISSUE THREAD

**Issue by macias1985gda** [mrknow/filmkodi#115]
po najnowszej aktualizacji, Specto nie znajduje stremow z dizilab i dizigold (gvideo), ale jak przeinstaluje wtyczke na wersje z 07.02.2016 wydaje sie byc wszystko w porzadku

**Comment by mrknow** [comment]
Dzięki za info - dzisiaj późnym wieczorem to sprawdzę

**Comment by macias1985gda** [comment]
a nie ma za co :), a tak przy okazji to chyba tez cos jest nie tak watch1080p, ale jesli dobrze widzialem to ten problem jest Ci znany i nad nim pracujesz ?

**Comment by mrknow** [comment]
Watch1080p kryje się za cloudflare (cache i anty ddos - wykrywa nie człowieka). W teorii już wiem jak to obejść, ale do tej pory po 2 dniach sie poddałem. Na razie dodam łatwiejsze serwisy, nastepnie real debrid a później wracam do watch1080p

**Comment by mrknow** [comment]
Już mi działa Watch1080 :) Ciężko było ale się udało. Pozostałe 2 serwisy do zrobienia

**Comment by macias1985gda** [comment]
widze, ze dzisiaj bylo pare aktualizacji, ale chyba zadna nie poprawiala tego problemu z w/w serwisami ? :)

**Comment by mrknow** [comment]
Zrobione
