### ISSUE TITLE
wtyczke do dropbox/google drive/one drive

### ISSUE THREAD

**Issue by xxcriticxx** [mrknow/filmkodi#118]
mr know prosba czy da rade wykonac jakies polonczenia wtyczki do could drives tak zeby oglodac tam dane materialy filmy, zdjecia, muzyka?

**Comment by mrknow** [comment]
Jasne, po to stworzyłem stronę http://xbmcfilm.com/ aby właśnie na niej wstawiać linki do swoich materiałóœ na zasobach w chmurze. Czy o to ci chodzi ?

**Comment by mrknow** [comment]
Zbyt skomplikowane
