### ISSUE TITLE
wtyczke do auto sciagania subs

### ISSUE THREAD

**Issue by xxcriticxx** [mrknow/filmkodi#119]
jest taki pomysl

**Comment by mrknow** [comment]
Moja wtyczka specto to potrafi. 
Gdzie byś chciał mieć mozliwość ściągania subów ?

**Comment by xxcriticxx** [comment]
seriale/filmy

**Comment by mrknow** [comment]
Będzie taka wtyczka, na razie się nazywa "specto po polsku" i tam będziesz miał takie opcje jak ściąganie subów
