### ISSUE TITLE
Nowe portale i porzadek

### ISSUE THREAD

**Issue by plumers** [mrknow/filmkodi#12]
A moja propozycja to:
1-zobacz-tv.eu
2-screen-tv.eu
3-typerTv
4.looknijtv
5.Vidtv.pl
6-Cinema-tv.eu
7-darmowe.tv

poza tym --- Mr --- wywalić stare nazwy które już nie istnieją - wiele linków sie powiela np filmob premium 2 razy w nazwie i żaden nie działa link :) 

 no i poprawić ścieżkę w nazwie do UPDATE pliku librt w xmbc na kodi .. i będzie się aktualizowało ładnie :) 

RESPECT za dobrą robotę :)

**Comment by xxcriticxx** [comment]
dodac jeszcze freedisc.pl i bendzie super

**Comment by ip5d** [comment]
https://github.com/mrknow/filmkodi/issues/16#issuecomment-162817884

**Comment by mrknow** [comment]
To mamy już zrobione:
1-zobacz-tv.eu
2-screen-tv.eu
3-typerTv
5.Vidtv.pl
7-darmowe.tv

Pozostało 
1. freedisc.pl
4.looknijtv
6-Cinema-tv.eu

**Comment by plumers** [comment]
super :)

Eleven i Eleven sports dodałeś do ukrytych - programy dla dorosłych - nie widać tych kanałów domyślnie dopiero po wł w/w opcji :P 

vidtv nie prądzi a screen no stream - ale o tym pisałeś chyba zmienili adres ...jeśli chodzi o aktualizację librt to na androidzie dalej jest xmbc a nie kodi w ścieżce podane :) 

dodaj ipla tak jak tvn jest i bedzie juz miodzio

 dobra robota pozdrawiam

**Comment by WerVa** [comment]
Jest możliwość dodania tego serwisu? 
southparksite.pl

**Comment by plumers** [comment]
Hej hej MrKnow - ostatnio trochę posypało się stronek z linkami - typer screen i inne po prostu padły oraz zmieniają podobno PLAYERY na stronach ... cinema zmienia adres vidtv na vidco.tv jedynie darmowe tv jeszcze się jakoś trzyma :)

Ludzie info do was - jeżeli jeden portal padnie i nie działa dłużej niż kilka dni ,to wtedy się trzeba grzecznie zapytać - a WY myślicie ,że autor nic nie robi poza siedzeniem przed kompem i dodawaniem na nowe linków etc etc - (wspomniał ,ze ma czas weekend tylko ) dajcie mu żyć :)

Jeżeli znajdziesz czas na spokojnie zrób mały porządek z serwisami - wywal te co nie działają już i będzie git :) no librt xmbc zmieniamy na kodi :) dla androida ofc bo winda ładnie się aktualizuje :D

**Comment by xxcriticxx** [comment]
http://pure-cast.net/kanaly-online
https://videostar.pl/
http://cyberms.pl/onlinetv/

**Comment by plumers** [comment]
Wtyczka jednego kolesia poszla na wykop i ... sie zesralo he he ... Mr looknij tv nie ma a fajne bylo bo smigalo :( reszta portali now is offline :( pozdro

**Comment by xxcriticxx** [comment]
www.moje-filmy.tk
http://zalukaj.top/

**Comment by plumers** [comment]
http://screen-tv.eu/ już działa na www inny player FLOW mają itp :)

Proponuje zrobić tak :) 

1-TELEWIZJADA
2-screen-tv.eu
3-Filmbox
4-Looknij.tv
5-Darmowe.tv
6-http://www.typertv.com.pl/
7-iklub

potem jak uważasz :) vid wywal,bo i tak przy odtwarzaniu na Windows eset wychwytuje trojany ...poza tym oni tylko podlikowywują się do innych stron - takie pijaweczki :)

jak znajdziesz czas to coś dodaj do serwisu meczyki mecze jakieś inne portale z transmisjami live przydają się wtedy ,gdy na ogólnych jest przeciążenie :)

Miłego weekendu i pozdro :D

**Comment by mrknow** [comment]
dodane wszystko z tego:
www.moje-filmy.tk - mają własną wtyczkę nie zamierzam tworzyć mojej bez ich akceptacji
