### ISSUE TITLE
Film kodi

### ISSUE THREAD

**Issue by borys76** [mrknow/filmkodi#123]
Niedziala wtyczka film-kodi dzisiaj?
byl jakis update?

**Comment by xxcriticxx** [comment]
ver 2016.02.21.4 tez mi cos nie odpala

**Comment by borys76** [comment]
Aha czyli narazie nic nierobie, pewnie prace trwaja

**Comment by karnage11** [comment]
i am only on version 2016.02.20.2 on my firestick

**Comment by mrknow** [comment]
Grrr - się wizieło mi gr#@#*&($..

**Comment by karnage11** [comment]
what happened ?

**Comment by xxcriticxx** [comment]
@mrknow podaj linka na github po server hyba dead

**Comment by karnage11** [comment]
when is the new update for real-debrid ? :D

**Comment by mrknow** [comment]
W teorii powinno działać, w razie  zainstaluj aktualizacje i sprawdź czy działa. Napisz czy jest OK

**Comment by karnage11** [comment]
i need the update please

**Comment by xxcriticxx** [comment]
openelec 6.0

Filmy Online - mrknow.pl

add-on is incompatible due to unmet dependencies.
would you like to disable it on your system?

**Comment by xxcriticxx** [comment]
z servera update fail 

za 3 razem cos poszlo

**Comment by mrknow** [comment]
OK 
[plugin.video.specto-2016.02.21.1.zip](https://github.com/mrknow/filmkodi/files/139428/plugin.video.specto-2016.02.21.1.zip)

**Comment by karnage11** [comment]
Specto is updating for now , is that the real-debrid fix ? .. and what else is the update for MrKnow?

**Comment by mrknow** [comment]
No real-debrid is no working yet

**Comment by karnage11** [comment]
ahh ok

**Comment by karnage11** [comment]
whats this update for ?

**Comment by karnage11** [comment]
ah stuck at 61%

**Comment by mrknow** [comment]
Accidentally let go update, and 
I do not know what works and what does not work.

**Comment by xxcriticxx** [comment]
sciagnal mi sie respitorium ale wtyczki niema

**Comment by karnage11** [comment]
alright i will let you know , if i can update it

**Comment by xxcriticxx** [comment]
resptorium puste na win7

**Comment by karnage11** [comment]
update failed atm

**Comment by mrknow** [comment]
@xxcriticxx - repozytorium jest puste, bo przekroczone są limity na serwerach. Aby nie zabić serwerów ustawiłem po 2000 połączeń per serwer (a mam ich 4)

**Comment by karnage11** [comment]
ahh alright

**Comment by xxcriticxx** [comment]
wrzuc na github please

**Comment by karnage11** [comment]
hey Mrknow , have you worked on fixing no no source or wrong movie source yet or not yet ?

**Comment by xxcriticxx** [comment]
karnage11 please give us sec here

**Comment by karnage11** [comment]
alright , sorry

**Comment by mrknow** [comment]
@karnage11 - Can you send the film - to show what exactly is the problem. Tomorrow

**Comment by karnage11** [comment]
thats fine , yea anyway to contact you faster at all ?

**Comment by mrknow** [comment]
@karnage11 - i need to see this problem. It would be easier for me to solve it

**Comment by karnage11** [comment]
i understand , thats fine with me

**Comment by mrknow** [comment]
OK , I'll try to fix this problem with " wrong movie error"  tomorrow if I could.

**Comment by karnage11** [comment]
alright , but anyway to contact you faster , so if i find any other problems i can tell you right away?

**Comment by karnage11** [comment]
by the way your doing an awesome job with this addon , Thanks alot

**Comment by niapia95** [comment]
Hey mrknow don't mean to bug but I downloaded the Specto Genesis fork and I get an error when trying to play any movie, it says error check log for information... No idea how to fix that

**Comment by mrknow** [comment]
Install this 
[plugin.video.specto-2016.02.21.1.zip](https://github.com/mrknow/filmkodi/files/139428/plugin.video.specto-2016.02.21.1.zip)

**Comment by xxcriticxx** [comment]
there is problem with the server right now mrknow trying to fix right now by posting files on github

**Comment by niapia95** [comment]
Ahhh is that installing through a pc?

**Comment by xxcriticxx** [comment]
all version are down right now

**Comment by niapia95** [comment]
I installed zip directly thru the Firestick. I tried installing that last week I believe when I seen you post it on a different post but not so computer literate lol

**Comment by karnage11** [comment]
@niapia95 give it time , the servers are prob overloaded atm

**Comment by niapia95** [comment]
Alright I'll just wait until tomorrow

**Comment by niapia95** [comment]
And keep my eyes on github lol

**Comment by karnage11** [comment]
yea let it clam down alittle

**Comment by xxcriticxx** [comment]
use the link above and report if it works or not

**Comment by karnage11** [comment]
i got up to 67% right now

**Comment by niapia95** [comment]
I don't know how to install through a zip on a Mac

**Comment by karnage11** [comment]
moving slowly but looks like it is working , i am updating it from the repo on my firestick

**Comment by niapia95** [comment]
Sadly everyone on YouTube posts installs directly through Firestick lol :-(

**Comment by mrknow** [comment]
@niapia95 - Check this http://kodi.wiki/view/HOW-TO:Install_add-ons_from_zip_files

**Comment by xxcriticxx** [comment]
system > settings > add-ons > install from zip file

**Comment by mrknow** [comment]
@xxcriticxx - napisz do mnie maila na mrknow@interia.pl
Chciał bym pogadac o współpracy

**Comment by niapia95** [comment]
@mrknow I already installed from zip then installed from repo but movies won't play they all say check the log for more information. It's no biggie I'll wait and see what's going on with it tomorrow

**Comment by karnage11** [comment]
@niapia95 maybe i can help here is my chat http://chatwing.com/Karnage11

**Comment by xxcriticxx** [comment]
pisalem kilka razy zobacz w spam folder

**Comment by niapia95** [comment]
Let me pull out my laptop give me a sec @karnage11

**Comment by xxcriticxx** [comment]
niapia95 restart your stick

**Comment by karnage11** [comment]
@xxcriticxx hey , i use a chat room to try to help them out alittle if no one can get them on on here right away

**Comment by xxcriticxx** [comment]
@mrknow xxcritic2001xx[małpa]hotmail.com

**Comment by karnage11** [comment]
@niapia95 alright

**Comment by borys76** [comment]
Mrknow dalej niedziala film kodi

**Comment by xxcriticxx** [comment]
borys76 czekamy na files

**Comment by bjgood** [comment]
mrknow or xxcriticxx,
What does this update fix? Specto has been running fine for me all day.

Bob

**Comment by borys76** [comment]
@xxcriticxx 
Dzieki

**Comment by xxcriticxx** [comment]
ask mrknow he's the author

borys76 co nowego na mods-kodi i na sd-xbmc widze ze sie uczeszczasz tam jak w kosciele

**Comment by karnage11** [comment]
@xxcriticxx Mrknow is in my chat room but quiet lol

**Comment by karnage11** [comment]
@xxcriticxx Join if you like

**Comment by xxcriticxx** [comment]
on my way

**Comment by bjgood** [comment]
mrknow,
What does this update fix? Specto has been running fine for me all day.

Bob

**Comment by karnage11** [comment]
@xxcriticxx joining :D

**Comment by karnage11** [comment]
@xxcriticxx you get lost ?

**Comment by borys76** [comment]
@xxcriticxx :)

**Comment by karnage11** [comment]
@mrknow you let :(

**Comment by xxcriticxx** [comment]
borys zapraszam wiecej na github

**Comment by borys76** [comment]
bede czesciej zagladal

**Comment by xxcriticxx** [comment]
@borys76 moze cos modrego doradzisz 

moze jakos liste kanalow masz

**Comment by borys76** [comment]
Teraz jak dziala telewizjada to nawet niewyciagam zadnych adresow

**Comment by xxcriticxx** [comment]
moze jakies private iks server?

**Comment by mrknow** [comment]
Obecnie dzienny ruch tylko do repo z addonami to ok 3 TB jak jest aktualizacja.

**Comment by karnage11** [comment]
Mrknow add me on skype if you want to chat Karnage11

**Comment by mrknow** [comment]
więc jeżeli będę miał serwer z łączem 1 GB brak limitów na ruch - to powinno wystarczyć 
Musze poszukac. Jeżeli o inne parametry - to 1 prcek 1 GB ram i 10 GB dysk - wystarczy

**Comment by karnage11** [comment]
@mrknow  i can always help on your website , if no one is around

**Comment by xxcriticxx** [comment]
na stronie ktos pisal ze ma miesce

**Comment by mrknow** [comment]
A faktycznie - tylko wtedy nie wiedziałem czego potrzebuję

**Comment by mrknow** [comment]
@karnage11 - Tomorrow I'll talk to you

**Comment by karnage11** [comment]
@mrknow alright sounds good if you have skype add me

**Comment by xxcriticxx** [comment]
z checia udostepnie Ci miejsce na serwerze a takze stworze uzytkownika dla Ciebie abys mogl cieszyc sie wydajnoscia ktora uciagnie nawet i kilka milionow polaczen jednoczesnie , oczywiscie wszystko w podziekowaniu za prace ktora wkladasz w swoj projekt.

skontaktuj sie ze mna to poradzimy cos na ten problem

**Comment by mrknow** [comment]
Dobranoc ... Good night ....

**Comment by mrknow** [comment]
Jutro

**Comment by karnage11** [comment]
alright Night

**Comment by borys76** [comment]
Night everybody

**Comment by Darrius87** [comment]
No i dramat... Nie działa. Wina  aktualizacji kodi? Jeszcze rano działało

**Comment by krzjel** [comment]
Do ok. godz. 10 jeszcze oglądałem coś przez wtyczkę. Zobaczyłem że wykonała się aktualizacja i po ponownym uruchomieniu już nie działa.

**Comment by krzjel** [comment]
Logi wyjątków:
10:53:04 T:1952   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named mrknow_Player
                                            Traceback (most recent call last):
                                              File "C:\Users\Krzysiek\AppData\Roaming\Kodi\addons\plugin.video.mrknow\default.py", line 108, in <module>
                                                import wykop, joemonster, milanos,filmbox,vodpl, filmydokumentalne, zalukaj, efilmyseriale
                                              File "C:\Users\Krzysiek\AppData\Roaming\Kodi\addons\plugin.video.mrknow\host\filmydokumentalne.py", line 15, in <module>
                                                import mrknow_pLog, mrknow_pCommon, mrknow_Parser, mrknow_Player
                                            ImportError: No module named mrknow_Player
                                            -->End of Python script error report<--



10:53:11 T:4700   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named requests
                                            Traceback (most recent call last):
                                              File "C:\Users\Krzysiek\AppData\Roaming\Kodi\addons\plugin.video.mrknow\default.py", line 29, in <module>
                                                import common
                                              File "C:\Users\Krzysiek\AppData\Roaming\Kodi\addons\script.module.xbmcfilm\lib\common.py", line 118, in <module>
                                                from utils.webUtils import CachedWebRequest
                                              File "C:\Users\Krzysiek\AppData\Roaming\Kodi\addons\script.module.xbmcfilm\lib\utils\webUtils.py", line 7, in <module>
                                                import requests
                                            ImportError: No module named requests
                                            -->End of Python script error report<--
