### ISSUE TITLE
Problem z wtyczką mrknow w kodi tv box

### ISSUE THREAD

**Issue by Anna2584** [mrknow/filmkodi#124]
Witam
Posiadam tv box z systemem Android, kilka tygodni temu zainstalowałem wtyczkę mrknow w kodi do odbioru telewizjady, oglądania filmów w CDA, alletube i korzystania z innych serwisów, do dziś wszystko działało bezproblemowo, niestety dziś próbując uruchomić z wtyczek wideo mrknow.pl pokazuje mi się kółko z krzyżykiem w środku, na górze pojawia się literka B i komunikat źe "więcej informacji na ten temat znajdziesz w pliku dziennik" przypuszczam że chodzi o dziennik diagnostyczny, próbowałam już wszystkiego odinstalowywałam kodi i instalowałam ponownie wszystkie wtyczki, zresetowałam tv box do ustawień fabrycznych i od nowa wszystko instalowałam, ale bez żadnego rezultatu, komunikat nadal się pojawia i blokuje mi połączenie wtyczki z internetem. Bardzo proszę o pomoc bo wygląda to tak jakby mój adres IP został zablokowany gdzieś na serwerze. Posiadam też tablet z systemem Android ta sama wersja co na tv box 5.1 i tam wtyczka działa i wszystko się otwiera. Jeszcze raz bardzo proszę o radę jak mogę znów oglądać wszystko z kodi.

**Comment by mrknow** [comment]
Mam 7 serwerów z sieciówką  100 Mbit (taki tani hosting) i może tak być że przez około 2 godziny od aktualizacji może być problem z bieżącym pobraniem wtyczki. 
Ograniczyłem łączność do max 1200 aktywnych połączeń per serwer. Więc jeżeli w danym momencie jest więcej pobrać„ serwer odmawia połaszenia. 
 
Odczekaj max 2 godziny i spowrotem serwery będa działały normalnie
