### ISSUE TITLE
Filmy Online - mrknow.pl error

### ISSUE THREAD

**Issue by aente** [mrknow/filmkodi#125]
Witam
Dzisiaj postanowiłem spróbować z wtyczna mrknow.pl
Ale wyskakuje mi błąd, z tego co czytałem może być to związane z polskimi znakami w nazwie użytkownika lecz moja nazwa nie posiada takich.
 Zamieszczam logi 

http://xbmclogs.com/pttiupuo1

**Comment by mrknow** [comment]
Cześć - tak faktycznie był problem już go poprawiłem.Dzięki za informację

**Comment by mrknow** [comment]
Przepraszam za ten błąd, poważnie się wkurzyłem na siebie.. 
 
Następne aktualizację będą przeprowadzane w nowym modelu, aby tego typu sytuacja już się nie powtórzyła. 

Model jeszcze muszę opracować, ale następnym razem postaram się przeprowadzać aktualizację  według nastepującego scenariusza:
- testy nowej wersji w grup[ie testerów
- komunikacja o aktualizacji 
- aktualizacja

**Comment by aente** [comment]
Błąd występuje nadal 
http://xbmclogs.com/ppruuffbd

**Comment by mrknow** [comment]
Sprawdź czy masz wersję wtyczki 2016.02.21.7

**Comment by mrknow** [comment]
MOże za 3 godziny - bo serwery teraz zdychają

**Comment by zjac** [comment]
Skąd 2016.02.21.7, jak w repo jest 2016.02.21.4

**Comment by aente** [comment]
Dzięki za info, mam wersję 2016.02.21.4 Czyli tak jak pisałeś jeszcze nie ma jej prawdopodobnie na serwerach.
Jeszcze raz dzięki za pomoc

**Comment by mrknow** [comment]
Poniżej pliki dop ręcznej instalacji 

[plugin.video.mrknow-2016.02.21.7.zip](https://github.com/mrknow/filmkodi/files/139636/plugin.video.mrknow-2016.02.21.7.zip)
[script.module.xbmcfilm-2016.02.21.3.zip](https://github.com/mrknow/filmkodi/files/139637/script.module.xbmcfilm-2016.02.21.3.zip)

**Comment by zjac** [comment]
Dzięki ! Jak zwykle dobra robota.

**Comment by mrknow** [comment]
No nie bardzo z tymi aktualizacjami, ale będzie lepiej....

**Comment by aente** [comment]
Dzięki wszystko działa ! temat można zamknąć.

**Comment by aente** [comment]
script.module.xbmcfilm-2016.02.21.3.zip 
Script module posiada trojana.
https://www.virustotal.com/pl/file/741ecd364452ce26bfe344dea6d08b47c1a065f9e825fda4e1906f0dae535608/analysis/1456068189/

**Comment by mrknow** [comment]
Nie nie posiada trojana. To błedny test.

**Comment by mrknow** [comment]
Kurcze, sprawdzę jeszcze wszystkie serwery - może miałem włamanko a pliki są przechowywane na 7 maszynach, zaraz odpiszę
