### ISSUE TITLE
after installing 2.20.2 update of specto

### ISSUE THREAD

**Issue by fate8383** [mrknow/filmkodi#126]
I cannot play any movie as in when i click on a movie or tv show it says specto encountered an error please check log file. I can search movies/tv shows but cannot get to search sources, instantly i get an error log when i select a movie/tv show episode. MAC jarvis latest kodi (not beta version).

I have attached the log file screenshot if need be.

Thanks.
![screen shot 2016-02-21 at 2 17 09 pm](https://cloud.githubusercontent.com/assets/17381874/13202769/2464277a-d8a7-11e5-90a1-55c76003ad36.png)

**Comment by StopperN12** [comment]
same here. "specto-...fork error. please check log for details." after selecting any episode or movie.

**Comment by karnage11** [comment]
Uninstall specto , now after you do that go back to. Kodi main screen , hover over system - file manager - add sources - click on None and add this repo http://filmkodi.com/repository and name it Specto , after you add that , go back to kodi main screen and click on system - add-ons - install from Zip - Specto folder - Repository.filmkodi.com.zip , install it , then after that go to install from repository and you will see filmkodi.com-MRKNOW open it and go to video-addons , you should see Specto to install

**Comment by fate8383** [comment]
i had it installed like this from the first version of specto. anyway I did uninstall and reinstall from filmkodi repository...nothing changed. still getting the same error. thanks.

**Comment by karnage11** [comment]
Join The chat room , so we can talk about http://chatwing.com/Karnage11

**Comment by karnage11** [comment]
@StopperN12 Join my chat when you get a chance

**Comment by karnage11** [comment]
i will be back in about an hour and and half

**Comment by mrknow** [comment]
Please update specto to last version 2016.02.21.3.
10 minutes ago I added new servers so the update should go without problems

**Comment by karnage11** [comment]
hey mrknow

**Comment by tt1994** [comment]
I get the same error message for every show/movie but the latest update appearing 2.20.2
