### ISSUE TITLE
Being kicked out of Kodi when Lazy TV opens a Specto tv show

### ISSUE THREAD

**Issue by JohnathanGould** [mrknow/filmkodi#127]
I am at work and I am thinking back to what happened last night.

I remember messing with settings and think I turned one on that looks for Debrid first but I don't have debrid.

When I try to watch a show through LazyTV is it kicking me out of Kodi because it found no debrid sources and got confused?

I tried to watch something straight from the add-on and it did the same thing.

Is it possible something else is happening?

**Comment by karnage11** [comment]
Try redoing specto

**Comment by JohnathanGould** [comment]
Thanks karnage11... I reinstalled Specto but got the same results then reinstalled LazyTV and now its working fine.
