### ISSUE TITLE
MrKnow We need to talk - Don't Forget

### ISSUE THREAD

**Issue by karnage11** [mrknow/filmkodi#128]
Hey , don't forget to add me , so we can talk about it , Thank you

**Comment by mrknow** [comment]
@karnage11 - development  version. 

Because I do not have an account on a real - debrid , I can not see if it works correctly .
Go to settings-> SETTINGS[/B] : Accounts-> and Authorize your kodi. 


[plugin.video.specto-2016.02.22.0010.zip](https://github.com/mrknow/filmkodi/files/139997/plugin.video.specto-2016.02.22.0010.zip)

**Comment by karnage11** [comment]
alright i will

**Comment by karnage11** [comment]
doing it now

**Comment by karnage11** [comment]
if you have skype contact me there

**Comment by karnage11** [comment]
same as my name in here

**Comment by karnage11** [comment]
i tried Trakt.tv run Pin  Authorize went thru on my account but nothing on Specto at all

**Comment by karnage11** [comment]
wouldn't something pop up on Specto saying it went thru

**Comment by karnage11** [comment]
i just tested it on another addon worked , so it needs more work on specto needs to add my password once i add everything in

**Comment by karnage11** [comment]
let me know when you have another zip i will test it out

**Comment by karnage11** [comment]
you still want to do Business? i can help the people on here with Specto

**Comment by karnage11** [comment]
the URL Resolver Real Debrid Authorization works with my account on the website but doesn't go thru on specto

**Comment by Thewatchfuleye** [comment]
Mr.Know, great work on this so far. I can test the real debrid function if you want.

**Comment by karnage11** [comment]
Mrknow contact me on skype

**Comment by karnage11** [comment]
Let me know when you have another Zip so i can test it out , to see if Real-debrid will work
