### ISSUE TITLE
If Anyone Need's Help - NOT IN CHAT

### ISSUE THREAD

**Issue by karnage11** [mrknow/filmkodi#129]
if anyone needs help come to this chat i will be there - http://chatwing.com/Karnage11

**Comment by StopperN12** [comment]
Hey

**Comment by karnage11** [comment]
i am in the chat room

**Comment by karnage11** [comment]
@StopperN12 i found a better live PPV addon better the sportsDevil

**Comment by StopperN12** [comment]
What do you call it?

**Comment by karnage11** [comment]
@StopperN12 called castaway http://tutorial-iptv-xbmc.blogspot.com/2015/08/castaway-add-on-for-kodi-castaway-like.html , same as Sporstdevil but it works ... Sportsdevil isnt working

**Comment by karnage11** [comment]
i just tested it out

**Comment by karnage11** [comment]
same setup and everything

**Comment by karnage11** [comment]
same setup and everything

**Comment by karnage11** [comment]
didn't mean to close it lol

**Comment by karnage11** [comment]
i just tested it out with WWE Fast Lane , it works

**Comment by karnage11** [comment]
I am around , sorry if someone joined the chat , was watching TV
