### ISSUE TITLE
OpenELEC 6.0.0

### ISSUE THREAD

**Issue by go-misiek** [mrknow/filmkodi#13]
Na OpenELEC 6.0.0  na RPI.arm instalacja wtyczki przebiega pomyślnie (brak błędów). Na końcu komunikat że wtyczka jest aktywna. Po wejściu w ustawienia Dodatki->Moje dodatki - widnieje ona jako zainstalowana i aktywna. Jednak po wejściu w Wideo->Dodatki z ekranu głównego nie jest ona widoczna....Restart "malinki" nie pomaga.

**Comment by mrknow** [comment]
Prześlij logi jeżeli problem jeszcze występuję - https://github.com/mrknow/filmkodi/wiki/Jak-przes%C5%82a%C4%87-logi-z-kodi
