### ISSUE TITLE
jak instaluje wtyczke mr know to nie wyswietla sie nic

### ISSUE THREAD

**Issue by MatiQQQ** [mrknow/filmkodi#130]
jak w temacie wchodze w zakladke instaluj z repozytorium i jak wchodze dalej zeby zainstalowac wtyczki wideo to nic nie ma pusta lista (system OSMC 2016.01.01) i to samo w kodi 15.2 na win8

**Comment by karnage11** [comment]
update kodi to Kodi 16 Jarvis

**Comment by xxcriticxx** [comment]
server przeladowany zamontuj z zip

https://github.com/mrknow/filmkodi/files/139636/plugin.video.mrknow-2016.02.21.7.zip
https://github.com/mrknow/filmkodi/files/139637/script.module.xbmcfilm-2016.02.21.3.zip

**Comment by karnage11** [comment]
@xxcriticxx do you know if Mrknow is working on the Real-debrid API at all ? he never contacted me yet

**Comment by xxcriticxx** [comment]
am not involved in that plugin sorry

**Comment by karnage11** [comment]
alright no problem, thought you would know if he is updating anything today thats all
