### ISSUE TITLE
If anyone needs help I'm willing to help too

### ISSUE THREAD

**Issue by Thewatchfuleye** [mrknow/filmkodi#131]
First off, great work on Specto Mr.Know! A lot of people are really appreciative of your work, hope you're ready for the fame once all the bugs are ironed out.

I installed Specto very early so I've played around with it quite a bit. I have real debrid. I'm willing to help this effort and anyone with trouble based on my experiences.

**Comment by karnage11** [comment]
Hey did you just test out the development version for Specto for Real-debrid , it works with the site but not with specto...did it work for you or no ?

**Comment by Thewatchfuleye** [comment]
I have not yet tested, I'll try and get to it today if possible.

**Comment by karnage11** [comment]
yeah works with the website but doesn't go thru on Specto for me at all

**Comment by karnage11** [comment]
i am in Chat if you want to talk
