### ISSUE TITLE
videomega i uptobox

### ISSUE THREAD

**Issue by macias1985gda** [mrknow/filmkodi#132]
praktycznie kazdy stream umieszczony na w/w serwisach wyrzuca komunikat "brak dostepnego strumienia danych"

**Comment by mrknow** [comment]
@macias1985gda ale mowa o której wtyczce, bo mam trzy i każda na razie korzysta z innego resolvera ...

**Comment by mrknow** [comment]
Czekam na dodatkowe informację.
