### ISSUE TITLE
typertv nie dziala

### ISSUE THREAD

**Issue by kuba191994** [mrknow/filmkodi#133]
witam, kanały z  typertv nie działają w kodi

**Comment by xxcriticxx** [comment]
mrknow srawdz tv znowu potwierdzam ze typertv nie dziala

**Comment by plumers** [comment]
screen-tv.eu to samo a na stronce hula .... dalej nie dodałeś looknij tv a kiedyś było ---- nowy portal http://cinema-tv.xyz pozdrawiam

**Comment by xxcriticxx** [comment]
maja swoje linky czy jak reszta? jeden od drugiego

**Comment by mrknow** [comment]
Sprawdzę to jutro ... Może pozmieniali na stronie

**Comment by xxcriticxx** [comment]
trzeba cale section tv przejrzec wiekszosc nie dziala

**Comment by donald73** [comment]
wiem co jest z xbmcfilm.com ? u mnie błąd dodatku

**Comment by mrknow** [comment]
kurcze pododwali nowe streamy. Musze napisać do nich resolvery. Zajme się typerem w piątek od wieczora. Myślę że na niedziele 28.02.2016 powinien typer działac

**Comment by kucyk84** [comment]
a czy to bodajrze na typerze mialo byc KSW w ta sobote?

**Comment by mrknow** [comment]
Witam usiadłem i sprawdziłem - to było prostę Tutaj nowa wersja do testów 
http://kodi.filmkodi.com/plugin.video.specto/plugin.video.specto-2016.02.21.3.zip

Sprwadźcie czy wszystko działa to jutro rano wrzucę na serwery

**Comment by xxcriticxx** [comment]
typer na 02.25.1 no streams available 

zobacztv no work
vidtv.pl works
typertv no work 
telewizjada works
screen-tv no work
pivotv no work
itivi no work 
iklub works 
filmbox works 
darmowe no works

**Comment by plumers** [comment]
dokładnie jak wyżej w dodatku nie ma dalej LOOKNIJ TV a było ... możesz dodać mojefilmy.tk - (mają swoją wtyczkę ale nie chce mi się skakać po nich ) 

CAŁA sekcja TV dokładnie jest do poprawy .... SERWIS http://www.cinema-tv.xyz też działa ale chyba jada na linkach z typera i screena ... lol

**Comment by xxcriticxx** [comment]
filmy.tk tv hyba premium only trzeba placic

**Comment by plumers** [comment]
no tak ale zarejestrowani tez mają kilka kanałow free ale jak ktoś ma premium -- to sobie skorzysta :)

**Comment by mrknow** [comment]
Dobra - dodałem looknij, ale bardzo tnie u mnie. NIe wiem dlaczego

**Comment by xxcriticxx** [comment]
plumers premium jest w 1080p?

**Comment by mrknow** [comment]
typer naprawiony. Co prada dzisiaj nie działa HBO, ale to nie wina wtyczki. Na stronie również nie działa
