### ISSUE TITLE
Specto Alpha versions

### ISSUE THREAD

**Issue by mrknow** [mrknow/filmkodi#134]
RealDebrid FIX
[plugin.video.specto-2016.02.28.8.zip](https://github.com/mrknow/filmkodi/files/146118/plugin.video.specto-2016.02.28.8.zip)

OLD FILES

[plugin.video.specto-2016.02.28.7.zip](https://github.com/mrknow/filmkodi/files/145796/plugin.video.specto-2016.02.28.7.zip)
[plugin.video.specto-2016.02.28.001.zip](https://github.com/mrknow/filmkodi/files/141843/plugin.video.specto-2016.02.28.001.zip)
[plugin.video.specto-2016.02.28.002.zip](https://github.com/mrknow/filmkodi/files/141884/plugin.video.specto-2016.02.28.002.zip)

**Comment by karnage11** [comment]
Thank you

**Comment by karnage11** [comment]
going to test it out now

**Comment by karnage11** [comment]
Still doesn't show Real-debrid sources at all

**Comment by macias1985gda** [comment]
nie wiem czy to wina aktualizacji, ale zwlaszcza przy serialach, bardzo czesto wyrzuca komunikat "brak strumienia danych"

**Comment by karnage11** [comment]
Tried it out , trying to play an Episode and it is saying No Source at all

**Comment by mrknow** [comment]
Ok Try this one, 
In specto go to tools -> accounts -> and RealDebrid Authorize KODI

Should work  
[plugin.video.specto-2016.02.28.004.zip](https://github.com/mrknow/filmkodi/files/143767/plugin.video.specto-2016.02.28.004.zip)

**Comment by mrknow** [comment]
@macias1985gda - tak to wina wtyczki, w tej wersji plugin.video.specto-2016.02.28.004.zip
Poprawiłem to

**Comment by karnage11** [comment]
@mrknow going to try it now

**Comment by karnage11** [comment]
all i see when i start a show is Oneclickwatch and TVrelease

**Comment by mrknow** [comment]
Yes i must fix labels, but files  should go from realdebrid

**Comment by karnage11** [comment]
@mrknow  those where the only 1080p and HD sources I saw , it would say Real debrid if it was a source

**Comment by karnage11** [comment]
@mrknow your doing an awesome job hope you get it to work , Thanks

**Comment by karnage11** [comment]
@mrknow you still want to do business like you said , and something with paypal or something you said

**Comment by mrknow** [comment]
@karnage11 - I'm going to sleep. For four hours I have to go to work. 
I appreciate your support. For now, I do not need financial support. I was not refreshed and tired
But once again thank you for your support for Specto

**Comment by mrknow** [comment]
but somehow i want to cooperate with you, but now i dont now how. We must think how to do it.

**Comment by macias1985gda** [comment]
wyglada na to, ze wszystko teraz bardzo fajnie dziala :), super! dzieki za Twoja ciezka prace ! Twoja wtyczki razem z Mrknow Filmy do tego Exodus i zyc nie umierac ! :D

**Comment by karnage11** [comment]
Still not working for me , not getting any Real-debrid sources at all

**Comment by Thewatchfuleye** [comment]
I'll test the .005 alpha version later this evening. I had set up the RD on the initial release and still was getting RD sources even after the subsequent updates. 

karnage11 if you want email me and I'll send you a pic of this before I test the alpha version if they're still coming up.

**Comment by karnage11** [comment]
@Thewatchfuleye Vamgothic69@gmail.com , yeah not real debrid links pop up for me at all

**Comment by karnage11** [comment]
@Thewatchfuleye whats your email ?

**Comment by Thewatchfuleye** [comment]
YRLY59E@aol.com

**Comment by Thewatchfuleye** [comment]
I sent you an email

**Comment by karnage11** [comment]
i am on Kodi 16 Jarvis , i updated Specto to 2016.02.28.005 , i will send a pic

**Comment by Thewatchfuleye** [comment]
For Jarvis I'll have to fire up my computer, that'll have to wait until I get home.

**Comment by karnage11** [comment]
i am on a fire stick using it

**Comment by karnage11** [comment]
when i got to tv shows , i dont get real-debrid sources at all

**Comment by karnage11** [comment]
i sent a pic

**Comment by Thewatchfuleye** [comment]
Just out of curiousity how'd you set up the real debrid? I initially set it up the old Genesis way, but I looked at the code and it looks like it was updated so as that it sets up like SALTS now. Programs that use the SALTS type all work after one program is verified on real debrid.

**Comment by karnage11** [comment]
i uninstalled Genesis and just install Specto , i went to accounts , click on real-debrid , went to www.real-debrid/device and entered the code

**Comment by karnage11** [comment]
@mrknow  
![img_20160224_120152910](https://cloud.githubusercontent.com/assets/17055538/13293772/1cb8989a-daef-11e5-8633-ce9a375fc683.jpg) 

This is what i get

**Comment by Thewatchfuleye** [comment]
What show did you try, I'll test it in my end.
P

**Comment by karnage11** [comment]
those are just reg sources they work , but i just dont get the Real-debrid sources

**Comment by Thewatchfuleye** [comment]
I installed the initial release alongside Genesis and set it up with the old username/password. I also have SALTS on here which does the go to site enter code, if the code is the same as SALTS style verification all addons that use that type of code work after verifying one program.

**Comment by Thewatchfuleye** [comment]
What tv show was it though, I just want to see if I get any here

**Comment by karnage11** [comment]
i only use Specto and Exous ... Exous has all the real-debrid sources just not Specto

**Comment by Thewatchfuleye** [comment]
Try installing SALTS or Entertainment Hub and verifying that then try Specto.

**Comment by karnage11** [comment]
ok

**Comment by Thewatchfuleye** [comment]
Can you send me a pic of your setting account screen?

**Comment by karnage11** [comment]
alright for Specto ?

**Comment by Thewatchfuleye** [comment]
Yea, I just want to see what yours looks like under the accounts for the real debrid

**Comment by karnage11** [comment]
Contact me on Google hangouts , (914) 365 - 7834 so easier to text

**Comment by Thewatchfuleye** [comment]
I gotta leave for work in like 5 min, I'll be back tonight some time if you can

**Comment by karnage11** [comment]
alright @Thewatchfuleye 
![img_20160224_121923416_hdr](https://cloud.githubusercontent.com/assets/17055538/13294295/4476a186-daf1-11e5-969a-cfd31574842b.jpg)

**Comment by Thewatchfuleye** [comment]
Hmm, I'll have to try Jarvis anyway since that different than the Helix setup. I'll talk to you this evening.

**Comment by karnage11** [comment]
alright

**Comment by Thewatchfuleye** [comment]
Ok, I'm back, on the Helix/Isengard when you put in the real debrid it looks like the old Genesis where you put in your ID and password.

**Comment by Thewatchfuleye** [comment]
![image](https://cloud.githubusercontent.com/assets/17402766/13305071/a9895930-db26-11e5-8cfa-d54b196e5169.jpeg)

This is what it looks like on Isengard on a fresh install

**Comment by karnage11** [comment]
yea but i am on Kodi 16 Jarvis

**Comment by Thewatchfuleye** [comment]
Gonna try and have that up in a bit, it shouldn't be different though, don't see anything inThe code that should indicate it. Did you try the SALTS install like I recommended?

**Comment by karnage11** [comment]
yea still nothing

**Comment by Thewatchfuleye** [comment]
What happens if you click the real debrid over the real debrid authorize Kodi?

**Comment by karnage11** [comment]
i have to do to www.real-debrid.com/device and enter the code on the screen

**Comment by Thewatchfuleye** [comment]
Testing the alpha on my laptop now, gimme a min

**Comment by karnage11** [comment]
it isnt in Alpha anymore

**Comment by karnage11** [comment]
just go to www.kodi.tv/downloads for it now

**Comment by Thewatchfuleye** [comment]
I installed the latest version, doesn't work in the laptop, not sure if it's Jarvis or Specto itself

**Comment by karnage11** [comment]
ohh ok , real-debrid works from link but not specto at all

**Comment by Thewatchfuleye** [comment]
I'm not sure where the problem is though it works fine on helix and Isengard but those are both on android

**Comment by karnage11** [comment]
yeah if you can find the Problem let mrknow .. know about it

**Comment by karnage11** [comment]
i am using the Amazon fire stick with Kodi

**Comment by Thewatchfuleye** [comment]
I think he updated the code to correspond with the SALTS method of authorization, but other than the laptop it works fine

**Comment by Thewatchfuleye** [comment]
I've got MXQ boxes and 4 different android tablets and 2 laptops to test on

**Comment by karnage11** [comment]
he should make it correspond like Exdous does , if he wanted too

**Comment by karnage11** [comment]
the people that made Exduos made Genesis , beofore they gave up on it

**Comment by Thewatchfuleye** [comment]
It seems to but it doesn't seem to work on some versions of Kodi

**Comment by karnage11** [comment]
well hopefully he will get it to work

**Comment by Thewatchfuleye** [comment]
It's probably not too major of it works on some and not others. I'm not to familiar with Python, it seems like a conditional jump language I used years ago, but I'd have to familiarize with it more to find small issues.

**Comment by karnage11** [comment]
well every other link works ,hopefully he has another download zip for the fix tonight

**Comment by Thewatchfuleye** [comment]
I wouldn't worry too much, it's pretty early on in development

**Comment by karnage11** [comment]
yea

**Comment by karnage11** [comment]
all i use for my Kodi is , Specto , Exdous and Cast away addons

**Comment by karnage11** [comment]
@mrknow going to test it out now , Thank you

**Comment by karnage11** [comment]
@Thewatchfuleye new update now at the top of the page

**Comment by karnage11** [comment]
@mrknow showing up now .. Thank you for everything

**Comment by karnage11** [comment]
@mrknow  only 1 or 2 HD that shows up , everything else is HQ , if you can get more HD or 1080p with it that would be great

**Comment by karnage11** [comment]
add more sources would be awesome for the TV shows too

**Comment by karnage11** [comment]
@MrKnow everything is working , thank you , I got HD links 1080p links

**Comment by karnage11** [comment]
@mrknow on a role today huh lol

**Comment by Ivac** [comment]
Thank you for continuing with specto great work.  Can you add a section for 3d movies and bring back new HD movies like genisis used to have?

**Comment by karnage11** [comment]
@Ivac give him time with the HD movies he is still adding stuff , but 3D movies would be great too

**Comment by karnage11** [comment]
@mrknow anymore Alpha Test?
