### ISSUE TITLE
Got problem with profile name and latin characters

### ISSUE THREAD

**Issue by sejkomax** [mrknow/filmkodi#136]
After update to plugin.video.mrknow-2016.02.21.7 still got problem with polish characters in profile name. Here is a log:

` THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named wykop
                                            Traceback (most recent call last):
                                              File "C:\Users\micha�\AppData\Roaming\Kodi\addons\plugin.video.mrknow\default.py", line 108, in <module>
                                                import wykop, joemonster, milanos,filmbox,vodpl, filmydokumentalne, zalukaj, efilmyseriale
                                            ImportError: No module named wykop
                                            -->End of Python script error report<--
18:38:09 T:6216   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.mrknow/
18:38:09 T:6216   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mrknow/) failed
`

Profile name is spelling "michaś" and I think that should be problem.

**Comment by xxcriticxx** [comment]
please change ś to s and it will work or install under different user

Błąd instalacji dodatku na Windows

nazwa użytkownika - nie może zawierać polskich znaków

**Comment by sejkomax** [comment]
Thanks. It's not so easy to change name this folder, but it works :)

**Comment by xxcriticxx** [comment]
you're welcome
