### ISSUE TITLE
sportsdevil not working error

### ISSUE THREAD

**Issue by xxcriticxx** [mrknow/filmkodi#137]
od czasu do czasu wyskakuje mi error cos sports devil not working. nie wiem czy to bug czy cos niemam tej wtyczki zamonotanej

**Comment by karnage11** [comment]
Use Castaway

**Comment by xxcriticxx** [comment]
i get this while using/watching polish tv

**Comment by karnage11** [comment]
Castaway works , try it out

**Comment by xxcriticxx** [comment]
karnage you missing the point i am getting that msg while using polish tv plugin by mrknow comprende?

**Comment by karnage11** [comment]
ohhhh

**Comment by mrknow** [comment]
Poprawię w ten weekend. Poprostu silnik wtyczki to sportsdevil

**Comment by xxcriticxx** [comment]
thx

**Comment by milemar** [comment]
Mam ten sam problem.
Ten blad pokazuje przy kazdej probie uruchomienia
