### ISSUE TITLE
Mrknow nie działa z windows 10

### ISSUE THREAD

**Issue by chmurek77** [mrknow/filmkodi#140]
Witam,
Po zainstalowaniu windows 10 mam problem z MRKNOW, nie działa, nawet ta najnowsza wersja . Specto działa bez problemu, nie wiem o co chodzi.
Posiadam Kodi wersja 16
Pozdrawiam i czekam na jakies info

**Comment by xxcriticxx** [comment]
log?

**Comment by mrknow** [comment]
Ja mam 10 i u mnie działa ...

**Comment by chmurek77** [comment]
OK, u mnie wszystko działałao, jak miałem 8.1, ale przestało [po upgrdade
do windows 10, nie wiem czy to jest powiazane czy przypadek, dlatego szukam
pomocy, moze muszę ustawić cos dodatkowo o czym nie wiem, czemu specto
działa bez problem?

2016-02-26 7:26 GMT+00:00 mrknow <notifications@github.com>:

**Comment by xxcriticxx** [comment]
jaki masz user name do windowsa?

podaj logs please?

**Comment by chmurek77** [comment]
chmurarafal1@gmail.com

2016-02-26 11:50 GMT+00:00 xxcriticxx <notifications@github.com>:

**Comment by chmurek77** [comment]
A po co ci ten log?

2016-02-26 11:58 GMT+00:00 Rafał Chmura <chmurarafal1@gmail.com>:

**Comment by xxcriticxx** [comment]
pokaze blendy jakie kodi znalazlo

czy user do windowsa masz Rafał czasem?

**Comment by chmurek77** [comment]
nie, jak tylko updradowałem do windows 7 uzywalem tego loga co ci podałem

Nie rozumiemtylko czemu specto dziala bez probelmu a to nie, ale ty pewnie
jestes wiekszym fachowcem I moze tak moze byc
jesli uwazasz ze mam cos zmienic, loga czy cos, to daj znac, bo irytuje
mnie to strasznie

na drugim kompie co mam jest windows 7 I tam dziala bez problem, na
tablecie dziala bez problem, a tu ciagle jest blad dodatku

W dniu 26 lutego 2016 14:09 użytkownik xxcriticxx <notifications@github.com>
napisał:

**Comment by xxcriticxx** [comment]
python nie rozumie polskich znakow dlatego pytam jak sie logujesz do windowsa?

jesli nie polskie znaki log pokaze wiecej 

czekam na loga

https://github.com/mrknow/filmkodi/wiki/Jak-przes%C5%82a%C4%87-logi-z-kodi
http://mods-kodi.pl/articles.php?article_id=36
http://iptvlive.org/97-pomoc/98-jak-wyslac-log-file

**Comment by chmurek77** [comment]
bez polskich znaków, ale loga ci podałem już chmurarafal1@gmail.com, tak
sie loguje

W dniu 26 lutego 2016 15:09 użytkownik xxcriticxx <notifications@github.com>
napisał:

**Comment by plumers** [comment]
chmurek nie LOGIN tylko log - to coś , co jest plikiem zdarzeń tego co się wydarzyło od momentu włączenia programu itd.

Odinstaluj KODI wywal repo i zainstaluj na nowo - wszystko na 10 działa  przechodziłem z 7 na 10 i zrobiłem tak i wsio hula do dziś - pozdro

**Comment by chmurek77** [comment]
To co, pomoże ktoś, bo dalej nie działa i nie wiem o co to ku.. chodzi...

**Comment by xxcriticxx** [comment]
oczywiscie jak podasz log

**Comment by chmurek77** [comment]
ok, a jak mogé znaleśc ten log, bo u mnie pojawia się info błąd dodatku,
szczególowe info w rejestrze zdarzeń, a ajk ide do zdarzeń to jedyne co
jest to że kodi się poprawnie uruchomiło o tej i o tej godzinie


2016-02-29 0:25 GMT+00:00 xxcriticxx <notifications@github.com>:

**Comment by xxcriticxx** [comment]
https://github.com/mrknow/filmkodi/wiki/Jak-przes%C5%82a%C4%87-logi-z-kodi
http://mods-kodi.pl/articles.php?article_id=36
http://iptvlive.org/97-pomoc/98-jak-wyslac-log-file

**Comment by zlotychlopak** [comment]
Mam problem z wtyczką po backupie. Zrobilem kopie kodi na androidzie i zaktualizowalem to na WIN10. Wszystkie wtyczki i ustawienia dzialaja oprocz MrKnow. Wczesniej mrknow działal prawidlowo na WIN10. Prosze o pomoc bo juz nie mam koncepcji. Link do loga http://xbmclogs.com/ppu2y8vmx

**Comment by chmurek77** [comment]
Witam,

Jak zainstalowałem kodi log uploader to on jakby nie działał.
Dodałem email, dałem ok, jak się pojawi błąd to idę do tego dodatku kodi log uploader, klikam na niego, ale nic nie działa (wiec nie ma okna z pytaniem czy ma wysłać maila).

Nawet jak z poziomu konfiguruj klikam na uruchom to nic się nie dzieje, tak jakby w ogóle nie reagowało, masacra jakaś.

Nie wiem, ale to chyba jakaś większa sprawa u mnie jest????

R.

**Comment by xxcriticxx** [comment]
napewno cos prostego 

próbowaliście odmontowac plugin i zamontowac jeszcze raz?

**Comment by zlotychlopak** [comment]
Tak. Odinstalowalem najpierw plugin i repozyturium ale nie pomoglo. Odinstalowalem cale Kodi a potem przywrocilem kopie z backupu. Rezultat taki sam. Bład dodatku, jednoczesnie specto działa bardzo dobrze. Czy z mojego loga nic nie wynika ?

**Comment by xxcriticxx** [comment]
przegladam jestem w pracy troche zajmie czasu

**Comment by xxcriticxx** [comment]
20:16:42 T:8852   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: Bad magic number in C:\Users\Mario\AppData\Roaming\Kodi\addons\script.module.xbmcfilm\lib\Parser.pyo
                                            Traceback (most recent call last):
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\plugin.video.mrknow\default.py", line 108, in <module>
                                                import wykop, joemonster, milanos,filmbox,vodpl, filmydokumentalne, zalukaj, efilmyseriale
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\plugin.video.mrknow\host\milanos.py", line 15, in <module>
                                                import mrknow_pLog, settings, Parser
                                            ImportError: Bad magic number in C:\Users\Mario\AppData\Roaming\Kodi\addons\script.module.xbmcfilm\lib\Parser.pyo
                                            -->End of Python script error report<--

**Comment by xxcriticxx** [comment]
mrknow bendzie potrzebny

**Comment by zlotychlopak** [comment]
Dobra u mnie problem rozwiązany :-)

C:\Users\Mario\AppData\Roaming\Kodi\addons\script.module.xbmcfilm\lib\Parser.pyo

trzeba zmienic nazwe na parser.pyo z malej litery :-) Wzcesniej kombinowalem na androidzie z tymi nazwami bo nie dzialalo i widocznie cos tam zostalo

**Comment by xxcriticxx** [comment]
youtube dodatek masz zamontowany?

**Comment by zlotychlopak** [comment]
Tak. wszystko działa. Problem rozwiązany.

**Comment by xxcriticxx** [comment]
youtube w ostatniej ver?

**Comment by zlotychlopak** [comment]
5.1.17 nie wiem czy to najnowsza wersja. Rzadko korzystam z YT.

**Comment by xxcriticxx** [comment]
potrzebne do filmow dokumentalnych

**Comment by chmurek77** [comment]
U mnie dalej nic nie działa, teraz nawet już specto przestało działać...
Chyba muszę się pogodzić, że upgrade do windows 10 zakończył moją erę kodi..

no chyba, że ktoś mi pomoże w końcu...
Poprzednie porady nie dają rady....

**Comment by xxcriticxx** [comment]
napisz co do tej pory zrobiles 

od montuj wszystko i zacznij od nowa

**Comment by chmurek77** [comment]
Kilka razy odinstlowywałem I kodi I wtyczki, nie działa

Nie dziala loguploader, żebym mógł chociaż problem wyświetlić...
Nie wiem co miałbym zrobić jeszcze,
raczej Windowsa 10 to wolalbym nie odinstalowywać itp

2016-03-01 22:57 GMT+00:00 xxcriticxx <notifications@github.com>:

**Comment by xxcriticxx** [comment]
jakiego masz usera do windows? tyle ray pytalem 
kiedys dziala?
podaj wiecej info

**Comment by chmurek77** [comment]
Kilka razy już ci pisałem

User do windowsa: chmurarafal1@gmail.com

Działało jak miałem windows 8.1, jak updragowałem do 10 to przestało działać, tzn. Nigdy nie działało jak mam windows 10, mimo wielokrotnego instalowania i odinstalowania kodi (wersje 15.2 i teraz 16).

Na początku Specto działało, teraz już nic nie działa, żadna wtyczka…

Moim zdaniem, cos to blokuje, ale nie wiem co i gdzie szukać…

R.

**Comment by xxcriticxx** [comment]
chmurka od kiedy email jest userem w windowsie?

**Comment by chmurek77** [comment]
oczywiści, że nie jest, sorry..
Już sobie sam poradziłem z problemem....

**Comment by xxcriticxx** [comment]
jak rozwiazales?

**Comment by marqius2** [comment]
Temat widzę zamknięty a ja mam ten sam problem. 
WIN10 Home Edition.
Konto zmieniłem bez polskich znaków.
Plik Parser.pyo jest z małych liter.

Mrknow- wywala błąd
KODI Log....też nie moge uruchomić - wywala błąd
Ale wtyczka SPECTO działa :)

Przekopałem internet- nic nie znalazłem. Kodi odinstalowałem 3 razy, czyściłem rejestr etc. Dalej to samo.
KODI- ostatnia wersja. 16.xxx
mrknow- ostatnia dostepna wtyczka.

Może jakiś pomysł co jeszcze mógłbym sprawdzić ? :)

**Comment by rysson** [comment]
@marqius2, w robocie właśnie mnie zmuszają do pracy z Windowsem (co za pech), akurat 10, to w tygodniu postaram się sprawdzić i zobaczyć czy działa.
