### ISSUE TITLE
Specto Provider Issue

### ISSUE THREAD

**Issue by CrazyCrew** [mrknow/filmkodi#143]
Let me first start out by saying excellent work on building upon Genesis.

I have an issue I want to bring to your attention. I have tried everything to get DIZILAB GVIDEO, PUBFILM GIVIDEO and SEZONLUKDIZI to show up as a provider. Anyway of adding this back on. I have them turned on in the menu system. I looked at the settings.xml file as well and they show as TRUE.

Thanks

**Comment by karnage11** [comment]
Get the latest real-debrid fix it should have new sources too https://github.com/mrknow/filmkodi/issues/134

**Comment by CrazyCrew** [comment]
Hey karnage11 that solved my problem thanks for the help!

**Comment by karnage11** [comment]
anytime
