### ISSUE TITLE
Source not working 

### ISSUE THREAD

**Issue by karnage11** [mrknow/filmkodi#144]
Tv release source not working at all

**Comment by niapia95** [comment]
Hey @karnage11

**Comment by niapia95** [comment]
You hear of anyone having problems downloading the repo?

**Comment by karnage11** [comment]
Add this repo HTTP://filmkodi.com/repository

**Comment by niapia95** [comment]
Do you still have that chat wing?

**Comment by karnage11** [comment]
Yea

**Comment by karnage11** [comment]
i am in it right now

**Comment by karnage11** [comment]
Join if you like

**Comment by karnage11** [comment]
@niapia95 if you like to join , join now

**Comment by karnage11** [comment]
http://chatwing.com/Karnage11

**Comment by karnage11** [comment]
heading to bed soon

**Comment by karnage11** [comment]
@niapia95  i will be on tomorrow around 12 Eastern Standard Time if you need help at all or if you have the Whatsapp Messenger (914) 563-7198 or (914) 365-7103 ....
