### ISSUE TITLE
dodajemy sekcje bajek

### ISSUE THREAD

**Issue by xxcriticxx** [mrknow/filmkodi#147]
tutaj podajemy ulubione strony z bajkami

**Comment by mrknow** [comment]
OK - pomysł się podoba tylko stron nie znam. Super czekam na strony do doannia :)

**Comment by xxcriticxx** [comment]
http://bajkipopolsku.com/

**Comment by xxcriticxx** [comment]
http://bajkionline.com/

**Comment by xxcriticxx** [comment]
http://www.gralandia.tv/bajka/

**Comment by xxcriticxx** [comment]
http://e-bajkidladzieci.pl/

**Comment by xxcriticxx** [comment]
http://bajowo.blogspot.com/

**Comment by xxcriticxx** [comment]
duzo materialu jest na youtube nie mozna jakiegos scapera napisac co by szukal?

**Comment by xxcriticxx** [comment]
http://www.filmyhd-online.com/category/animacja/

**Comment by borys76** [comment]
Yes,yes jestem za bo mi dzieci przestana mowic posted Polsku

**Comment by borys76** [comment]
Mialo byc po Polsku

**Comment by xxcriticxx** [comment]
szukam stron masz cos podaj

**Comment by borys76** [comment]
Chyba wszystkie podales
Good job

**Comment by xxcriticxx** [comment]
borys co ja sie sie stoba mam

**Comment by plumers** [comment]
southparkonline.pl

**Comment by xxcriticxx** [comment]
to hyba dla duzych dzieci

**Comment by mrknow** [comment]
Dodane dzisiaj 

http://bajkipopolsku.com/
http://bajkionline.com/

**Comment by xxcriticxx** [comment]
super sprawa

**Comment by mrknow** [comment]
dodane. Nowe strony proszę zgłaszajcie w nowych zgłoszeniach
