### ISSUE TITLE
Nie dzialaja streamy rtmp

### ISSUE THREAD

**Issue by przem** [mrknow/filmkodi#15]
Hej,

zaden kanal nie dziala, takie logi:

20:48:26 596.771606 T:1743254560  NOTICE: [script.module.xbmcfilm]     -> 1 item(s) found
20:48:26 596.771973 T:1743254560  NOTICE: [script.module.xbmcfilm] Find rtmp stream
20:48:26 596.772278 T:1743254560  NOTICE: [script.module.xbmcfilm] Find embedding javascripts
20:48:26 596.772583 T:1743254560  NOTICE: [script.module.xbmcfilm] find redirects
20:48:26 596.774536 T:1743254560  NOTICE: [script.module.xbmcfilm] End of directory
20:48:26 596.775085 T:1743254560  NOTICE: ('MMMMMMMM', <entities.CListItem.CListItem object at 0x5ff773b0>, {'infos': {u'catcher': u'streams', u'url.tmp': u'embed/hbo.html', u'title': u'HBO ', u'url': u'http://www.screen-tv.eu/embed/hbo.html', u'cfg': u'screen-tv.pl.cfg@CATCH', u'image': u'includes/img/flash-player-icon.png', u'videoTitle': u'HBO ', u'director': u'screen-tv.pl', u'referer': u'http://www.screen-tv.eu/http://www.screen-tv.eu/hbo.php', u'definedIn': u'screen-tv.pl.cfg', u'icon': u'/home/osmc/.kodi/addons/script.module.xbmcfilm/resources/images/screen-tv.png'}})
20:48:26 596.777161 T:1957782064   ERROR: GetDirectory - Error getting plugin://plugin.video.mrknow/?item=catcher%3dstreams%26url.tmp%3dembed%252Fhbo.html%26title%3dHBO%2b%26url%3dhttp%253A%252F%252Fwww.screen-tv.eu%252Fembed%252Fhbo.html%26cfg%3dscreen-tv.pl.cfg%2540CATCH%26image%3dincludes%252Fimg%252Fflash-player-icon.png%26videoTitle%3dHBO%2b%26director%3dscreen-tv.pl%26referer%3dhttp%253A%252F%252Fwww.screen-tv.eu%252Fhttp%253A%252F%252Fwww.screen-tv.eu%252Fhbo.php%26definedIn%3dscreen-tv.pl.cfg%26icon%3d%252Fhome%252Fosmc%252F.kodi%252Faddons%252Fscript.module.xbmcfilm%252Fresources%252Fimages%252Fscreen-tv.png&mode=110
20:48:26 596.781921 T:1957782064   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mrknow/?item=catcher%3dstreams%26url.tmp%3dembed%252Fhbo.html%26title%3dHBO%2b%26url%3dhttp%253A%252F%252Fwww.screen-tv.eu%252Fembed%252Fhbo.html%26cfg%3dscreen-tv.pl.cfg%2540CATCH%26image%3dincludes%252Fimg%252Fflash-player-icon.png%26videoTitle%3dHBO%2b%26director%3dscreen-tv.pl%26referer%3dhttp%253A%252F%252Fwww.screen-tv.eu%252Fhttp%253A%252F%252Fwww.screen-tv.eu%252Fhbo.php%26definedIn%3dscreen-tv.pl.cfg%26icon%3d%252Fhome%252Fosmc%252F.kodi%252Faddons%252Fscript.module.xbmcfilm%252Fresources%252Fimages%252Fscreen-tv.png&mode=110) failed
20:48:26 596.805420 T:1646261280  NOTICE: Thread BackgroundLoader start, auto delete: false
20:48:26 596.874512 T:1957782064  NOTICE: DVDPlayer: Opening: rtmp://204.45.157.226/app playpath=171941?MTQ0OTUxNzcwNjs5NWYxNjQ3ZjU3NGRiNTVhYzhmMmE5NmZiNTMyYWU4OA== swfVfy=1 timeout=10 swfUrl=http://cdn.shidurlive.com/player.swf live=true pageUrl=http://www.shidurlive.com/embed/sdaffsdafsdf
20:48:26 596.874756 T:1957782064 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
20:48:26 596.875122 T:1646261280  NOTICE: Thread DVDPlayer start, auto delete: false
20:48:26 596.875488 T:1646261280  NOTICE: Creating InputStream
20:48:27 597.905029 T:1646261280   ERROR: rtmp server requested close
20:48:27 597.905701 T:1646261280   ERROR: CDVDPlayer::OpenInputStream - error opening [rtmp://204.45.157.226/app playpath=171941?MTQ0OTUxNzcwNjs5NWYxNjQ3ZjU3NGRiNTVhYzhmMmE5NmZiNTMyYWU4OA== swfVfy=1 timeout=10 swfUrl=http://cdn.shidurlive.com/player.swf live=true pageUrl=http://www.shidurlive.com/embed/sdaffsdafsdf]
20:48:27 597.905945 T:1646261280  NOTICE: CDVDPlayer::OnExit()
20:48:27 597.929504 T:1957782064  NOTICE: CDVDPlayer::CloseFile()

odpalam na osmc, w zeszlym tygodniu wszystko dzialalo :-)
ocs zepsulem czy to znany problem?

**Comment by widgetpl** [comment]
Dzisiaj pojawił się problem z telewizjadą jak i samą wtyczką.
Przy wyborze telewizji wymagającej nowego librtmp pojawia się błąd wtyczki [logi](http://xbmclogs.com/ptcpg274f)

**Comment by mrknow** [comment]
Już wiem na czym polegał problem. We wtyczce źle były ustawiane zależności. Nowe wersje już nie będą miały takiego problemu
