### ISSUE TITLE
SPECTO - error. Suspended api   themoviedb.org

### ISSUE THREAD

**Issue by mrknow** [mrknow/filmkodi#153]
{"status_code":10,"status_message":"Suspended API key: Access to your account has been suspended, contact TMDb."}

**Comment by xxcriticxx** [comment]
no good! 

mozna uzyc TheTVDB.com albo Rotten Tomatoes ale to kilka ladnych godzin programowania

**Comment by mrknow** [comment]
na razie znalazłem w necie trochę kluczy i teraz wykorzystuję je. Do celowo przepisze wtyczkę na  imdb

Lub zrobię synchronizacje bazy.
