### ISSUE TITLE
cda.pl - brak streamingu

### ISSUE THREAD

**Issue by przemekb22** [mrknow/filmkodi#154]
W nowej wersji wtyczki nie działa cda.pl

**Comment by xxcriticxx** [comment]
czekamy asz cda.pl skonczy zmieniac potem bendzie poprawka do wtyczki

**Comment by Seico** [comment]
teraz już z żadnego serwisu xbmcfilm poprzez kodi nie odtwarza filmów ani cda.pl ani openload.co

**Comment by mrknow** [comment]
Tak wiem 
Tu wersje beta 
http://kodi.filmkodi.com/beta/plugin.video.mrknow/plugin.video.mrknow-2016.03.05.1.zip
http://kodi.filmkodi.com/beta/plugin.video.xbmcfilm/plugin.video.xbmcfilm-1.1.5.zip

**Comment by Seico** [comment]
Wczoraj openload.co po aktualizacji działał a dzisiaj po aktualizacji nie działa

**Comment by mrknow** [comment]
openload poprawione i cda też
