### ISSUE TITLE
SportsDevil Info

### ISSUE THREAD

**Issue by czacha1903** [mrknow/filmkodi#155]
"No stream available"

Dokładnie taki komunikat mam po aktualizacji na moim boxie. Probuje otwozyc jakakolwiek tv na mrknow i to sie pojawia. 
Phantom Film jest pusto jak wejde w np. "najnowsze"
Specto rowniez przestalo dzialac.
Ten sam komunikat w SportsDevil w kazdym podkatalogu.
Na drugim boxie w pracy wszystko ok. Nie wiem co sie  stalo u mnie, ale wszystko nagle przestalo dzialac. Odinstalowywalem i instalowalem z 20 razy  i nic.
Pomoooocy.
Ps. Jedyna zmiana to nowy internet z BT, bo w uk mieszkam.

**Comment by xxcriticxx** [comment]
sportsdevil duplicate https://github.com/mrknow/filmkodi/issues/137

phantom film to inna wtyczka

log?

**Comment by czacha1903** [comment]
Moj caly Log   http://xbmclogs.com/pqsljfi8z

**Comment by xxcriticxx** [comment]
@czacha1903 da rade kodi i mrknow tylko? tu jest ze 3 dni czytania

**Comment by milemar** [comment]
Ja mam zainstalowany plugin na OSMC na rPI2 i dzisiaj zaczelo hulac, jak trzeba moge podac logi tylko dajcie znac jakie i gdzie sa (linux nie jest moja mocna strona ale dam rade;) )

**Comment by xxcriticxx** [comment]
@milemar hyba posty pomyliles

**Comment by czacha1903** [comment]
Mozna zamknac temat. Problem naprawiony.
Po zalozeniu internetu z BT w uk musialem wylaczyc opcje na routerze "smart setup". Teraz wszystko dziala.
