### ISSUE TITLE
Brak listingu Specto Fork

### ISSUE THREAD

**Issue by pkakakozi** [mrknow/filmkodi#156]
Witam
Od jakiegos czasu wtyczka nie wyswietla zawartosci katalogow.
Brak mozliwosci przegladania oraz wyszukiwania. 
Filmy dodane do ulubionych uruchamiaja sie.

Kawalek kodu z logu:

11:30:08 T:140299867219712  NOTICE: [SPECTO]: ->----------                PARAMS: {'action': 'movieNavigator'}
11:30:10 T:140299867219712  NOTICE: [SPECTO]: ->----------                PARAMS: {'action': 'movieYears'}
11:30:11 T:140299191973632  NOTICE: [SPECTO]: ->----------                PARAMS: {'action': 'movies', 'url': 'http://api.themoviedb.org/3/discover/movie?api_key=%s&year=2015&primary_release_date.lte=2016-03-01&page=1'}
11:30:12 T:140299191973632  NOTICE: [SPECTO]: ### CLIENT CLIENT HTTP Error 401: Unauthorized
11:30:12 T:140300974798848   ERROR: GetDirectory - Error getting plugin://plugin.video.specto/?action=movies&url=http%3a%2f%2fapi.themoviedb.org%2f3%2fdiscover%2fmovie%3fapi_key%3d%25s%26year%3d2015%26primary_release_date.lte%3d2016-03-01%26page%3d1
11:30:12 T:140300974798848   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.specto/?action=movies&url=http%3a%2f%2fapi.themoviedb.org%2f3%2fdiscover%2fmovie%3fapi_key%3d%25s%26year%3d2015%26primary_release_date.lte%3d2016-03-01%26page%3d1) failed
11:30:12 T:140299191973632  NOTICE: [SPECTO]: ->----------                PARAMS: {'action': 'movieYears'}
11:30:18 T:140299867219712  NOTICE: [SPECTO]: ->----------                PARAMS: {'action': 'movies', 'url': 'http://api.themoviedb.org/3/discover/movie?api_key=%s&year=2016&primary_release_date.lte=2016-03-01&page=1'}
11:30:19 T:140299867219712  NOTICE: [SPECTO]: ### CLIENT CLIENT HTTP Error 401: Unauthorized
11:30:19 T:140300974798848   ERROR: GetDirectory - Error getting plugin://plugin.video.specto/?action=movies&url=http%3a%2f%2fapi.themoviedb.org%2f3%2fdiscover%2fmovie%3fapi_key%3d%25s%26year%3d2016%26primary_release_date.lte%3d2016-03-01%26page%3d1
11:30:19 T:140300974798848   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.specto/?action=movies&url=http%3a%2f%2fapi.themoviedb.org%2f3%2fdiscover%2fmovie%3fapi_key%3d%25s%26year%3d2016%26primary_release_date.lte%3d2016-03-01%26page%3d1) failed
11:30:19 T:140299867219712  NOTICE: [SPECTO]: ->----------                PARAMS: {'action': 'movieYears'}
11:30:42 T:140299191973632  NOTICE: [SPECTO]: ->----------                PARAMS: {'action': 'movieNavigator'}
11:30:46 T:140299191973632  NOTICE: [SPECTO]: ->----------                PARAMS: {'action': 'movies', 'url': 'theaters'}
11:30:46 T:140299191973632  NOTICE: [SPECTO]: ### CLIENT CLIENT HTTP Error 401: Unauthorized
11:30:46 T:140300974798848   ERROR: GetDirectory - Error getting plugin://plugin.video.specto/?action=movies&url=theaters
11:30:46 T:140300974798848   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.specto/?action=movies&url=theaters) failed
11:30:47 T:140299191973632  NOTICE: [SPECTO]: ->----------                PARAMS: {'action': 'movieNavigator'}
11:30:49 T:140299191973632  NOTICE: [SPECTO]: ->----------                PARAMS: {}

Pozdrawiam

**Comment by mrknow** [comment]
Tu wersja beta nie wiem czy działa 
http://kodi.filmkodi.com/beta/plugin.video.specto/plugin.video.specto-2016.03.03.1.zip

**Comment by karnage11** [comment]
Thanks , works good , everything working good with the beta
