### ISSUE TITLE
brak dźwieku w telewizjada

### ISSUE THREAD

**Issue by pawlik2016** [mrknow/filmkodi#158]
Ja mam problem z głosem w Telewizjada. Często po włączeniu dowolnego kanału zanika głos.Leci tylko obraz. Czasem  wróci po jakimś czasie , potem znowu zniknie . Czy przyczyną może być stosunkowo wolne łącze jak na obecne czasy bo tylko 5-6 Mb . Czy może jakieś ustawienie w Kodi. Kodi używam w tv philips

**Comment by xxcriticxx** [comment]
jaka ver kodi? jaki os? czy kiedys kolwiek dzialalo? czy dziala na jakimys innym sprzentem? podaj more info plz

**Comment by pawlik2016** [comment]
kodi 15.2 , android 5.1 w tv 50 pfh 6550/88. dźwięk czasem działa a czasem nie działa Np dłuższy czas zanikał głos na republice tv. Dzisiaj np na HBO 2 , praktycznie pzrez wiekszośc zcasu nie miałem głosu. teraz na Canal + seriale jest . brak reguły

**Comment by xxcriticxx** [comment]
zrob update firmware telewizora i daj znac 

wysle ze problem moze byc kodeku do dzwieku

masz jakies inne urzadzenie zeby przetestowac dzwiek? cos nie android

**Comment by pawlik2016** [comment]
telewizor był aktualizowany już wcześniej, ale to sie dzieje od dawna tylko teraz w końcu mnie to zaczęło bardziej irytować. Mam teraz Telewizjadę w kodi i to sie zdarza częściej. Wcześniej przy oglądaniu seriali np z kinomana problemu nie było

**Comment by xxcriticxx** [comment]
po testuj na windowsie i zobacz czy przycina wtedny bendziesz wiedzial for sure
