### ISSUE TITLE
Specto Beta is Here (2016.03.03.1)

### ISSUE THREAD

**Issue by karnage11** [mrknow/filmkodi#159]
Give Mrknow time to update and fix everything .. everything should be back to normal soon

**Comment by mrknow** [comment]
Beta - http://kodi.filmkodi.com/beta/plugin.video.specto/plugin.video.specto-2016.03.03.1.zip

**Comment by karnage11** [comment]
Thanks Mrknow

**Comment by joshwaa123** [comment]
Can I get this for my android box

**Comment by karnage11** [comment]
@joshwaa123 no you need to use your pc to transfer the file , what android box you have ?

**Comment by karnage11** [comment]
@mrknow if there anymore beta's just post it here , Thank you
