### ISSUE TITLE
gdzie jest mrknow

### ISSUE THREAD

**Issue by xxcriticxx** [mrknow/filmkodi#16]
?

**Comment by widgetpl** [comment]
dajcie człowiekowi spokój, poświęcił swój prywatny czas na stworzenie tej wtyczki i udostępnił ją nam.
Jeżeli chcecie coś wnieść w jej rozwój to zachęcam do nauki pythona i konrybuowania na jej rzecz.
To nie jest forum do ogólnego użytku tylko do dyskusji na temat bugów i  ewentualnych zmian/poprawek. Zatem cierpliwie czekajcie aż @mrknow znajdzie trochę wolnego czasu i będzie w stanie wypuścić nową wersję.

**Comment by ip5d** [comment]
@widgetpl dokladnie :+1:

**Comment by xxcriticxx** [comment]
pisza otym nawet na sd-xbmc

http://sd-xbmc.org/pl/content/problem-z-wtyczk%C4%85-mrknow

**Comment by mrknow** [comment]
Cześć 
Generalnie jestem bardzo zajętym człowiekiem. Moja praca zajmuje mi ok 150% mojego czasu,  do tego żona,  rodzina i takie tam. 
Na rozwijanie wtyczki mam czas od 22:00 w piątek do 22:00 w niedzielę. Więc jeżeli widzicie jakiś obszar gdzie mogli byście mi pomóc to chętnie podzielę się obowiązkami. 

Widzę że zainteresowanie wtyczką jest, więc nadal będę rozwijał wtyczki. Bardzo dziękuję za wszelką pracę jaką tutaj wkładacie, 
@ip5d - dzięki za parser.py - poprawię to dzisiaj.

**Comment by plumers** [comment]
Super - wiem jak to jest jak się coś robi (odnosi to sukces)  a w dod potem trzeba znaleźć na to czas a tu są priorytety jak rodzina - nie zaniedbuj :) ---> ona najważniejsza wtyczka poczeka

polecam mój post z linkami do tv no i doszła nowa telewizjada.net - tutaj jest wielki wybór :)

pozdrawiam czekamy na świąteczny prezent w 

od 30 stycznia będę dostępny ---> więc pomogę jak tylko zacznę grzebać w tym pythonie :)

**Comment by ip5d** [comment]
@mrknow nie ma sprawy, w sumie to ja chcialem podziekowac za wtyczke :smiley: 

Nie wiem na ile moja pomoc moze byc przydatna bo z pythonem dopiero zaczynam przygode. Siedze glownie w C#, C++, T-SQL ale chetnie pomoge. :wink:
