### ISSUE TITLE
Teleiwzjada

### ISSUE THREAD

**Issue by zjac** [mrknow/filmkodi#160]
Coś się zmieniło we wtyczce ? Telewizjada ( strona ) normalnie chodzi, a w Kodi jest info " Web request failed"

**Comment by xxcriticxx** [comment]
sprawdze jak bende w domu dam znac

**Comment by czacha1903** [comment]
Sprawdzalem teraz i dziala normalnie.

**Comment by zjac** [comment]
Tak, tez przed chwilą sprawdzałem, ale do ok. 23 godz. nie było. Tak już jest kolejny raz w ciągu ostatnich kilku dni.

**Comment by xxcriticxx** [comment]
zjada chodzi na openelec, win7, antek

**Comment by zjac** [comment]
Tak teraz chodzi, ale często ostatnio pojawiało się  " Web request failed" mimo iż w przeglądarce działała telewizjada. Sprawdzane na 2 kodi: jeden na tablecie z win 8.1, drugi na kompie win 7

**Comment by xxcriticxx** [comment]
web request failed wyskakuje jak cookie hyba sie skonczy

**Comment by borys76** [comment]
Sprobuj wyczyscic cache and pure packages

**Comment by xxcriticxx** [comment]
wystarczy wyskoczyc do main menu i spowrotem i wszystko dziala

**Comment by plumers** [comment]
qwa telszajsjada wkrótce zakończy swój żywot .... serwery przeciążone i tiwien i polszajs już drążą temat ... ave ... a jak masz takie info - to po prostu poczekaj a nie od razu NIE DZIAŁA MI 2 min MrKnow zrób coś ... lamentujecie jakby Mr nie miał nic innego w życiu do roboty ehh

**Comment by zjac** [comment]
**@plumers** już się wypłakałeś ?

**Comment by zjac** [comment]
Ponownie ta sama sytuacja. Fakt,ze niektóre kanały na telewizjadzie nie sa włączone, ale chcę korzystać z tego, który jest a otrzymuje info " Web request failed"

**Comment by xxcriticxx** [comment]
jaki kanal?

**Comment by zjac** [comment]
obojętne jaki kanał - pokazuje się info i wywala z telewizjady. Tak było od ok. 19:30 do chyba 21

**Comment by xxcriticxx** [comment]
a na stronie dzialaly?

**Comment by zjac** [comment]
Tak, strona działała, i te kanały co klikałem były dostępne - normalnie przez przeglądarkę oglądałem.

**Comment by xxcriticxx** [comment]
internet bylo ok wtym czasie?

masz inny system zeby to sprawdzic?

**Comment by zjac** [comment]
Zapewniam Cię, że wszystko było OK: z internetem, z systemami, sprzętem.
Tablet windows 8.1, komp windows 7.

**Comment by xxcriticxx** [comment]
ok maybe bug

**Comment by zjac** [comment]
Nie wiem, znowu to samo. Po kilku godz. oglądania, przełączania kanałów itp.
O ile mógłbym zrozumieć jakieś trojany i cuda na stacjonarnym, to na tablecie mam gołego windowsa ( instalka 2 tyg temu - sys oryginał z wszelkimi poprawkami ). Nagle kanał out, "web ....", a po próbie wejścia w telewizjadę pusto.

**Comment by xxcriticxx** [comment]
what channel ?

**Comment by xxcriticxx** [comment]
twoj router sie nie zacina? 

umnie teraz wszystkie kanaly go na openelec, win7, antek

**Comment by plumers** [comment]
zjac - popatrz w majtki i nie pisz mi tu takich poje...nych komentarzy ,od kiedy tu jesteś...?  od tygodnia---> się dowiedziałeś przez wykop ha ha ha - dalsza rozmowa nie ma sensu pajacu.A jak się nie znasz na obsłudze prostych rzeczy to się nie bierz za to.

Zlituje się nad Toba pajacu - telewizjada też ma limit userów i jeśli się nie załapiesz wywala taki błąd ---ave dla tematu MrKnow zamknij go  ,bo szkoda czasu.

**Comment by zjac** [comment]
To, że jestem od tygodnia, a Ty dłużej nie upoważnia Cię do obrażania nikogo. To takie typowe dla chłopaków z małym fiutkiem - mają pole do popisu w internecie, to ich dowartościowuje.

Czytaj ze zrozumieniem: nie mogłem się nie załapać, bo byłem już na kanale ok. 2 godzin.

**Comment by xxcriticxx** [comment]
come on boys! please stop this shit!

**Comment by zjac** [comment]
Ponownie to samo. Wydaje mi się, że jest to powiązane z dużą ilością osób używająca wtyczkę - bo pojawia się to regularnie w godz ok. 19-20

**Comment by plumers** [comment]
zjac doucz się buffonie a jak lubisz temat o fiutkach to na _parade_ :)  dużo osób co ma do wtyczki ... temat uważam za zamknięty :)

**Comment by zjac** [comment]
@plumers - jestes niestety typowym hejterem forumowym. Tyle masz do powiedzenia co zwyzywanie kogoś. Ale jeśli to Ci polepszy humor, to przyjmuje na klatę.

**Comment by xxcriticxx** [comment]
boys please!

**Comment by xxcriticxx** [comment]
zjac temat jest towj to go zamknij please
