### ISSUE TITLE
How long will it be down for?

### ISSUE THREAD

**Issue by joshwaa123** [mrknow/filmkodi#161]

**Comment by xxcriticxx** [comment]
3 months ...

**Comment by joshwaa123** [comment]
You having a laugh

**Comment by xxcriticxx** [comment]
yes

**Comment by karnage11** [comment]
how long till he fixes it ?

**Comment by xxcriticxx** [comment]
about 3 months

**Comment by karnage11** [comment]
Umm why so long?????

**Comment by xxcriticxx** [comment]
mrknow is m.i.a he got fbi on his back :(

**Comment by karnage11** [comment]
damn that really sucks

**Comment by xxcriticxx** [comment]
possible no more

**Comment by karnage11** [comment]
i Hope Not

**Comment by karnage11** [comment]
i am surprised that they went after him , thats so stupid

**Comment by karnage11** [comment]
all he needs to do for now is fix it back to the way it was for now where everything was working

**Comment by xxcriticxx** [comment]
i think they going to put him in Guantanamo Bay detention camp

**Comment by karnage11** [comment]
there not going to put him there

**Comment by xxcriticxx** [comment]
they have no internet no free wifi

**Comment by karnage11** [comment]
he should have it fixed soon

**Comment by xxcriticxx** [comment]
have you notice he hasn't been on the internet lately

**Comment by karnage11** [comment]
@xxcriticxx beta is out for Specto

**Comment by joshwaa123** [comment]
Is it working

**Comment by karnage11** [comment]
@joshwaa123 the beta works

**Comment by joshwaa123** [comment]
Wooooo

**Comment by karnage11** [comment]
you know how to install zips ?

**Comment by joshwaa123** [comment]
Is it a different zip file to what it was before

**Comment by karnage11** [comment]
@joshwaa123  https://github.com/mrknow/filmkodi/issues/159

**Comment by karnage11** [comment]
@joshwaa123 installed it ?

**Comment by karnage11** [comment]
https://github.com/mrknow/filmkodi/issues/166

**Comment by joshwaa123** [comment]
Can I get this on my android box

**Comment by karnage11** [comment]
@joshwaa123 what android box do you have ?

**Comment by joshwaa123** [comment]
MCQ

**Comment by joshwaa123** [comment]
MXQ

**Comment by karnage11** [comment]
can you Transfer zips to your box ?

**Comment by joshwaa123** [comment]
I've never done it before

**Comment by karnage11** [comment]
doesn't the MXQ box have a micro SD card you can add in it ?

**Comment by karnage11** [comment]
join to the chat easier to talk - http://chatwing.com/Karnage11#
