### ISSUE TITLE
Can only get a few things working

### ISSUE THREAD

**Issue by iRushh** [mrknow/filmkodi#162]
I can only get Latest Movies, Oscar Winner, Box Office and People Watching the rest just do nothing when I click on them

**Comment by xxcriticxx** [comment]
plugin has massive problems right now we all waiting on mrknow to fix it

please be patient

**Comment by iRushh** [comment]
Ok Thank you

**Comment by xxcriticxx** [comment]
thank you for your continuous support

**Comment by mrknow** [comment]
Beta http://kodi.filmkodi.com/beta/plugin.video.specto/plugin.video.specto-2016.03.03.1.zip

**Comment by iRushh** [comment]
Thank you!
