### ISSUE TITLE
zalukaj

### ISSUE THREAD

**Issue by 0gyy** [mrknow/filmkodi#164]
Witam po ostatniej aktualizacji nie działa zalukaj proszę o odpowiedź

**Comment by xxcriticxx** [comment]
duplicate https://github.com/mrknow/filmkodi/issues/85

**Comment by mrknow** [comment]
nie działa wyszukiwanie, reszta powinna działać

**Comment by 0gyy** [comment]
👍

**Comment by mrknow** [comment]
działa wszystko. Tak myślę
