### ISSUE TITLE
Is their only me that it doesn't work for 

### ISSUE THREAD

**Issue by joshwaa123** [mrknow/filmkodi#167]
Nothing opens when I click on it

**Comment by xxcriticxx** [comment]
you have kodi 16?

uninstall old install new reboot

**Comment by joshwaa123** [comment]
Yeah I have kodi 16

**Comment by joshwaa123** [comment]
I have done what you have said and it still doesn't work

**Comment by xxcriticxx** [comment]
please provide logs

**Comment by karnage11** [comment]
@joshwaa123 still having problems
