### ISSUE TITLE
Telewizjada - "No stream available" (opis problemu, prób naprawy, debug)

### ISSUE THREAD

**Issue by DawidR3st3r** [mrknow/filmkodi#169]
Witam

Na wstępie przede wszystkim gratulacje za świetną wtyczkę! Znajomy niedawno polecił i aż załuję, że wcześniej nie dowiedziałem się o niej ;)

Mam jednak pewien problem, z którym najpierw próbowałem sobie poradzić na ile potrafiłem/wygooglowałem, ale niestety bez skutku i dlatego ostatecznie jestem tu. Chodzi o ten błąd:
http://i.imgur.com/rGAYcn6.png
Po kliknięciu "Telewizjada" 3 sekundy coś próbuje i wyrzuca błąd "No stream available" (okno błędu o nazwie "SportsDevil Info", które chyba oznacza "silnik", który jest wykorzystywany)

Podczas debugowania, w xbmc.log pojawia mi się w tym czasie np. coś takiego:

> 21:21:24 T:1628  NOTICE: [script.module.xbmcfilm] Local file tv/telewizjada.net.adult.cfg opened
> 21:21:24 T:1628  NOTICE: Previous line repeats 1 times.
> 21:21:25 T:1628  NOTICE: ('>>>>>>>>>>>>> LEN <<<<<<<<<', 18713)
> 21:21:25 T:1628  NOTICE: [script.module.xbmcfilm] Remote URL http://www.telewizjada.net/get_channels.php opened
> 21:21:25 T:1628  NOTICE: Previous line repeats 1 times.
> 21:21:25 T:1628  NOTICE: ('-----------', u'http://www.telewizjada.net/get_channels.php', u'videoTitle', u'tv/telewizjada.net.adult.cfg', <entities.CListItem.CListItem object at 0x0569A110>)
> **21:21:25 T:1628  NOTICE: [script.module.xbmcfilm]     -> 0 item(s) found**
> 21:21:25 T:1628  NOTICE: Previous line repeats 1 times.
> 21:21:25 T:1628  NOTICE: [script.module.xbmcfilm]     -> No redirect found
> 21:21:25 T:1628  NOTICE: Previous line repeats 1 times.
> 21:21:25 T:1628  NOTICE: ('>>>>>>>>>>>>> LEN <<<<<<<<<', 18713)
> 21:21:25 T:1628  NOTICE: [script.module.xbmcfilm] Remote URL http://www.telewizjada.net/get_channels.php opened (demystified)
> 21:21:25 T:1628  NOTICE: Previous line repeats 1 times.
> 21:21:25 T:1628  NOTICE: ('-----------', u'http://www.telewizjada.net/get_channels.php', u'videoTitle', u'tv/telewizjada.net.adult.cfg', <entities.CListItem.CListItem object at 0x0569A110>)
> **21:21:25 T:1628  NOTICE: [script.module.xbmcfilm]     -> 0 item(s) found**
> 21:21:25 T:1628  NOTICE: Previous line repeats 1 times.
> 21:21:25 T:1628  NOTICE: [script.module.xbmcfilm]     -> No redirect found
> 21:21:25 T:1628  NOTICE: Previous line repeats 1 times.
> 21:21:25 T:3364   DEBUG: ------ Window Init (DialogOK.xml) ------
> 21:21:26 T:3364   DEBUG: CApplication::ProcessMouse: trying mouse action leftclick
> 21:21:27 T:3364   DEBUG: ------ Window Deinit (DialogOK.xml) ------
> 21:21:27 T:1628  NOTICE: [script.module.xbmcfilm] End of directory
> 21:21:27 T:1628  NOTICE: Previous line repeats 1 times.
> 21:21:27 T:1628    INFO: Scriptresult: Success
> 21:21:27 T:1628    INFO: Python script stopped
> 21:21:27 T:1628   DEBUG: Thread XBPyThread 1628 terminating

W katalogu danych aplikacji programu, w folderze "addons" nie ma folderu "script.module.xbmcfilm", do którego chyba odnosi się to co jest wyżej. Wtyczka oczywiście była instalowana bezpośrednio z repo http://filmkodi.com/repository/repository.filmkodi.com.zip w kompletnie świeżym programie.
Spróbowałem zatem wrzucić (brakujący?) katalog "script.module.xbmcfilm" z https://github.com/mrknow/filmkodi (po ściągnięciu całości w .zip), ale po tym nawet nie chciała się odpalić wtyczka ("Filmy Online - mrknow.pl") w całości. Kombinowałem jeszcze z instalacją różnych script.module i jeszcze z czymś, czego już nie pamiętam, ale to też niestety nic nie pomogło. Obecnie katalog "addons" wygląda tak: http://i.imgur.com/akaPmtN.png
Jeszcze jedno - zdziwiłem się, że nie ma w podkatalogu "hosts" skryptu np. "telewizjada.py". Oczywiście próbując już wszystkiego, wrzuciłem tam telewizjada.py z innej wtyczki, ale było bez raczej zaskoczenia - nic to nie zmieniło ;) Dopiero po debugu zrozumiałem, że "telewizjada" leży w plugin.video.mrknow\resources\modules\tv

**Comment by zjac** [comment]
Czyli tak dla laika co należy gdzie wrzucić ? Bo u mnie też lipa z tiwijadą

**Comment by DawidR3st3r** [comment]
Znalazłem "script.module.xbmcfilm", który nie psuje całej wtyczki (tak jak wyżej opisałem, że nie mogłem w ogóle włączyć wtyczki - wywalał błąd od razu) na http://kodi.filmkodi.com/beta/script.module.xbmcfilm/script.module.xbmcfilm-2016.02.25.2.zip

Co ciekawe gdy na świeżo wrzucam ten katalog do "addons", to przy pierwszym kliknięciu w "Telewizjada" wyrzuca błąd "Web request failed" (http://i.imgur.com/BlxRNxa.png) ale tylko raz. Każda kolejna próba wejścia w Telewizjada wyrzuca błąd "No stream available". Gdy usunę folder "script.module.xbmcfilm" i wrzuce ściągnięty na nowo, to podobnie ma się sytuacja - jednorazowy błąd z "Web request failed" i dalej już tylko "No stream available"

**Comment by zjac** [comment]
Czyli tak naprawdę nic to nie zmienia - nadal nie działa

**Comment by DawidR3st3r** [comment]
Niestety nie. Sam jestem laikiem ;) ale po prostu kombinuję

**Comment by zjac** [comment]
ja pokombinuje jutro w dzien, dzisiaj na przegladarce ogladam.

**Comment by DawidR3st3r** [comment]
@mrknow Może źle wydaje mi się, że to może pomóc, ale z tego co googluje i wyszukuję rozwiązania, podobno zmienił się "json" i we wspominanym w 1. wpisie "python.py", z wcześniejszego:
> params = {'service': SERVICE, 'id': item['id'], 'title': item['displayName'].encode('utf-8'), 'icon': MAINURL + item['bigThumb']}
zmiana na:
> params = {'service': SERVICE, 'id': item['id'], 'title': item['displayName'].encode('utf-8'), 'icon': MAINURL + item['thumb']}
umożliwiła przynajmniej wyświetlenie listy kanałów, ale podobno nie można mimo to włączyć streamu

**Comment by DawidR3st3r** [comment]
@mrknow Jeżeli będzie Ci działać Telewizjada, to czy możesz spakować i wrzucić wszystkie aktualne potrzebne do Twojej wtyczki "script.module"? Będą to: **script.module.beautifulsoup**, **script.module.simple.downloader**, **script.module.requests**, **script.module.xbmcfilm** i jeszcze jakiś?
Mam (może złudne) wrażenie, że coś chyba nie do końca z którymś z nich u mnie jest ok

PS Tak, do tej pory nad tym siedzę ;)

**Comment by mrknow** [comment]
Zaktualizuj wtyczke. Dzisiaj cos pozmieniali na stronie i wrzuciłem update

**Comment by zjac** [comment]
@mrknow widzę tylko starą z 25.02

**Comment by prostaczek** [comment]
Witam,
zrugacie mnie ale nie mogę nigdzie w necie znaleźć instrukcji - zapytam więc tu. 
Mam na ps3 moviana, na nim navi-x. Jak zainstalować na navi-x wtyczkę filmkodi?
Przepraszam i pozdrawiam.

**Comment by DawidR3st3r** [comment]
@mrknow Dzięki za szybki update :) Po aktualizacji wtyczka jest w wersji 2016.03.05.10 (http://i.imgur.com/ZGFcZK4.png) jednak wciąż pojawia się błąd "No stream available" (http://i.imgur.com/27k5Eoq.png)
Przed updatem zrobiłem kopię katalogu addons i zauważyłem, że nie zaktualizował się "script.module.xbmcfilm", w którym skrypt (chyba) odpowiadający za Telewizjadę znajduje się w script.module.xbmcfilm\resources\modules\tv

Spróbowałem odinstalować wtyczkę i zainstalować na nowo z repo (oraz z http://kodi.filmkodi.com) ale w dalszym ciągu jest "script.module.xbmcfilm" ten sam. Czy "script.module.xbmcfilm" z http://kodi.filmkodi.com/ w wersji 2016.02.25.2 jest aktualny?

**Comment by DawidR3st3r** [comment]
@mrknow  Z tego co sprawdzam, to (o ile to odpowiada za nią) "telewizjada.txt" (plugin.video.mrknow\resources\catchers) z wersji np. 2016.03.05.3 jest identyczna jak w wersji 2016.03.05.10

**Comment by DawidR3st3r** [comment]
@mrknow Dzięki za szybki update :)
Po aktualizacji wtyczka jest w wersji 2016.03.05.10 (http://i.imgur.com/ZGFcZK4.png) jednak...
wciąż pojawia się błąd "No stream available" (http://i.imgur.com/27k5Eoq.png) :(
Spróbowałem odinstalować wtyczkę i zainstalować na nowo z repo (oraz z http://kodi.filmkodi.com) ale w dalszym ciągu jest to samo

- Czy "**script.module.xbmcfilm**" z kodi.filmkodi.com w wersji **2016.02.25.2** jest aktualny? (http://kodi.filmkodi.com/script.module.xbmcfilm/)
- Jeżeli coś więcej odpowiada za Telewizjadę niż http://kodi.filmkodi.com/plugin.video.mrknow/plugin.video.mrknow-2016.03.05.10.zip (jakiś dodatkowy script.module np. beautifulsoup czy requests) to bardzo proszę wrzuć na _kodi.filmkodi.com_, Może po aktualizacji tego będzie i u mnie działać (jeżeli Telewizjada już powinna być ok), z góry dzięki

**Comment by gumball1** [comment]
kombinujesz jak kon pod gore , po aktualizcji dziala , narobiles burdel u siebie to posprzataj

**Comment by DawidR3st3r** [comment]
To dobrze, że u Ciebie działa. Jak już pisałem, próbowałem również na czystym programie itd. Wszystko inne działa. A że kombinowałem najpierw samemu to chyba plus, że od razu nie czekałem bezczynnie na "zbawienie" jak większość? Zawsze najpierw próbuję wszystko sam ogarnąć, a dopiero później proszę o pomoc, gdy nie udaje się i nie mam już pomysłu.

@mrknow Zatem ostatnia prośba i już nie będę zawracał Ci głowy ;) Najwyżej odpuszczę temat tej telewizjady jeżeli znowu się nie uda.
Czy mógłbyś wrzucić gdzieś spakowane wykorzystywane do Twojej wtyczki **script.module.beautifulsoup**, **script.module.requests** i być może jeszcze jakieś niezbędne katalogi ze skryptami? Na mobilnej wersji widziałem, że instalując z repo pobiera właśnie te wymienione script.module, ale może jeszcze coś wiecej? Na PC mam caly czas wrażenie, że to one mi psują tę telewizjadę. Mam tu beautifulsoup w wersji 3.2.1 oraz requests w wersji 2.4.3

**Comment by zjac** [comment]
Ale wszystko działa - weź ściągnij najnowsze i wrzuć. Co Ty kombinujesz z tymi plikami ? I po co ?

**Comment by DawidR3st3r** [comment]
Przecież pisałem, że mam najnowszą *.10 A chodzi mi o to, że wydaje mi się, że mam starszą wersję któregoś z wymienionych script.module (nie aktualizuje się, nie pobiera się z repo) i dlatego pewnie nie działa. Dlatego proszę o wrzucenie również tego na http://kodi.filmkodi.com tak jak obecny już tam script.module.xbmcfilm

**Comment by zjac** [comment]
zgraj sobie z repo - przecież mrknow wrzucił ..

**Comment by DawidR3st3r** [comment]
Żeby się dało to bym przecież zgrał... Wyraźnie pisałem, że z repo nie aktualizuje/ściąga mi module.scriptów dlatego proszę o ich .zipy, których nie ma też na kodi.filmkodi.com

**Comment by xxcriticxx** [comment]
usun pierwszo wtyczke potem repo i zamontuj od nowa probowales?

**Comment by DawidR3st3r** [comment]
Próbowałem, pisałem ;)

**Comment by zjac** [comment]
przeinstaluj Kodi i po sprawie
