### ISSUE TITLE
Mrknow.pl na TV Android Philips

### ISSUE THREAD

**Issue by Kreator100** [mrknow/filmkodi#17]
Witajcie,
Zainstalowałem wtyczkę zgodnie z instrukcją: http://filmkodi.com/pl/wtyczka-filmy-online-mrknow/ 
Instalacja przebiegła bez problemów, natomiast przy próbie uruchomienia wtyczki wyskakuje mi błąd i nie chce się uruchomić. Podobnie z wtyczką xbmcfilm.com.

Czy te wtyczki działają na android tv (lolipop)?

**Comment by widgetpl** [comment]
proponuję przeglądać poprzednie wpisy #5 
jeżeli to nie ten sam problem to najlepiej zamiścić logi

**Comment by Kreator100** [comment]
Dzieki,
W ciemno zainstalowałem to co cieniawa 83 wrzucił w poprzednim wpisie:) i o dziwo działa!
Mam informacje: Aktualizuj LIBRTMP - aby działały kanały TV.
Pytanie: mam do wyboru: linux 32bit, Linux 64bit, Windows run kodi as admin, ios atv2,RasPi i Android ARM.
Który system wybrać dla TV bo nie mam pojęcia na czym ten android jest postawiony:) 

cieniawa83 commented a day ago
Problem rozwiązany,wystarczy ze zainstalujecie ten plik i wtyczka działa wraz z nowymi serwisami,
http://przeklej.org/file/Zzvd7p/14489957458581.zip 
Wtyczka sie automatycznie zaktualizuje

**Comment by widgetpl** [comment]
jeżeli się nie mylę to lollipop jest 64bit

**Comment by Kreator100** [comment]
Dzięki,
Prosi o jakiś root password.

**Comment by adaski8** [comment]
Android arm system lolipop a bez roota nie zainstalojesz tego

**Comment by mrknow** [comment]
Myślę żę  kanały filmowe z telewizjady będą działały bez librtmp. Musisz sprawdzić we własnym zakresie
