### ISSUE TITLE
Furk doesn't work 

### ISSUE THREAD

**Issue by ronney67** [mrknow/filmkodi#171]
I have a Furk account and it's not working.  All my credentials are ok,  but I see no stream at all.  In other addons it is working.  Is there a problem with it?

**Comment by karnage11** [comment]
go in to tools , go to movies and tv shows and look for the Furk Source , you have to turn then on

**Comment by ronney67** [comment]
It's turned on.  That was the first thing that I had checked.  Normally it was working.  Suddenly it didn't.  So I checked Salts and there I see the streams that are available.

**Comment by karnage11** [comment]
give him time to fix everything then

**Comment by karnage11** [comment]
Real-debrid works with it , just give him time

**Comment by ronney67** [comment]
Of course I will give him time to fix it.  So now he is aware of the issue.

**Comment by karnage11** [comment]
yeah
