### ISSUE TITLE
yoy.tv sporo kanałów przydała by się dostęp.

### ISSUE THREAD

**Issue by tuchas** [mrknow/filmkodi#174]
Witam serdecznie.
Ostatnio na yoy.tv pojawila się dość spora liczba kanałów.
Przydał by się dostęp w mrknow

Jeśli da ktoś radę, mogę podać jakieś konto premium na 1-3 dni.

**Comment by mrknow** [comment]
OK. Zrobimy tak.
Kupie sobie premium u nich w następny weekend (w dni powszednie zajmuje mnie moja robota). 

Tylko i wyłącznie wtedy kiedy uda  mi się  dodać tą stronę  do wtyczki i będzie działać - to  zwrócisz poprzez donacje koszty zakupu konta na 7 dni. 7 dni to optymalny czas na poprawki. 
Nie chce danych twojego konta

**Comment by tuchas** [comment]
Ok zgadzam się na to.

**Comment by borys76** [comment]
To I ja sie dozuce  10$ starczy?

**Comment by xxcriticxx** [comment]
i $10 na piwo

**Comment by borys76** [comment]
Poszlo
Confirmation number:		7H666259HE8480405
Donation amount:		50.00 PLN
From Amount:		$13.07 USD
To Amount:		50.00 PLN
Exchange Rate:		1 U.S. Dollar = 3.82555 Polish

**Comment by tuchas** [comment]
ja też się dorzucę mam wypłatę w środę.

**Comment by borys76** [comment]
Mrknow dodaj PayPal address do wtyczki albo url do strony filmkodi.com Bo wszyscy wchodza na mrknow.pl a ta niedziala I ciezko znalezc address PayPal

**Comment by xxcriticxx** [comment]
xxcriticxx your donation is now complete
Payment by PayPal
Confirmation number: 8HD05105ME400011S.
An email with your donation details has been sent to xxcriticxx and you can print your donation receipt.

**Comment by tuchas** [comment]
Widać że jest spore zainteresowanie tym yoy.tv oby wtyczka dobrze funkcjonowała.

**Comment by xxcriticxx** [comment]
@tuchas czekamy na twoja donacje w srode :+1:

**Comment by tuchas** [comment]
jestem starym użytkownikiem wtyczki :)

**Comment by tuchas** [comment]
Jak ida prace?

**Comment by mrknow** [comment]
Yoy.tv - tu będzie bardzo ciężko. Stosują jakiś sposób autentykacji po nawiązaniu połączenia z kanałem. jest około 10% szans że to rozwalę
Napisze dzisiaj na http://stream-recorder.com/ - może ktoś mi tam pomoże ...

**Comment by borys76** [comment]
Zapomnij o yoy.tv nie warte centa ,wykupilem tam premium na prube straszne dziadostwo nawet za darmo nie chcem tego servisu 
Polecam wszystkim teraz 
http://www.moje-filmy.tk
200 kanalow polowa HD I maja liste M3U

**Comment by xxcriticxx** [comment]
@borys76 nagraj tego troche na youtube

jak cena jest za mies?

**Comment by borys76** [comment]
Ja zaplacilem 40 pln za 3 miesiace mozna placic przez PayPal :)
Niema lepszej TV full HD zero buffering

**Comment by xxcriticxx** [comment]
ciekawe jak dlugo :)

**Comment by borys76** [comment]
narazie dziala to korzystam

**Comment by zjac** [comment]
@borys76 
Jakie mają kanały ? Bo pisałem do niego przez gg wtyczkę na stronie, to nie chciał mi podać jakie ...
A w ciemno nie kupię ...

Jest np. Comedy Central, Comedy Central Family, Wszystkie Discovery, BBC BRIT ?

**Comment by borys76** [comment]
Moje-filmy czy yoy.tv?

**Comment by zjac** [comment]
@borys76  moje-filmy

**Comment by borys76** [comment]
Minuta zrobie filmik I wzuce na Google drive

**Comment by borys76** [comment]
https://drive.google.com/file/d/0B1dXAJm1v3D0czd5NjVIZUdHb00/view?usp=docslist_api

**Comment by zjac** [comment]
Aż tak niepotrzebnie :) Ale Dziękuje

**Comment by borys76** [comment]
W kinie z dzieckiem jestem I tak nie mam Co robic

**Comment by zjac** [comment]
No 200 kanałów to tam nie ma - raczej standard to co wszędzie ( jest 200 na liście, ale podwójnie każdy, bo pewnie SD i HD )

**Comment by borys76** [comment]
Ja tylko sport ogladam I dla dzieci potrzebuje polskie bajki zeby mi Polskiego nie zapomnialy odkad mam moje-filmy ogladam mecze bez stresu

**Comment by zjac** [comment]
Zgadza się, ja też oglądam 3-4 kanały. Tylko wkurza mnie, to, że napisał mi facio z mojefilmy, że ma 200 kanałów ... to tak jak bym TVP 1 wrzucił w 100 rozdziałkach i napisał, że mam 100 kanałów ...

**Comment by borys76** [comment]
Moze byc ze jest okolo 200 do wczoraj bylo 250 na liscie

**Comment by borys76** [comment]
Niewazne zaplacilem 12$ za 3 miesiace, mozna placic PayPal /bitcoin dla mnie to wygoda

**Comment by xxcriticxx** [comment]
tam tak caly czas na zmiane tylko na zaproszenie albo server pada

**Comment by xxcriticxx** [comment]
@borys76 nagraj krotki filmik jak to chodzi

**Comment by borys76** [comment]
Jest wyzej film z kanalami

**Comment by zjac** [comment]
po kontakcie przez gg na stronie nie dam temu facetowi ani grosza zarobić. kawał chama i prostaka.

**Comment by borys76** [comment]
Ja znim gadalem pare razy mi sie wydawal ok najwazniejsze ze odpisuje na GG I forum I ze TV dziala gorszych chamow od weeba niema a I tak wszyscy maja TV od nich

**Comment by xxcriticxx** [comment]
nice

**Comment by mrknow** [comment]
Yoy.tv - powinno działac w nowej wtyczce mrknowtv

**Comment by mrknow** [comment]
Dodałem do nowej wtyczki MrKnow TV. Działa (oprócz HBO -coś zacina)

**Comment by borys76** [comment]
Dziala super nawet bez premium

**Comment by zjac** [comment]
@borys76  jak ten głupek z m-f.tk ? Zrobił w końcu ta TV ? Już u niego jest po niespodziewanej komunii córki, czy nadal nie ? Pozdrawiam z forum

**Comment by borys76** [comment]
Wyjebal mnie z forum ale sd dalej nie dzialaja bo wszystkie byly z telewizjady a HD nieda sie ogladac ciagle buffor

**Comment by zjac** [comment]
@borys76 jeszcze byłem jak mu pisałeś o zwrocie kasy, mi załozył perma na IP - za to, że żądałem od niego działania TV za którą płacę- do tej pory wisi mi kase za premke,a na email nieodpisuje. Także, to ostrzeżenie dla chcących korzystać z moje-filmy.tk / gośc to gbór i prostak. **Admina za of top Przepraszam.**

**Comment by hercpaint** [comment]
zajebista hujnia brak kanałów hd a rwie sie tak jak majtki kurwie na  dupie nie polecam

**Comment by yarecco** [comment]
http://tele-wizja.com/
bez limitów bez opłat i szeroki wybór kanałów
po co opłacać się jakimś wyłudzaczom?
