### ISSUE TITLE
Question: decode Openload function

### ISSUE THREAD

**Issue by mortael** [mrknow/filmkodi#175]
Hey,

You guys are using the decodeOpenload function I created for Ulimate Whitecream.
It seems like obfuscating and putting a nice other video when 'abused' didn't work :)
My question is, could you give me (mortael) proper credits for the function...just a small thank you or something for the headache Openload is giving me with their aaencode :)
Second question, how did you deobfuscate it so fast...are you using a script for that?

Kinds regards,
  mortael

**Comment by mrknow** [comment]
@mortael - for me you are master. What kind of information put in credits ? email, website, nick, name?
I put this information in function header and changelog, 

Second question - for me it was simple 

> import
> re;import base64
>decoded = (lambda p,y:(.......
>print decoded

**Comment by mortael** [comment]
lol, so simple :)

just my name(mortael) is good enough....thanks for understanding.

**Comment by mrknow** [comment]
Today I see that after decoding code are credits. 
Yesterday, it just had not noticed (maybe 4 am is not the best time for thinking) . In a moment I release updating the add-on 's on my servers.

**Comment by xxcriticxx** [comment]
please post github links only or server will die again

**Comment by mrknow** [comment]
github commit - done
plugin.video.mrknow - done
plugin.video.xbmcfilm - done 
plugin.video.specto - tomorow morning, i will release update.

**Comment by xxcriticxx** [comment]
post all links to github in new post called [LINKS] DATE

**Comment by mortael** [comment]
Great :+1:
