### ISSUE TITLE
please donate/prosimy o dotację

### ISSUE THREAD

**Issue by xxcriticxx** [mrknow/filmkodi#177]
Darowizna

Jeżeli wtyczka okazała się pożyteczna, proszę o wsparcie
w postaci darowizny na rzecz dalszego rozwoju wtyczki.

dotacje prosimy na stronie http://filmkodi.com/pl/start/ na dole

**Comment by mrknow** [comment]
uuu 
czekaj, czekaj

**Comment by zjac** [comment]
donate,donate... ja rozumiem, że trzeba z czegoś opłacić, ale powiedz mi teraz jak to się ma do moich 2 dotacji po parę zyli od Grudnia - gdy od jakiegoś czasu wywala mi połączenia np. z telewizjadą, screen tv ...

Człowiek traci chęci na donate, jak przestaje korzystać, bo kaszani co chwilę wtyczka kodi

**Comment by zjac** [comment]
Odnośnie linku: "Niestety, po kliknięciu ostatniego łącza lub przycisku wystąpił błąd."

**Comment by xxcriticxx** [comment]
zjac dziekujemy serdecznie za grudzien :+1: 

tak jak pisalem wczesnej podaj wiecej info w odzielnym temacie o setupie (router/firewall/antivirus/szybkosc internetu, log, etc) sprobujemy pomoc !!!

**Comment by zjac** [comment]
Siedzę w IT od strony sprzętowej i zapewniam Cię, że wszystko mam jak należy. A tablet mam golutki z nowym windows ( oryginał ) i na nim tylko przeglądarka ( czysta ) oraz Kodi - typowo do oglądania. I niestety wywala połaczenia na Kodi ( na www. działa non top bez problemu )

**Comment by xxcriticxx** [comment]
otworz nowy temat pogadamy wiecej tutaj jest donation

**Comment by zjac** [comment]
Temat zamknięty, skoro tylko u mnie to jest, nie ma sensu pisać.

**Comment by xxcriticxx** [comment]
thx zjac
