### ISSUE TITLE
marked as watched

### ISSUE THREAD

**Issue by splasheye** [mrknow/filmkodi#179]
hi, i am using Specto ver. 2016.03.05.1 on an Android box with Kodi 15.2. the check for watch movies or shows does not work , automatic or if you manually try and mark it as watched. The working popup in the lower right corner comes up by no check. This started about 2 or 3 updates ago.

Any thoughts or solution will be great

**Comment by mrknow** [comment]
Yes, problem was with meta-handlers. 
In new version i must set this as required in add-on  settings. Tomorow will be update and this issue will be resolved

**Comment by splasheye** [comment]
Thank you very much.

Since this was not working I had been using other stuff and check back at Specto

To see if it was working.

 

I love your Add on and thanks for the reply.

 

Patrick

**Comment by splasheye** [comment]
Hi I just tried it again last night and still not working for me.

 

Or maybe you was unable to get the update done yet.

 

Patrick

**Comment by splasheye** [comment]
Hi, This is still not working I had 2016.03.12.2
and I upgraded it to a beta ver 2016.03.15.1 and still not working
