### ISSUE TITLE
TV nie działa

### ISSUE THREAD

**Issue by marsik2008** [mrknow/filmkodi#18]
Co zrobić aby działały kanały ??

**Comment by widgetpl** [comment]
zaktualizować wtyczkę, w ostateczności odinstalować i zainstalować ponownie.

**Comment by mrknow** [comment]
wersja 2016.01.03 - powinna to poprawić. jeżeli nie to prosze pokaż mi logi według tej instrukcji https://github.com/mrknow/filmkodi/wiki/Jak-przes%C5%82a%C4%87-logi-z-kodi
