### ISSUE TITLE
Propozycja nowych serwisów

### ISSUE THREAD

**Issue by maxxwell87** [mrknow/filmkodi#180]
Witam czy była by możliwość dodania takich serwisów jak:
ninateka.pl
http://www.kreskowkazone.pl/
http://nasze-kino.eu/
http://teledyski.info/

**Comment by xxcriticxx** [comment]
serwisy z sd-xbmc.org

**Comment by plumers** [comment]
serwisy muzyczne jak eska go i inne ... southpark

**Comment by zjac** [comment]
Nowe serwisy,może jak ogarniecie przepustowość serwera ? Dacie nowe, i znowu będa problemy...

**Comment by xxcriticxx** [comment]
zjac nasz server nic nie nadaje tylko ma pliki to wtyczki

**Comment by zjac** [comment]
to skąd zwiechy wtyczki ?

**Comment by xxcriticxx** [comment]
co?

**Comment by zjac** [comment]
Skąd zwisy przy próbie załadowania strony np. Telewizjady

**Comment by xxcriticxx** [comment]
wtyczka laczy strone telewizjady z twojm tv

strona wyswietla wtyczka dziala strona przestanie wyswietlac wtyczka przestanie nadawac i service jest dead

na serrwerach sa tylko pliki do wtyczek niema zadnych streamow korzystamy z obcych serwisow 

niewma serwisow niema wtyczki w kolko 

server pada wtedy jak wychodzi nowa wersia wtyczki i kazdy chce ja miec wystepuje przeladownaie i wszystko pada

**Comment by zjac** [comment]
TAK ? Zobacz teraz web chodzi, a w KODI nie łączy

**Comment by xxcriticxx** [comment]
umnie wszystko zasuwa tak jak trzeba

**Comment by zjac** [comment]
2 godz 20 minut potem sprawdzasz ... Pasowało by aby ktoś na bieżąco to sprawdzał  to widział by te zatykania wtyczki do telewizjady.

**Comment by xxcriticxx** [comment]
wczoraj zostawilem discovery wlonczony przez cala noc czyli chodzilo okolo 1.5 dnia i bylo ok 

to bylo na win7 na openelec niesety rozlonczylo

**Comment by xxcriticxx** [comment]
zjac ja tobie wierze ze ciebie rozlancza tylko by trzeba bylo pokopac czemu

**Comment by maxxwell87** [comment]
proponuje dodać obsługę tej strony z tv
[https://www.firstonetv.eu/en/countries](url)

**Comment by mrknow** [comment]
nie będzie realizowane to zgłoszenie
