### ISSUE TITLE
epg

### ISSUE THREAD

**Issue by xxcriticxx** [mrknow/filmkodi#181]
niewiem czy pytalem juz czy w ogole sa chetni ale by sie przydal jakis firmowy epg. prosze wyrazac opine ponizej.

**Comment by borys76** [comment]
Po co? sa juz trzy epg

**Comment by borys76** [comment]
https://github.com/en0x/script.etvguide/blob/master/zip/repository.etvguide/repository.etvguide-1.0.5.zip?raw=true

http://ziecina.com/pliki/plugins/script.iamepg.zip

**Comment by xxcriticxx** [comment]
niedluga benda hyba tylko dwie

31 marca 2016 będzie najprawdopodobniej ostatnim dniem generowania pełnej listy epg (epg-full). Być może w najbliższym czasie dotyczyć to będzie również listy krótkiej (standard). Kilka miesięcy temu ruch do plików był na poziomie 100-200 megabajtów dziennie. W tej chwili jest to 10-15 gigabajtów na godzinę! Świadczy to o sporym zainteresowaniu tym projektem. Niestety nie przewidziałem aż takiego obciążenia łącza w tak krótkim czasie i jeżeli nie będę w stanie utrzymać tego projektu z własnej kieszeni to będę musiał go zakończyć. Dlatego proszę o dobrowolne acz stałe wpłaty na poziomie 1 PLN miesięcznie od każdego użytkownika. W tej chwili jest już ok 2-3 tys. osób w miarę regularnie korzystających z list. Nie proszę więc Was o miliony ale o jedną złotówkę raz na miesiąc. Nie trzeba posiadać konta PayPal. Wystarczy posiadać kartę płatniczą. Połączenie jest całkowicie bezpieczne, gwarantowane renomą firmy PayPal. Link po prawej stronie, ikona DONATE.
Pozdrawiam
Darek

**Comment by borys76** [comment]
http://testers-inc.com/test-tv/
Lista do simple

**Comment by gumball1** [comment]
kundel skomle o ''mleko''
