### ISSUE TITLE
Kodi i Telewizjada

### ISSUE THREAD

**Issue by zjac** [mrknow/filmkodi#185]
Czy ktoś może w tym momencie sprawdzić odtwarzanie na Kobi Telewizjady ? Ponownie to samo co mam codziennie od jakiegoś czasu ( w porach  18-20 godz. )

Gra,gra, gr ai nagle JEB: "web request failed"
Oglądam kanał Comedy Central

O co K chodzi ? Nikt nie ma takiego problemu ? Tylko ja ?

**Comment by Adam-po** [comment]
Ja też mam ten sam Problem....
Gesendet von Yahoo Mail auf Android 
 
  Am Mi., 9. Mär. 2016 um 17:35 hat zjac<notifications@github.com> Folgendes geschrieben:   
Czy ktoś może w tym momencie sprawdzić odtwarzanie na Kobi Telewizjady ? Ponownie to samo co mam codziennie od jakiegoś czasu ( w porach 18-20 godz. )

Gra,gra, gr ai nagle JEB: "web request failed"

O co K chodzi ? Nikt nie ma takiego problemu ? Tylko ja ?

**Comment by zjac** [comment]
No Dzięki za info, bo już nie wiem co u siebie sprawdzać,ale jak widać to nie tylko u mnie.

**Comment by Adam-po** [comment]
Od dni nic nie działa niewiem po jaki H.....ne Aktualizację jak na końcu Dupa....

Gesendet von Yahoo Mail auf Android 
 
  Am Mi., 9. Mär. 2016 um 17:45 hat zjac<notifications@github.com> Folgendes geschrieben:   
No Dzięki za info, bo już nie wiem co u siebie sprawdzać,ale jak widać to nie tylko u mnie.

**Comment by milemar** [comment]
u mnie wcale nie dziala, mam error Sportsdevil Info: no stream available

**Comment by xxcriticxx** [comment]
w usa dziala no problem
