### ISSUE TITLE
MRKnow

### ISSUE THREAD

**Issue by karnage11** [mrknow/filmkodi#186]
Any new Beta's or adding anything new to Specto at all ?

**Comment by xxcriticxx** [comment]
mrknow mentioned that he is rewriting the code

**Comment by karnage11** [comment]
@xxcriticxx  what code ?

**Comment by xxcriticxx** [comment]
i guess specto

**Comment by karnage11** [comment]
do you know if he is working to get those other accounts to work at all ?

**Comment by xxcriticxx** [comment]
i don't know his plans sorry

**Comment by xxcriticxx** [comment]
new code i assume smother, faster, lighter kind of deal

**Comment by karnage11** [comment]
ohh alright

**Comment by karnage11** [comment]
you know where i can get premiumize.me voucher code to test it out for 1 month at all ?

**Comment by xxcriticxx** [comment]
nope i use rapidgator

**Comment by karnage11** [comment]
doesnt work with the addons though huh ?

**Comment by xxcriticxx** [comment]
i dont use specto

**Comment by karnage11** [comment]
ohh what do you use  then ?

**Comment by xxcriticxx** [comment]
read above

**Comment by karnage11** [comment]
i saw that i though that was just for an account for extra HD links thats why

**Comment by xxcriticxx** [comment]
50 mb isp i get avg download speed btw 6-8 mb

**Comment by xxcriticxx** [comment]
nope is just file host

**Comment by karnage11** [comment]
ohh got ya

**Comment by xxcriticxx** [comment]
goodnight karnage and good luck

**Comment by karnage11** [comment]
goodnight too you , i am always around lol
