### ISSUE TITLE
tvn player 

### ISSUE THREAD

**Issue by xxcriticxx** [mrknow/filmkodi#188]
na sd-xbmc podaja ze jest blad w API player we wtyczce mr.know

**Comment by addab83** [comment]
Nie działa wtyczka do TVN Playera od ponad 1,5 tyg. Czy to jest problem z repo mr. known czy jakiś globalny problem ? 
Kodi na Philips PFH6550

**Comment by xxcriticxx** [comment]
globalny

**Comment by eko5** [comment]
Dziś przy próbie odpalenia serialu dostałem zwrot 

> Na Kodi nie ma możliwości odtwarzania plików Widevine
> Spróbuj bezpośrednio na tablecie

**Comment by mrknow** [comment]
Tak, na razie nie mam koncepcji jak to obejść. Standardowo kodi nie wspiera widevine, grrrr

**Comment by xxcriticxx** [comment]
slyszalem ze jest nowy auth key z samsunga

**Comment by mrknow** [comment]
Mam nowe klucze do api. Problemem są pliki wideo, które są kodowane w widevine

**Comment by xxcriticxx** [comment]
stym nieda sie nic zrobic

http://miniskrypt.blogspot.com/2014/04/3-w-1.html
http://olesio.eu/downloaders/

**Comment by xxcriticxx** [comment]
But it will run on chromium and chromium will do netflix if you add the widevine libraries.

http://openelec.tv/forum/128-addons/7664...mitstart=0

**Comment by eko5** [comment]
haha niezła jazda po komunikacie 

> Na Kodi nie ma możliwości odtwarzania plików Widevine
> Spróbuj bezpośrednio na tablecie

Mogę normalnie odpalić https://onedrive.live.com/redir?resid=D8627CEEE21EB3F7!53766&authkey=!APR2hS2WGMs3Xz0&v=3&ithint=photo%2cpng

**Comment by xxcriticxx** [comment]
ubuntu?

**Comment by eko5** [comment]
Tak zgadza się , dokładnie Ubuntu 16.04 LTS

**Comment by xxcriticxx** [comment]
nice os!
