### ISSUE TITLE
is there a new update at all ?

### ISSUE THREAD

**Issue by karnage11** [mrknow/filmkodi#189]
is there a new update for Specto yet ?

**Comment by Thewatchfuleye** [comment]
Just updated a few minutes ago. Haven't tested it yet, in the middle of watching something.

**Comment by karnage11** [comment]
whats was the new update for , you know ?

**Comment by Thewatchfuleye** [comment]
Looks like it repairs the Movie database using IMDB

**Comment by karnage11** [comment]
oh alright , Thank you

**Comment by xxcriticxx** [comment]
https://raw.githubusercontent.com/mrknow/filmkodi/dabb1103855befd86c29773d936725f4399e0652/plugin.video.specto/changelog.txt

https://github.com/mrknow/filmkodi/blob/dabb1103855befd86c29773d936725f4399e0652/plugin.video.specto/changelog.txt

+------------------------
+Specto v2016.03.11.3
+------------------------
+Cache repair
+Movies repair - done in 90%
+TV Shows repair  - done in 2%

**Comment by karnage11** [comment]
@xxcriticxx  Thank you , didnt pop up on Specto when i started it up thats why i was asking

**Comment by xxcriticxx** [comment]
i found it by luck

**Comment by karnage11** [comment]
ohh ok lol

**Comment by karnage11** [comment]
@xxcriticxx if you can get in touch with him somehow , and you ask him to fix premiumize.me account on specto

**Comment by xxcriticxx** [comment]
please make new post about it

**Comment by karnage11** [comment]
@xxcriticxx i have the other day
