### ISSUE TITLE
co jest grane z weeb.tv

### ISSUE THREAD

**Issue by xxcriticxx** [mrknow/filmkodi#19]
niby koniec ? jakie sa alternatywy ?

**Comment by mrknow** [comment]
Poczekaj, poczekaj. Strona weeb.tv - to inna wtyczka 
Zainstaluj wtyczkę ze strony weeb.tv http://weeb.tv/, lub z innego dobrego polskiego serwisu wtyczek do kodi http://sd-xbmc.org/.
