### ISSUE TITLE
Telewizjada

### ISSUE THREAD

**Issue by bob10699** [mrknow/filmkodi#191]
Nie działa telewizjada. Po kliknięciu wyskakuje okienko: No stream available. Używam Kodi 16, Windows 7, plugin.video.mrknow-2016.03.05.1. Please help.

**Comment by xxcriticxx** [comment]
niema mnie w domu ale ostatnia plugin hyba jest 3.06 jak sie nie myle

**Comment by bob10699** [comment]
Bazując na tej stronie: http://kodi.filmkodi.com/beta/plugin.video.mrknow/ ostatni plugin jest z 03.05. Nie znam nowszego.

**Comment by xxcriticxx** [comment]
zalogowalem sie domu i mam ver 2016.03.06.3 niewiem czy to ostatnia czy to jest beta

**Comment by borys76** [comment]
U mnie jest 2016.03.06.3 I wszystko dziala

**Comment by bob10699** [comment]
Czy wobec tego mogę prosić o link do tej wersji z 03.06? Zlośliwie się ukrywa gdzieś ta wersja! Dziękuję!

**Comment by borys76** [comment]
Odinstaluj repo wtyczke I z tego repo sprubuj zainstalowac http://filmkodi.com/repository/repository.filmkodi.com.zip

**Comment by bob10699** [comment]
Tak zrobiłem. Po zainstalowaniu repo i kliknięciu dostaje wiadomość: Could not connect to repository. Oczywiście internet i inne wtyczki działają. Wreszcie znalazłem ostatnią wersje plugin.video.mrknow i mam telewizjadę. Teraz mnie gnębi dlaczego repo nie działa!

**Comment by borys76** [comment]
Czesto jest ze repo mrknow nie dziala zostaw jak jest  wkoncu zrobi update po jakims czasie

**Comment by bob10699** [comment]
OK, dzięki za wsparcie!

**Comment by zjac** [comment]
Ja mam notorycznie popołudniami ten problem. Przestałem korzystać z wtyczki i przez web oglądam - bo to, że się pokazuje ten błąd jest już wkurzające.

**Comment by xxcriticxx** [comment]
zjac nigdy nie pytalem skad ty piszesz?

**Comment by zjac** [comment]
Ma to znaczenie dla wtyczki ? Web działa normalnie, wtyczka płata psikusy. Odbieram z PL

**Comment by zjac** [comment]
Wtyczka Telewizjady jest do poprawy ewidentnie - kaszani strasznie, sprawdzone u mnie na 2 łączach i 2 komputerach + u brata ( brat 200 km odemnie ) + u sąsiada: wszędzie telewizjada chodzi dobrze przez przeglądarke, a na wtyczke durne informacje,albo wisi, lub rozłącza kanały.

**Comment by bob10699** [comment]
Nadal problemy z wtyczka!  Telewizjada owszem, dziala ale np. seriale juz nie. Mam ostatnia wersje 03.16.1 wtyczki. Repository nadal niemozliwe do uruchomienia. Wyskakuje okno: Could not connect to repository.

**Comment by xxcriticxx** [comment]
mam 03.16.1 alltube.tv i zobaczto.tv dzialaja w kratke

tvseriesonline.pl sa puste

efilmy.tv wywala error caly czas

**Comment by bob10699** [comment]
Niestety seriale nadal nie dzialaja. Mialem wielka nadzieje ze udalo sie naprawic. Szkoda, ale bede czekal dalej!

**Comment by bob10699** [comment]
Repository nadal daje ten sam bląd: Could not connect to repository! Może to JA coś źle robię bo nie chce mi sie wierzyc aby tak długo był ten sam błąd?

**Comment by mrknow** [comment]
@zjac - mi się wydaje że niektóre linuchy i rasbery pi maja ogólnie problem z m3u8 http://forum.kodi.tv/showthread.php?tid=154016&page=1
Możesz na windzie po testować ?

**Comment by mrknow** [comment]
@bob10699 - pliki wszystkie zawsze są tutaj
http://kodi.filmkodi.com/
A tu wtyczka filmy online mrknow http://kodi.filmkodi.com/plugin.video.mrknow/

**Comment by zjac** [comment]
@mrknow Testuje na windzie: Tablet na win 8.1 32 bity ( czyściutki, jest tam tlyko win + kodi ), PC to win 7 64 bit.

**Comment by bob10699** [comment]
Dokładnie z tych adresow biorę Twoje wtyczki. Niestety repository.filmkodi.com-2.1.0.zip              20-Mar-2016 12:40 nadal nie działa (ten sam błąd), natomiast plugin.video.mrknow-2016.03.20.2.zip ma 50/50 działającą telewizjadę ale NIE działające seriale niestety. Używam win7/64+Kodi16. Szczególnie zależy mi na serialach. Dzięki za zainteresowanie.

**Comment by bob10699** [comment]
Czy jest nadzieja uruchomienie seriali? Jesli nie to moze dobrze byloby to oglosic bo sporo ludzi czeka.

**Comment by mrknow** [comment]
@zjac 
Czy możesz  **advancedsettings.xml** (u mnie jest w  .kodi/userdata/advancedsettings.xml ) ustawić w następujący sposób i przeprowadzić testy ?
```
<advancedsettings>
    <network>
        <buffermode> 0 </buffermode>
        <readbufferfactor>30</readbufferfactor>
        <cachemembuffersize> 104857600 </cachemembuffersize>
    </network>
</advancedsettings>
```
Dasz info ?

**Comment by borys76** [comment]
Advancedsettings pomaga tylko w przypadku VOD
Dla telewizji na zywo nic nie date
Ja mam takie ustawienie 1gb ram android box
<advancedsettings>
  <network>
    <buffermode>1</buffermode>
    <cachemembuffersize>157286400</cachemembuffersize>
    <readbufferfactor>20</readbufferfactor>
  </network>
</advancedsettings>

To Co ty podales uzywam na 2gb ram android box

**Comment by borys76** [comment]
Advancedsettings pomaga tylko w przypadku VOD
Dla telewizji na zywo nic nie daje
Ja mam takie ustawienie 1gb ram android box
<advancedsettings>
    <network>
        <buffermode> 1 </buffermode>
        <readbufferfactor>20</readbufferfactor>
        <cachemembuffersize> 157286400</cachemembuffersize>
    </network>
</advancedsettings>
To Co ty podales uzywam na 2gb ram android box
I dziala dobrze w przypadku ogladania filmow

**Comment by borys76** [comment]
Twoje dane jest bardziej Dla 2 gb ram

**Comment by zjac** [comment]
@mrknow jak nie zapomnę to po świętach - nie mam teraz jak

**Comment by oomek** [comment]
Czy jest szansa na naprawienie tej kapryśnej Telewizjady? Rzadko kiedy działa a ostatnio to nawet thumbnaile kanałów przestały się ładować.

**Comment by bob10699** [comment]
Czy strona telewizjada.net nie działa już?

**Comment by borys76** [comment]
Cos dzisiaj nie dziala

**Comment by oomek** [comment]
No nieeeee, a tak było już fajnie, ktoś wie coś czemu strona padła?

**Comment by mrknow** [comment]
Już działa
