### ISSUE TITLE
Specto not updating TV shows 

### ISSUE THREAD

**Issue by djdaxinspain** [mrknow/filmkodi#192]
Hi! 
First of all thank you for your brilliant add on! 
I am having trouble with my TV shows... I have added both the Movies and the TV Shows folder to my Kodi library. If I manually search for new episodes in Specto, I can find them, but they are not automatically added to my library. I have tried reinstalling Kodi, Specto and reset settings etc. I use trakt.tv to keep track of watched episodes and I imported my trakt library  to  Specto to have it all there. Please help!

**Comment by Thewatchfuleye** [comment]
The newest update says they're only 2% done fixing the TV show side.

**Comment by karnage11** [comment]
its working for me
