### ISSUE TITLE
wypadki samochodowe

### ISSUE THREAD

**Issue by xxcriticxx** [mrknow/filmkodi#194]
http://fukk.pl/

moze ma ktos ochote dodac wypadki do wtyczki?

**Comment by zjac** [comment]
Ost. aktualizacja na tej śmiesznej stronie w listopadzie 2015, strona definitywnie umiera, a Ty chcesz wtyczkę ? PO CO ?

**Comment by xxcriticxx** [comment]
podaje nowe pomysly nie wszystkie benda we wtyczce. jestem otwarty na twoje pomysly

**Comment by plumers** [comment]
http://wizja.tv

**Comment by xxcriticxx** [comment]
@plumers masz moze stream do discovery w HD?

**Comment by plumers** [comment]
nie mam nic ---tylko to co podaję

**Comment by zjac** [comment]
@plumers nic nowego z ta wizja.tv - to co oni tam mają to bieda,aż piszczy .... Po co takiego następnego gniota dawać, który pewnie zniknie za kilka tygodni.

**Comment by plumers** [comment]
gniota masz w spodniach nie komentuj tylko znajdź coś lepszego --- amen

**Comment by zjac** [comment]
@plumers po co szukać jak masz to co podałeś w kilku TV, któe już są we wtycze ... kolejny raz to samo ?
