### ISSUE TITLE
yoy.tv i cyberms.pl

### ISSUE THREAD

**Issue by xxcriticxx** [mrknow/filmkodi#196]
na androidzie mam dwie nowe tv ktorych niemam na win7

ver wtyczki 03.11.03 jest taka sama

**Comment by borys76** [comment]
Ja na androidzie ich nie mam :(

**Comment by mrknow** [comment]
Yoy.tv - tu będzie bardzo ciężko. Stosują jakiś sposób autentykacji po nawiązaniu połączenia z kanałem. jest około 10% szans że to rozwalę 
Napisze dzisiaj na http://stream-recorder.com/ - może ktoś mi tam pomoże ...

**Comment by mrknow** [comment]
Cybrems - dodane, resztę w #174
