### ISSUE TITLE
Telewizja ie działa większość serwerów

### ISSUE THREAD

**Issue by ghost** [mrknow/filmkodi#197]
Witam
Nie działają mi wszystkie serwery, tylko Telewizjada działa poprawnie. W niektórych jest no stream available, lub pisze na dole po prawej prosze czekac i znika albo całkowicie zawiesza się kodi . To samo jest na windowsie i androidzie?
Można to naprawić

**Comment by xxcriticxx** [comment]
tak jest od czasu do czasu jak na stronie sie cos zmienia

**Comment by asweryu** [comment]
A czy ma coś do rzeczy napis niektóre kanały działają z nowym librtmp
http://images76.fotosik.pl/427/6e17170f14f76e57.jpg

**Comment by xxcriticxx** [comment]
@asweryu uzywasz android czy win?

**Comment by asweryu** [comment]
@xxcriticxx  na androidzie i Windowsie jest to samo

**Comment by xxcriticxx** [comment]
zrob sobie update librtmp na windowsie i zobacz czy czy jest roznica 

i tak wszyscy siedza na telewizjadzie

**Comment by asweryu** [comment]
Pobrałem z tej strony:
https://seo-michael.co.uk/how-to-update-to-latest-librtmp/
I dalej żadnen serwis nie działa

**Comment by xxcriticxx** [comment]
moment zaraz sprawdze dopiero wstalem

**Comment by xxcriticxx** [comment]
tak wyglonda ze mr know zrobil wiosene porzadki. ja mam tylko iklub itivi looknijtv pivoto.pl scrreen-tv i telew. 

pivotv.pl i screen-tv nie pracuja

**Comment by asweryu** [comment]
@xxcriticxx  dzięki za odpowiedzi. Nie wiem tylko czy dobrze zrobiłem update Librtmp ale poczekam na aktualizacje to może serwisy zaczną działać.

**Comment by plumers** [comment]
do euro to wszystko zamkną ) MrKnow po prostu robi to , co potrzeba ... :) pozdro

**Comment by mrknow** [comment]
Wszystkie serwisy popadały Dodajcie serwisy o których nie wiem a które nalezy dodać

**Comment by xxcriticxx** [comment]
@mrknow  cinema-tv.xyz i http://wizja.tv co plumers podal 

czy jest szansa na cos platnego tak jak polsky.tv albo telezon.tv?

uzywa ktos jeszcze weeb.tv?

**Comment by mrknow** [comment]
wizja.tv - pracę ruszyły. Łatwo nie idzie bo kryją się za cloudflare, ale to bardziej kwestia dziś lub jutro

**Comment by mrknow** [comment]
OK Wizja.tv - powinna działać, na razie mam taki objaw że po zakończeniu oglądania, należy odczekać ok 2 minuty (jest błąd - ktoś korzysta już z tego IP)
http://kodi.filmkodi.com/beta/plugin.video.mrknow/plugin.video.mrknow-2016.03.19.2.zip

**Comment by xxcriticxx** [comment]
good job wizja chodzi!

**Comment by plumers** [comment]
http://lajf.tv kolejny serwis malo kanałów ale śmigaja od strzała ---- pozdro

**Comment by xxcriticxx** [comment]
@plumers dobry z ciebie sherlock holmes :)

**Comment by maryanek** [comment]
Działa mi tylko Telewizjada... Robię coś nie tak, czy to normalne? Wszedzie albo 'web serwer error response', albo po prostu brak reakcji po kliknięciu na nazwę kanału (obojętnie z której, innej niz telewizjada strony).

Prosze o pomoc.

**Comment by plumers** [comment]
jaka wersja kodi - jaka wersja wtyczki MRKnow ???-----> nic nie napisałeś - wszystko smiga co podane jeżeli jest web serwer error ,to strona nie hula ..

ZAPAMIĘTAJCIE - MrKnow -to tylko człowiek , który za frajer poświęca swój czas aby zadowolić polski naród ,który malo zarabia aby płacić premium za kablówkę itp :D pozdro .

**Comment by maryanek** [comment]
Jasne. Już pisze dokładnie (dopiero zaczynam używac Kodi):
Windows 7 x64
Kodi 16.0 git
Wersja wtyczki: 2016.03.20.5

Dołaczam logi z proby otwarcia 2 serwisow. Trzeci nie ładuje w ogole kanałów (web request faild) - looknij-tv.

[kodi-wizja.txt](https://github.com/mrknow/filmkodi/files/183707/kodi-wizja.txt)
[kodi-screen.txt](https://github.com/mrknow/filmkodi/files/183708/kodi-screen.txt)

**Comment by JohnBBC** [comment]
no wizja.tv nie działa :(

**Comment by xxcriticxx** [comment]
poprawka potrzebna

**Comment by mrknow** [comment]
Wizja.tv - poprawiona w wersji 2016.03.22.2
