### ISSUE TITLE
nie działa nowa wersja

### ISSUE THREAD

**Issue by wjj1** [mrknow/filmkodi#2]
Witam, dziś zrobiłem aktualizacje mrknow do wersji  20151128 i po aktualizacji nie działa, nie chce się uruchomić, posiadam kodi 15,2 wcześniej nie było problemów.

**Comment by adaski8** [comment]
Wersja po akttualizacji wywala blad ale tylko na androidzie na windzie ok. W logu kodi bledy .

**Comment by adaski8** [comment]
Dokladnie w lini 864 i 189 w default.py  komunikat

**Comment by adaski8** [comment]
Parser object has no atribute getParams

**Comment by mrknow** [comment]
Witam 
Nowa wersja 2015 11 29 powinna rozwiązać ten problem. Proszę o sprawdzenie czy po aktualizacji nadal występują błędy.

**Comment by nica81** [comment]
Witam, nie wiem czy temat został już zamknięty ale mam mediabox z kodi i od ok 3 czy 4 dni wtyczka mrknow.pl nie działa :-( nie mam problemu z otwieraniem na laptopie ale problem wystąpił na urządzeniu z androidem. Czy ktoś mógłby mi pomóc ? nie wiem czy to wina aktualizacji i czy mogę coś zrobić aby spróbować to sama naprawić. Zależy mi aby oglądać polskie programy na dużym ekranie :)

**Comment by wjj1** [comment]
nadal nowa wersja nie działa.
