### ISSUE TITLE
www.eska.tv/player

### ISSUE THREAD

**Issue by xxcriticxx** [mrknow/filmkodi#200]

**Comment by mrknow** [comment]
A nie lepiej dodać http://www.eskago.pl/tv

**Comment by xxcriticxx** [comment]
free material jest tylko w 360p chyba czasu nie bedziemy marnowac

**Comment by mrknow** [comment]
EskaGo powinna działać - tu można sprawdzać 
http://kodi.filmkodi.com/beta/plugin.video.mrknow/plugin.video.mrknow-2016.03.19.1.zip

**Comment by mrknow** [comment]
Dodane
