### ISSUE TITLE
Telewizja obsługiwana przez MrKnow

### ISSUE THREAD

**Issue by zjac** [mrknow/filmkodi#202]
Czy  mi się wydaje, czy jeszcze wczoraj było więcej TV we wtyczce ?
Dzisiaj mam raptem 7 tvonline.

Wg. opisu na stronie powinno być:
– Cinema-tv.xyz [wkrótce]
– Darmowe.tv
– Filmbox.tv
– iKlub.net
– Itivi.tv
– Looknij.tv
– Piovotv.pl
– Screen-tv.pl
– Telewizjada.net
– Typertv.com.pl
– Vidtv.pl
– Zobacz-tv.eu

Na pewno miałem Zobacz-tv.eu i cos jeszcze, teraz jakos mniej ...

Jest gdzieś jakieś info co znika/pojawia się w aktualizacjach ?

**Comment by xxcriticxx** [comment]
https://github.com/mrknow/filmkodi/issues/197

 mrknow commented 4 hours ago

Wszystkie serwisy popadały Dodajcie serwisy o których nie wiem a które nalezy dodać

**Comment by mar2016** [comment]
Wizja.TV

**Comment by zjac** [comment]
Ponowie pytanie: "Jest gdzieś jakieś info co znika/pojawia się w aktualizacjach ?"

**Comment by xxcriticxx** [comment]
nope

to co nie dziala przewaznie znika

**Comment by mrknow** [comment]
OK - aktualizację informacji na stronię zostawie sobię na przyszły weekend. Teraz skupiam się aby dodać Wizja.TV

Niestety chowają się za cloudflare i na razie jeszcze mi nie działa, ale to kwestia: dzisiaj lub jutro

**Comment by mrknow** [comment]
OK Wizja.tv - powinna działać, na razie mam taki objaw że po zakończeniu oglądania, należy odczekać ok 2 minuty (jest błąd  - ktoś korzysta już z tego IP)
http://kodi.filmkodi.com/beta/plugin.video.mrknow/plugin.video.mrknow-2016.03.19.2.zip

**Comment by mrknow** [comment]
#197
