### ISSUE TITLE
Nowa strona z telewizją http://pierwsza.tv/ 

### ISSUE THREAD

**Issue by mrknow** [mrknow/filmkodi#206]
http://pierwsza.tv/player/watch/38

**Comment by xxcriticxx** [comment]
mrknow hyba spania to dzisaj nie bylo?

**Comment by borys76** [comment]
Chyba nie juz ze 3 updates dzisiaj bylo

**Comment by borys76** [comment]
Kiedy wtyczka :)

**Comment by xxcriticxx** [comment]
soon

**Comment by mrknow** [comment]
#278 - tutaj będę kontynuował wątek
