### ISSUE TITLE
Żadna wtyczka nie działa

### ISSUE THREAD

**Issue by rafal1231** [mrknow/filmkodi#208]
Żadna wtyczka nie chce mi działać, wykakuje zawsze ten sam błąd. logi

http://pastebin.com/DK162qDU
http://pastebin.com/8Z0i3NRB

**Comment by mrknow** [comment]
W logach jest informacja  że masz w nazwie użytkownika ( polskie znaki C:\Users\Rafa**ł**), to jest przyczyna problemu.
Jeżeli będziesz miał użytkownika bez polskich liter będzie działać

Moja wtyczka na razie tego nie obsługuje

 https://github.com/mrknow/filmkodi/wiki/FAQ

**Comment by rafal1231** [comment]
Dzięki!! 

    22:17 niedziela, 2016-3-20, mrknow <notifications@github.com> napisał(a):
 
 

 Closed #208.—

**Comment by rafal1231** [comment]
Zmieniłem z Rafał na Rafal i dalej ten sam błąd wyskakuje :/ Co może być powodem?

**Comment by rafal1231** [comment]
Zmieniłem z Rafał na Rafal i dalej ten sam błąd wyskakuje :/ Co może być powodem?
 

    6:04 poniedziałek, 2016-3-21, Rafał Szymański <rafaszymanski65@yahoo.pl> napisał(a):
 
 

 Dzięki!! 

    22:17 niedziela, 2016-3-20, mrknow <notifications@github.com> napisał(a):
 
 

 Closed #208.—
