### ISSUE TITLE
itivi.tv domain change 

### ISSUE THREAD

**Issue by xxcriticxx** [mrknow/filmkodi#216]
http://itivi.pl/program-telewizyjny/

**Comment by mrknow** [comment]
Dodane do wersji beta

**Comment by xxcriticxx** [comment]
link?

**Comment by mrknow** [comment]
Zawsze wersje beta leżą na http://kodi.filmkodi.com/beta/plugin.video.mrknow/

Wystarczy zainstalować tylko 1 plik http://kodi.filmkodi.com/beta/plugin.video.mrknow/plugin.video.mrknow-2016.03.22.1.zip

**Comment by mrknow** [comment]
Wdrożone na produkcję
