### ISSUE TITLE
Aktualizacja stream`ów ..

### ISSUE THREAD

**Issue by drjoints** [mrknow/filmkodi#22]
Witam chciałem zapytać o metode aktualizacji streamów konkretenie z looknijTV bo live na stronie działają, natomiast te same kanały z ftyczki np.  kuchnia+, tvnstyle.. nie otwierają się..

**Comment by widgetpl** [comment]
jakieś logi ?

**Comment by mrknow** [comment]
Muszę zrobić proces wysyłania logów na np na http://wklej.to. Wtedy będzie można więcej się wywiedzieć. Dodaję funkcje do nowej wersji jako usprawnienie

**Comment by xxcriticxx** [comment]
pastebin.com moze lepiej

**Comment by mrknow** [comment]
jest w FAQ
