### ISSUE TITLE
Bug: Specto problem with trakt

### ISSUE THREAD

**Issue by chrisnikol** [mrknow/filmkodi#221]
Although the Specto say that is authorized seccessfully with my trakt account cant bring any of lists tv-shows or movies that i am having at at my trakt account. When i press the trakt tv-shows menu or the trakt watchlist (movies) and generally with whatever has to do with trakt account nothing happens.
I am running Kodi 16.1 rc1 at Windows 10 OS.
At the log shows these  lines with the error: 
**ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.specto/?action=tvUserlists**
**ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.specto/?action=tvUserlists) failed**
and for movies
**ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.specto/?action=movies&url=traktwatchlist**
**ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.specto/?action=movies&url=traktwatchlist) failed**

You can see the full log with debug on from my system http://xbmclogs.com/pf1scdq8k

**Comment by LJHookem14** [comment]
I'm having exact same issue. The Specto Library submenu inside TOOLS doesn't import Trakt TV Shows or Movies. It also doesn't import IMDb tv watchlist. Only import that works is IMDb Watchlist (movies).
