### ISSUE TITLE
Bład#2

### ISSUE THREAD

**Issue by rafal1231** [mrknow/filmkodi#222]
Pisałem niedawno, że nie odpala mi ta ani żadna inna wtyczka. Odpowiedziałeś, że to przez "ł" w nazwie mojego komputera. Zmieniłem na "l" ale błąd wciąż występuje ten sam. Co może być przyczyną?

**Comment by xxcriticxx** [comment]
zaloz nowego usera bez polskich znakow i testuj 

podaj wiecej info o sprzecie 

podaj log please

**Comment by rafal1231** [comment]
Ok, nowy user zadziałał (zmiana nazwy w panelu sterowania nie zmienia nazwy folderu). Dzięki!

**Comment by xxcriticxx** [comment]
@rafal1231 niewiem czy ty jestes ten sam rafal ale to jusz hyba raz przerabialismy

**Comment by mrknow** [comment]
działa, zamykam
