### ISSUE TITLE
nowa aktualizacja

### ISSUE THREAD

**Issue by Pinol** [mrknow/filmkodi#223]
niedzialaja itivi.pl  wizja.tv ??

**Comment by borys76** [comment]
https://github.com/mrknow/filmkodi/issues/216

**Comment by xxcriticxx** [comment]
@borys76 whats new?

**Comment by borys76** [comment]
Nothing just can't wait for long weekend :)

**Comment by xxcriticxx** [comment]
easter?

**Comment by borys76** [comment]
Yep, good Friday

**Comment by xxcriticxx** [comment]
well enjoy your holiday

**Comment by borys76** [comment]
Thanx
