### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by splasheye** [mrknow/filmkodi#224]
Hi can someone tell me what is the latest version of Specto ?

i am still having issues with Specto marking TV Shows as watched.

Thanks

**Comment by xxcriticxx** [comment]
plugin.video.specto-2016.03.15.1.zip               16-Mar-2016 19:27 

http://kodi.filmkodi.com/beta/plugin.video.specto/plugin.video.specto-2016.03.15.1.zip

------------------------
Specto v2016.03.12.3
------------------------
Cache repair
Movies repair - done in 90%
TV Shows repair  - done in 80%

------------------------
Specto v2016.03.11.3
------------------------
Cache repair
Movies repair - done in 90%
TV Shows repair  - done in 2%

------------------------
Specto v2016.03.06
------------------------
Openload   decodeOpenLoad made by mortael

**Comment by mrknow** [comment]
2016.05.8.4
