### ISSUE TITLE
Propozycje wtyczek

### ISSUE THREAD

**Issue by rafal1231** [mrknow/filmkodi#229]
Świetna robota, wtyczka daje naprawdę duże możliwości! Jeżeli mogę to chciałbym złożyć propozycje dot. tych stron:
Poprawienie Wizja.tv (kanały mało kiedy działają)
vidto.pl
pierwsza.tv
pure-cast.net
typertv.com.pl/
soccer-live.pl i livelooker.com (chodzi mi o wtyczki podobne do Meczyki.pl)

Jaka jest szansa, że takie powstaną i ile mogłoby to zająć? Z góry dzięki :)

**Comment by moras86** [comment]
Kilka z tych serwisów było już we wtyczce, ale zostały usunięte (prawdopodobnie zbyt częste zmiany po stronie serwisów): **vidto.pl**, **typertv**.

**Soccer-live** dostępny jest jako parser tutaj http://sd-xbmc.org/pl/content/parsery-stron-dla-wtyczki-p2p-streams

**Comment by mrknow** [comment]
Jezeli działają - to dodam większość do 2 kwietnia 2016

**Comment by xxcriticxx** [comment]
a co za okazja 2 kwietnia?

**Comment by borys76** [comment]
Weekend, wiecej czasu pewnie 
P.s pure-cast.net maja wtyczke nie ma sensu kopiowac

**Comment by borys76** [comment]
MrKnow ja bym proponowal zrobic wtyczke TVP VOD
Jest na sd-xbmc ale nie dziala od dluzszego czasu
http://vod.tvp.pl

**Comment by xxcriticxx** [comment]
w usa tego nie ogladamy

**Comment by borys76** [comment]
Ja ogladalem jak dzialalo

**Comment by xxcriticxx** [comment]
proxy czy hola?

**Comment by borys76** [comment]
Hola

**Comment by xxcriticxx** [comment]
znasz moja opinie na temat hola

**Comment by borys76** [comment]
Uzywam tylko na android box , na ktorych jest tylko kodi nic wiecej,  po drugie nie obchodzi mnie ze ktos korzysta z mojego neta w danym czasie , Bo ja uzywam tez

**Comment by borys76** [comment]
Uzywam tylko na android box , na ktorych jest tylko kodi nic wiecej,  po drugie nie obchodzi mnie ze ktos korzysta z mojego neta w danym czasie , Bo ja uzywam tez  czyjs

**Comment by xxcriticxx** [comment]
ale placisz ty

**Comment by borys76** [comment]
Nie

**Comment by xxcriticxx** [comment]
zaloz jeszcze proxy to wszyscy z korzystamy

**Comment by borys76** [comment]
Na sd-xbmc maja proxy za pare $ jak potrzebuje to biore od nich

**Comment by xxcriticxx** [comment]
mrknow mial cos zalozyc

**Comment by xxcriticxx** [comment]
sd to wirus!

**Comment by plumers** [comment]
http://cinema-tv.xyz/ działa na nowo  z tym ,że hasło do polszajsowatych kanałów - wiadomo why :)

**Comment by xxcriticxx** [comment]
nie wiadomo why? please tell more

**Comment by plumers** [comment]
bo polszajs sie czepia- a jak haslo to nie widac z zewnątrz :) pozdro

**Comment by xxcriticxx** [comment]
@plumers ja z toba lubie pisac

**Comment by kama2016** [comment]
czy jest mozliwosc dodania HBO GO,kiedys byla taka wtyczka ,ale projekt upadl

**Comment by mrknow** [comment]
NIe mam konta do hbo go. Dodatkowo nie wiem jakiego używają szyfrowania. 

Do tematu wrócę około połwy 2017 roku

**Comment by ch3mn3y** [comment]
I jak? Coś z livelooker.com się zmieniło? Bo obecnie (przynajmniej mi) najlepiej działają ich streamy.
