### ISSUE TITLE
Wtyczka Filmy online

### ISSUE THREAD

**Issue by doggydogg** [mrknow/filmkodi#230]
Po ostatniej aktualizacji nie ma mozliwosci uruchomienia wtyczki na xbmc

**Comment by xxcriticxx** [comment]
podaj wiecej info please

windows/openelec/android?

kodi ver?

log maybe?

**Comment by doggydogg** [comment]
Sprzet to primscube ruby, xbmc, 
Jak podpowiesz gdzie znajde loga to podam

**Comment by xxcriticxx** [comment]
https://github.com/mrknow/filmkodi/wiki/Jak-przes%C5%82a%C4%87-logi-z-kodi


http://kodi.wiki/view/Log_file/Easy

http://kodi.wiki/view/Log_file/File_manager_access

http://iptvlive.org/97-pomoc/98-jak-wyslac-log-file

**Comment by xxcriticxx** [comment]
Prismcube Ruby jaki to ma os?

**Comment by eko5** [comment]
Android .  Frodo Xbmc

**Comment by xxcriticxx** [comment]
dlamnie wyskakuje ze to jakis receiver do satelity

ver frodo troche stara

**Comment by doggydogg** [comment]
dokladnie to satelita jesli chodzi o loga, moge go tutaj wkleic ?

**Comment by xxcriticxx** [comment]
wklej loga na http://xbmclogs.com/#### albo http://pastebin.com/ albo cos tego typu

**Comment by doggydogg** [comment]
http://xbmclogs.com/ptixtvqtd

**Comment by xxcriticxx** [comment]
sprawdz linijke 1927-1937

**Comment by doggydogg** [comment]
widze

**Comment by xxcriticxx** [comment]
sorry net umnie padl! jaka ver kodi? mrknow bendzie musial spojrzec czy ten package brakuje unas czy u ciebie.

**Comment by doggydogg** [comment]
Tak jak pisalem, syplo sie po ostatniej aktualizacji,  XBMC 13.2 Git:20150707-21da8e0

Am 25. März 2016 20:57:49 MEZ, schrieb xxcriticxx <notifications@github.com>:
>sorry net umnie padl! jaka ver kodi? mrknow bendzie musial spojrzec czy
>ten package brakuje unas czy u ciebie. 
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mrknow/filmkodi/issues/230#issuecomment-201461262

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by xxcriticxx** [comment]
nowej ver kodi nie da rady zamontowac?

**Comment by doggydogg** [comment]
niestety nie

**Comment by xxcriticxx** [comment]
zostal tylko mrknow zapytaj ladnie

**Comment by doggydogg** [comment]
Ok, dzieki za poswiecony czas i wesolych

**Comment by xxcriticxx** [comment]
montujesz to na wlasna reke!

http://www.prismcube-community.net/board/forums/prismcube-ruby-blackhole-images.20/

**Comment by doggydogg** [comment]
Tylko co ma mi dac zmiana na blachole? Mam ostatni oficjalny wgrany, to wyraznie cos z wtyczka, skoro przed aktualizsacja dzialala a po juz nir

**Comment by doggydogg** [comment]
Tylko co ma mi dac zmiana na blackhole? Mam ostatni oficjalny wgrany, to wyraznie cos z wtyczka, skoro przed aktualizsacja dzialala a po juz nie

**Comment by xxcriticxx** [comment]
dokladnie delveloper supportuje do przodu a nie do tylu

**Comment by doggydogg** [comment]
Niestety zmiana image nie pomogla

**Comment by xxcriticxx** [comment]
jaki problem?

**Comment by doggydogg** [comment]
Efilmy.tv tez masz script error

**Comment by xxcriticxx** [comment]
tak ale to hyba cos na stronie sie zmienilo bendzie poprawka

**Comment by mrknow** [comment]
naprawione dawno temu
