### ISSUE TITLE
Specto error

### ISSUE THREAD

**Issue by colinlee2016** [mrknow/filmkodi#233]
Specto error since updated to latest release 2016.3.12?

**Comment by colinlee2016** [comment]
After updating to 2016.3.26 - also not working

**Comment by bambo1** [comment]
i had the same problem, i opened the addon settings and clicked "defaults" on settings and now it works fine, why that fixed it i have no idea, but it worked,hope it helps

**Comment by colinlee2016** [comment]
Thanks man! You are a genius!!! Really thank you! Also Specto now is much much better - more sources too! Thanks to MrKnow!

**Comment by bjgood** [comment]
No problems for me since updating to 2016.3.26. Everything works fine. Same profile that I had before updating.
