### ISSUE TITLE
TVNPlayer: Bug when program has seasons to chose.

### ISSUE THREAD

**Issue by cybernetic87** [mrknow/filmkodi#235]
There is a bug when the program has seasons - you can't enter into Episode selections.
Tested on "Usterka". Serials and programs without seasons to chose mostly work ok.
Can you fix it please ?

**Comment by xxcriticxx** [comment]
to my last knowledge tvnplayer was down.

**Comment by cybernetic87** [comment]
TVNPlayer works but not for the programs which have series to choose...

**Comment by xxcriticxx** [comment]
sorry i cant find working proxy to test

**Comment by cybernetic87** [comment]
Aaa, nie wiedziałem, że jesteś Polakiem - to po co CI proxy ? :P Chyba, że mieszkasz za granicą.
Mam VPSa i mogę postawić proxy specjalnie dla Ciebie jeśli chcesz :) i jeśli naprawisz buga z tvnplayerem :)

**Comment by xxcriticxx** [comment]
ja tu tylko sprzatam 

mrknow bendzie spowrotem w sabotem 4/02 to sie zapytaj jego on jest autorem wtyczki

**Comment by plumers** [comment]
-- zajumana porada od kogoś :)  we wtyczce player do tvn-u który odtwarza, to SAMSUNG a wystarczy zmienić na android :) tak zadziałało na innej wtyczce , bo tak samo sypało się API - spróbować warto u mnie na MR TVN zacina po 10s. na innej śmiga full :) 

zmienili chyba kodowanie ale dajmy czas , bo czego człowiek nie potrafi :)

**Comment by mrknow** [comment]
TVN powinien działać, w razie co należy wybrać platforma Android2
