### ISSUE TITLE
Specto Download to NAS Issue

### ISSUE THREAD

**Issue by mobile4357** [mrknow/filmkodi#236]
Thank you for creating Specto !  And thank you for keeping the Favorites, My Specto!! 

I haven't seen a topic about this, so I thought I'd better let you know about this.

On both Kodi Isengard and Jarvis, when setting the download location for Specto to my NAS (SMB Share), I can browse to it and select the share, but then it fails with 'Failure: Check Logs'.... At this point you cannot even launch Specto any more. 

Once I get back into the addon settings again, through video addons, and set downloads to default, it works again.
Is this something that will be addressed in the near future? I'm anxious to get rid of Genesis altogether.

**Comment by ViperRunner** [comment]
Also happens on mine :(

**Comment by mobile4357** [comment]
I know fixes can take time, but it would be great if I could just know that this has been seen, so I can wait for the fix.
Thanks

**Comment by Scotster** [comment]
I've just posted a workaround for this. Hope it helps you as I was in the same situation. Mine is working fine now.

**Comment by mrknow** [comment]
Resolved in #290
