### ISSUE TITLE
Telewizjada nie działa?!

### ISSUE THREAD

**Issue by ozmatox** [mrknow/filmkodi#237]
Cześć na win10 - kodi 17 - wtyczka mr.know w wersji 2016.03.2.22 nie działają kanały telewizjady.
Ogólnie wtyczka jest sprawna na innych urządzeniach, ale na PC przestała.
Po włączeniu dowolnego programu w zakładce telewizjada, w dolnym prawym rogu wyświetla się błąd.
W logu znajduje się taki wpis:
10:23:12 T:7332  NOTICE: [plugin.video.mrknow] LEN: 385
10:23:12 T:7332  NOTICE: [plugin.video.mrknow] mode: 110
10:23:12 T:7332  NOTICE: [plugin.video.mrknow] Local file C:\Users\ozzi\AppData\Roaming\Kodi\addons\plugin.video.mrknow\resources\catchers\__streams.cfg opened
10:23:13 T:7332  NOTICE: [plugin.video.mrknow] Remote URL http://www.telewizjada.net/live.php?cid=2 opened
10:23:13 T:7332  NOTICE: [plugin.video.mrknow] _parseCommands called
10:23:13 T:7332  NOTICE: [plugin.video.mrknow] Get Info from: "http://www.telewizjada.net/get_mainchannel.php" from "http://www.telewizjada.net/live.php?cid=2"
10:23:13 T:7332  NOTICE: [plugin.video.mrknow] _parseCommands called
10:23:13 T:7332  NOTICE: Previous line repeats 1 times.
10:23:13 T:7332  NOTICE: [plugin.video.mrknow] Get Info from: "http://www.telewizjada.net/statistics/statistic.php" from "http://www.telewizjada.net/live.php?cid=2"
10:23:13 T:7332  NOTICE: [plugin.video.mrknow] _parseCommands called
10:23:13 T:7332  NOTICE: [plugin.video.mrknow] Get Info from: "http://www.telewizjada.net/get_channel_url.php" from "http://www.telewizjada.net/live.php?cid=2"
10:23:13 T:7332  NOTICE: [plugin.video.mrknow] _parseCommands called
10:23:13 T:7332  NOTICE: [plugin.video.mrknow] Get Info from: "http://www.telewizjada.net/set_cookie.php" from "http://www.telewizjada.net/live.php?cid=2"
10:23:13 T:7332  NOTICE: [plugin.video.mrknow] _parseCommands called
10:23:13 T:7332  NOTICE: Previous line repeats 2 times.
10:23:13 T:7332  NOTICE: [plugin.video.mrknow]     -> 1 item(s) found
10:23:13 T:7332  NOTICE: [plugin.video.mrknow] End of directory
10:23:13 T:3308   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.mrknow/?item=catcher%3Dstreams%26url.tmp%3D2%26title%3DTVP%2B2%26url%3Dhttp%253A%252F%252Fwww.telewizjada.net%252Flive.php%253Fcid%253D2%26videoTitle%3DTVP%2B2%26director%3DTelewizjada%26referer%3Dhttp%253A%252F%252Fwww.telewizjada.net%252Flive.php%253Fcid%253D2%26definedIn%3Dtv%252Ftelewizjada.net.cfg%26icon.tmp%3D%255C%252Fmedia%255C%252Fstream%255C%252Fimg%255C%252Ftvp2.png%26icon%3Dhttp%253A%252F%252Fwww.telewizjada.net%255C%252Fmedia%255C%252Fstream%255C%252Fimg%255C%252Ftvp2.png&mode=110
10:23:13 T:7332   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'PLAYER_CORE_AUTO'
                                            Traceback (most recent call last):
                                              File "C:\Users\ozzi\AppData\Roaming\Kodi\addons\plugin.video.mrknow\default.py", line 920, in <module>
                                                init.showListOptions(sys.argv)
                                              File "C:\Users\ozzi\AppData\Roaming\Kodi\addons\plugin.video.mrknow\default.py", line 270, in showListOptions
                                                self.playVideo(videos[0], True)
                                              File "C:\Users\ozzi\AppData\Roaming\Kodi\addons\plugin.video.mrknow\default.py", line 514, in playVideo
                                                xbmc.Player(self.getPlayerType()).play(url, listitem)
                                              File "C:\Users\ozzi\AppData\Roaming\Kodi\addons\plugin.video.mrknow\default.py", line 520, in getPlayerType
                                                return xbmc.PLAYER_CORE_AUTO
                                            AttributeError: 'module' object has no attribute 'PLAYER_CORE_AUTO'
                                            -->End of Python script error report<--
10:23:13 T:3308   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mrknow/?item=catcher%3Dstreams%26url.tmp%3D2%26title%3DTVP%2B2%26url%3Dhttp%253A%252F%252Fwww.telewizjada.net%252Flive.php%253Fcid%253D2%26videoTitle%3DTVP%2B2%26director%3DTelewizjada%26referer%3Dhttp%253A%252F%252Fwww.telewizjada.net%252Flive.php%253Fcid%253D2%26definedIn%3Dtv%252Ftelewizjada.net.cfg%26icon.tmp%3D%255C%252Fmedia%255C%252Fstream%255C%252Fimg%255C%252Ftvp2.png%26icon%3Dhttp%253A%252F%252Fwww.telewizjada.net%255C%252Fmedia%255C%252Fstream%255C%252Fimg%255C%252Ftvp2.png&mode=110) failed.

Jak odinstaluję wtyczkę i na nowo zainstaluje  to też nie działa.
Czysta instalacja kodi + backip z działającej wersji nie pomaga???
Wtyczka SD-XBMC z telewizjadą działa.
Ten problem miałem już kilka razy z różnymi wtyczkami, 
co jest przyczyną? jak to naprawić w szybki sposób bez deinstalacji KODI?

**Comment by xxcriticxx** [comment]
to hyba cos u ciebie na windows 7 dziala

**Comment by ozmatox** [comment]
znalazłem....mój błąd na wersji kodi 17 nie działa wróciłem do 16RC2 i działa wyśmienicie.

**Comment by xxcriticxx** [comment]
staraj sie uzywac Stable release 16.0 / 20 February 2016; 38 days ago

na RC2 build jeszcze zawczesnie ma za duzo bugs

**Comment by mrknow** [comment]
Działa
