### ISSUE TITLE
nocnyseans.pl  Propozycja Nowego Serwisu 

### ISSUE THREAD

**Issue by eko5** [mrknow/filmkodi#238]
Sprawdził by ktoś czy  da się dołożyć do kodi ten serwis

**Comment by xxcriticxx** [comment]
to jest jusz hyba w planach albo bylo

**Comment by eko5** [comment]
Jeśli jest w planach dodania to super , bo z tego co pamiętam to nie było .

**Comment by xxcriticxx** [comment]
sie dowiemy jak mrknow sie pokaze

**Comment by Adam-po** [comment]
Gdzie znajdę na Kodi.....Pitbull nowe porządki...? Nigdzie niema stream...Cda albo zalukaj.TV,specto poprostu nigdzie...

Gesendet von Yahoo Mail auf Android 
 
  Am Di., 29. Mär. 2016 um 14:38 hat eko5<notifications@github.com> Folgendes geschrieben:   
Sprawdził by ktoś czy da się dołożyć do kodi ten serwis

**Comment by xxcriticxx** [comment]
tego jeszcze niema! zawczesnie wszystko co jest to jest fake!

stop hijacking subjects!!!

**Comment by Adam-po** [comment]
Czego jeszcze niema?  Inne filmy są po 6 tygodniach online a Pitbull?

Gesendet von Yahoo Mail auf Android 
 
  Am Fr., 1. Apr. 2016 um 13:20 hat xxcriticxx<notifications@github.com> Folgendes geschrieben:   
tego jeszcze niema! zawczesnie wszystko co jest to jest fake!

stop hijacking subjects!!!

**Comment by xxcriticxx** [comment]
adam-po temat jest o nocnyseans.pl a nie pitbullu.

otworz nowy temat to pogadamy

**Comment by Adam-po** [comment]
Hej mam Pytanie jest Możliwość Pooglądać gdzieś przez Kodi.... Pitbull nowe porządki..... Szukam i nic....bez premium to lipa...a do kina nie mogę bo w Polsce nie jestem.

**Comment by mrknow** [comment]
Error 404
