### ISSUE TITLE
Itivi we wtyczce MrKnow

### ISSUE THREAD

**Issue by zjac** [mrknow/filmkodi#239]
Wchodzi w TV Online, we wtyczkę Itivi a tam burdel jak nie wiem - oprócz kanałów TV cholerka wie co ... niby alfabetycznie ułożone, a nie idzie dojść co jest live tv, a co jakimś chłamem.

**Comment by xxcriticxx** [comment]
to sa filmy odpal jeden to zobaczysz

**Comment by zjac** [comment]
OK, to, że filmy, to wiem, ale dlaczego są w TV Online, a nie w "Filmach" ?

**Comment by xxcriticxx** [comment]
wejdz na http://itivi.pl/ i zobacz co widzisz za kanalami tv

to jest taki ala VOD

**Comment by plumers** [comment]
idiot!!!!!!!!!!!!!!!!!!! kolejny temat bez sensu

**Comment by zjac** [comment]
@plumers  lecz swoje kompleksy gdzie indziej.

**Comment by mrknow** [comment]
postaram się to posprzątać

**Comment by mrknow** [comment]
Na razie nie będę tego poprawiał. Brak znaków szczególnych aby odsiać filmy
