### ISSUE TITLE
PORNOGRAFIA !!!

### ISSUE THREAD

**Issue by gumball1** [mrknow/filmkodi#24]
TAKA FAJNA WTYKA BYLA !!! TERAZ ZAWIERA KANALY PORNO DLA EROTOMANOW !!!

**Comment by xxcriticxx** [comment]
parental control trzeba było zrobić

**Comment by mrknow** [comment]
A możesz dokładniej napisać o jakich kanałach piszesz i w jakiej telewizji ?
parental control - dobry pomysł. Pomyślę jak to zrealizować

**Comment by gumball1** [comment]
Czesc MrKnow. W telewizjadzie sa trzy landrynki - hustler, private, redlight . Nie ma jak tego zblokowac a przeciez z wtyczki korzystaja rodziny z dziecmi. Strach dopuscic dzieciaka do minimini+ czy tvp abc :)
Pozdrawiam.

**Comment by xxcriticxx** [comment]
http://www.tvaddons.ag/parental-controls-kodi/

**Comment by mrknow** [comment]
Jasne. Postaram się szybko naprawić ten problem

**Comment by luki199112** [comment]
Witam. Jest możliwość w jakikolwiek sposób usunąć te kanały z listy?

**Comment by mrknow** [comment]
Witam 
Dodałem opcję do ustawień - domyślnie wyłączone jest pokazywanie kanałów dla dorosłych. Dzisiaj (za kilka godzin) wrzucę na serwery nową wersję  wtyczki. To powinno wystarczyć

**Comment by xxcriticxx** [comment]
jakis pin/code/password by sie przydal zeby otworzyc filmy dla doroslych

**Comment by mrknow** [comment]
Na razie nie będę dodawać kodu pin. Skupiam się na serwisach z serialami  i   filmami dokumentalnymi
