### ISSUE TITLE
Przerywanie oglądania w filmy-Online podczas przewijania

### ISSUE THREAD

**Issue by coycoyote** [mrknow/filmkodi#240]
Witam, niedawno zainstalowałem najnowszy OSMC z zainstalowałem paczkę mrknow. Problem mam z filmami online z zalukaj lub cda. Jeżeli chcę przewinąć film dalej bądź wznowić oglądanie to wywala mnie do OSMC. Mogę jedynie rozpocząć film od nowa. Zmieniałem playery w ustawieniach, szukałem czegoś w opcjach ale nic nie znalazłem. Ma ktoś może podobny problem ?

**Comment by xxcriticxx** [comment]
masz hard drive? czy tylko eMMC?

**Comment by coycoyote** [comment]
nie mam dysku, system siedzi na karcie pamięci  a całość oczywiście na Rasperry Pi 3

**Comment by xxcriticxx** [comment]
karta spora? mozesz zapisywac do karty tak zwane cache.

albo jak masz usb drive zrobic z tego ala mini hard drive

**Comment by coycoyote** [comment]
kartę mam małą, zmienię kartę na większą i zobaczę jak to działa. Czy zapisywanie cache jakoś włącza  się specjalnie. Zastanawiam się jeszcze czy nie jest to wina wolnego internetu (około 4Mb download 1Mb upload) ?

**Comment by widgetpl** [comment]
Podejrzewam że to wina internetu. U mnie przewijanie działa do x8 przy x16 też mi się zwiesza i czasami muszę ubić proces ( net 50/50 Mb )

**Comment by coycoyote** [comment]
coż, kartę wymienię na większą. W przyszłym roku kończy się umowa z obecnym operatorem a w domu mam już światłowód z tym że jeszcze nie podpięty, Mam nadzieję że przy pakiecie 1000/20 będzie to jakoś śmigało. Dziękuję za pomoc.

**Comment by xxcriticxx** [comment]
przetestuj z usb 3 daj znac

**Comment by coycoyote** [comment]
ale tu nie chodzi o odtwarzanie z dysku czy pendrive tylko o stream ze stron zalukaj albo cda

**Comment by xxcriticxx** [comment]
jak masz dysk material sie nagrywa pierwszo na dysk. jak masz to na dysku potem mozeszz przewiac

**Comment by coycoyote** [comment]
przerzuciłem cały system na szybką kartę 32GB. Pod USB podpiąłem dodatkowo dysk zewnętrzny 1TB na USB 3.0 i nic to niestety nie pomogło. Dalej podczas streamingu filmu jeżeli go przerwę i chcę odtwarzać od zastopowanego miejsca to się nie da i wywala wszystko. Nie widzę też żeby podczas odtwarzania stream cache'ował coś na dysku bo dioda od dysku świeci stale (jak zapisuje coś lub odczytuje to mruga). Sprawdziłem czy dysk jest dobrze wykryty przez OSMC.
Chyba że cache gdzieś dodatkowo się włącza ?

**Comment by xxcriticxx** [comment]
bendzie troche czytania ja niema malinki zeby przetestowac 

moze ktos na forum pomoze

poszukaj cos na temat zero caching

https://www.google.com/#q=how+to+setup+cache+on+raspberry+pi

https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=73126

http://www.htpcbeginner.com/fix-raspberry-pi-xbmc-buffering-issues/

http://www.htpcbeginner.com/raspberry-pi-openelec-tweaks/

**Comment by coycoyote** [comment]
@xxcriticxx dzięki stokrotne. Miałeś 100% rację, problemem był wyłączony bufor. Poczytałem trochę i już miałem tworzyć plik ręcznie ale znalazłem filmik na YT i zrobiłem wszystko po kolei: https://www.youtube.com/watch?v=ja9MYZvRsd0. Teraz wszystko działa, przewija się, można stopować. Wprost idealnie to działa pomimo że internet nie jest zbyt szybki. Jeszcze raz dziękuję za pomoc i trafną diagnozę. Pozdrawiam

**Comment by xxcriticxx** [comment]
np film sie nam tutaj przyda
