### ISSUE TITLE
People Search is gone

### ISSUE THREAD

**Issue by Beckles83** [mrknow/filmkodi#242]
Quick question,,, in Specto, under Movies there used to be a "People Search" function, I was just wondering if this had been removed to correct a problem with it? I saw another post where someone had mentioned it was not working. I can live without it. Everything else seems to be working ok, I just wondered what the plans for this feature were? If it was coming back or had been removed permanently?

**Comment by mrknow** [comment]
I plan to add this in Specto ver 2016-05-28

**Comment by mrknow** [comment]
I restored People Search
