### ISSUE TITLE
dodac onet vod

### ISSUE THREAD

**Issue by xxcriticxx** [mrknow/filmkodi#244]
http://vod.pl/filmy

**Comment by mrknow** [comment]
DODANY, na razie jako Beta http://kodi.filmkodi.com/beta/plugin.video.mrknow/plugin.video.mrknow-2016.04.01.1.zip

**Comment by eko5** [comment]
`10:00:02 T:140342812731136 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.mrknow/?service=vodpl&name=playSelectedMovie&category=None&title=Postal&url=None&icon=http%3A%2F%2Fm.ocdn.eu%2F_m%2F3d17bc689646740f6c49316fc2c3700e%2C10%2C1.jpg&id1=157754&id2=354088.1255602076&year=2007`

**Comment by xxcriticxx** [comment]
z ver 2016.04.01.3 filmy na przyklad nie dzialaja, seriale w tez w kratke dzialaja

**Comment by Crisever** [comment]
Wersja LITE wtyczki Mrknow na KODI - tylko Telewizjada

Proponowałbym utworzyć wtyczkę Mrknow tylko dla Telewizjady(z tego względu, iż jest ona chyba najpopularniejsza). Mniemam, że ilość pozostałych telewizji np. ITIVI, seriali itd. oprócz Telewizjady ma wpływ na płynność i szybkość działania wtyczki zakładając SZYBKIE DZIAŁANIE PROGRAMU Kodi NIE WE WTYCZCE, a W MENU, dobre łącze internetowe, dobry sprzęt i dobry stream bez zrywania... Oczywiście byłaby to wersja dla chętnych. Nawet niepotrzebne byłyby do niej aktualizacje, a wystarczyłoby jednorazowe wydanie. Pozdrawiam i czekam pozytywną na odpowiedź Mrknow. Myślę, że nie byłoby przy tym dużo pracy, ponieważ wystarczyłoby pousuwać pozostałe rzeczy poza Telewizjadą.
