### ISSUE TITLE
Wersja LITE wtyczki Mrknow na KODI - tylko Telewizjada [część 1]

### ISSUE THREAD

**Issue by Crisever** [mrknow/filmkodi#253]
Proponowałbym utworzyć wtyczkę Mrknow tylko dla Telewizjady(z tego względu, iż jest ona chyba najpopularniejsza). Mniemam, że ilość pozostałych telewizji np. ITIVI, seriali, bajek itd. z wtyczki oprócz Telewizjady ma wpływ na płynność i szybkość działania wtyczki zakładając SZYBKIE DZIAŁANIE PROGRAMU Kodi NIE WE WTYCZCE, a W MENU, dobre łącze internetowe, dobry sprzęt i dobry stream bez zrywania... - Bo jeżeli występuje taka bardzo dobra sytuacja sprzętowo-łącznościowa, a korzystając np. z Telewizjady czy innej telewizji trzeba czekać kilka(kilkanaście) sekund na przełączenie z kanału na kanał czy też na "serfowanie" po wtyczce("Uruchamianie...") - przejście z jednej opcji do drugiej to chyba siedzi przyczyna we wtyczce, z nadmiaru materiału - ilości materiałów, które oferuje... Oczywiście byłaby to wersja dla chętnych. Nawet niepotrzebne byłyby do niej aktualizacje, a wystarczyłoby jednorazowe wydanie. Pozdrawiam i czekam pozytywną na odpowiedź Mrknow. Myślę, że nie byłoby przy tym dużo pracy, ponieważ wystarczyłoby pousuwać pozostałe rzeczy poza Telewizjadą.

**Comment by xxcriticxx** [comment]
pomysl jest

**Comment by Crisever** [comment]
Czekamy na wypowiedź(odpowiedź) odnośnie tej sprawy Mrknow.

**Comment by borys76** [comment]
Ilosc programow w wtyczce nie ma nic do szybkosci przelanczania kanalow w telewizjadzie itp...
Wersja light nic nieda

**Comment by Crisever** [comment]
Więc co ma wpływ na to, że wtyczka działa tak wolno ??? Zakładając bardzo dobre pozostałe warunki do jej pracy o których pisałem wyżej. Może tylko ja tak mam ? Jak jest u Was z szybkością wtyczki ?

**Comment by xxcriticxx** [comment]
ja oglondam na apple tv 1 hyba 9 letni maszyna i dziala 

no fakt ze mam 50 mb internet

**Comment by Adam-po** [comment]
U mnie na FireTv Kodi nie dziala nic. ani jedna wtyczka a telewizjada to Co 5 sec. PuffernOd czasu aktualizacje Lipa

Gesendet von Yahoo Mail auf Android 
 
  Am So., 3. Apr. 2016 um 15:41 hat xxcriticxx<notifications@github.com> Folgendes geschrieben:   
ja oglondam na apple tv 1 hyba 9 letni maszyna i dziala 

no fakt ze mam 50 mb internet

**Comment by xxcriticxx** [comment]
firetv (box) czy firetv (stick)?

jaki masz net?

**Comment by Crisever** [comment]
@xxcriticxx 
Ok działa Ci, ale jak długo trwa przejście z jednego kanału na drugi przez KODI oraz przejście z jednej opcji do drugiej we wtyczce(NIE w menu KODI). Wyniki podaj w sekundach(zmierz).

**Comment by Adam-po** [comment]
FireTv  Stick Internet 6000 DSL przejscie do kanałów bardzo długo....a jak złapie to pochodzi parę sekund in lipa Pufferowanie....ale to tylko w domu.A na przykład jak jestem w Pracy tam jest HotSpot to chodzi jak Burza... Czemu to tak?

Gesendet von Yahoo Mail auf Android 
 
  Am So., 3. Apr. 2016 um 16:21 hat Crisever<notifications@github.com> Folgendes geschrieben:   
@xxcriticxx 
Ok działa Ci, ale jak długo trwa przejście z jednego kanału na drugi przez KODI oraz przejście z jednej opcji do drugiej we wtyczce(NIE w menu KODI). Wyniki podaj w sekundach(zmierz).

**Comment by xxcriticxx** [comment]
Na jakej maszynie? Bo troche tego jest?

**Comment by xxcriticxx** [comment]
@Adam-po zrób speed test na tym twoim DSL please

**Comment by xxcriticxx** [comment]
![image](https://cloud.githubusercontent.com/assets/15007183/14233028/e6d7bdb8-f98a-11e5-9976-8d7275ea6bd7.png)

**Comment by borys76** [comment]
Pufferowanie....ale to tylko w domu.A na przykład jak jestem w Pracy tam jest HotSpot to chodzi jak Burza... Czemu to tak?
Sam odpowiedziales na pytanie
W domu masz h.. owy internet/modem/router

**Comment by borys76** [comment]
@crisever Ok działa Ci, ale jak długo trwa przejście z jednego kanału na drugi przez KODI oraz przejście z jednej opcji do drugiej we wtyczce(NIE w menu KODI). Wyniki podaj w sekundach(zmierz).

U mmnie to od 5 do 8 sec. Zalezy na jakim sprzecie.  to wszystko zalezy od sprzetu , Internetu i ustawien buffora w kodi

**Comment by borys76** [comment]
Wlasnie przelonczylem sie na Hotspot I przelonczenie kanału trwalo 13 sec.
Net Hotspot 10mb w domu mam 50mb

**Comment by borys76** [comment]
Najszybciej przelancza mi na 
Raspberry pi 2 -3 sec
Fire stick- 5 sec
Android TV box 7-8 sec

**Comment by xxcriticxx** [comment]
@borys76 malinka na jakim os? openelec? osmc? raspbian?

Raspberry Pi 3 on sale now at $35

**Comment by borys76** [comment]
Openelec

**Comment by xxcriticxx** [comment]
ohh ok

**Comment by Crisever** [comment]
Ja mam Smart BOXa podłączonego do TV i przełączanie trwa od około 12 do niekiedy 20 sekund. RAM tego BOXa podczas korzystania z KODIEGO dochodzi do trochę tylko ponad połowę możliwości RAM-u... Działanie w systemie BOXa następuje sprawnie bez zacięć i płynnie - reakcja na przejście to 1 sekunda(może mniej)... W KODIM jeszcze mnie niż sekunda - w MENU KODI ! Bo od wejścia we wtyczkę Mrknow zaczynają się schody... Tak wielo-sekundowe oczekiwanie na przejście do następnej opcji we wtyczce oraz przełączanie między kanałami...

@borys76 "ustawien buffora w kodi" - Jakie masz ustawienia bufora w KODIM ? Ja dziś spróbowałem tych: http://filmkodi.com/pl/bufor-przepelniony-osiagnieciem-wymaganego/ ale nic to nie dało.

DLACZEGO @mrknow się nie wypowiada :(

**Comment by xxcriticxx** [comment]
jaka versia kodi? jaki os na smart boxie?

**Comment by xxcriticxx** [comment]
a jak dzialaja inne wtyczki z sd czy phathom?

**Comment by Crisever** [comment]
Korzystam z SPCM bardziej rozbudowanej teoretycznie wersji KODI, ponieważ tylko taka wersja na tym moim sprzęcie działa mi. Wersja 13.4.0(Tylko ta wersja działa). Myślę, że wina nie siedzi w programie tj. KODi, ale być może... Spróbuje z inną wtyczką później.

**Comment by Crisever** [comment]
Wersja BOXa to: Android 4.0.4, Linux 3.0.8.

**Comment by Crisever** [comment]
Jaką inną wtyczkę proponujecie wgrać ?

**Comment by xxcriticxx** [comment]
mysle ze openelec natym napewno bendzie chodzil

**Comment by xxcriticxx** [comment]
albo osmc

**Comment by xxcriticxx** [comment]
probowales SMPC w wersji 16.1.1?

**Comment by Crisever** [comment]
Z SMPC nie idzie ściągnąć wersji 16.1.1 - http://spmc.semperpax.com/ . Ale próbowałem 16.2.0 i wszystkie wcześniejszew dostępne i nie dało rady zainstalować.

**Comment by Crisever** [comment]
Dasz linka skąd ściągnąć najlepiej te wtyczki Openelec lub OSMC ?

**Comment by xxcriticxx** [comment]
no to albo openelec albo osmc sprobuj

ja mam openelec na 10 latnim apple 1 co ma cpu 1 ghz i 250 mb ramu

**Comment by xxcriticxx** [comment]
open i osmc to jest caly os na linuxie nie tylko kodi

**Comment by Crisever** [comment]
Aha rozumiem. Ale która wersja Openleca ? http://openelec.tv/get-openelec Proszę niżej zjechać na tej stronie.

**Comment by xxcriticxx** [comment]
podaj mi model tej box co masz

**Comment by Crisever** [comment]
Medion LiveSmart TV P85251 MD86711

**Comment by xxcriticxx** [comment]
to box czy tv wkoncu?

**Comment by Crisever** [comment]
To jest Box. Sprawdź na internecie.

**Comment by xxcriticxx** [comment]
malo info jest

**Comment by xxcriticxx** [comment]
moze szybcej by bylo ubuntu na usb sticku

**Comment by Crisever** [comment]
Ale pójdzie mi Openelec lub OSMC ? Musze sprawdzić o co chodzi z tym Ubuntu i co to w ogóle jest. Chyba, że w skrócie powiesz co mam robić. Z czym spróbować najpierw.

**Comment by Crisever** [comment]
Z tego co widzę nie ma chyba Openeleca lub OSMC na APK.

**Comment by xxcriticxx** [comment]
na necie strasznie malo info 

masz usb stick z 8gb?

**Comment by xxcriticxx** [comment]
niemasz starego laptop czy czegos? albo jakiegos starego pc?

**Comment by borys76** [comment]
@crisever zainwestuj w raspberry pi albo jakis dobry android box

**Comment by xxcriticxx** [comment]
albo stary pc z piwnicy

**Comment by Crisever** [comment]
Mam starego PC ale ze słabymi parametrami.

Ale Panowie program KODI(SPMC) chodzi płynnie,  sprawnie bez zacięć. Czas reakcji poza wtyczką mrknow to mniej niż sekunda.

**Comment by borys76** [comment]
Zainstaluj wtyczke z weeb tv I zobacz Ile tam czasu ci zajmuje przelonczac kanaly

**Comment by Crisever** [comment]
Dasz linka żeby konkretnie tą dobrą wtyczkę ściągnąć ?

**Comment by xxcriticxx** [comment]
jescze raz ja zamotowalem na 9 letnim apple tv 1 openelec parametry czym starsze tym lepsze :)

http://weeb.tv/xbmc
http://mods-kodi.pl/downloads.php?cat_id=5&download_id=86
http://mods-kodi.pl/downloads.php?cat_id=5&download_id=1

**Comment by borys76** [comment]
http://static.weeb.tv/plugin.video.weeb.tv-0.1.4.zip

**Comment by Crisever** [comment]
Dzięki zaraz zobaczę. Wersja 0.1.4 czy 0.2.0(beta) jest lepsza ?

**Comment by borys76** [comment]
1.4

**Comment by Crisever** [comment]
Zainstalowałem ! I co się okazuje: Przełączanie między kanałami na wtyczce Weeb.tv trwa maksymalnie 5 sekund przy przy 20 sekundowym przełączaniu na wtyczce Mrknow. Widać stąd ewidentnie, że wtyczka Mrknow coś "krzaczy" u mnie.

**Comment by borys76** [comment]
Umnie na weeb.tv I Mrknow-telewizjada tak samo 3-5 sec.

**Comment by Adam-po** [comment]
Jaki jest aktualny link na Mrknow?

Gesendet von Yahoo Mail auf Android 
 
  Am Mo., 4. Apr. 2016 um 14:56 hat borys76<notifications@github.com> Folgendes geschrieben:   
Umnie na weeb.tv I Mrknow-telewizjada tak samo 3-5 sec.

**Comment by Crisever** [comment]
@borys76  No i mam problem... :(

**Comment by Crisever** [comment]
@Adam-po Tutaj masz zawsze najnowszą wersję wtyczek: http://kodi.filmkodi.com/ . Wchodzisz w: "plugin.video.mrknow/ " i później na samym dole najnowsze masz: "plugin.video.mrknow-2016.04.02.1.zip" . NIE ZAWSZE NAJNOWSZE JEST NA SAMYM DOLE. Patrz na datę.

**Comment by Crisever** [comment]
@borys76 Jaką masz wersję wtyczki Mrknow ?

**Comment by borys76** [comment]
04.02.1

**Comment by Crisever** [comment]
Czyli najnowszą. Ale jakby @mrknow zrobił wersję LITE wtyczki tj. tylko Telewizjadę mogę się założyć, że by inaczej hulało... Nawet żeby potestować, a on się w ogóle w tej sprawie nie wypowiada :(

**Comment by borys76** [comment]
Ile ci trwa zmiana kanalow telewizjady na sd-xbmc Wtyczce ?
Moze po prostu jestes daleko od serverow telewizjady

**Comment by Crisever** [comment]
Tyle, że na lapku trwa to sekundy... A korzystam z tego samego neta i na lapku i na Smart BOXie.

**Comment by Crisever** [comment]
@borys76 Jeszcze jakbyś mógł dać link do Wtyczki SD-XBMC.

**Comment by borys76** [comment]
http://mods-kodi.pl/downloads.php?cat_id=5&download_id=1

**Comment by borys76** [comment]
Odrazu mowie umnie trwa tyle samo 3-5sec.

**Comment by Crisever** [comment]
No i Telewizjada u mnie na wtyczce SD-XBMC chodzi jak trzeba ! 5 sekund wczytywania maksymalnie !

**Comment by Crisever** [comment]
Coś wtyczka mrknow nie podchodzi pod mój sprzęt czy sam nie wiem pod co nie podchodzi. Moim zdaniem ilość Oferowanych Materiałów we wtyczce Mrknow ma wpływ na szybkość jej działania. Dlatego prosiłbym o wydanie wtyczki @mrknow tylko z Telewizjadą ! :) Czekamy na głos wydawcy wtyczki :)

**Comment by Crisever** [comment]
Gdybym umiał sam bym zrobił taką wtyczkę only Telewizjada i wypuścił bym ją w świat :)

**Comment by Crisever** [comment]
Ale dziwne, że u Ciebie @borys76 wtyczka chodzi tak jak pozostałe dobrze, a u mnie nie w porównaniu z pozostałymi. Próbowałem z różnymi dostępnymi wersjami z najstarszymi z marca różnicy nie widać może minimalna... Z lutego są niedostępne, tyle że między czasie dochodziło do różnych roszad tak, że nawet kiedyś było więcej TV, ale za to mniej serwisów VOD. Kiedyś wtyczka zajmowała około 2 MB, a teraz ponad 4 MB...

**Comment by borys76** [comment]
Na sd-xbmc tez jest duzo vod,TV itp...
Dla calej rodziny, znajomych instaluje kodi na roznych urzadzeniach I nigdy nie zauwazylem zeby telewizjada   dlugo uruchomiala Kanal
Zainstaluj kodi na pc,laptop I zobacz moze to wina twojego urzadzenia

**Comment by gumball1** [comment]
@Crisever masz jakies gowniane pudelko z adroidem 4.0 na ktorym poza gotham wiecej nie pojdzie
zainwestuj w lepszy sprzet

**Comment by Crisever** [comment]
@gumball1 Całkiem możliwe, tyle że dziwi mnie ta sytuacja, że na innych wtyczkach(SD-XBMC) działa wszystko jak trzeba, a na Mrknow coś niezbyt. Sprzęt całkiem zły nie jest... Poczytaj wszystkie posty wyżej to zobaczysz, że ze sprzętem nie mam ŻADNEGO problemu.

**Comment by borys76** [comment]
Wina sprzetu 100%

**Comment by borys76** [comment]
Na telefonie mobilny net.
https://www.dropbox.com/s/1adg0mr7w6chdz2/2016_04_04_10_23_02.mp4?dl=0

**Comment by gumball1** [comment]
@borys76 dokladnie tak chodzi telewizjada na mrknow

**Comment by borys76** [comment]
Wczoraj jak sprawdzalem na raspberry pi 2 I domowy net 50mb to bylo okolo 3sec. Na telefonie I mobilny net okolo 5sec

**Comment by Crisever** [comment]
Na laptopie i Mrknow i SD-XBMC chodzą dobrze płynnie, ale jak już być dokładnym to z 1 do 2 sekund szybciej działa SD-XBMC.

**Comment by Crisever** [comment]
Wtyczkę SD-XBMC rozwijają ?

**Comment by borys76** [comment]
Czyli znasz odpowiedz na swoj problem

**Comment by borys76** [comment]
@Crisever Wtyczkę SD-XBMC rozwijają ?
Raz w miesiacu jest update

**Comment by borys76** [comment]
@Crisever 
Zainwestuj w raspberry pi 2-3
Zajebisty sprzet

**Comment by Crisever** [comment]
@borys76 Z tego co widzę najnowsza to 2.0.0 ?

**Comment by borys76** [comment]
Repo jest 2.0
Wtyczka jest 23 .3

**Comment by Crisever** [comment]
Czym się różni Repo od Wtyczki ? (Jestem jeszcze w tym zielony).

**Comment by borys76** [comment]
Repo jest potrzebne zeby zainstalowac wtyczke I zeby wtyczka robila update
Bez repo nie zrobi update

**Comment by Crisever** [comment]
Aha dobra już widzę i czaje... Ale tak dokładnie to wersja Wtyczki to 0.23.3 :)

**Comment by borys76** [comment]
Tak czyli marzec 23

**Comment by Crisever** [comment]
Aha ok w taki sposób to działa. Ok dzięki. Mniej więcej co równy miesiąc wydają aktualizacje czy po prostu raz na miesiąc ?

**Comment by borys76** [comment]
Jak mowia na forum to pierwszy weekend miesiaca
Ale w ten weekend cos nie bylo update

**Comment by Crisever** [comment]
Yhm ok dzięki.

**Comment by Crisever** [comment]
Duże poprawki tam robią ?

**Comment by xxcriticxx** [comment]
@borys76 support center otworz!

**Comment by borys76** [comment]
@xxcriticxx nudy w robocie
A support center ty juz prowadzisz to nie bede ci roboty zabierac :)

**Comment by xxcriticxx** [comment]
@borys76 (Marcin B) pomagam w innym projekcje na github wylapujemy reklamy na polskich stronach wpadnij do nas od czasu do czasu 

zapraszam wszystkich

https://github.com/MajkiIT/polish-ads-filter/issues
