### ISSUE TITLE
telewizjada polonczenja

### ISSUE THREAD

**Issue by xxcriticxx** [mrknow/filmkodi#257]
osiagnieto limit polaczen. odzekaj chwile i sprobuj polaczyc sie ponownie. 

sprobuj ponownie

**Comment by Crisever** [comment]
To samo miałem wczoraj. Widocznie za dużo ludzi siedzi na Telewizjadzie jak na te łącza.

**Comment by plumers** [comment]
qwa ludzie ile można klepać jedno ---- teleszasjada juz jest znana w ponad 50% ludzi ,którzy mają neta - każdy siedzi itd więc serwery nie wytrzymują - a boba tyka :D

**Comment by Crisever** [comment]
Masz rację dlatego Telewizjada powinna zrobić opcję dowolnego wsparcia pieniężnego, które to pozwoliłoby na zakup lepszych łącz lub ich poprawienia.

**Comment by plumers** [comment]
Taaa i co jeszcze ---- lepiej MrKnow wesprzeć niż tamtych patałachów - którzy nic nie udostępniają na zywo tylko restream :) LoL
