### ISSUE TITLE
Propozycja: http://pierwsza.tv/

### ISSUE THREAD

**Issue by zjac** [mrknow/filmkodi#258]
Witam.
Czy jest możliwe zrobienie wtyczki do: http://pierwsza.tv/
Jest tam kilka kanałów, których nigdzie nie ma a tam są, np. BBC Brit

**Comment by xxcriticxx** [comment]
cos jak weeb.tv

**Comment by zjac** [comment]
niezupełnie, bo bezpłatny i sprawdzany przez week - ZERO zwiech

**Comment by Crisever** [comment]
Też właśnie na weekendzie patrzyłem na pierwsza.tv i raz że oferta inna choć trochę od pozostałych to i dobrze działa transmisja.

**Comment by xxcriticxx** [comment]
poczekajcie zobaczycie

**Comment by Crisever** [comment]
Co zobaczymy ? Że kiedyś też zacznie zacinać ? Prędzej czy później to czeka każdą TV transmitowaną z neta... Czym więcej ludzi wie tym wiadomo...

**Comment by zjac** [comment]
Póki co działa lepiej niż połowa tych linków, które mam - to chyba warto ? Nawet w weekend ZERO zacięcia.

**Comment by borys76** [comment]
Chodzi dobrze ale na telewizjade tez nie narzekam

**Comment by moras86** [comment]
Jestem za dodaniem tego serwisu. Kanałów całkiem sporo i kilka niedostępnych nigdzie indziej.

**Comment by gumball1** [comment]
Zgadzam sie z poprzednikiem.

**Comment by Crisever** [comment]
Również polecam dodać ten serwis do wtyczki.

**Comment by xxcriticxx** [comment]
duplicate https://github.com/mrknow/filmkodi/issues/206

**Comment by plumers** [comment]
he he coraz zabawniej w świecie piratów :) a pakiety na kablówkach tanieją :p pozdro

**Comment by zjac** [comment]
@plumers nie wiem po co ten troll tu siedzi

**Comment by mrknow** [comment]
#278 - tutaj będę kontynuował wątek

**Comment by piotr19669** [comment]
pierwsza tv pobiera opłaty ale nie daja usługi. Mnie skasowali za 90 dni , mija 3 miesiące i premium nie ma. To zwykłe oszustwo
