### ISSUE TITLE
Anime PL Kodi / Naprawa wtyczki 

### ISSUE THREAD

**Issue by eko5** [mrknow/filmkodi#262]
Tu wielka prośba wtyczka jest forkiem Anime44 i wcale nie działa , dało by radę naprawić wtyczkę aby pobierała i odtwarzała anime . 

Więcej informacji tu http://forum.shinden.pl/threads/16907-Anime-na-XBMC-Kodi

http://xbmc-huball-repository.googlecode.com/svn/trunk/repository.huball.zip

**Comment by mrknow** [comment]
Tu masz aktualną wersję wtyczki https://github.com/huballo/xbmc-huball-repository
