### ISSUE TITLE
Cyfrowy Polsat GO

### ISSUE THREAD

**Issue by xxcriticxx** [mrknow/filmkodi#264]
kto wykupi do testu?

http://www.cyfrowypolsat.pl/cpgo/

**Comment by zjac** [comment]
Trzeba mieć pasy do konta ICOK ? Ile to kosztuje ? za cholerę nie mogę nic znaleźć, dla kogo to ( czy tylko dla abonentów CP )

**Comment by xxcriticxx** [comment]
Nie masz jeszcze telewizji w Cyfrowym Polsacie?

Sprawdź naszą polecaną ofertę i zyskaj dostęp
do 170 kanałów z satelity

59,99 zł /mies.
Zamów ofertę»

Dodatkowo dostęp do telewizji na urządzeniach
mobilnych już za 5 zł/mies.
Masz już naszą telewizję?

Zyskaj dostęp do tysięcy treści na życzenie
bez dodatkowych opłat. Ciesz się telewizją
na urządzeniach mobilnych.

już od  5 zł /mies.

Zadzwoń 801 080 808 i poznaj ofertę
przygotowaną specjalnie dla Ciebie!

**Comment by borys76** [comment]
Musisz byc klijentem polsatu
