### ISSUE TITLE
Wersja LITE wtyczki Mrknow na KODI - tylko Telewizjada [część 2]

### ISSUE THREAD

**Issue by Crisever** [mrknow/filmkodi#268]
Kontynuacja wątku stąd: https://github.com/mrknow/filmkodi/issues/253

Korzystam testowo z płatnej telewizji: GoldVodTV(http://goldvod.tv/) i tam wszelkie czynności uruchamiają się w te pędy(2-3 sekundy)...Przy około 6 do 8 sekund we wtyczce SD-XBMC i około 15 niekiedy 20 sekund we wtyczce Mrknow !!!

Widać stąd, że te wtyczki(SD-XBMC, Mrknow) można przyśpieszyć na miarę wtyczki GoldVodTV :)
P.S. Testowane na tym samym sprzęcie i na tym samym połączeniu internetowym.

**Comment by xxcriticxx** [comment]
@Crisever borys76 mowil ze goldvodtv to smieci

**Comment by borys76** [comment]
@crisever ale ten problem jest tylko u ciebie !! dla ciebie  jednego nikt nie bedzie  dopasowywal  wtyczki pod twoj sprzet

**Comment by borys76** [comment]
@xxcriticxx na goldvod zadko kiedy co dziala ,darmowa telewizjada dziala duzo lepiej

**Comment by mrknow** [comment]
Bardzo fajny pomysł. Myślę że stworzę osobną wtyczkę tylko do telewizji. Wtedy powinno przyspieszyć

**Comment by mrknow** [comment]
Powstała wtyczka MrknowTV
