### ISSUE TITLE
Philips 6650/88  - Android TV | Nie instaluje

### ISSUE THREAD

**Issue by hammer404** [mrknow/filmkodi#27]
W modelu 6650 próba instalacji wtyczki Filmy online – mrknow.pl zostaje przerwana przy 3%.

**Comment by mrknow** [comment]
Proszę prześlij logi błędów jeżeli problem nadal występuję https://github.com/mrknow/filmkodi/wiki/Jak-przes%C5%82a%C4%87-logi-z-kodi

**Comment by hammer404** [comment]
Wczoraj wtyczka zainstalowała się już poprawnie.
