### ISSUE TITLE
cda.pl nie daje rady

### ISSUE THREAD

**Issue by xxcriticxx** [mrknow/filmkodi#270]
W środę (6 kwietnia) nasze serwery po raz kolejny pod naporem kilkuset tysięcy internautów odmówiły posłuszeństwa. Czekamy na nową infrastrukturę, dzięki której mamy nadzieję osiągniemy prędkość światła. Szacujemy, iż nowe serwery będą w stanie udźwignąć 300.000 osób jednocześnie korzystających ze strony. Nowe maszyny będą miały łącznie aż 6144 GB RAM i ultra szybką światłowodową sieć wewnętrzną. Przepraszamy za ostatnie przerwy w działaniu serwisu i dziękujemy za korzystanie z cda.pl

**Comment by Adam-po** [comment]
Przepraszam mam Pytanie..: Jest możliwość Pooglądać Polski Film Pitbull nowe porządki gdzieś na Necie. Nie mieszkam w Polsce......:(

**Comment by xxcriticxx** [comment]
@Adam-po jeszcze niema!
