### ISSUE TITLE
MrKnow - This addon needs an update ASAP! Fix all Trakt/IMDb import features

### ISSUE THREAD

**Issue by LJHookem14** [mrknow/filmkodi#273]
Love this addon especially for TV Shows but it needs some attention. Please fix the import features for Trakt and IMDb for the SpectoLibrary. Thanks!!

**Comment by LJHookem14** [comment]
Thanks for updating!!!

**Comment by mrknow** [comment]
OK. In the second week of May, I plan to improve  trakt.tv  service

**Comment by mrknow** [comment]
Trakt.tv should work correctly . Check out this beta version
http://kodi.filmkodi.com/beta/plugin.video.specto/plugin.video.specto-2016.05.8.2.zip
