### ISSUE TITLE
Losing settings....A Lot !

### ISSUE THREAD

**Issue by uvxcoin** [mrknow/filmkodi#274]
Specto is losing its settings a lot. Like every few hours all the settings I set are gone.
I am running Jarvis and AFTV with all latest updates.

I set up Specto, configure trakt and real debrid and other settings, watch a hour long show and boom all settings are gone.

Please Help! I dont want to have authorize Trakt and Real Debrid and reconfigure everything 2-3 times a night!

**Comment by uvxcoin** [comment]
This is still happening. Is Specto project dead?

**Comment by uvxcoin** [comment]
Still happening. Watching a show last night. Show ended and I clicked on another one and saw no Real-Debrid streams. So I immediately knew all my settings were once again wiped. I have never lost any settings on any other add-on. Sucks to have to stop watching tv and run to the pc and get new codes for real-debrid and trakt and reconfigure Specto . Come on Mrknow! Please address this.

**Comment by mrknow** [comment]
OK 
I will check this issue.

**Comment by mrknow** [comment]
old issue
