### ISSUE TITLE
pierwsza.tv do wtyczki Mrknow

### ISSUE THREAD

**Issue by Crisever** [mrknow/filmkodi#278]
http://pierwsza.tv/
Zero zacięć, a wykupienie premium(abonamentu) też w rozsądnych cenach.

**Comment by eko5** [comment]
#258 wątek już istnieje , propozycja ciekawa , testowałem przez ostatni tydzień i naprawdę fajnie się spisuję .

**Comment by xxcriticxx** [comment]
duplicate #206

**Comment by mrknow** [comment]
No poświęciłem kilkanaście godzin na to szyfrowanie AES i chwilowo się poddałem. 
Temat chwilowo zawieszam, ale jak będę miał więcej czasu w lipcu to się za niego wezmę .

**Comment by mrknow** [comment]
Witam 
Otrzymałem informację że w niedługim czasie będę mógł włączyć pierwsza.tv do swojej wtyczki. 
Telewizja będzie dostępna tylko dla użytkowników premium. Planuje podać więcej szczegółów na początku maja

**Comment by mar2016** [comment]
Po instalacji wtyczki Telewizja Premium wyskakuke blad  INSTALACJA NIEUDANA

**Comment by mrknow** [comment]
jest nowa wersja. Powinno wszystko działac poprawnie. Sprawdziłem na Linux, ATV, Mac

**Comment by piotr19669** [comment]
pierwsza tv istnieje jako wabik na wpłaty subskrypcji, a tan na serio, to niczego nie dają. To oszustwo. Próbowałem testować ale nie ma możliwości otrzymać usługi za pieniądze

**Comment by teleman82** [comment]
Pierwsza to dno i 4 metry mułu .. Ostrzegam przed premium Ja straciłem 19 zł , bez możliwości odzysku kasy.. Nic nie działa.. Lipa i tyle .. No coments...Niech się udławią...
