### ISSUE TITLE
Don't let the whiners get you down, Mr Know

### ISSUE THREAD

**Issue by bjgood** [mrknow/filmkodi#279]
This post is not about an issue, Mr Know. I just wanted to say thank you for all your efforts on Specto. There are many of us who really appreciate it. Don't let the complainers get you down. There are some who act like they actually paid something for this addon and expect you to immediately jump up and fix it...when the problem they are experiencing is probably caused by them not using it properly. Everything is working fine on my end. Keep up the great work.

You have friends and admirers out here, Mr Know.

Regards,
Bob

**Comment by mrknow** [comment]
Thanks for your support. I am the fighter and never give up
