### ISSUE TITLE
yoy.tv

### ISSUE THREAD

**Issue by mar2016** [mrknow/filmkodi#28]
Witam
Jest nowa telewizja calkowicie darmowa yoy.tv
Czy jest mozliwsc dodania jej do wtyczki

**Comment by xxcriticxx** [comment]
yoy.tv jest platna za darmo dziala tylko przez chwile

**Comment by mar2016** [comment]
Wiem  tym ale wiele osob tam wykupilo premium i problemem jest ogladanie na androidzie

**Comment by mrknow** [comment]
nie mam tam konta, ale sprawdzę czy uda mi się dodać obsługę tej strony. W teorii nie powinno być skomplikowane.

**Comment by mar2016** [comment]
da rade dodac yoy.tv

**Comment by mrknow** [comment]
Tak dodamy, może już się uda dodać do 12 marca. Na razie pracuje nad tym  w #174 

Ten wątek zamykam
