### ISSUE TITLE
Downloads/Library location

### ISSUE THREAD

**Issue by piotrekcrash** [mrknow/filmkodi#281]
Currently only location starting with "special://" are supported in Specto settings.
I tried to change location manually in setting.xml but in log I see result:

`Error Contents: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'smb:'`

I.m trying to put SMB location because I have few devices with OpenELEC at home I my idea is to centralize Specto Library location.

**Comment by Scotster** [comment]
I've just posted a workaround for this. Hope it helps you as I was in the same situation. Mine is working fine now.

**Comment by mrknow** [comment]
#290 Solution to this issue

**Comment by piotrekcrash** [comment]
Thanks for Your fix. Is it possible to add customization also for favourites file location?
For me it will be great to keep also this data in one common location and connect there each of Specto instances on different devices.
