### ISSUE TITLE
Problemy z wtyczko filmy online-mr know

### ISSUE THREAD

**Issue by Calvajo** [mrknow/filmkodi#282]
Witam,
jestem mile zaskoczony jak bardzo wtyczka powiększyła swoją bazę filmów. Niestety mam problem, zarówno na kodi na windowsie jak i na android boxie przy włączaniu filmu bądź serialu(efilmy.tv bądź alltube.tv) wyskakuje komunikat: błąd dodatku filmy online-mr know. Na przykład cda albo streamy z telewizją działają bez problemu. Jak można rozwiązać ten problem? Z góry bardzo dziękuję za odpowiedź i pozdrawiam.

**Comment by xxcriticxx** [comment]
https://github.com/mrknow/filmkodi/issues/272 czekamy na mrknow

**Comment by piotrekcrash** [comment]
Myślę , że powinniście dodać wasze logi. To na pewno ułatwi sprawę...

**Comment by xxcriticxx** [comment]
mrknow powiedzial ze rodzina jest dla niego numero #1 a wtyczka to hobby jak jest wolny czas

**Comment by Calvajo** [comment]
A Wy nie macie takich problemów?

**Comment by piotrekcrash** [comment]
Ja właśnie sprawdziłem i u mnie działają wyżej opisane serwisy.

**Comment by xxcriticxx** [comment]
mozliwe ze nie

**Comment by Calvajo** [comment]
Sprawdziłem i mam aktualna wersje. Dziwne bo dzieje się tak na 2 urządzeniach. Może ktoś mi powiedzieć gdzie znaleźć ten log aby go wrzucić?

**Comment by xxcriticxx** [comment]
https://github.com/mrknow/filmkodi/wiki/Jak-przes%C5%82a%C4%87-logi-z-kodi

**Comment by Calvajo** [comment]
Ok, dzięki w takim razie wrzucam. Od 167 linijki zaczyna coś wariować:
http://xbmclogs.com/pidvsytcf

**Comment by xxcriticxx** [comment]
What type of machine?

**Comment by Calvajo** [comment]
Android box Measy b4a. Windows 10 laptop Zenbook Asus.

**Comment by xxcriticxx** [comment]
czekamy na mr know z poprawka

**Comment by Adam-po** [comment]
Co to znowu za błąd nic nie łączy na telewozjadzie....HTTP Error 500........

**Comment by xxcriticxx** [comment]
zjada rady nie daje sprobuj ten sam kanal jeszcze raz

**Comment by Calvajo** [comment]
I jak coś już wiadomo skąd ten błąd?

**Comment by Calvajo** [comment]
XBMC JSON-RPC Error: Invalid params.
(Code: -32602)
Data: (null)

METHOD
Files.GetDirectory

PARAMETERS
{directory="plugin://plugin.video.mrknow/?service=alltubeseriale&name=main-menu&category=Alfabetycznie&title=None&url=None&icon=None&strona=";"file_properties"=(thumbnail);media=video;sort={ignorearticle=0;method=none;order=ascending;};}

**Comment by mrknow** [comment]
Będę 6 i 7 maja poprawiał wtyczkę. Możesz wrzycić logi jeszcze raz bo są dla mnie niedostępne teraz

**Comment by Calvajo** [comment]
Ok dziękuje za informacje, bede czekał :)

W dniu wtorek, 3 maja 2016 mrknow <notifications@github.com> napisał(a):

**Comment by mrknow** [comment]
Dobra mam dostep  przez google cache. Czy ty masz serwer proxy ?. 
W logach zawsze jest  Error Contents: HTTP Error 403: Forbidden

A może antywirus. Możesz sprawdzić, np wyłaczyć antywirusa i spróbować kodi ?

**Comment by Calvajo** [comment]
Używam android boxa na którym nie mam antywirusa. Wczesniej jak opisywałem
problem to wchodząc w alltube wyskakiwał błąd wtyczki mrknow ale po np 5
próbach miałem możliwość wejśćia w film bądź serial, natomiast od około
tygodnia w ogole nie jestem w stanie nic odtworzyć.

W dniu wtorek, 3 maja 2016 mrknow <notifications@github.com> napisał(a):

**Comment by mrknow** [comment]
przeinstaluj kodi na tym urządzeniu
