### ISSUE TITLE
Minix neo x8-h - XBMC Kodi buffering issue @ Telewizjada

### ISSUE THREAD

**Issue by lluuppoo** [mrknow/filmkodi#283]
Witam!
prosze o pomoc - zyje w Austrii, posiadam Minix Neo x8-h box i chce oglondac dzieki mrknow plugin 
(versia 11.04.16) telewizjade przez xbmc/kodi. Moj internet ma ok 8-12MBit (download speed) i co chwile dochodzi do buffering przy oglondaniu kanalow - to zwlaszcza wieczorem. 
Probowalem juz przez easy advanced settings plugin (versia 0.8.8) zmienic ustawienia network -> 

<advancedsettings>
<network>
<buffermode>1</buffermode>
<cachemembuffersize>157286400</cachemembuffersize>  (150MB podane w Byte)
<readbufferfactor>10</readbufferfactor>   (probowalem tez 20, 30, 40 itd.)
</network>
</advancedsettings>

niestety to wszystko nie prowadzi do rozwiazania problemu i do mozliwosci oglondania bez przerywania. Oglondanie filmow lub seriali dziala przez ten box uzywajac ten sam wlan.

Za wszystkie propozycje dziekuje z gory
pozd
Luppo ;-)

**Comment by xxcriticxx** [comment]
tego sprobuj

https://github.com/mrknow/filmkodi/wiki/Buffer-size-buffering-issues-cache-setup
