### ISSUE TITLE
[solved] Znikające thumbnaile kanałów

### ISSUE THREAD

**Issue by oomek** [mrknow/filmkodi#284]
Plugin telewizjady wyświetla tylko ok 5 ikon kanałów z 73. Po skasowaniu pliku textures13.db i zrestartowaniu Kodi #thumbnaile się pojawiaja, ale zaraz znów znikają jak przejadę całą listę kanałów.

**Comment by xxcriticxx** [comment]
bug?

**Comment by oomek** [comment]
Tylko w tym pluginie mam ten problem, więc bug.

**Comment by xxcriticxx** [comment]
jaki os? jak box or pc?

**Comment by oomek** [comment]
Asrock QC5000M-ITX (AMD A4-5000)
Windows 10 x64

**Comment by oomek** [comment]
Okazao się, że miałem zaśmiecony katalog miniatur. Jakby ktoś miał podobny problem polecam plugin 
Profile Cleaner [https://github.com/cibboy/script.profilecleaner](url)

**Comment by xxcriticxx** [comment]
page not found
