### ISSUE TITLE
TV Shows progress - not updating

### ISSUE THREAD

**Issue by xX-Nexus-Xx** [mrknow/filmkodi#285]
Specto is working fine on my OpenElec system .. the only issue I have is that lately the TV schows progress is not getting updated anymore. I see the an earliers show which has been watched and when I click into it i can find more recent shows .. but they are not showing in the progress!

This was working earlier !! ... any idea how to get this fixed?

btw: Great work .. thank you for continuing with that Add-on

**Comment by dvint1** [comment]
Same. If I have hide watched on the shows disappear as the Ep showing in progress is old but if I turn it off and click the old Ep there is a new one in the submenu. 

Use to be fine.

**Comment by mrknow** [comment]
Fixed
