### ISSUE TITLE
Have problem with plugin mr know

### ISSUE THREAD

**Issue by VarioShadow** [mrknow/filmkodi#288]
http://xbmclogs.com/pdvpdeeub

Help

**Comment by VarioShadow** [comment]
Pls

**Comment by xxcriticxx** [comment]
ERROR: virtual void PERIPHERALS::CPeripherals::Initialise() - failed to initialise bus cec

unplug all from your box and test

**Comment by VarioShadow** [comment]
Nadal mam nieudane wykonanie skryptu

**Comment by xxcriticxx** [comment]
cos masz jescze podlonczone co sie zawiesza

niemam cec do przetestowane ale mam flirc w moim minix x8 i dziala super 

dasz rade zrobic upgrade do kodi?

**Comment by VarioShadow** [comment]
> cos masz jescze podlonczone co sie zawiesza
> 
> niemam cec do przetestowane ale mam flirc w moim minix x8 i dziala super 
> 
> dasz rade zrobic upgrade do kodi?
> 
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mrknow/filmkodi/issues/288#issuecomment-214415284 

Szefie wiem ze czasami pilot na bluetooth sie wiesza ale problem mam z wtyczka mr know caly czas pokazuje mi nieudane wykonanie skryptu 
Sorki za wprowadzenie w blad

**Comment by xxcriticxx** [comment]
zamontuj najowszy firmware ten co uzywasz jest z 2014

**Comment by VarioShadow** [comment]
> cos masz jescze podlonczone co sie zawiesza
> 
> niemam cec do przetestowane ale mam flirc w moim minix x8 i dziala super 
> 
> dasz rade zrobic upgrade do kodi?
> 
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mrknow/filmkodi/issues/288#issuecomment-214415284
Wydaje mi sie ze jest problem z w linijce 695 

xbmclogs.com/pjskglkjr

**Comment by VarioShadow** [comment]
> zamontuj najowszy firmware ten co uzywasz jest z 2014
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mrknow/filmkodi/issues/288#issuecomment-214418457
 Aha ok :) udanego wieczoru

**Comment by xxcriticxx** [comment]
zrob format minix przez podlonczenie kablem usb do kompa i hyba najnowszy firmware jest ver 9 i potem bendziemy testowac dalej
