### ISSUE TITLE
filmy

### ISSUE THREAD

**Issue by heniek-997** [mrknow/filmkodi#29]
Witam. Mam taki mały problem , po zainstalowaniu ostatniej wersji wtyczki (tej z telewizjadą) w zakładce filmy przestały mi działać przestały mi działać cda, filmbox, iptak i pozostałe, działa jedynie alltube. W zakładce telewizja wszystko jest ok. Co dziwne problem jest jedynie na androidzie, na windowsie wszystko jest ok. Próbowałem zmieniać nazwy pliku parser.py na parser.py.bak, ale bez rezultatu. Po przywróceniu wtyczki za pomocą repozytorium 14489957458581.zip, podanego w innym wątku, wszystkie zakładki w zakładce filmy działają  poprawnie, ale niestety w zakładce telewizja brak jest telewizjada :(.  Czy jest na to jakiś sposób ? Nadmieniam, że kodi działa na urządzeniu tv box cs918 z androidem 4.4.2 z rootem. Pozdrawiam.

**Comment by xxcriticxx** [comment]
odmontuj i zamontuj jeszcze raz jest nowa wersia plugin

**Comment by heniek-997** [comment]
dzięki za szybką odpowiedź, ale niestety nic nie pomaga, zainstalowałem kodi jeszcze dla sprawdzenia w telefonie, jest wtyczka mrknow z dnia 27.12.2015, ale sytuacja jest identyczna

**Comment by xxcriticxx** [comment]
ja posiadam minix 8h dziala bez problemu

sprobuj facotory reset zrobic i pierwsze co zamontuj to jest kodi i plugin

**Comment by mysecretidentity** [comment]
Mocno na wyrost ta rada z factory reset, to wina wtyczki a nie systemu. Też mam ten problem od wersji 27.3, na dwóch urządzeniach, android 4.4.  kodi 15.2.

**Comment by xxcriticxx** [comment]
jakie urzadzenia macie moze jakos liste zrobimy?

**Comment by mysecretidentity** [comment]
Ugoos UM2, SAMSUNG SM-T315, android 4.4.2. Wnosząc z zachowania wtyczki, może to być błąd zbliżony do tego związanego z plikami parser, który nękał użytkowników androida przez ostatnich kilka aktualizacji wtyczki. O dziwo przedostatnia wersja, bodajże 2015.12.23, chodziła w pełni poprawnie.

**Comment by mysecretidentity** [comment]
[kodi log.zip](https://github.com/mrknow/filmkodi/files/76285/kodi.log.zip)
Wklejam fragment loga z błędami.

**Comment by xxcriticxx** [comment]
jak cowniesz sie do tej ver to chodzi?

**Comment by mysecretidentity** [comment]
Nie mam zarchiwizowanych poprzednich wersji i nie za bardzo mam pomysl jak sie do nich cofnac. W ostatnim czasie dosc intensywnie sledzilem zmiany wersji, bo po kazdym updacie wracal problem z plikami parser, co wymagalo recznej interwencji. Wydaje mi sie, ze ostatnia dzialajaca wersja to 12.23 lub 12.24. BTW, dzieki za link do phantomvideo w innym watku.

**Comment by xxcriticxx** [comment]
wyloncz auto update plugins w kodi 

system -> settings -> add-ons -> press left for left side menu i wyloncz auto update

potem 

https://github.com/mrknow/filmkodi/commits/master

wybierz wersje press Browse Files potem Download Zip

good luck

**Comment by mysecretidentity** [comment]
Dzięki za pomoc, jak się okazało winne były znowu pliki parser w katalogu script.module.xbmcfilm/lib. Dalbym sobie uciac reke, ze juz tego probowale... no ale...

**Comment by xxcriticxx** [comment]
sorry umnie tez nie dziala siedzialem caly czas na telewizjada no nie widzialem az wlaczylem cda.pl i dostalem script error

**Comment by mrknow** [comment]
Pracuję nad wyeliminowaniem tego błędu. Muszę sprawdzić te kilkadziesiąt plików ... 
Dzięki za informację.

**Comment by mrknow** [comment]
wersja 2016.01.03 - powinna to poprawić. jeżeli nie to prosze pokaż mi logi według tej instrukcji https://github.com/mrknow/filmkodi/wiki/Jak-przes%C5%82a%C4%87-logi-z-kodi

**Comment by mysecretidentity** [comment]
U mnie po updacie cda, filmbox itp.. chodzą bez zarzutu, dzięki za update.

**Comment by heniek-997** [comment]
U mnie również teraz jest wszystko  OK. Dzięki.
