### ISSUE TITLE
moze dodac wp.tv

### ISSUE THREAD

**Issue by xxcriticxx** [mrknow/filmkodi#291]
co myslicie?

**Comment by plumers** [comment]
szajs ... nie chce mi się juz wiecej polecac streamów bo wszystkie free padaja po ok miesiacu --tutaj na odchodne L:))

http://tvtoss.com/pages/all-channels.php?ctd=11&t=Poland%20TV%20Channels

http://zobacz-to.com

no i ...thats the finish :_) kablówka za 57zl dala max pakiet i net 30 -- styknie powodzonka :)

**Comment by xxcriticxx** [comment]
@plumers zaczni nadawac to wykupie od ciebie :)

**Comment by plumers** [comment]
teleszajsjada id dead!! mówilem lol
