### ISSUE TITLE
Wyszukiwanie w zalukaj.tv

### ISSUE THREAD

**Issue by gregor102** [mrknow/filmkodi#292]
czy wyszukiwanie w serwisie zalukaj nie działa w ogóle, czy to tylko jakiś problem u mnie? próbowałem wyszukiwać i na raspberry pi 3 pod Kodi, jak i pod Windows 10 (też Kodi) i w każdym przypadku nie działa.

**Comment by mrknow** [comment]
Hmm 
Chyba nie działa dobrze. Planuję sprawdzić dokładnie i poprawić ok 8 maja 2016

**Comment by mrknow** [comment]
ok poprawione wyszukiwanie filmów. za kilka godzin wypuszczę aktualizację
