### ISSUE TITLE
Source WSOnline has changed addresses

### ISSUE THREAD

**Issue by bjgood** [mrknow/filmkodi#295]
Hi Mr Know,
You might want to check this out, but I think source wsonline.py has changed its internet address from http://watchseries-online.il to http://watchseries-online.li. I noticed last night that I wasn't receiving any links for a tv series we normally watch from WSOnline where previously we had. After checking and changing http://watchseries-online.il to http://watchseries-online.li I now am receiving working links for our tv series. As a matter of interest, http://watchseries-online.il is not showing as a valid internet address (at least not here in the US).

Hope this helps.

Bob

**Comment by mrknow** [comment]
this issue is fixed in the new version
