### ISSUE TITLE
Alltube

### ISSUE THREAD

**Issue by mochercn** [mrknow/filmkodi#296]
Mam problem z alltube niemoge otworzyc zadnego filmu ani serialu pisze (może to chwilowa awaria.sprubuj ponownie za jakiś czas) czekam na odpowiedz

**Comment by garyfisher** [comment]
Potwierdzam

**Comment by eyu2136** [comment]
Dokładnie mam to samo. Rbpi + kodi+mr.know

**Comment by Adam-po** [comment]
Tak jest od około 2 Miesięcy..... Jak tylko wyjdzie jakaś nowa Aktualizacja Mrknow to po tym zawsze coś wysiada..... A telewizjada będzie wyłączona.... Bo jak długo można Piracko TV oglądać...

Gesendet von Yahoo Mail auf Android 
 
  Am Sa., 30. Apr. 2016 um 22:39 hat eyu2136<notifications@github.com> Folgendes geschrieben:   
Dokładnie mam to samo. Rbpi + kodi+mr.know

**Comment by mrknow** [comment]
Obecnie jestem na urlopie. Planuję zweryfikować i poprawić usterkę około 8 maja 2016

**Comment by rkolasie** [comment]
masz diffa do poprawki altube:
--- lib/mrknow_Pageparser.py.bak        2016-05-02 08:44:36.715236485 +0200
+++ lib/mrknow_Pageparser.py    2016-05-02 08:46:51.965090280 +0200
@@ -272,7 +272,7 @@
         query_data = {'url': url, 'use_host': False, 'use_cookie': False, 'use_post': False, 'return_data': True}
         link = self.cm.getURLRequestData(query_data)
         match1 = re.compile(
-            '<td><img src="(.*?)" alt="(.*?)"> (.*?)</td>\n              <td class="text-center">(.*?)</td>\n              <td class="text-center"><a class="watch" data-urlhost="(.*?)" data-iframe="(.*?)" data-version="(.*?)" data-short="(.*?)" data-size="(.*?)" (.*?)>(.*?)</a>\n                            </td>').findall(
+            '<td><img src="(.*?)" alt="(.*?)"> (.*?)</td>\n              <td class="text-center">(.*?)</td>\n              <td class="text-center"><a class="watch" data-iframe="(.*?)" data-version="(.*?)" data-short="(.*?)" data-size="(.*?)" (.*?)>(.*?)</a>\n                            </td>').findall(
             link)
         # print("Match1",match1)
         tab = []
@@ -280,8 +280,8 @@
         if match1:
             for i in range(len(match1)):
                 # print("Link", match1[i])
-                tab.append(match1[i][6] + ' - ' + self.getHostName(match1[i][4]))
-                tab2.append(match1[i][4])
+                tab.append(match1[i][5] + ' - ' + self.getHostName(match1[i][4].decode('base64')))
+                tab2.append(match1[i][4].decode('base64'))
             d = xbmcgui.Dialog()
             video_menu = d.select("Wybór strony video", tab)
             if video_menu != "":

**Comment by rkolasie** [comment]
Zrobiłem pull request z poprawką tego błędu - sprawdź, czy zgodnie ze sztuką bo u mnie działa :)
Jak by co to pchnij zmianę na produkcję i niech się cieszą również pozostali :)

#298

**Comment by mochercn** [comment]
Witam prosze mi napisac jak to mam zrobic bo nierozumiem zabardzo
2 maj 2016 9:06 AM "rkolasie" <notifications@github.com> napisał(a):

**Comment by rkolasie** [comment]
Cześć,

Uhh, sam nie wiem jak to zrobić - to był mój pierwszy pull request, ale z
tego co widzę w dokumentacji można to szybko wyklikać via web interface
Githuba => https://help.github.com/articles/merging-a-pull-request/

Potem lokalnie na swoim kompie robisz:
git pull

A potem tak jak zwykle robisz z tego paczuszkę i wysyłasz tam gdzie do tej
pory :)


2016-05-02 9:37 GMT+02:00 mochercn <notifications@github.com>:

**Comment by mochercn** [comment]
tylko ja dalej nierozumie co mam zrobic jaki dokument ittp

W dniu 2 maja 2016 09:46 użytkownik rkolasie <notifications@github.com>
napisał:

**Comment by rkolasie** [comment]
Ahh, odpisywałem bezpośrednio ze swojej skrzynki pocztowej - te zmiany o których pisałem musi wykonać twórca pluginu, czyli mrknow.
Użytkownicy muszą niestety poczekać na tworcę, który udostępni uaktualnioną wersję pluginu :(

Jeśli nie posiadasz odpowiedniej wiedzy a z twoich komentarzy na to wygląda to niestety samodzielna poprawa pluginu (hotfix) będzie dla ciebie zbyt problematyczna  - poczekaj aż autor wypuści poprawkę.

**Comment by garyfisher** [comment]
@rkolasie Wielkie dzięki, działa :) (mam spokój z dziewczyną)

Zrobiłem tak wlazłem na swoje kodi (osmc) przez ssh (PuTTY), zainstalowałem sobie mc (Midnight Commander) sudo apt-get install mc (tak jestem leniem i nie lubię vim). Odpaliłem mc wlazłem do /home/osmc/.kodi/addons/plugin.video.mrknow/lib/ edytowałem pliczek mrknow_Pageparser.py zgodnie z poprawką @rkolasie zapisałem i działa :) Mam nadzieje ze komuś pomogłem przed zatwierdzeniem poprawki przez @mrknow 

Pozdrawiam

**Comment by eyu2136** [comment]
Czy moglbys wstawic tutaj sam gotowy plik? Lub jego zawartosc?
03.05.2016 5:49 PM "Gary" <notifications@github.com> napisał(a):

**Comment by garyfisher** [comment]
@eyu2136 https://raw.githubusercontent.com/rkolasie/filmkodi/patch-1/plugin.video.mrknow/lib/mrknow_Pageparser.py

**Comment by eyu2136** [comment]
Dziekuje. Zaraz sprawdze u siebie.
03.05.2016 7:55 PM "Gary" <notifications@github.com> napisał(a):

**Comment by mrknow** [comment]
Witam 
Poprawki naniesione. Powinno działać. Tutaj wersja beta http://kodi.filmkodi.com/beta/plugin.video.mrknow/plugin.video.mrknow-2016.05.08.1.zip

**Comment by mrknow** [comment]
Trakt.tv Fixed. Try install beta version http://kodi.filmkodi.com/beta/plugin.video.specto/plugin.video.specto-2016.05.8.2.zip
