### ISSUE TITLE
Specto problem 

### ISSUE THREAD

**Issue by grneski** [mrknow/filmkodi#297]
Hello Specto has a new problem where none of the streams are working at all ,
When Specto is loaded error msg comes up
Version check error but it's the latest updates version 
Need help ? What is going on

Thanks bob

**Comment by mrknow** [comment]
Currently I am working on it. Check out this beta version
http://kodi.filmkodi.com/beta/plugin.video.specto/plugin.video.specto-2016.05.8.2.zip

**Comment by mrknow** [comment]
This issue is fixed in the new version

**Comment by grneski** [comment]
Sweet buddy is working all good
Thanks for the champ

**Comment by grneski** [comment]
Hi buddy how we you

Just have a problem with my kodi with Specto.
It won't update automatically and it has. Error
Add on is incompatible or has been market broken in respository

Dependencies not met. Please Contact add on author

Can you help mate?
Cheers bobi


Sent from my iPhone

On 4 May 2016, at 3:12 AM, mrknow <notifications@github.com<mailto:notifications@github.com>> wrote:


Currently I am working on it. Check out this beta version
http://kodi.filmkodi.com/beta/plugin.video.specto/plugin.video.specto-2016.05.8.2.zip

-
