### ISSUE TITLE
Librtmp dla android

### ISSUE THREAD

**Issue by xxcriticxx** [mrknow/filmkodi#3]
Prosze o poprawke librtmp dla androida. nie mozna zamontowac na minix x8 h.

**Comment by eclipse05** [comment]
Niestety problem wciąż występuje
Na zrootowanym Note3 wraz z Kodi 15.2 - akutalizacja LIBRTMP nie działa
Na zrootowanym Note3Neo wraz z Kodi 15.2 - akutalizacja LIBRTMP nie działa
Na zrootowanym S4 mini wraz z Kodi 15.2 - akutalizacja LIBRTMP nie działa
Android Box MX3 z XBMC 13.4(OMAN) - akutalizacja LIBRTMP nie działa
Android Box MX3 z KODI 16.0(Jarvis) - akutalizacja LIBRTMP nie działa
Windows 10 z prawami administratora dla Kodi aktualizacja działa.

**Comment by hahabla** [comment]
U mnie to samo, obojetnie na jakim Androidzie.

Blad jest taki:

> [Errno 2] No such file or directory: u'/data/data/org.xbmc.xbmc/lib/librtmp.so'

**Comment by kucyk84** [comment]
niestety u mnie i kilku znajomych to samo ;/

**Comment by wujek35** [comment]
Mam ten sam problem na kodi 16.0 czy jest mozliwosc pobrania samego pliku LIBRTMP i wrzucenia go wlasnorecznie?prosze o link do pobrania

**Comment by mrknow** [comment]
Funkcja wycofana, ze względu na zbyt dużą różnorodność
