### ISSUE TITLE
Movie search error

### ISSUE THREAD

**Issue by sleotescu** [mrknow/filmkodi#302]
Hi. When I try to search for a Movie I get error. If I search for TV show it's working.

**Comment by mrknow** [comment]
Hi 
Problem is in:                                               
File "/home/mrknow/.kodi/addons/plugin.video.specto/resources/lib/indexers/movies.py", line 212, in search

` - self.list = cache.get(self.trakt_list, 0, url)`
`+ self.list = cache.get(self.trakt_list, 0, url, self.trakt_user)`

I will fix this next update 2016-05-07

**Comment by rmj35** [comment]
I have the latest version but im still having this problem.
Please fix it T^T

**Comment by mrknow** [comment]
Fixed in version 2016.05.8.4.
