### ISSUE TITLE
Need more 1080p sources 

### ISSUE THREAD

**Issue by karnage11** [mrknow/filmkodi#303]
Hey needs more 1080p sources please , Thank you

**Comment by xxcriticxx** [comment]
you have any websites you can provide?

**Comment by markos89** [comment]
OK mrknow and other developers,now i will give you some great tv shows and movie sources:
123movies.to(movies/tv shows)
dayt.se tv(tv shows)
cdn.serieswatch.tv/2 (movies with 5.1 audio and big number of tv shows)
fardadownload.ir (bunch of tv shows in hd and x265)
I will add more soon

**Comment by markos89** [comment]
Anyone here??

**Comment by xxcriticxx** [comment]
yes

**Comment by mrknow** [comment]
Good news. dayt.se added (mail.ru). Please check new version 2016.05.8.4. Tomorrow will try to add cdn.serieswatch.tv/2. 

thanks for this sources

**Comment by markos89** [comment]
Ok mrknow.

123movies.to is great source,make sure you add it if you can!
Thanks for this

**Comment by markos89** [comment]
kiwihd.com- bunch of tvshows and movies in hd

**Comment by mrknow** [comment]
123movies.to - added as Muchmovies
 dayt.se - added without youtube sources ...

**Comment by xxcriticxx** [comment]
list taken from this YouTube video (https://www.youtube.com/watch?v=RCDaGdi25xE) and seems to work well


your Sources list order should look like this order more or less:

1. sezonlukdizi - (Episodes ) (Episodes Only) (HD Source)
2. DayT - (Episodes) (HD Source) 
3. dizilab - (Episodes Only) (HD Source) (HC TURK for some)
4. TVWTVS - (Episodes) (HD Source)
5. Watch5s - (Movies and Episodes) (HD Source) *new
6. 9Movies - (Movies Only) (HD Source)
7. 123movies - (Movies Only) (HD Source)
8. CloudMovie- (Movies) (HD Source) 
9. HEVCBluRay - (Movies Only) (HD Source )
10. FardaDownload - (Movies and Episodes) (HD Source)
11. PirateJunkies - (Movies) (HD Source) *new
12. Torba - (Movies and Episodes) (HD Source) (great source but ned a verification to watch)
13. Serieswatch - (Movies & Episodes) (HD Source)
14. Filmovizija - (Movies & Episodes) (HD Source) *new
15. HDmovie14 - (Movies and Episodes) (HD Source)
16. MiraDeTodo - (Movies Only) (HD Source)
17. dizimag - (Episodes Only) (HD Source) 
18. MWM - (Episodes) (HD Source )
19. Dizibox - (Episodes) (HD Source)
20. MovieSub - (Movies Only) (HD Source )
21. Emovies.pro - (Movies Only) (HD Source)
22. dizigold - (Episodes) (HD Source)
23. vivo.to - (Movies and Episodes) (HD Source)
24. xvideos8.v2 - (Movies Only) (HD Source)
25. pubfilm - (Movies Only) (HD Source) 
26. MovieXK - (Episodes And Movies) (HD Source ) (have MovieXK watermark)
27. clickplay.to - (Episodes Only) (HD Source)
28. Stage66 - (Movies Only) (HD Source )
29. RainierLand - (Movies and Episodes) (HD Source)
30. ViewMovies - (Movies Only) (HD Source)
31. Kiwihd - (Movies and Episodes) (HD Source) (have Kiwihd watermark) *new
32. PutMV - (Movies Only) (HD Source)
33. Zumvo - (Movies Only) (HD Source)
34. primewire - (Movies and Episodes) (SD Source)

**Comment by mrknow** [comment]
Great list . I start work on it in June

**Comment by xxcriticxx** [comment]
hd host from fastest to slowest


    MrFile
    Gvideo
    Yify
    Dizimag
    VK
    Muchmovies
    Videomega
    Turbovideos
    Openload
    Vidplay
    MovieTV
    Moviefarsi

**Comment by xxcriticxx** [comment]
sd host from fastest to slowest


    Openload HQ
    Mrfile HQ
    Uptobox HQ
    Dizimag HQ
    Turbovideos HQ
    V-vids HQ
    Skyvids HQ
    Gvideo HQ
    Mightupload HQ
    zStream HQ
    Vidspot MQ
    Streamin MQ
    Allmyvideos MQ
    Vidto MQ
    Streamcloud MQ
    Letwatch MQ
    Divxpress LQ
    Filehoot LQ
    Beststreams LQ
    Vidzi LQ

**Comment by mrknow** [comment]
old issue
