### ISSUE TITLE
Telewizjada is back online

### ISSUE THREAD

**Issue by borys76** [mrknow/filmkodi#306]
96 kanalow, dziala na wtyczce mrknow 
Jakosc duzo lepsza

**Comment by xxcriticxx** [comment]
@borys76 duplicate https://github.com/mrknow/filmkodi/issues/304

**Comment by borys76** [comment]
My bad

**Comment by xxcriticxx** [comment]
bad borys!

**Comment by gumball1** [comment]
jakosc taka sama lizusie
