### ISSUE TITLE
Wtyczka Mr. Know not work

### ISSUE THREAD

**Issue by low1988xx** [mrknow/filmkodi#309]
Witam wtyczka od kilku dni nie działa, w Kodi ustawiono na automatyczną aktualizacje, reinstalacja wtyczki wraz z usunięciem całego repetytorium, nie przyniosło żadnych rezultatów. wtyczka nie reaguje na nic niestety wyświetla się tylko info że wtyczka mrknow nie działa poprawnie więcej szczegółów...

Link do logu:

http://xbmclogs.com/plfxl83sy/2b7dkn

**Comment by mrknow** [comment]
Widzę, nie działa 

` File "C:\Users\Tomasz\AppData\Roaming\Kodi\addons\plugin.video.mrknow\lib\utils\webUtils.py", line 10, in <module>
`from HTMLParser import HTMLParser`
`ImportError: cannot import name HTMLParser`

Spradze u siebie na windzie i odpiszę ...

**Comment by mrknow** [comment]
U mnie działa
