### ISSUE TITLE
WSOnline is not providing any links

### ISSUE THREAD

**Issue by bjgood** [mrknow/filmkodi#311]
Hey Mr Know,
WSOnline must have made some changes on their website because no links are being found through wsonline.py. The address is still the same so that's not the problem. If I go to the website and search for a TV series I can play the episodes fine. Might want to look into it when you get the chance.

Best regards,
Bob

**Comment by bjgood** [comment]
BTW, SALTS scrapers are not finding any episodes either...so we're both in the same boat. I installed it just to find out if their wsonline version worked or not. 

Later...
Bob

**Comment by bjgood** [comment]
Mr Know,
I withdraw my report about WSOnline. It seems to be working now. Funny, for two days it was not working, but now it is. Sorry for the fuss.

Please close this thread. Thank you.

Best regards,
Bob

**Comment by mrknow** [comment]
OK 
Today we release new version. This version fix issues with gvideo sources in putlocker, sezonlukdizi,
