### ISSUE TITLE
Telewizjada - zrywanie i buforowanie streamu

### ISSUE THREAD

**Issue by oomek** [mrknow/filmkodi#312]
Kodi 16.1, Windows 10 x64, mini PC.
Czy problemy ze zrywaniem streamu oraz ciągłe buforowanie (głównie zaczynające się podczas reklam i ciągnie się od tego momentu) to wina pluginu czy streamów źródłowych Telewizjady? 
Wciśnięcie stop oraz play pomaga na jakieś 15-30 minut a potem znów to samo, mam wrażenie jakby plugin odtwarzał stream za szybko i trafiał w końcu na początek bufora.
Na pewno zrywa Discover Science, reszta nie wiem bo tylko ten kanał oglądam.
P.s. Mam ustawione w Kodi w settings/playback/sync playback to display i adjust display refresh rate
Odtwarzanie w 50hz.

**Comment by xxcriticxx** [comment]
jaka maszyna jaki internet?

**Comment by oomek** [comment]
AMD A4-5000 quad, 120mbit

**Comment by xxcriticxx** [comment]
usa?

**Comment by oomek** [comment]
Uk.

**Comment by xxcriticxx** [comment]
server jest teraz w romani moze slabszy odpaliwilem discovery science teraz i testuje

**Comment by oomek** [comment]
Ok, dzięki, poczekaj jak możesz do 2 rzutów reklam, to wtedy się najczęściej zaczyna ciąć. Często też wtedy przeskakuje jakby z początku buffora na koniec obcinając część streamu.

**Comment by xxcriticxx** [comment]
zobaczymy teraz cos sie konczy benda reklamy

**Comment by xxcriticxx** [comment]
hakuna matata

**Comment by oomek** [comment]
Lol:)

**Comment by xxcriticxx** [comment]
teraz hyba mnejszy traffic na lini

**Comment by oomek** [comment]
No właśnie tez coś mi się wydaje, że to jednak dziury w streamie i plugin głupieje, bo teraz nic nie zerwało, najczęściej ten problem występuje w godzinach szczytu.

**Comment by xxcriticxx** [comment]
nadawca nie nadarzy

**Comment by oomek** [comment]
Problem jest tego typu, że jak są dziury to plugin zaczyna odtwarzanie na samym końcu bufora zamiast poczekac aż się nabuduje trochę i zaczyna rwać od tego momentu.

**Comment by oomek** [comment]
Wiem, bo jak wcisnę stop i play to stream się cofa o jakieś 20-30 sekund

**Comment by xxcriticxx** [comment]
ja oglondam reg discovery tam wczoraj od casu do czasu skakalo ale minium na androdzie

**Comment by xxcriticxx** [comment]
cache masz ustawiony jakis? masz hard drive? tak?

**Comment by oomek** [comment]
Pytnie jest następujące, czy dałoby się ustawić minimalny bufor w programie, żeby nie odtwarzał przy samej krawędzi

**Comment by oomek** [comment]
Mam cache ustawiony a sys jest na ssd

**Comment by xxcriticxx** [comment]
to pytanie do mrknwo czy cos takiego by napisal

**Comment by xxcriticxx** [comment]
zrob speed test tego twgo netu

**Comment by oomek** [comment]
Mój net chodzi bez zarzutu.

**Comment by xxcriticxx** [comment]
zobacz jaki masz ping nie zaszkodzi

**Comment by oomek** [comment]
[http://www.speedtest.net/result/5310298732.png](http://www.speedtest.net/result/5310298732.png)

**Comment by xxcriticxx** [comment]
byly natepne reklamy nie bylo problemu

**Comment by oomek** [comment]
U mnie też ok, jak sie zacznie jutro ciąć, to napiszę.

**Comment by xxcriticxx** [comment]
masz androida? wloncz kilka innych box zobacz to sie dzieje. ja  jestem w usa z czasem jest troche innaczej

**Comment by oomek** [comment]
Nie mam, mogę odpalić tylko na chrome na ipadzie

**Comment by xxcriticxx** [comment]
potestuj i zobaczymy

**Comment by oomek** [comment]
Od czasu naszej rozmowy miałem zacinki już 3x. Raz po 48 minutach i 2x po około 10-20.
Tak to wygląda u mnie na debug view [link](http://youtu.be/-mqQzA_T1u4)
Vq: zawsze leci w dół przed zacięiem.

**Comment by xxcriticxx** [comment]
mnie wczoraj tez kompletnie z discovery wywalilo

hyba sie zgodze z toba ze cos jest nie tak

**Comment by Adam-po** [comment]
Wygląda na to że Pirackie nadawania telewizjada.net doszły końca nic nie działa.strony nie ładuje ani przez net ani przez Mrknow,Telewizja Polska.
Jak pisze Gazeta Polska doszło do prokuratury Warszawie 


I co teraz?😭

**Comment by Adam-po** [comment]
Wygląda na to że Pirackie nadawania telewizjada.net doszły końca nic nie działa.strony nie ładuje ani przez net ani przez Mrknow,Telewizja Polska.
Jak pisze Gazeta Polska doszło do prokuratury Warszawie 

Telewizje skarżą się w nim na serwis Telewizjada.net. Pojawił się on pod koniec ubiegłego roku i momentalnie napsuł krwi nadawcom. Nic dziwnego: 75 kanałów – od wielkiej czwórki, czyli TVP 1, TVP 2, TVN i Polsatu, poprzez kanały tematyczne, a nawet płatne, jak HBO, Canał+ czy Orange Sport – jest dostępnych za darmo i do tego bez żadnych reklam. Serwis ten zaczął momentalnie zbierać ogromną rzeszę użytkowników. Według wyliczeń Gemiusa ma ich już ponad 1,4 mln, z których część może nawet nie wiedzieć, że korzysta z serwisu pirackiego. Na stronie administrator asekuracyjnie pisze: „Telewizjada.net nie zajmuje się rozprowadzaniem plików chronionych prawem autorskim. Strona nie zawiera żadnych plików, zamieszcza jedynie ich sumy kontrolne”


I co teraz?😭

**Comment by oomek** [comment]
Wszyscy umrzemy!

**Comment by xxcriticxx** [comment]
"z których część może nawet nie wiedzieć, że korzysta z serwisu pirackiego"

LOL

**Comment by gumball1** [comment]
pismak szuka sensacji ;)

**Comment by xxcriticxx** [comment]
telewizjada server teraz w ukrainie

**Comment by mrknow** [comment]
Strona nie dziala na razie. Zamykam
