### ISSUE TITLE
Problem with Subtitles in Specto

### ISSUE THREAD

**Issue by dracosc** [mrknow/filmkodi#313]
Hi. Since last update (v2016.05.08.7), every movie i search for subtitles, i can only see English subtitles as options! I can't search for Greek or German. This problem didn't exist in  v2016.05.08.5.
Even in Specto settings, if i try to enable Greek or German as Primary and English as secondary, i only get English!
This is very strange.....i even compared subtitles.py file and has no changes!!!

**Comment by mrknow** [comment]
I will check this issue in weekend. Thx for info

**Comment by dracosc** [comment]
First of all i forgot...... GREAT WORK mrknow on this addon! A big BRAVO and a huge THANKS!
Anyway, back to our bug 😀
I think i solved it. I had to delete the settings.xml in userdata/addon_data/plugin.........specto!
Then everything was fixed again!
But still don't know why the bug appeared!

**Comment by dracosc** [comment]
Then i made a "small" modification to the plugin default settings.xml. I set my preferred settings as default, and saved settings.xml.
Then i made another modification to the default.py of the addon, by adding a script to autodelete settings.xml from userdata folder, so that it always uses my modified stock settings.xml! 
I now have no errors but i have to modify these on every Specto update 😀😀😀

**Comment by mrknow** [comment]
please write here this "small" modification  default settings.xml and default.
I can not reproduce this error

**Comment by dracosc** [comment]
I can, but it is useless for a global addon. This is just for me or for anyone that never needs to edit settings. If you do it in specto, all users will have the same settings, either they like it or not.

**Comment by mrknow** [comment]
old issue.
