### ISSUE TITLE
pierwsza.tv

### ISSUE THREAD

**Issue by mar2016** [mrknow/filmkodi#318]
Czy jesr mozliwosc dodania http://pierwsza.tv

**Comment by xxcriticxx** [comment]
https://github.com/mrknow/filmkodi/issues/278
https://github.com/mrknow/filmkodi/issues/258
https://github.com/mrknow/filmkodi/issues/225
https://github.com/mrknow/filmkodi/issues/206

**Comment by mrknoworg** [comment]
W tym lub prszyszłym tygodniu zostanie dodana. Niestety - będzie tylko działać dla kont premium.

**Comment by mar2016** [comment]
Dziekuje za informacje , wiele osob ma wykupione Premium

**Comment by xxcriticxx** [comment]
ja niemam

**Comment by mar2016** [comment]
to sobie wykup premium i bedziesz mial

**Comment by xxcriticxx** [comment]
szukam sponsora

**Comment by mrknow** [comment]
Witam 
Dzisiaj udostępniłem wersję alpha wtyczki Telewizja polska - premium. 
Wtyczka ta obsługuje pierwsza.tv, ale tylko konta premium

**Comment by borys76** [comment]
Tylko jak wykupic premium na pierwsza tv?

**Comment by xxcriticxx** [comment]
@borys76 hyba konto pierwszo musisz zalozyc

http://pierwsza.tv/account/register

**Comment by borys76** [comment]
Zalozylem I nie ma opcji premium, na stronie dziala bez premium

**Comment by mar2016** [comment]
Sproboj z mojego linka sie zarejestrowac 
http://pierwsza.tv/account/register?ref_id=1205

**Comment by borys76** [comment]
Ja mam account tylko nie ma opcji premium

**Comment by xxcriticxx** [comment]
http://pierwsza.tv/premium

**Comment by borys76** [comment]
Cos maja nie tak, dlatego niema opcji premium 
Po wejsciu na  /premium tez nie dziala

**Comment by xxcriticxx** [comment]
Może bendzie tak jak z weeb.tv

**Comment by mrknow** [comment]
Na razie czekam na odpowiedź jak wykupić premium. Jak tylko dostanę informację napisze na tym wątku.

**Comment by mrknow** [comment]
OK 
Pierwsza dodana - ale tylko jako premium w MrKnow TV
