### ISSUE TITLE
Failed to install dependency

### ISSUE THREAD

**Issue by voytecPL** [mrknow/filmkodi#319]
Error is displayed 'Failed to install dependency' while installing plugin ' Filmy online mrknow.pl'

**Comment by xxcriticxx** [comment]
jaka ver kodi masz?

**Comment by voytecPL** [comment]
Wersja 16.1

sob., 14.05.2016, 02:00 użytkownik xxcriticxx <notifications@github.com>
napisał:

> jaka ver kodi masz?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mrknow/filmkodi/issues/319#issuecomment-219186255>
>


-- 

Wojciech Jakubas

**Comment by xxcriticxx** [comment]
win czy android? log?

uninstall and install again

**Comment by voytecPL** [comment]
Android

sob., 14.05.2016, 19:15 użytkownik xxcriticxx <notifications@github.com>
napisał:

> win czy android? log?
>
> uninstall and install again
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mrknow/filmkodi/issues/319#issuecomment-219232083>
>
-- 

Wojciech Jakubas

**Comment by xxcriticxx** [comment]
jaki box? jaki os masz?

**Comment by voytecPL** [comment]
Info na screenie.

sob., 14.05.2016, 19:22 użytkownik xxcriticxx <notifications@github.com>
napisał:

> jaki box? jaki os masz?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mrknow/filmkodi/issues/319#issuecomment-219232436>
>


-- 

Wojciech Jakubas

**Comment by xxcriticxx** [comment]
plugin ma dependency w zypie odmontuj i zamontuj jeszcze raz

**Comment by mrknow** [comment]
zamykam
