### ISSUE TITLE
przepraszam

### ISSUE THREAD

**Issue by Ponczo24** [mrknow/filmkodi#32]

**Comment by mrknow** [comment]
iklub.net dodałem. Zaktualizuj sobie rano. Ten drugi później

**Comment by Ponczo24** [comment]
ok spoko dziekuje i pozdrawiam




W dniu niedziela, 10 stycznia 2016 mrknow <notifications@github.com>
napisał(a):

**Comment by Ponczo24** [comment]
hej witam od rana niemoge wejsc w twoja wtyczke



W dniu niedziela, 10 stycznia 2016 Mateusz przybya <mprzybya@gmail.com>
napisał(a):

**Comment by mrknow** [comment]
Wydaje mi się że źle aktualizowałem nowe wersje wtyczki. Nie brałem pod uwagę zależności. Nowe wersje będą już aktualizowane z zależnościami. Sprawdź dzisiaj. Jest dostępna nowa wersja
