### ISSUE TITLE
SMB Library integration STILL not working

### ISSUE THREAD

**Issue by Scotster** [mrknow/filmkodi#320]
Everytime I see a thread on this it gets closed out as fixed. At no point has this issue been resolved. I'm not sure how well the problem is being looked into but there seems to be a clear misunderstanding with what the issue is. If the issue is not cared about then please let me know, my workaround is fine.... but please stop saying it's fixed when it isn't.

I apologise if this is really dumbed down but every time I cut to the chase with the issue it gets completely overlooked and "Fixed" gets stamped on the thread so I'm guessing I'm either not explaining well enough or there are wrong assumptions about what the issue is being made.

Specto - Tools - Specto:Library - Library:Settings - Movies and/or TV

*******PLEASE NOTE I'M NOT TALKING ABOUT "DOWNLOADS"*********

There is no way to select SMB as the option for the location of strm files. Local is the only option. If the "Settings.xml" file is manually changed on the following lines.....

```
<setting id="movie_library" value="smb://SMBShare/Movies/" />
<setting id="tv_library" value="smb://SMBShare/TV Shows//" />
```

It won't work, Specto won't open and the following log is generated......

```
13:29:02 T:6532  NOTICE: [SPECTO]: ->----------                PARAMS: {}
13:29:02 T:6532   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.WindowsError'>
                                            Error Contents: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'smb:'
                                            Traceback (most recent call last):
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.specto\default.py", line 139, in <module>
                                                navigator.navigator().root()
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.specto\resources\lib\indexers\navigator.py", line 51, in __init__
                                                if not os.path.exists(movie_library): os.makedirs(movie_library)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\os.py", line 150, in makedirs
                                                makedirs(head, mode)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\os.py", line 150, in makedirs
                                                makedirs(head, mode)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\os.py", line 150, in makedirs
                                                makedirs(head, mode)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\os.py", line 157, in makedirs
                                                mkdir(name, mode)
                                            WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'smb:'
                                            -->End of Python script error report<--
13:29:02 T:6820   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.specto/
13:29:02 T:6820   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.specto/) failed
13:29:02 T:6532  NOTICE: [SPECTO]: ->----------                PARAMS: {}
13:29:02 T:6532   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.WindowsError'>
                                            Error Contents: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'smb:'
                                            Traceback (most recent call last):
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.specto\default.py", line 139, in <module>
                                                navigator.navigator().root()
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.specto\resources\lib\indexers\navigator.py", line 51, in __init__
                                                if not os.path.exists(movie_library): os.makedirs(movie_library)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\os.py", line 150, in makedirs
                                                makedirs(head, mode)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\os.py", line 150, in makedirs
                                                makedirs(head, mode)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\os.py", line 150, in makedirs
                                                makedirs(head, mode)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\os.py", line 157, in makedirs
                                                mkdir(name, mode)
                                            WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'smb:'
                                            -->End of Python script error report<--
13:29:02 T:6820   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.specto/
13:29:02 T:6820   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.specto/) failed
```

The ONLY way I have got this to work is to remove the following code in the"\addons\plugin.video.specto\resources\lib\indexers\navigator.py" file

```
53	        if not os.path.exists(movie_library):	
54	            os.makedirs(movie_library)			
55	        if not os.path.exists(tv_library):			
56	            os.makedirs(tv_library)			
57	        if not os.path.exists(tv_downloads):			
58	            os.makedirs(tv_downloads)			
59	        if not os.path.exists(movie_downloads):			
60	            os.makedirs(movie_downloads)
```

The above solves my issue.

Please if you read this MrKnow, take some time to understand what I'm talking about here. If you do not wish to address this issue please simply let me know and I'll stop harping on about it. Please don't mark it as "solved" when it's not though.

**Comment by Scotster** [comment]
I believe I have now found a permanent solution.

I searched around trying to figure out what the issue was and it seems to be OS.Makedirs as it has no idea what an SMB share is.

Unfortunately it means that, at least for now, the settings.xml file needs to be manually changed. Instead of having smb://server/address it now needs to read \\server\address.

I also managed to get this working with MP3 Streams downloads as it had exactly the same problem.

**Comment by mrbill13** [comment]
I am able to select a network location for the library either movies or tv after hitting backspace a couple of times for the network option to show up. But if I select a network location specto crashes when I hit ok and wont launch again until I change to a local drive. It doesn't have to be default location, just has to be a local drive.

**Comment by xxcriticxx** [comment]
@Scotster what happens when you create folders by hand?

**Comment by Scotster** [comment]
@mrbill13 I can't even select a network address. Not sure why yours is different. But yeah, I'm guessing the error is the same as what I've posted above from the log.

@xxcriticxx The folders are actually already created. Unless it's looking to create a further sub-directory.

I've not bothered to test it yet but my guess is that having \\server rather than smb:\\server\ will fix it.

**Comment by Scotster** [comment]
@mrbill13 just checked it again and I can access the SMB share, only when it's blank though.

**Comment by xxcriticxx** [comment]
@Scotster try it by ip

**Comment by Scotster** [comment]
It's the "smb:" it's failing on, not what follows it unfortunately.

<snip>
Error Contents: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'smb:'
</snip>

I tried using my previous suggestion \\share\etc but as much as it doesn't fail.... it doesn't store to the network. I'm still messing around but my initial suggestion still holds up fine.

**Comment by Scotster** [comment]
Out of curiosity I tried using the IP.

I tried the following:

smb://IP
//IP
\\IP
IP

Nothing worked. With the edited file both the IP and domain name work fine.

**Comment by mrbill13** [comment]
Just commenting these 2 lines in navigator.py works for me, specto launches.
#if not os.path.exists(movie_library): os.makedirs(movie_library)                                                                #if not os.path.exists(tv_library): os.makedirs(tv_library)

**Comment by xxcriticxx** [comment]
is your smb accessible from different computer?

**Comment by xxcriticxx** [comment]
any firewall? antivirus? any other blocking program?

**Comment by Scotster** [comment]
The issue isn't the SMB being accessible, it's readily accessible from every other addon and Kodi itself.

*sigh*

I appreciate the willingness to help me out but if you have read my initial post and came to the conclusion that my SMB server isn't accessible then there's not a lot you can help me with unfortunately.

Thanks for trying :)

**Comment by xxcriticxx** [comment]
tell me what to click on i will test this on my end

**Comment by Scotster** [comment]
@mrbill13 - Yeah I thought those lines would be enough now. I had already edited the navigator.py file previously, from when even the downloads settings weren't working. I believe that side of it was addressed and that was the reason why the threads were marked as fixed. Unfortunately it was always the library side I had the issue with.

I'm curious as to what those lines of code actually do :D

**Comment by Scotster** [comment]
@xxcriticxx - Rather than store my library links locally, I store them on my server as it allows me to access them from multiple devices very easily without any duplication. If I add a show on one device, it's instantly available on all other devices.

With the background out of the way you simply create a storage location on your network share. Mine is simply "smb:\\desktop\Media\TVshows".

If you go into the library settings of specto and select one of your SMB shared locations then save the settings, specto will no longer load up. (short version)

Long version is in the first post :D

**Comment by xxcriticxx** [comment]
i dont see smb:// all i see is special://

**Comment by Scotster** [comment]
In settings, under "Library" where it says TV the link should read Special://userdata/addon_data/plugin.video.specto/TVShows

Or something like that?

Anyway, click on it, then press the back button multiple times till you can see the top directory. From there you should see Windows Network (SMB) as an option. If you don't, hit "Defaults" then try again. If you still can't get it to work then you need to manually change the settings.xml to your SMB share location.

**Comment by xxcriticxx** [comment]
sorry let me try

**Comment by xxcriticxx** [comment]
i confirm your findings when i add smb path for tv show and movies specto wont open any longer

**Comment by Scotster** [comment]
Bingo ;)

**Comment by Scotster** [comment]
Latest version shows this....

`
        if not os.path.exists(movie_library): os.makedirs(movie_library)
        if not os.path.exists(tv_library): os.makedirs(tv_library)
        #if not os.path.exists(tv_downloads) and tv_downloads!='' : os.makedirs(tv_downloads)
        #if not os.path.exists(movie_downloads) and movie_downloads != '': os.makedirs(movie_downloads)
`

Still doesn't work, but commenting out everything fixes it.....

`
        #movie_downloads = os.path.join(control.transPath(control.setting('movie_downloads')),'')
        #if not os.path.exists(movie_library): os.makedirs(movie_library)
        #if not os.path.exists(tv_library): os.makedirs(tv_library)
        #if not os.path.exists(tv_downloads) and tv_downloads!='' : os.makedirs(tv_downloads)
        #if not os.path.exists(movie_downloads) and movie_downloads != '': os.makedirs(movie_downloads)
`

**Comment by mrknow** [comment]
Download movies is fixed. How to http://filmkodi.com/en/kodi-specto-faq/

**Comment by Scotster** [comment]
Are you serious? Did you miss this....

****PLEASE NOTE I'M NOT TALKING ABOUT "DOWNLOADS"******

?

I'm talking about "Add to library" not "Download".
