### ISSUE TITLE
Nowe telewizje do wtyczki Mrknow !!!

### ISSUE THREAD

**Issue by Crisever** [mrknow/filmkodi#321]
Propozycja Nowych telewizji do wtyczki Mrknow: 
http://www.amigostv.eu/
http://seb-tv.pl/#

**Comment by lluuppoo** [comment]
Super pomysl !!!
jebac platna premium telewizjade !!!

**Comment by plumers** [comment]
http://www.kreskowkazone.pl/ MrKnow poprosze o to - tutaj jest mnóstwo dla dzieci :) Masza Rulzzz

**Comment by xxcriticxx** [comment]
@plumers sasiedzi rules!!! :100: %

**Comment by borys76** [comment]
Fajna strona,jestem tez za dodaniem do wtyczki

**Comment by mrknow** [comment]
Wersja 2016.05.28.1
    - nowa telewizja amigos.tv
Kreskówka - w tym tygodniu

**Comment by borys76** [comment]
Super dzieci beda mieli co ogladac :)

**Comment by borys76** [comment]
Na amigos tv cos malo kanalow 
Warto dodawac?

**Comment by borys76** [comment]
Widze ze amigos juz dodane

**Comment by mrknow** [comment]
dodałem - to 15 minut roboty. Bajki dodam w sobotę (taki mam przynajmniej plan)

**Comment by borys76** [comment]
A dalo by rade dodac 
http://www.kreskoweczki.pl
Jest na sd-xbmc ale mi cos niedziala a jest tam duzo bajek dla dzieci

**Comment by plumers** [comment]
http://pol-xtv.blogspot.com z okazji dnia dziecka niebawem :) pozdrawiam - jest więcej ale wolałbym MrKnow pisać do ciebie na Priv a za bardzo nie mam jak :) wtedy tylko byś dodawał nazwy np TV ONLINE 1  - a link nie byłby aż tak widoczny dla innych , dłużnej pośmiga  - pozdrawiam

TVN player dalej ciężko z kodowaniem ?? :)

**Comment by xxcriticxx** [comment]
@plumers super pomysl

**Comment by plumers** [comment]
http://www.kreskowki.tv
http://mytvlive.me/   cos tam działa  :) pozdrawiam

kiedy telewizja live com tutaj smiga najwiecej :) ??

**Comment by plumers** [comment]
http://telewizja-online.pl

**Comment by xxcriticxx** [comment]
pozdrowienia dla plumers!

http://telewizja-online.pl/
http://telewizja-live.com/
http://tvzafree.pl/

**Comment by plumers** [comment]
I-HTV.NET

**Comment by plumers** [comment]
MrKnow  kreskówki nie działa połowa , bo trzeba się zalogować na konto - jeśli możesz dodaj tę opcję w USTAWIENIACH pozdrawiam  :)

**Comment by plumers** [comment]
http://canlitvxl.blogspot.com/p/free-polska-vlc-tv.html --- śmiga :) pozdro

**Comment by mrknow** [comment]
@plumers - dzisiaj postaram się aby wszystko tam działało. Zabieram się do roboty ...

**Comment by mrknow** [comment]
looknij.in - też dodam ale do wtyczki  MrknowTV

**Comment by koladka** [comment]
Mam taka propozycje moze na youtube masz jakies konto gdzie mozna cos czasami napisac zapytac ,bo to bylo trudno znalesc i jakos malo widoczne to forum?

**Comment by koladka** [comment]
A wiec tak jakas aktualizacja byla wlasnie ? Mam pytanie czy na mrknow tv zeby cos obejrzec trzeba miecz premium wykupione zeby cos ogladac czy wystarczy zalozyc konto w tych serwisach z tv ?  Myslalem ze sie cos zmieni po aktualizacji tej zwyklej mrknow ale dalej nic nie idzie! Niewiem co jest przyczyna czy box czy moze cos innego --- wtyczka jest pozatym super dzieki , kawal dobrej roboty  .

**Comment by borys76** [comment]
Mrknowtv musisz miec premium konta do tych serwisow

**Comment by borys76** [comment]
Oczywiscie konto premium do serwisu ktory chcesz ogladac nie do mrknowtv 
Mrknowtv jest za darmo

**Comment by koladka** [comment]
Znow pisze sory ale dziwnie to napisales dobrze rozumiem musze miec wykupione premium i loguje sie wtedy z haslem na mrknow takim jak w serwisie?  A jaka jest mozliwosc ze na zwyklym mr know bedzie cos dzialac bo niestety naczytalem sie ze jest to nielegalne jak komus zaplacisz za ogladanie takiego serwisu, a co innego jak ogladasz takie darmowe!

**Comment by borys76** [comment]
Glupot sie naczytales ogladanie TV online jest legalne nie wazne czy zaplaciles czy nie 
Nie legalne jest streamowanie tv

**Comment by plumers** [comment]
borys76 uświadomię Cię - jeżeli płacisz za oglądanie TV - premium - to jesteś współsprawcą kradzieży sygnału --- poczytaj :) oglądanie streamu nie jest złem ale płacenie już tak :) ok MR czekam pozdro

**Comment by borys76** [comment]
Dalej twierdze ze ogladanie jest legalne night  nie slyszalem zeby kogos ukarali za ogladanie

**Comment by koladka** [comment]
Plumers dokladnie masz racje pytalem sie kumpla ktory mial rozprawe za to doszli po tym ze zaplacil mieli w sadzie wszystko jego dane z konta i komu co zaplacil a tego serwisu juz niema. Kara 5 tysiecy.

**Comment by koladka** [comment]
Dlatego wlasnie wole wtyczki darmowe

**Comment by borys76** [comment]
Pokazcie mi jeden artykul ze kogos ukarali za ogladanie.
Ogladanie nielegalnej tv online jest legalne

**Comment by plumers** [comment]
Ogladanie nielegalnej tv online jest legalne - przeczytaj co napisałeś i się zastanów. 

Poszukaj w internecie - porada prawna u radcy 50zł ... lepiej wiedzieć niż potem siedzieć ... nieznajomość prawa nie zwalnia z jego przestrzegania -- koniec tematu bo tutaj jest NOWE WTYCZKI a nie NOWE PORZĄDKI z PITBULLA :)

**Comment by koladka** [comment]
http://pol-xtv.blogspot.com 
Jak mozesz to wrzuc ta telewizja darmowa smiga super.
Te co sa aktualnie tylko wizja czasem chodzi.

**Comment by koladka** [comment]
http://pol-xtv.blogspot.com 
Jak mozesz to wrzuc ta telewizja darmowa smiga super.
Te co sa aktualnie tylko wizja czasem chodzi.

**Comment by koladka** [comment]
http://pol-xtv.blogspot.com 
Jak mozesz to wrzuc ta telewizja darmowa smiga super.
Te co sa aktualnie tylko wizja czasem chodzi.

**Comment by koladka** [comment]
http://pol-xtv.blogspot.com 
Jak mozesz to wrzuc ta telewizja darmowa smiga super.
Te co sa aktualnie tylko wizja czasem chodzi.

**Comment by koladka** [comment]
http://pol-xtv.blogspot.com 
Jak mozesz to wrzuc ta telewizja darmowa smiga super.
Te co sa aktualnie tylko wizja czasem chodzi.

**Comment by koladka** [comment]
http://pol-xtv.blogspot.com
Ta telewizja smiga jak mozesz to dodaj bo tylko Wizja z darmowych czasem chodzi. Dzieki

**Comment by koladka** [comment]
http://pol-xtv.blogspot.com
Ta telewizja smiga jak mozesz to dodaj bo tylko Wizja z darmowych czasem chodzi. Dzieki

**Comment by plumers** [comment]
koladka nie spamuj....z uwagi na to ,że wiecej tutaj dzieci niż normalnych userów darmowe strony z tv online szukajcie sobie już sami ---- pozdrawiam i THX MR za wkład włożony.... nikt prawie nie daje Ci na dotacje -- robisz to za free ale ten wolny czas trzeba jakoś znaleźć kosztem czegoś a jakby parę złotówek wpadło , to by wypełniło tę lukę ... pozdrawiammmmmmmmmmmmmmmmmm
