### ISSUE TITLE
Jak zainstalowac wtyczke premium tv

### ISSUE THREAD

**Issue by Pinol** [mrknow/filmkodi#322]
Witam jak zaonstalowac wtyczke i gdzie oplacic?

**Comment by xxcriticxx** [comment]
huh? wtyczka jest darmowa

**Comment by Pinol** [comment]
Ale niemoge zainstalowac wyskakuje blad

**Comment by xxcriticxx** [comment]
jaki system? jaki os? jaki blad? log?

podaj info

**Comment by gumball1** [comment]
Potwierdzam problem z istalacja:
ERROR: CAddonInstallJob[plugin.video.mrknowtv]: could not read addon description of special://home/addons/plugin.video.mrknowtv

**Comment by xxcriticxx** [comment]
jaka ver?

**Comment by mar2016** [comment]
Po instalacji wtyczki Telewizja Premium wyskakuke blad  INSTALACJA NIEUDANA

**Comment by Pinol** [comment]
Android kodi 16.1

**Comment by xxcriticxx** [comment]
ostatnia ver to 2016.05.15.4

Wersja 2016.05.15.4
    - cda.pl - poprawka
    - parsevshareio poprawka
    - tvn player - poprawiony (skopiowaÅ‚em jak leci ze strony http://sd-xbmc.org/)

**Comment by xxcriticxx** [comment]
hyba ze wam chodzi oto

------------------------
Premium TV v2016.06.01.01
------------------------
Startujemy

**Comment by mar2016** [comment]
Tak

**Comment by xxcriticxx** [comment]
jak cos sie dowiem to dam znac narazie wiem 0%

**Comment by mar2016** [comment]
Dziekuje

**Comment by Pinol** [comment]
Temat do zamkniecia

**Comment by Pinol** [comment]
Dziekuje za wyjasnienie

**Comment by Pinol** [comment]
Dzieki
