### ISSUE TITLE
telewizjada goes premium 

### ISSUE THREAD

**Issue by xxcriticxx** [mrknow/filmkodi#323]
Komunikat

   Mając na uwadze jakość oferowanych przez nas usług zostaliśmy zmuszeni do rozpoczęcia prac nad wprowadzeniem kont premium.
   Czynimy starania aby zakończyć je szybko. Za utrudnienia przepraszamy.

**Comment by Pinol** [comment]
A skad to wzieles?

**Comment by plumers** [comment]
LOL --- jak to było do przewidzenia - na początku ile utrzyma serwer ludzi - potem ilu chętnych a teraz KASIORĘ za to będą łykali --- > plan prawie doskonały :D

**Comment by diesel001** [comment]
Wiecie może mniej więcej kiedy to nastąpi?

**Comment by xxcriticxx** [comment]
wieczorem wyskakuje jak strona jest przeladowana 

napewno zacznie sie przed euro 2016 jak plumers mowil

**Comment by lluuppoo** [comment]
jebac ich i pomysl na jakies konto premium !!!

**Comment by gumball1** [comment]
Brawo Telewizjada !

**Comment by plumers** [comment]
Z uwagi na fakt iż niebawem zjbeajc ,czy jak się zwie ten kiep - będzie pośmiewiskiem YT ... :) wstrzymam się z komentarzem co do Tele...dy :) ... ale z uwagi na fakt ,ze Polska ,to kraj gdzie jak promocja jest za darmo , to jeszcze jest za mało :) -- tak więc z patrząc na stabilność serwisu , ile serwery wytrzymały i jaką można jakość zaoferować bez szwanku - technologia p2p wciąż żywa i fakt ,że nowy projekt jak i technika zastosowana wytrzymuje ok  kilka tys userów --- serwis niebawem będzie oferował coś pokroju DOSUG :)  z naciskiem na oczywiście to co się wyświetlało na stronie  docelowo 100 kanałów tych , które są najpopularniejsza z platform cyfrowych a są premium za dodatkową opłatą--- osoby zażenowany tym ,że nie jest za free muszą się z tym pogodzić , bo nie ma nic za darmo prawda Panie zjac :) --- ready and waiting :) 

MrKnow niebawem jedzie na urop - więc jemu też dajcie odpocząć czasu nikt nie kupi :) 

miłego upalnego weekendu i pogody
