### ISSUE TITLE
Question for Putlocker on Specto

### ISSUE THREAD

**Issue by dracosc** [mrknow/filmkodi#324]
Hi. Is there a reason why my Windows Kodi can get Putlocker sources, but my android kodi cannot?

**Comment by xxcriticxx** [comment]
Check kodi ver on both machines

**Comment by dracosc** [comment]
Both running on 16.1
Do you get putlocker on android?

**Comment by xxcriticxx** [comment]
i can test i let you know tonight

**Comment by dracosc** [comment]
Did you test?

**Comment by xxcriticxx** [comment]
what movie/tv show did you search for exactly?

**Comment by dracosc** [comment]
All! I NEVER get putlocker links

**Comment by dracosc** [comment]
Nobody got any idea?

**Comment by xxcriticxx** [comment]
i cant see any putlocker links in what i tested

**Comment by dracosc** [comment]
Lambda has updated exodus and added putlocker source from the same website, and works perfectly. So it is not a matter of windows vs android compatibility problem!

**Comment by xxcriticxx** [comment]
give me some title of movie/tvshow from exodus that has putlocker links

**Comment by dracosc** [comment]
Movie Deadpool for example, gives 1080p, HD and SD links so both android and windows. In Specto, i get putlocker links only under windows system!

**Comment by xxcriticxx** [comment]
i got zero putlocker links in deadpool on win7

**Comment by dracosc** [comment]
Exodus ver 1.3.3 last night updated!

**Comment by xxcriticxx** [comment]
i checked with specto 2016.05.10.7 on win7

**Comment by dracosc** [comment]
I said exodus gives putlocker...... https://www.dropbox.com/s/nsvlmd97bvwzrwt/Screenshot_2016-05-29-17-38-27.png?dl=0 this is on android

**Comment by dracosc** [comment]
Specto win7 gives me putlocker but cant share foto now. I am on mobile.

**Comment by xxcriticxx** [comment]
i dont get any and i have putlocker checked in settings

**Comment by xxcriticxx** [comment]
your dropbox is dead This account's links are generating too much traffic and have been temporarily disabled!

**Comment by dracosc** [comment]
Strange. I can send icons when i get back at a pc! I get MANY putlocker links in specto under win7 for most movies and tvshows as i remember

**Comment by dracosc** [comment]
http://s20.postimg.org/ss3uv7f99/screenshot008.png
http://s20.postimg.org/sgmeifyt9/screenshot009.png
http://s20.postimg.org/uz83j4kjh/screenshot010.png

**Comment by dracosc** [comment]
these are from specto on win7!

**Comment by xxcriticxx** [comment]
your zoolander http://s20.postimg.org/uz83j4kjh/screenshot010.png
compare 
my zoolader http://imgur.com/wcXuV5g

**Comment by dracosc** [comment]
Try deleting folder kodi\userdata\addon_data\plugin.video.specto , restart kodi and try again and post!

**Comment by xxcriticxx** [comment]
i dont have this folders

**Comment by xxcriticxx** [comment]
zoolander after i remove plugin.video.specto

![capture1](https://cloud.githubusercontent.com/assets/15007183/15637084/efead586-25de-11e6-86ee-f297b56efbbf.PNG)

**Comment by xxcriticxx** [comment]
my settings for movies showing putlocker selected
![capture2](https://cloud.githubusercontent.com/assets/15007183/15637089/1223b398-25df-11e6-9f0e-bef191256b82.PNG)

**Comment by dracosc** [comment]
So putlocker is locked by your isp!

**Comment by dracosc** [comment]
Try accessing http://www.putlocker.systems from your browser to see if it works!

**Comment by xxcriticxx** [comment]
it fowards to cloudfair then to flixanity.is

**Comment by dracosc** [comment]
For me it stays in www.putlocker.systems !!!! Very strange! Let me try something!

**Comment by xxcriticxx** [comment]
your sure you got the correct website?

**Comment by dracosc** [comment]
Wow! For me if i try to access flixanity.is, it takes me to putlocker-movies.tv
Try editing putlocker_mv_tv.py and change www.pulocker-systems to flixanity.is or putlocker-movies.tv
Clear sources from soecto tools and try to load links for some movies!

**Comment by dracosc** [comment]
Sure it is correct. Check the scraper file in lib, resolvers putlocker_mv_tv.py

**Comment by xxcriticxx** [comment]
not home right now i will try it today

**Comment by xxcriticxx** [comment]
putlocker-movies.tv brings me to flixanity.is

what isp you got? whats the ip? maybe we can try this way

**Comment by dracosc** [comment]
I am in Cyprus. Nothis actually is blocked here! Go to /kodi/addons/plugin.video.specto/resources/lib/sources and edit putlocker_mv_tv.py.......and where you see www.putlocker.systems change to flixanity.is or www.flixanity.is
Then load kodi again and test specto!

**Comment by xxcriticxx** [comment]
yes i will play with it once am home

**Comment by mrknow** [comment]
I will fix this issue today, or tomorrow

**Comment by dracosc** [comment]
I am sure you can do it mrknow 😀 we trust you! Thanks to you we have our favourite addon alive!

**Comment by xxcriticxx** [comment]
@dracosc you can close this issue

**Comment by dracosc** [comment]
Let mrknow solve the puzzle first. He may need our testings or help!

**Comment by dracosc** [comment]
I dont know what changed, but out of nowhere, i get putlocker links now on both Android and Windows!

**Comment by xxcriticxx** [comment]
new version?

**Comment by xxcriticxx** [comment]
or this 

 mrknow commented 4 days ago

I will fix this issue today, or tomorrow

**Comment by dracosc** [comment]
Seems like we lost putlocker links again.....

**Comment by mrknow** [comment]
putlocker fixed
