### ISSUE TITLE
update not working

### ISSUE THREAD

**Issue by karnage11** [mrknow/filmkodi#325]
Specto Update not working at all

**Comment by karnage11** [comment]
Just  tried to uninstall and reinstall but no luck at all

**Comment by mystico29** [comment]
same here could you add a zip file please

**Comment by karnage11** [comment]
just have to wait for Mrknow to replay

**Comment by xxcriticxx** [comment]
there is nothing newer then this plugin.video.specto-2016.05.8.7.zip                08-May-2016 22:18             6266417

**Comment by karnage11** [comment]
need the Zip please

**Comment by pio4ADay** [comment]
Hi, yeah as said above the update failed, specto now behaves just as genesis with nothing opening or working. Can some1 please place a zip link here or fix the update server? Thanks a heaps, keep up the good work.

**Comment by karnage11** [comment]
https://github.com/mrknow/filmkodi/issues/326

**Comment by reignmyway** [comment]
Specto version 2016.05.10.6 will not install from the filmkodi.com/repository is gives the message installation failed. Im using kodi 16.1 jarvis.
