### ISSUE TITLE
Specto-Fork update is not working

### ISSUE THREAD

**Issue by christian304** [mrknow/filmkodi#326]
I tried to update and returns with an error "update failed". I tried uninstalling and reinstalled same error. Thank you for any input on this matter.

**Comment by christian304** [comment]
Upon further research, I think server might down because of the sudden on set of new Specto users. Do to Exodus going over to onlySD links and pay for HD links.

**Comment by borys76** [comment]
Insall manually 
http://kodi.filmkodi.com/plugin.video.specto/plugin.video.specto-2016.05.10.6.zip

**Comment by reignmyway** [comment]
Specto version 2016.05.10.6 will not install from the filmkodi.com/repository is gives the message installation failed. Im using kodi 16.1 jarvis.

**Comment by reignmyway** [comment]
Also I use kodi on my firestick by the way.

**Comment by borys76** [comment]
Install plugin with out repository look one post up

**Comment by reignmyway** [comment]
So the add source would be the address listed above ??? If so then what am I looking for when I install from zip ...thanks a bunch

**Comment by borys76** [comment]
Just download zip file to your device and in kodi install from zip

**Comment by kostaboxon** [comment]
I have Specto version 2016.05.10.6 installed and am getting Update failed. I have been getting updates and this is the latest version updated on my system. Something causing available update and then update failed.

**Comment by reignmyway** [comment]
thank you that worked👍

**Comment by borys76** [comment]
NP

**Comment by LJHookem14** [comment]
thanks boyrs76

**Comment by dracosc** [comment]
There is something strange here! Mrknow has made some changes yesterday on 2016.05.10.6. he didn't release a newer version! But the strange thing is that, if you already have this version installed, his repo still finds an update but there is no update!!! This is why it fails!

**Comment by aft207** [comment]
Hi I have uninstalled and reinstalled it through repository but in the films section the films only go up until the 1970's nothing after that is there anything I can do to fix this.

**Comment by mrknow** [comment]
you have to set your clock in your  box

**Comment by mrknow** [comment]
Update problem is solved in new version

**Comment by kokoronikui** [comment]
Does specto work under Jarvis 16.1? I had no issue when on kodi but after migrating to 16.1 it would just crash to my android launcher when trying to select a drama title

**Comment by kostaboxon** [comment]
Sorry i use OpenELEC Jarvis 16.1 with no issues.
Cant comment on Android.

**Comment by christian304** [comment]
Thank you all, and to you Mr.Know. this issue has been repaired. ✴

**Comment by AliA786** [comment]
I have a new issue, Mr Know the links within spectro work and after a few minutes the links vanish and when u click on what u want to watch says source not available
