### ISSUE TITLE
Update/Installation Failure

### ISSUE THREAD

**Issue by deejay2102** [mrknow/filmkodi#329]
Running Kodi 15.2 on Win 10. Specto installed from Fusion/Goliath.
Specto working fine but fails to update. Uninstalled Specto, Tried to re-install from repo but although visible in repo fails to install. Restored from backup works fine but still will not update.

**Comment by deejay2102** [comment]
OK. Found solution in earlier post. Must learn to read before posting.

**Comment by mystico29** [comment]
how did you fix it
