### ISSUE TITLE
MySpecto Trakt Progress incorrectly shows "hidden" shows.

### ISSUE THREAD

**Issue by graulito** [mrknow/filmkodi#332]
So when linked with Trakt, the  MySpecto directory adds the "Trakt:Progress" directory which shows a list of all our trakt shows and their up to date progress... however, this list includes shows that are marked as hidden by trakt (and do not show up by default when querying the trakt website directly).

I tried tracking the specific call in the code.. and I THINK it falls within episodes.py.

The 'Trakt: Progress' directory makes a calls the Calendar routine with the progress param 
(e.g.  Calander("progress"))... which then calls the cached result of  the trakt_list2() routine.

Finally, trakt_list2 appends "?extended=full" to the url param and makes a call to getTrakt(url) - where in this case i belive url="calendar?extended=full". getTrakt makes the actual trakt api call and parses the results into the list...

I assume that maybe the extended=full option means that trakt is returning all shows (even hidden ones), but I couldn't verify because these trakt api calls are NOT the ones that trakt API documentation is telling developers to use... so im not sure if this is an older API or whatnot... anyway, It's really annoying to keep seeing shows on the progress list that we've hidden/abandoned or jsut don't wanna see for whatever reason so it would be great if this code could be updated to respect trakts "hidden" shows features...

Thanks!

**Comment by mrknow** [comment]
old issue
