### ISSUE TITLE
videostar.pl - nie wczytuje listy kanałów

### ISSUE THREAD

**Issue by ramiel90** [mrknow/filmkodi#334]
Po podaniu maila i hasła do konta premium można przejść do wyboru kanałów, ale wybór konkretnego kanału kończy się informacją o braku dostępnego strumienia danych.

Wersja wtyczki z dnia 26.05.2016, wersja Kodi 16.1

**Comment by mrknow** [comment]
Dzięki - a możesz sprawdzić na axn hd. Taki sam efekt ? czy masz wersję 2016.06.01.9?

**Comment by ramiel90** [comment]
Na axn hd tak samo. Tylko wtyczkę mam w wersji 2016.06.01.08. Do takiej mi się zaktualizowało i nowszej nie widzę.

**Comment by eko5** [comment]
wersji 2016.06.01.08 nie aktualizuję do wersji .9 , po za tym czy to pierwsza.tv czy yoy.tv na obu występuję ten sam problem , czyli braku dostępnego strumienia danych

**Comment by Adam-po** [comment]
Na Kodi pierwsza.tv nie działa a na stronie wszystko działa czemu?

Gesendet von Yahoo Mail auf Android 
 
  Am Fr., 27. Mai 2016 um 10:55 hat eko5<notifications@github.com> Folgendes geschrieben:   
wersji 2016.06.01.08 nie aktualizuję do wersji .9 , po za tym czy to pierwsza.tv czy yoy.tv na obu występuję ten sam problem , czyli braku dostępnego strumienia danych

**Comment by eko5** [comment]
wtyczka 2016.06.01.9  dalej to samo 

> braku dostępnego strumienia danych


15:15:25 T:140696820381440  NOTICE: [SPECTO]: ->----------                PARAMS: {'name': 'TVP Sport HD', 'service': 'pierwsza', 'title': 'TVP Sport HD', 'meta': '{"name": "TVP Sport HD", "service": "pierwsza", "title": "TVP Sport HD", "fanart": "http://pierwsza.tv/img/thumbs/2016-05-27_6e63ea3771235c5d737e4de4a61cfaf2.jpg", "poster": "http://pierwsza.tv/img/thumbs/2016-05-27_6e63ea3771235c5d737e4de4a61cfaf2.jpg", "next": "", "originaltitle": "TVP Sport HD", "id": "46"}', 't': '20160527081412417184', 'action': 'play'}
15:15:25 T:140696820381440 WARNING: Attempt to use invalid handle -1
15:15:25 T:140696820381440  NOTICE: [SPECTO]: ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ

**Comment by mrknow** [comment]
OK. Sprawdzę to i jutro rano wypuszczę aktualizację. Tymczasem wypuszczam wersję 2016.06.02.1. wyłączyłem cache kanałów - może to była przyczyna..

**Comment by wacekrnyna** [comment]
Witam. U mnie na Win10 działa tylko Weeb.  Na androidzie 5.1 działa Pierwsza.tv i Weeb. Nie działa Videostar.pl, do którego nawet nie mogę się zalogować. Nie mam możliwości sprawdzenia Yoy tv ponieważ nie posiadam tam konta premium. Obydwa urządzenia wersja 2016.06.02.1 na  Kodi v16.1 “Jarvis”

**Comment by mar2016** [comment]
Potwierdzam na win10 kodi 16.1 nie dziala pierwsza.tv i videostar , a na androidzie oprocz videostar dziala reszta

**Comment by wacekrnyna** [comment]
Po aktualizacji do 2016.06.02.2 , Android - nie działa tylko Videostar.pl , nie można się zalogować do tego serwisu. Win 10 działa tylko Weeb i Yoy

**Comment by mar2016** [comment]
U mnie na Win10 dziala juz pierwsza.tv po nowej aktualizacji , nie dziala tylko videostar na androidzie i PC

**Comment by wacekrnyna** [comment]
Potwierdzam. Pozostaje tylko problem z videostar na obu systemach

**Comment by mrknow** [comment]
Wklej logi z kodi. Mam podejrzenie że chodzi o blokady regionalne

**Comment by odziom91** [comment]
Log (z Linuxa) w załączniku. Testowano na Androidzie 5.1.1 (Android Box TV M8S+ oraz Sony Xperia Z3 Compact) i na PC z systemem Debian 9 (Jessie)
[kodi_mrknow.txt](https://github.com/mrknow/filmkodi/files/290148/kodi_mrknow.txt)

**Comment by odziom91** [comment]
Log Kodi (Android):
[kodi_android.txt](https://github.com/mrknow/filmkodi/files/290153/kodi_android.txt)

**Comment by mrknow** [comment]
Coś z logowaniem nie tak. Wypuściłem nową wersję 2016.06.02.4. A ty sprawdź poprawność loginu i hasła zapisanego w ustawieniach

**Comment by xxcriticxx** [comment]
lots font error and this on linux 
  
PARAMS: {}
01:25:09 T:140686921807616  NOTICE: [SPECTO]: ->----------                PARAMS: {'action': 'tv', 'url': 'videostar'}
01:25:10 T:140686921807616  NOTICE: [SPECTO]: Result status
01:25:10 T:140686921807616  NOTICE: [SPECTO]: Error tv.get2 string indices must be integers
01:25:10 T:140686921807616  NOTICE: [SPECTO]: Result channels
01:25:10 T:140686921807616  NOTICE: [SPECTO]: Error tv.get2 string indices must be integers
01:25:10 T:140689468144128   ERROR: GetDirectory - Error getting plugin://plugin.video.mrknowtv/?action=tv&url=videostar
01:25:10 T:140689468144128   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mrknowtv/?action=tv&url=videostar) failed
01:25:10 T:140686921807616  NOTICE: [SPECTO]: ->----------                PARAMS: {}
01:25:13 T:140686921807616  NOTICE: [SPECTO]: ->----------                PARAMS: {'action': 'tv', 'url': 'videostar'}
01:25:13 T:140686921807616  NOTICE: [SPECTO]: Result status
01:25:13 T:140686921807616  NOTICE: [SPECTO]: Error tv.get2 string indices must be integers
01:25:13 T:140686921807616  NOTICE: [SPECTO]: Result channels
01:25:13 T:140686921807616  NOTICE: [SPECTO]: Error tv.get2 string indices must be integers
01:25:13 T:140689468144128   ERROR: GetDirectory - Error getting plugin://plugin.video.mrknowtv/?action=tv&url=videostar
01:25:13 T:140689468144128   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mrknowtv/?action=tv&url=videostar) failed
01:25:13 T:140686921807616  NOTICE: [SPECTO]: ->----------                PARAMS: {}

**Comment by xxcriticxx** [comment]
android 

ERROR: int CScriptInvocationManager::ExecuteAsync(const string&, const AddonPtr&, const std::vector<std::basic_string<char> >&) - Not executing non-existing script /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.navi-x/service.py
01:32:30 T:18446744072347099392
ERROR: virtual bool CImageLoader::DoWork() - Direct texture file loading failed for resource://resource.images.studios.white/.png
01:32:45 T:18446744072007999744
ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.mrknowtv/?action=tv&url=videostar
ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mrknowtv/?action=tv&url=videostar) failed

**Comment by odziom91** [comment]
Ok. Już wiem w czym problem.
Videostar pracuje w dwóch trybach - darmowym i premium z poszczególnymi pakietami.
Niestety w chwili obecnej wtyczka NIE działa bez wykupionego konta premium - a szkoda, bo weeb.tv w MrKnowTV ładuje listę programów i można oglądać przez pierwsze 100MB za free.

A zatem błąd:
01:25:10 T:140686921807616 NOTICE: [SPECTO]: ->---------- PARAMS: {}
01:25:13 T:140686921807616 NOTICE: [SPECTO]: ->---------- PARAMS: {'action': 'tv', 'url': 'videostar'}
01:25:13 T:140686921807616 NOTICE: [SPECTO]: Result status
01:25:13 T:140686921807616 NOTICE: [SPECTO]: Error tv.get2 string indices must be integers
01:25:13 T:140686921807616 NOTICE: [SPECTO]: Result channels
01:25:13 T:140686921807616 NOTICE: [SPECTO]: Error tv.get2 string indices must be integers

Spowodowany jest brakiem konta premium. :) Testowałem na wersji "2016.06.02.4" - najpierw bez premium - wypluwając błąd:
07:19:22 T:140628083222272  NOTICE: [SPECTO]: ->----------                PARAMS: {'action': 'tv', 'url': 'videostar'}
07:19:22 T:140628083222272  NOTICE: [SPECTO]: Result status
07:19:22 T:140628083222272  NOTICE: [SPECTO]: Error tv.get2 string indices must be integers
07:19:22 T:140628083222272  NOTICE: [SPECTO]: Result channels
07:19:22 T:140628083222272  NOTICE: [SPECTO]: Error tv.get2 string indices must be integers
07:19:22 T:140629475523072   ERROR: GetDirectory - Error getting plugin://plugin.video.mrknowtv/?action=tv&url=videostar
07:19:22 T:140629475523072   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mrknowtv/?action=tv&url=videostar) failed
07:19:22 T:140628083222272  NOTICE: [SPECTO]: ->----------                PARAMS: {}

A potem z premium - bez błędów.

Sugestie?
- dodanie informacji o braku konta premium
lub
- dodanie darmowej obsługi (nie wiem, czy to możliwe, bo w darmowym trybie videostar wyświetla reklamy - a to w sumie nie fair, aby je pomijać w Kodi - poza tym nie wiem, czy API to obsługuje, więc to już programista musi wiedzieć ;))

Tak czy siak - u mnie działa (PREMIUM).
Pozdrawiam!

**Comment by xxcriticxx** [comment]
odziom91 jakiego typu reklamy? reklamy telewizyjne czy reklamy reklamy?

**Comment by xxcriticxx** [comment]
aha Proszę wyłączyć blokowanie reklam czyli anti-adblock-killer potrzebny

**Comment by odziom91** [comment]
@xxcriticxx 
` jakiego typu reklamy? reklamy telewizyjne czy reklamy reklamy?`
Reklamy udostępniane przez Videostar przed uruchomieniem programu TV (30 sekund).

W przeglądarce internetowej po prostu wyłącza się adblocka i śmiga. W oficjalnej aplikacji na Androida też ładuje reklamy.
Kodi prawdopodobnie wyłapuje tylko ścieżkę do streamu.

**Comment by xxcriticxx** [comment]
odziom91 zamontuj polish-ads-filter i anti-adblock-killer przetestuj

widze ze jest geo lock

**Comment by mrknow** [comment]
powinno być lepiej. Dodałem darmowe kanały
