### ISSUE TITLE
Konto premium dla wizja.tv

### ISSUE THREAD

**Issue by pafcio14** [mrknow/filmkodi#336]
Cześć,

Czy jest możliwość dodania logowania do konta premium dla wizja.tv?
Telewizjada tez już wprowadza...

**Comment by mrknow** [comment]
Witam. Mam dostać więcej informacji w przyszłym tygodniu (dzisiaj 28-05-2016). Jeżeli zespół wizji mi to umożliwi - na pewno dodam obsługę tej strony do swojej wtyczki.

**Comment by pafcio14** [comment]
Dzięki za odpowiedź. A jak z  yoy.tv i telewizjada?

**Comment by mrknow** [comment]
wizja.tv niebawem. Obecnie ruszyła produkcja

**Comment by mrknow** [comment]
wizja.tv dodana
