### ISSUE TITLE
trakt.tv manager missing from context menu

### ISSUE THREAD

**Issue by startreksuite** [mrknow/filmkodi#337]
Hi, 
I have noticed that when I go into my trakt tv collection in specto, and click on the context menu when selecting a tv show to manage, the trakt tv manager doesn't show up. This seems to be occurring in my g box mx2, running 15.1. My laptop and phone running 16.1 don't have this issue. Is this specific to 15.1, or is there another issue that needs to be addressed? 
Thanks!

**Comment by mrknow** [comment]
Added
