### ISSUE TITLE
Urlresolver on Specto.

### ISSUE THREAD

**Issue by dracosc** [mrknow/filmkodi#339]
Hi Mrknow.....i would like to ask, how difficult is it to integrate urlresolver in specto instead of its own resolvers? That would make future specto development much easier! I can help a bit with coding!

**Comment by mrknow** [comment]
Work on it in early July

**Comment by dracosc** [comment]
If you need any help or testing, just let me know my friend! And THANKS for all!

**Comment by xxcriticxx** [comment]
Lambda is currently working on a new Kodi add-on and wanted URLResolver to be the universal method for opening streams, so he changed over 143 sources files and 7000 lines of code to optimize and make URLResolver better:

URLResolver Kodi newest changes:

    Every resolver has been reviewed and fixed, as needed
    Every defunct resolver has been removed
    Five new resolvers have been added
    Simply-Debrid is now supported
    Google’s ReCaptcha Version 2 is now supported (“I’m not a robot” checkboxes)
    New method of simplifying ReCaptcha has been added
    FilePup’s resolver has been updated to a hoster supported method (meaning less frequent breakage)
    Simplification across the board to make adding resolvers easier

You probably already have the latest Kodi URLResolver update already, so you can go and enjoy the changes lambda has made!

You can view URLResolver settings and set things like priority and premium accounts up by navigating to SYSTEM > Add-ons > SYSTEM > Dependencies > URLResolver > Configure.

**Comment by bjgood** [comment]
Nice! Looking forward to it. :).

I had thought of the very same thing a month or two ago, but figured that would be a major undertaking...which I'm sure it will be.

Later...
