### ISSUE TITLE
xbmcfilm.com obsługa Uptobox

### ISSUE THREAD

**Issue by Seico** [mrknow/filmkodi#34]
Bardzo proszę o dodanie obsługi video na xbmcfilm.com z Uptobox.com

**Comment by xxcriticxx** [comment]
Sorry, Uptobox.com is not available in your country

**Comment by mrknow** [comment]
podaj przykładowego linka do materiału video.

**Comment by Seico** [comment]
Proszę bardzo 
http://uptostream.com/tym3s2tdoisf

**Comment by mrknow** [comment]
Witam 
Planuję do 25.01.2016 - dodać obsługę tego serwisu

**Comment by mrknow** [comment]
Trochę się przeciągnęło, ale dodałem. Możliwość odtwarzania będzie możliwa od jutra. Dzisiaj w nocy puszczę aktualizację.

**Comment by Seico** [comment]
Dzięki bardzo i czekam na wyniki :)

**Comment by mrknow** [comment]
dodałem, filmy z uptobox można oglądać już na kodi
