### ISSUE TITLE
Watched Status no longer working 

### ISSUE THREAD

**Issue by muzicman** [mrknow/filmkodi#340]
Recent movies that I've watched are not marked as "watched" in Specto.   I'm also unable to manually marked them as watched via the context menu. Older movies that I've watched over a month ago are marked as watched. However I cannot mark them as "unwatched".  Something is definitely broken.
On Trakt.tv, all these movies are showing up correctly as watched. Watched status is also working fine in other add-ons.

**Comment by muzicman** [comment]
Fixed it.  I backed up my settings.xml file, uninstalled Specto, deleted the plugin.video.specto folder in userdata folder, reinstalled Specto and now the Watched status works fine.

**Comment by mrknow** [comment]
Thanks, added this answer to faq http://filmkodi.com/en/kodi-specto-faq/
