### ISSUE TITLE
No search results from Furk or Real-Debrid

### ISSUE THREAD

**Issue by muzicman** [mrknow/filmkodi#341]
I no longer get any search results from Furk or Real-Debrid in Specto even though I have entered the account information correctly and authorized Kodi. I've verified that Furk and Real-Debrid work 100% in other add-ons.

**Comment by muzicman** [comment]
Partially fixed it. I backed up my settings.xml file, uninstalled Specto, deleted the plugin.video.specto folder in userdata folder, reinstalled Specto and now Real-Debrid results show up fine.  But I still get no results at all with Furk.  I also reentered the Furk account info.

**Comment by mrknow** [comment]
old issue
