### ISSUE TITLE
videostar.pl - nie wczytuje listy kanałów

### ISSUE THREAD

**Issue by odziom91** [mrknow/filmkodi#342]
Cześć!
Zgłaszam problem z videostar.pl. Pomimo wpisania prawidłowych danych do logowania, wtyczka MrKnowTV nie ładuje listy stacji telewizyjnych.

**Comment by mrknow** [comment]
dzięki, jaki masz system? Linux/Mac/Win/Android ?

**Comment by mrknow** [comment]
OK #334 - tutaj będę to rozwiązywał. Wklej logi z kodi - może chodzi o blokady regionalne
