### ISSUE TITLE
Yoy.tv

### ISSUE THREAD

**Issue by dman25** [mrknow/filmkodi#345]
Hello,

I apologize as I speak very little Polish, but I am setting Kodi up on an Amazon Fire TV for my grandmother whose first language is Polish. I am trying to use yoy.tv with the addon and it prompted me for a premium account. I paid the money for the premium account and it works fine in a web browser, but even with the login credentials in Kodi for yoy.tv, for whatever reason it is not recognizing that the account is premium. If you could please look into this, that would be great.

**Comment by dman25** [comment]
Also of note, this issue occurs on my PC as well in Kodi

**Comment by mrknow** [comment]
- please check your Premium status https://snag.gy/m4dpDw.jpg
- check your login and password in settings, 
- clean Cookies folder in add-on userdata http://kodi.wiki/view/userdata (path in my PC is .kodi/userdata/addon_data/plugin.video.mrknowtv/Cookie 

Update addon to new version 2016.06.02.4.

**Comment by dman25** [comment]
Thank you so much! Dziekuje! Appears to be working on my PC. Will try the Amazon Fire TV later.
