### ISSUE TITLE
oficjalne streamy

### ISSUE THREAD

**Issue by elizord** [mrknow/filmkodi#346]
Czy istnieje jakaś szansa na dodanie obsługi vectraonline?
Ewentualnie Horizon.pl, nc+go, a dla filmów i seriali hbo go?

**Comment by xxcriticxx** [comment]
do vectry plugin masz tutaj https://github.com/rafakob/plugin.video.vectra.tvonline

**Comment by mrknow** [comment]
Na razie nie mam w planach. 
Jeżeli będzie dla danego serwisu 10 chętnych to zacznie się produkcja danego dodatku.

**Comment by mrknow** [comment]
nie będę realizował na razie
