### ISSUE TITLE
na kiedy mozna oczekiwac polskiej wersji Specto?

### ISSUE THREAD

**Issue by xxcriticxx** [mrknow/filmkodi#348]

**Comment by mrknow** [comment]
Od 1 lipca  rozpocznie się produkcja. Zakładam że  wersje działające pojawią się około 15 lipca.

**Comment by mrknow** [comment]
Próbowałem, ale to za dużo. Nie będzie polskiej wersji specto. Wycofuje się z tego projektu ze względu na brak czasu. Fan Film zostanie skasowane
