### ISSUE TITLE
Specto not working

### ISSUE THREAD

**Issue by juju0525** [mrknow/filmkodi#349]
Just loads a screen with pigeons on it.

**Comment by xxcriticxx** [comment]
screenshot please

**Comment by KBug** [comment]
I saw this issue and having the same issue. Here's a screenshot of what you get.


![image2](https://cloud.githubusercontent.com/assets/7025650/15827570/a48d932a-2bd9-11e6-8211-8744f0b38c18.JPG)

**Comment by KBug** [comment]
Openload is now working for me with the new update just pushed out.

**Comment by juju0525** [comment]
The same thing

**Comment by xxcriticxx** [comment]
not specto problem 

what movie? what website? did you try?

**Comment by xxcriticxx** [comment]
@arkmilcz jaki film? jaka strona nie dziala?

**Comment by KBug** [comment]
It was a Specto problem with openload links. The newest update for it today fixes that problem.

**Comment by xxcriticxx** [comment]
ok time to update

**Comment by xxcriticxx** [comment]
Specto v2016.06.06.1
------------------------
- oneclickwatch - disabled
- openload - fixed (maybe?)

**Comment by danita1** [comment]
I very much appreciate this brilliant addon and the hard work, freely given, involved in its maintenance!
Sadly, I can confirm that open load sources, of which there are many, are currently not working.
The entertaining pigeons are back!

**Comment by DEViANCE75** [comment]
I am running 2016.06.06.1 openload still buggered lol

**Comment by mrknow** [comment]
Openload sometimes limited viewing video . Wait 15 minutes and the video from  openload should play normally.
