### ISSUE TITLE
plugin for filmydokumentalne.eu

### ISSUE THREAD

**Issue by xxcriticxx** [mrknow/filmkodi#35]
da sie zrobic plugin do tego serwisu?

**Comment by mrknow** [comment]
Da sie zrobić. Popracuję nad tym w weekend - bo ten serwis też mi się podoba

**Comment by mrknow** [comment]
Witam 
Dodałem stronę  do mojej wtyczki. Za kilka godzin puszczę nową wersję i będzie dostępny ...
