### ISSUE TITLE
Filmyonline-mrknow nie działaja na smart TV

### ISSUE THREAD

**Issue by Cffaniak** [mrknow/filmkodi#350]
Witam,

Podczas próby uruchomienia wtyczki Filmyonline  - mrknow wyskakuje bląd
Jestem zielony w tym temacie nie nie mam pojęcia co powinienem zrobić.
Inne wtyczki jak spectro, działaja
Telewizor philips na adroidzie 5,1

**Comment by seba741** [comment]
Po aktualizacji wtyczki do ver. 2016.06.06.1 nie działa (filmyonline) inne wtyczki ok (system openelec,kodi 15,2)

**Comment by xxcriticxx** [comment]
jaki tv? jaka ver adnroid?

**Comment by seba741** [comment]
blockquote {padding-left: 1ex; margin: 0px 0px 0px 0.8ex; border-left: #cccccc 1px solid;} p {margin: 0px;padding: 0px;} 
Nie pamiêtam dok³adnie wersji wtyczek po numerach ale wtyczka w wersji 2016.06.03.8 dzia³a³a poprawnie , natomiast po aktualizacji do wersji 2016.06.06.1 wogole nie odpala juto do³acze loga zainstalowane to jest na dwóch kompach asus sytem openelec 6.0.3 , kodi 15,2 i openelec beta 6.9.5 kodi 16,1 telewizory to panasonic i sony
Dnia Poniedzia³ek, 6 Czerwca 2016 23:54 xxcriticxx <notifications@github.com> napisa³(a)

jaki tv? jaka ver adnroid?

**Comment by xxcriticxx** [comment]
dokladnie podaj log i zobaczymy ja mam openelec na apple tv1 i 2016.06.06.1 no problem

**Comment by Cffaniak** [comment]
Gdzie można znaleźć log na smart TV?
TV Philips 55pus7101/12 Android 5.1

**Comment by xxcriticxx** [comment]
@Cffaniak dobre pytanie

**Comment by xxcriticxx** [comment]
@Cffaniak zobacz czy masz

<data/sdcard/Android>/data/org.xbmc.kodi/cache/temp/kodi.log

albo

/sdcard/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log

**Comment by enderek** [comment]
Mi na openelec po aktualizacji do  mrknow ver.2016.06.06.1 przetsało działać. W logu były błedy związane z URLResolver. W systemie nie było wtyczki urlresolver - doinstalowanie rozwiązało problem.
Może problem w zależnościach?

**Comment by OenSan** [comment]
Openelec Kodi 15.2 Jarvis wtyczka mrknow ver.2016.06.06.1 przestała działać. Wcześniej problem był z serialami openload i innymi strumieniami. Działy jedynie cda.pl .

[01_KODI.txt](https://github.com/mrknow/filmkodi/files/302555/01_KODI.txt)

**Comment by mareka61** [comment]
Witam, na moim lapku HP Win10 Pro (Kodi Jarvis 16.1) 
wtyczka Filmy online - Mrknow wczoraj zaraz po aktualizacji do najnowszej wersji ver.2016.06.06.1 przestała działać 
Dziś intuicyjnie doinstalowałem coś czego nie widziałem wczesniej :)  (dokładnie tak jak opisał to  *enderek*) Wyskoczył komunikat, czy chcę coś tam wyczyscić zwiazanego z URL... i nie dało się bo nie było wtyczki URL Resolver... doinstalowałem i już od kilkunastu minut wtyczka działa jak dawniej :)

**Comment by xxcriticxx** [comment]
@enderek podaj link

**Comment by xxcriticxx** [comment]
https://github.com/Eldorados/script.module.urlresolver/archive/2.8.0.zip

**Comment by Cffaniak** [comment]
log file nigdzie nie ma, foldery są puste.
Po aktualiacji do 2016.06.06.2 zaczęło działać.

Dziękuję za pomoc

**Comment by Moreras** [comment]
Tv Box M8 KitKat, Android 4.4.2, Kodi 14.1. Wtyczka Mrknow 2016.06.06.2 po wybraniu jakiegokolwiek kanału wyświetla się komunikat "No stream available". Tvaeriesonline.pl po wybraniu ostatnio dodane odcinki wyświetla się błąd "Nieudane wykonanie skryptu!: Filmy Online- mrknow.pl

**Comment by mar2016** [comment]
Sony Smart KD 85005c Android 5.1 Kodi 16.1 wszystkie wtyczki dzialaja

**Comment by mrknow** [comment]
nie mam takiego sprzętu - nie umiem odtworzyć problemu
