### ISSUE TITLE
mrknow openload

### ISSUE THREAD

**Issue by arkmilcz** [mrknow/filmkodi#351]
nie działa mrknow openload, pokazuje tylko jakieś gołębie

**Comment by xxcriticxx** [comment]
duplicate same as https://github.com/mrknow/filmkodi/issues/349

**Comment by arkmilcz** [comment]
some solution

**Comment by xxcriticxx** [comment]
kontynuujemy pod https://github.com/mrknow/filmkodi/issues/349

**Comment by danita1** [comment]
I very much appreciate this brilliant addon and the hard work, freely given, involved in its maintenance!       Sadly I can confirm that open load links, of which there are many, do not currently work.
 The entertaining pigeons are back!

**Comment by mrknow** [comment]
Thanks for reporting . I'm working on it. If I can solve this problem today will release an update

**Comment by mystico29** [comment]
url resolver broke the openload fix

**Comment by danita1** [comment]
mrknow, thank you for your vigilance, swift attention and response - especially since it is the weekend!
Live long and prosper!

**Comment by mrknow** [comment]
I could not figure out how to fix openload . I'll be working on that next weekend

**Comment by danita1** [comment]
All efforts greatly appreciated!

**Comment by xxcriticxx** [comment]
mortael hyba naprawil Openload

**Comment by xxcriticxx** [comment]
temporary openload solution:

with notepad++ and replace
Code:
r"<video(?:.|\s)*?<script\s[^>]*?>((?:.|\s)*?)</script"
with
Code:
r"<video(?:.|\s)*?<script\s[^>]*?>.+?<\/script>\s<script\s[^>]*?>((?:.|\s)*?)<\/"

**Comment by mrknow** [comment]
Nowa wersja resolvera powinna rozwiązać ten problem. Zaktualizuj wtyczkę Mrknow URLResolver do wersji 2016.07.30.2

**Comment by danita1** [comment]
Thank you!😊
