### ISSUE TITLE
Specto update unavailable

### ISSUE THREAD

**Issue by rcordero87** [mrknow/filmkodi#352]
Hi I am new to this so forgive me if I'm in the wrong place for this.

I don't see the specto update 6.6.1 on my phone, just 6.1.3. I did the update on my mac but  I don't see it at all on my phone. Please help.

**Comment by xxcriticxx** [comment]
http://kodi.filmkodi.com/plugin.video.specto/plugin.video.specto-2016.06.06.1.zip

**Comment by rcordero87** [comment]
Thank you!
