### ISSUE TITLE
Bug with using Trakt custom user list

### ISSUE THREAD

**Issue by shareall123** [mrknow/filmkodi#353]
Hello, anyone aware the problem to use custom Trakt user lists with Specto (although it worked well in the past and still working with Exodus and SALTS). I want to use this custom list it as a personal TV shows library and play it with Specto without luck. Any suggestions?

**Comment by bmurr327** [comment]
I'm having the same problem. The Trakt Movie Collection seems to be working with Specto, but not the TV Show Collection.

**Comment by mrknow** [comment]
Try it now.
