### ISSUE TITLE
xbmcfilm.com openload

### ISSUE THREAD

**Issue by Seico** [mrknow/filmkodi#356]
Nie działa stream z openload.co na xbmcfilm.com

**Comment by mrknow** [comment]
Poprawiłem. Na razie wydaje mi się że streamy z openload maja jakieś ograniczenie. Jezeli otdwarzamy 1 na 15 minut to jest ok, natomiast jak odpalimy 5 razy stream w przeciągu paru minut to pokazują sie gołębie. Jeszcze to rozkminiam

**Comment by Seico** [comment]
Po poprawce nic nie dało, streamy nadal nie działają,wyskakuje błąd

**Comment by mrknow** [comment]
Sprawdź prosze wersję 1.2.4. 
Faktycznie był problem. Kopiując pliki nie zmieniłem nazwy wtyczki
