### ISSUE TITLE
pierwsza.tv Brak kanałów 

### ISSUE THREAD

**Issue by eko5** [mrknow/filmkodi#357]
Nie wiem czym to jest spowodowane lecz nie wszystkie kanały są wczytywane w wersji premium . Mam tu na myśli kanały na Euro które są generowane tuż przed audycją .

**Comment by mczerski** [comment]
mi się wydaje że to jest kwestia tego że wtyczka nie pobiera aktualnej listy kanałów za każdym razem. lista jest trzymana w cache'u. po skasowaniu pliku cache tej wtyczki i ponownym uruchomieniu jej kanały się zaczytują ponownie i jest to aktualna lista kanałów.

**Comment by mrknow** [comment]
OK może macie rację - wyłaczam cache i zaraz wypuszczam aktualizację.
