### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by ariesd76** [mrknow/filmkodi#358]
Have tried to install several times and keep ketting the same error. Is there any known issue? TIA!

**Comment by xxcriticxx** [comment]
what plugin? what os? what ver of kodi? provide more info plz

**Comment by ariesd76** [comment]
I'm so sorry. Pretty noob of me. I'm trying to install: Specto-...Fork version 2016.05.8.7, Android 4.4.2 , Kodi 16.1

**Comment by bjgood** [comment]
That's an old version of Specto. Might want to grab the latest version (2016.06.06.1)...

http://kodi.filmkodi.com/plugin.video.specto/plugin.video.specto-2016.06.06.1.zip

Later...

**Comment by ariesd76** [comment]
Thanks for the link to the zip file. That worked perfectly!

**Comment by xxcriticxx** [comment]
you welcome

**Comment by kostaboxon** [comment]
@ariesd76 
You must install The Repository to get the Updates.
There is an Update that came down today 2016.06.18.1
Be patient it is a bit slow coming down.

**Comment by mrknow** [comment]
Howto http://filmkodi.com/en/specto-1080p-kodi-add/
