### ISSUE TITLE
xbmcfilm  error

### ISSUE THREAD

**Issue by thecord** [mrknow/filmkodi#359]
Hi there,
hopefully you can help me with my issue. I have kodi 16 on both windows and Android TV, I installed XBMCFILM om them but I have the flowing error :
`09:04:22 T:166016   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
09:04:22 T:164044   ERROR: EXCEPTION: Unknown addon id 'plugin.video.mrknow'.
09:04:22 T:164044   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: Unknown addon id 'plugin.video.mrknow'.
                                            Traceback (most recent call last):
                                              File "C:\Users\wahbah42\AppData\Roaming\Kodi\addons\plugin.video.xbmcfilm\default.py", line 21, in <module>
                                                import mrknow_pLog, settings, mrknow_Parser, xbmcfilmapi, mrknow_urlparser, mrknow_Player, mrknow_pCommon
                                              File "C:\Users\wahbah42\AppData\Roaming\Kodi\addons\plugin.video.xbmcfilm\resources\lib\mrknow_urlparser.py", line 19, in <module>
                                                ptv = xbmcaddon.Addon(scriptID)
                                            RuntimeError: Unknown addon id 'plugin.video.mrknow'.
                                            -->End of Python script error report<--
09:04:22 T:166016   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.xbmcfilm/
09:04:22 T:166016   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.xbmcfilm/) failed
`

thanks in advance...

**Comment by mrknow** [comment]
Fixed in version 1.2.4
