### ISSUE TITLE
SCREEN-TV

### ISSUE THREAD

**Issue by xxcriticxx** [mrknow/filmkodi#36]
trzeba poprawic service plugin laczy sie z .pl nowy domain konczy sie z .eu

**Comment by gumball1** [comment]
Jest dobrze. W module masz adres http://www.screen-tv.eu/

**Comment by mrknow** [comment]
Wprowadziłem poprawkę w nazwie wyświetlanej. Zmiana będzie widoczna podczas następnej aktualizacji
