### ISSUE TITLE
cda nie działa

### ISSUE THREAD

**Issue by drrak** [mrknow/filmkodi#360]
Od wczoraj cda.pl nie odtwarza filmów. "Nie znaleziono streamingu. Może to chwilowa awaria... bleble"

Na wszelki wypadek podaje wersje wtyczki: 2016.06.15.1

OpenELEC 6.0.3, RPi2

**Comment by mrknow** [comment]
Sprawdzę, może coś pozmieniali na cda.

**Comment by kostaboxon** [comment]
My current Version is 2016.06.1
I am getting Update failed notification.
Tried Manual Update. Showing Update to 2016.06.18.1
Tried that. Update Failed.
OpenElec 16.1 Jarvis

**Comment by drrak** [comment]
Po aktualizacji do 2016.06.18.1 działa.

Wielkie dzięki.

**Comment by mrknow** [comment]
poprawiłem w obu wtyczkach
