### ISSUE TITLE
Unuseable

### ISSUE THREAD

**Issue by davidg2016** [mrknow/filmkodi#362]
Whenever i try to install spectro on an Android TV running Android 4.4.2 with a ARM Cortex-A9 with 4 cores clocked at 1.99GHz and a Mali-450MP and a copy of Kodi 16.1 Jarvis I just get an error saying Error Installing From Zip File .When you fix this error please can you email me the new version when you release it . Email it to me at dg3973145@gmail.com . 

Thanks, 
David Griffin

**Comment by borys76** [comment]
Try other versions 
http://kodi.filmkodi.com/plugin.video.specto/

**Comment by xxcriticxx** [comment]
whats up borys76!
