### ISSUE TITLE
Specto will not install from zip

### ISSUE THREAD

**Issue by donr1961** [mrknow/filmkodi#363]
I am running kodi 16.1 . When I add the source then I go to add from zip I get an installation error? 

Is there a server problem or is there a fix coming?

**Comment by xxcriticxx** [comment]
what os? what box/computer? what ver of kodi? log? please provide more info

**Comment by donr1961** [comment]
I'm using android box , kodi 16.1. It's just started. I have never had a problem installing before

**Comment by xxcriticxx** [comment]
i have minix x8 plugin installed with no problem you have latest ver?

**Comment by donr1961** [comment]
I can install if I download the file it self but not the repository by using http://filmkodi.com/repository

**Comment by xxcriticxx** [comment]
http://kodi.filmkodi.com/repository.filmkodi.com/repository.filmkodi.com-2.1.0.zip

http://kodi.filmkodi.com/plugin.video.specto/plugin.video.specto-2016.06.18.1.zip

**Comment by donr1961** [comment]
ok, I will give this a go when I get home and see how that works. Thanks and I will post if it works.

**Comment by xxcriticxx** [comment]
good luck

**Comment by donr1961** [comment]
That worked, thank you very much.
