### ISSUE TITLE
Problem z wtyczką yoy.tv

### ISSUE THREAD

**Issue by ares85** [mrknow/filmkodi#364]
W wtyczce yoy.tv nie działają strony z filmami dla dorosłych, przez przeglądarkę wszystko jest OK

**Comment by mrknow** [comment]
nie mam tam konta premium, zwrócę się do nich aby mi przyznali takie konto.

**Comment by lukart23** [comment]
Mi wyskakuje komunikat, że nie mam konta premium. I brak reakcji. 
Po dłuższym przytrzymaniu i wykonaniu polecenia Otwórz z tego miejsca, zamyka całe kodi. 
Mimo iż dane są dobrze wpisane i konto aktywne.

**Comment by mrknow** [comment]
nie dali mi konta premium. Reszta kanałów powinna działać
