### ISSUE TITLE
Alltube.tv Seriale - Alfabetycznie - Błąd wtyczki...

### ISSUE THREAD

**Issue by drrak** [mrknow/filmkodi#369]
Jak w temacie.

OpenELEC 6.0.3, RPi2, Filmy Online - mrknow.pl wersja 2016.6.18.1

---

Już działa.

**Comment by drrak** [comment]
Znów nie działa. Wpadłem na stronę alltube.tv i co prawda filmu nie odpaliłem (za dużo syfiastych reklam), ale listę z odcinkami zobaczyłem. To błąd wtyczki czy alltube.tv?

**Comment by mrknow** [comment]
coś zmieniali na stronie. Pewnie dlatego był taki efekt. Poprawione w nowej wersji #373
