### ISSUE TITLE
Błąd dodatku Filmy Online -mrknow.pl - potrzebna pomoc

### ISSUE THREAD

**Issue by michalek600** [mrknow/filmkodi#37]
Witam,

mam problem z włączeniem wtyczki mrknow. W prawym dolnym rogu Kodi wyskakuje komunikat "Błąd dodatku Filmy Online - mrknow.pl" . Usuwałem i instalowałem ponownie zarówno kodi jaki i sam dodatek z różnych kopii.

Czy ktoś może pomóc? Dzięki

**Comment by xxcriticxx** [comment]
jaki system jaki os?

**Comment by michalek600** [comment]
Mam Win7 64bit. 

Na innym kompie z win7 32bit działa , na win10 również .

**Comment by xxcriticxx** [comment]
kiedys dziala natym systemie?

podaj log. https://github.com/mrknow/filmkodi/wiki/Jak-przes%C5%82a%C4%87-logi-z-kodi

**Comment by michalek600** [comment]
Nie. Nigdy wcześniej nie działało na tym komputerze i systemie.

Niestety nie umiem wysłać tego loga. Robię tak jak w instrukcji. mail podałem. Później nie da się już wejść do tej wtyczki. Klikam w Programach na Kodi Log Uploader i nic się nie otwiera.

**Comment by xxcriticxx** [comment]
poszukam jakis inny sposob na log

masz moze polskie znaki w nazwie użytkownika?

**Comment by michalek600** [comment]
Ok dzięki.

Nie mam polskich znaków.

**Comment by xxcriticxx** [comment]
log nam pokaze co za blad. 

jakies inne plugin wogule dzialaja?

**Comment by xxcriticxx** [comment]
http://kodi.wiki/view/Log_file/Easy

**Comment by michalek600** [comment]
wycinek z loga o błędzie:
21:19:58 T:2104    INFO: initializing python engine.
21:19:58 T:2104   DEBUG: CPythonInvoker(2, C:\Users\Michał\AppData\Roaming\Kodi\addons\plugin.video.mrknow\default.py): start processing
21:19:58 T:2104  NOTICE: -->Python Interpreter Initialized<--
21:19:58 T:2104   DEBUG: CPythonInvoker(2, C:\Users\Michał\AppData\Roaming\Kodi\addons\plugin.video.mrknow\default.py): the source file to load is "C:\Users\Michał\AppData\Roaming\Kodi\addons\plugin.video.mrknow\default.py"
21:19:58 T:2104   DEBUG: CPythonInvoker(2, C:\Users\Michał\AppData\Roaming\Kodi\addons\plugin.video.mrknow\default.py): setting the Python path to C:\Users\Michał\AppData\Roaming\Kodi\addons\plugin.video.mrknow;C:\Users\Michał\AppData\Roaming\Kodi\addons\script.module.beautifulsoup\lib;C:\Users\Michał\AppData\Roaming\Kodi\addons\script.module.requests\lib;C:\Users\Michał\AppData\Roaming\Kodi\addons\script.module.simplejson\lib;C:\Users\Michał\AppData\Roaming\Kodi\addons\script.module.xbmcfilm\lib;C:\Program Files (x86)\Kodi\system\python\DLLs;C:\Program Files (x86)\Kodi\system\python\Lib;C:\Program Files (x86)\Kodi\python27.zip;C:\Program Files (x86)\Kodi\system\python\lib\plat-win;C:\Program Files (x86)\Kodi\system\python\lib\lib-tk;C:\Program Files (x86)\Kodi;C:\Program Files (x86)\Kodi\system\python;C:\Program Files (x86)\Kodi\system\python\lib\site-packages
21:19:58 T:2104   DEBUG: CPythonInvoker(2, C:\Users\Michał\AppData\Roaming\Kodi\addons\plugin.video.mrknow\default.py): entering source directory C:\Users\Michał\AppData\Roaming\Kodi\addons\plugin.video.mrknow
21:19:58 T:2104   DEBUG: CPythonInvoker(2, C:\Users\Michał\AppData\Roaming\Kodi\addons\plugin.video.mrknow\default.py): instantiating addon using automatically obtained id of "plugin.video.mrknow" dependent on version 2.1.0 of the xbmc.python api
21:19:58 T:1444   DEBUG: ------ Window Init (DialogBusy.xml) ------
21:20:00 T:2104  NOTICE: ('pluginDataDir', u'C:\\Users\\Micha\u0142\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.module.xbmcfilm\\')
21:20:00 T:2104   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named wykop
                                            Traceback (most recent call last):
                                              File "C:\Users\Micha�\AppData\Roaming\Kodi\addons\plugin.video.mrknow\default.py", line 114, in <module>
                                                import wykop, joemonster, milanos,filmbox,vodpl, filmydokumentalne, zalukaj, efilmyseriale
                                            ImportError: No module named wykop
                                            -->End of Python script error report<--

**Comment by xxcriticxx** [comment]
pytalem czy masz polskie znaki w nazwie użytkownika widze C:\Users\Michał\

cos nie tak z pythonem moze mrknow sie pokaze to cos poradzi modrego

**Comment by michalek600** [comment]
O kurcze faktycznie.  Na innych kompach na ktorych instalowalem i dzialalo nie bylo polskich znakow i to moze byc powod. 
Probowalem kopiowac folder modules z innego komputera oraz plik default.py. nic to nie dalo. Ponadto, zmienialem parser.py na parser.py.bak.  dalej nie dziala. 

Pokombinuje z nazwa uzytkownika windowsa.

**Comment by michalek600** [comment]
Powodem są polskie znaki w nazwie konta w Windowsie. Na nowym koncie mrknow działa. Pozostaje zmienic nazwe folderu poprzez zabawe w rejestrze albo format albo migracja na nowe konto. 



Dzięki za zainteresowanie 


Temat raczej do zamknięcia.

**Comment by mrknow** [comment]
Dzieki za info. Dodałem do FAQ i zamykam
