### ISSUE TITLE
xbmcfilm.com cda.pl

### ISSUE THREAD

**Issue by Seico** [mrknow/filmkodi#372]
Nie działa stream z cda.pl na xbmcfilm.com

**Comment by mrknow** [comment]
sprawdzam ...

**Comment by mrknow** [comment]
Pewnie poprawiłem przypadkiem, zweryfikuj w wersji 1.2.1

**Comment by mrknow** [comment]
OK wersja 1.2.4 powinna definitywnie rozwiązać problem
