### ISSUE TITLE
Filmy online - mrknow.pl  Alltube.tv

### ISSUE THREAD

**Issue by Seico** [mrknow/filmkodi#373]
Po zmianie wyglądu strony Alltube.tv wtyczka przestała działać

**Comment by hekelezeme** [comment]
Potwierdzam padło w nocy

**Comment by mrknow** [comment]
Pracuje nad tym...

**Comment by mrknow** [comment]
ok prawie wszystko porawione, pozostało szukanie filmów

**Comment by drrak** [comment]
Po ostatniej aktualizacji i próbie odpalenia alltube.tv z ulubionych (dokładniej serie Dragon Ball Z), całe Kodi zawiesza się i nie może niczego wczytać. Nie ma informacji o błędzie, po prostu lista próbuje wczytać się, ale nie może. Po takiej akcji nawet YouTube nie działa. Pomaga reset i omijanie alltube.tv z daleka.

OpenELEC 6.0.3, RPi2, 2016.6.25.1

**Comment by Seico** [comment]
Po aktualizacji wtyczki nie działa stream z cda.pl

**Comment by mrknow** [comment]
Sprawdzam ...

**Comment by hekelezeme** [comment]
Awaria wtyczki alltube ?

**Comment by musi1313** [comment]
Witam, dlaczego filmy z tego repozytorium w ogole nie dzialaja? Nic nie dziala z wtyczki mrknow...pozdr

**Comment by hekelezeme** [comment]
Seriale działają, filmy oraz wyszukiwarka nie

**Comment by mrknow** [comment]
Sprawdź teraz wersję 2016.07.30.3

**Comment by musi1313** [comment]
Dziala wszystko :) dzieki

Tomek


Sent from iPhone

Dnia 31.07.2016 o godz. 13:04 MrKnow <notifications@github.com> napisał(a):
