### ISSUE TITLE
Wizja.tv

### ISSUE THREAD

**Issue by borys76** [mrknow/filmkodi#374]
Witam, cos nie dziala premium na wizja.TV mozesz sprawdzic?

**Comment by borys76** [comment]
Jak potrzebne konto premium do sprawdzenia to moge dac

**Comment by mrknow** [comment]
OK sprawdzam w czym problem

**Comment by mrknow** [comment]
Dobrze nie działa wizja. A możesz mi napisać jaki komunikat masz na stronie po zalogowaniu? Czy jest informacja (pisze z pamięci) że używasz już na innym urządzeniu ...

**Comment by borys76** [comment]
Dzisiaj juz wszystko ok, wczoraj mialem problem wyskakiwal komunikat brak premium na wtyczce, a na stronie wszystko bylo ok

**Comment by mrknow** [comment]
Dokładnie tak samo jak u mnie :). A teraz działa. ok zamykam

**Comment by borys76** [comment]
Dzieki 
Zamykam temat
