### ISSUE TITLE
New Specto Win 10 fresh install error.

### ISSUE THREAD

**Issue by Scotster** [mrknow/filmkodi#375]
Newly formatted PC with a fresh install of Win10 & Kodi from scratch. Latest version of Specto from the repository. Following Error Log....

`23:57:44 T:4580   ERROR: EXCEPTION: Unknown addon id 'script.specto.media'.
23:57:44 T:4580   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: Unknown addon id 'script.specto.media'.
                                            Traceback (most recent call last):
                                              File "C:\Users\Scotster\AppData\Roaming\Kodi\addons\plugin.video.specto\default.py", line 27, in <module>
                                                from resources.lib.libraries import control
                                              File "C:\Users\Scotster\AppData\Roaming\Kodi\addons\plugin.video.specto\resources\lib\libraries\control.py", line 54, in <module>
                                                addonInfoMedia = xbmcaddon.Addon(scriptIDMedia).getAddonInfo
                                            RuntimeError: Unknown addon id 'script.specto.media'.
                                            -->End of Python script error report<--`

**Comment by Stevemb** [comment]
I have the same problem. It was working and now it fails with a similar log, i have uninstalled and re installed.. then re installed from the file, It works then updates to 2016.6.18.4 and then it stops :(

**Comment by kostaboxon** [comment]
Version update to 2016.6.18.4 has broken the addon.
I'm running Linux Jarvis 16.1 so it is not just a windows issue.

**Comment by xxcriticxx** [comment]
same problem here on win7 kodi 16.1

**Comment by mrknow** [comment]
I'm checking it. As a workaround , install http://kodi.filmkodi.com/plugin.video.specto/plugin.video.specto-2016.06.18.3.zip

**Comment by mrknow** [comment]
Problem solved, forced installation addon script.specto.media

**Comment by rickparsons** [comment]
@mrknow I still get the same script error when running the latest version.  Do I need to reinstall the latest version?  I really don't want to have to start from scratch and lose all my favourites, etc...  Sorry, but I'm relatively new to all of this!  Thanks.

**Comment by kostaboxon** [comment]
http://filmkodi.com/en/themes-for-specto/
Do you have the repo installed ? You must have the repo to get the update and fix.
See link above.

**Comment by rickparsons** [comment]
@kostaboxon yes, I installed specto from the repo described in that link some time ago.  How do I go about getting the update and fix?  Should it be an automatic update/fix or do I have to do something manually?  thanks.

**Comment by kostaboxon** [comment]
It should have updated and fixed itself. Did you install from zip the file http://kodi.filmkodi.com/plugin.video.specto/plugin.video.specto-2016.06.18.3.zip
That should have fixed windows issues. After that installation force an update. System/Add-on/ Hit option check for updates / ok.
Otherwise uninstall the add-on and the repo. Re install repo and install add-on.
I apologise but i am running Linux Kodi 16.1 
You might want to disclose your operating system and version of kodi as well to assist you from others running the same.

**Comment by rickparsons** [comment]
@kostaboxon Sorry, I'm running Linux Kodi 16.1 as well on my set-top box.  My other Kodi is running on my Android tablet.  I just installed from the zip file and it worked.  I've turned off auto-update for now, until I know the latest update works.  Thanks!

**Comment by mrknow** [comment]
Here you have more information about this change http://filmkodi.com/en/themes-for-specto/
