### ISSUE TITLE
cda.pl - historia wyszukiwania

### ISSUE THREAD

**Issue by drrak** [mrknow/filmkodi#376]
Zastanawiam się czy mógłbyś dodać coś takiego do cda.pl. Drobiazg, ale przydałby się.

**Comment by xxcriticxx** [comment]
+1

**Comment by rysson** [comment]
Dodałem pewien moduł do obsługi wyszukiwań. Na razie użyty w cda.pl, ale we wszystkich innych serwisach można go też dodać. Przeniesienie do innych wtyczek (specto?) też nie powinno być trudne.
