### ISSUE TITLE
xbmcfilm.com cda.pl

### ISSUE THREAD

**Issue by Seico** [mrknow/filmkodi#377]
Po aktualizacji wtyczki do wersji 1,2,4 nadal nie działa stream z cda.pl na xbmcfilm.com

**Comment by mrknow** [comment]
wstępnie wydaje się że działa. Możesz podac link do nie działającego filmu ?

**Comment by Seico** [comment]
Prosze bardzo : http://www.cda.pl/video/631677ba

Wszystkie filmy przez kodi nie mają steamu , na stronie xbmcfilms.com jest ok

**Comment by borys76** [comment]
Umnie ten link "Galerianki" przez Kodi dziala, inne tez

**Comment by Seico** [comment]
Tu chodzi o działanie streamu poprzez wtyczkę xbmcfilms.com

**Comment by borys76** [comment]
Ja mowie o wtyczce xbmcfilm

**Comment by Seico** [comment]
A linki z openload.co ci działają ?

**Comment by borys76** [comment]
Ostatnio jak sprawdzalem to same golebie byly

**Comment by Seico** [comment]
gołębie sa cały czas , a jak wchodzę bezpośrednio na openload.co przez kodi
to smiga wszystko ok

2016-06-30 0:04 GMT+02:00 borys76 <notifications@github.com>:

**Comment by Seico** [comment]
Bardzo dziwna sprawa , mam w telefonie z androidem 6.0 zainstalowane kodi i tam filmy z cda.pl odtwarzają się normalnie , na boxie mam androida 4.4 i tam juz występował błąd , skopiowałem pliki kodi z telefonu do boxa i wszystko jest ok , więc myślę ze wina tkwi ściąganiu wtyczki albo w systemach, gdyż na windowsie nadal mam problem (Na telefon ściagałem tak samo jak na boxa i windowsa)

Stream z Openload.co nadal nie działa nigdzie ani we wtyczce mrknow ani we wtyczce xbmcfilms.com

Dodam że we wtyczce alakamba - alltube stream z openload.co działa

**Comment by mrknow** [comment]
poprawiłem wczoraj. Powinno juz działać prawidłowo
