### ISSUE TITLE
alltube.tv zawiesza Kodi

### ISSUE THREAD

**Issue by drrak** [mrknow/filmkodi#378]
Po ostatniej aktualizacji i próbie odpalenia alltube.tv (dokładniej serii Dragon Ball Z), Kodi zawiesza się i nie może już niczego wczytać. Nie ma informacji o błędzie, tylko niekończące się "wczytywanie".

OpenELEC 6.0.3, RPi2, Filmy Online - mrknow 2016.6.25.1

**Comment by mrknow** [comment]
Też miałem podobny efekt, ale zignorowałem to. Postaram się to sprawdzić lepiej

**Comment by mrknow** [comment]
Dzięki za wychaczenie tego błędu. SPrawdź proszę wersję 2016.06.25.2

**Comment by mrknow** [comment]
Dobra zamykam, jeżeli nowa wersja nie działa proszę o ponowne otworzenie zgłoszenia
