### ISSUE TITLE
After update to v. 2016.06.18.4

### ISSUE THREAD

**Issue by jenirose123** [mrknow/filmkodi#379]
After update in 2 of my fire boxes I get specto-fork error. On my other 2 no update and no issues. Please help! TIA

**Comment by rickparsons** [comment]
Same happened to me.  My tablet updated and then would receive the error, so, before I realized it was due to the update, I fired up my TV box.  It worked until Specto auto-updated, then it stopped working, with the same error.  Please help!

**Comment by jenirose123** [comment]
Rick Parsons... If you look down the page to the issue about new install on Windows 10 there is a zip that works

**Comment by rickparsons** [comment]
Thanks @jenirose123 but how do I install the previous version from the zip file?  Do I need to unistall specto then reinstall, or is there a simpler, less destructive process?  Thanks!

**Comment by jenirose123** [comment]
I just installed over the top of it and it's good

**Comment by mrknow** [comment]
Try install  specto repository
Here you have more information about this change http://filmkodi.com/en/themes-for-specto/

**Comment by ACCGoddess** [comment]
I tried to be install this themes for specto and it keeps failing. My system tells me there is an update for specto fork but that fails when I try to install it.  Help!  Specto won't work at all.  I am using kodi 16

**Comment by kinzer73** [comment]
after updating on my android box none of the categories in the movies section load.  I have tried installing an older version but the links have no stream error.  and the year category onlt goes upto 1970
