### ISSUE TITLE
Telewizjada nie działa

### ISSUE THREAD

**Issue by mrknow** [mrknow/filmkodi#38]
Po aktualizacji nie działa 
  ERROR: Open - failed to open source <http://l142.telewizjada.net:1935/tw/2014tvhbo2hd/playlist.m3u8?N2H2Isfud0v3WbonRqQk4SqSEdHMMOhtbLlqnvBzgxAHSPVlfG0HvM3Fv5svz3VYLdCIgR6coNJJqO1JfppQV82rxrTX6I6Z1y%2FRu25njkGEYOYXmxH8Q53XBDMxgqv6ATuQrg6zeZbftd8eIKijxxyqClMzTerzirJ2YPH1V7EaHq%2FGV8qa5QwNC%2FuUXLW69qrBTYhtm6qH7g%3D%3D|Cookie=msec=F2joLNryJwa0FP80BZYhtnmZEMvcGsh7M6d9iqRT43UBTegxS3UVv5r6vtYUymAOdIrM2wPHs486g9spV9gRWcilx6n144yQ1GOV3j4tzx3UefwQhhX8Q53f;sessid=mfdgqp1bvcu3kel97dvi0dt6i0;statid=7g0h2n30ab02pj2brse0pum3s1&User-Agent=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36>

**Comment by xxcriticxx** [comment]
poprawka bendzie?

**Comment by mrknow** [comment]
Naprawiłem nowa wersja powinna działać poprawnie
