### ISSUE TITLE
Instalacja z repo filmkodi nieudana

### ISSUE THREAD

**Issue by shaggee** [mrknow/filmkodi#383]
Od kilku dni, wtyczka mrknow nie może się zaktualizować. Pobiera się update a następnie pojawia się instalacja nieudana. Próbowałem odinstalować i zainstalować na nowo. Bez efektu. Próbowałem z pliku zip też nic nie działa. Obecnie nie mogę zainstalować żadnej wtyczki. Specto tak samo. Nic nie było grzebane, zawsze aktualizowało się samo.
Jakaś podpowiedź?

**Comment by mrknow** [comment]
Sprawdź teraz jeszcze raz 
W razie co tu masz instrukcję instalacji http://filmkodi.com/pl/wtyczka-filmy-online-mrknow/ 

Jeżeli serwery są przeciążone (nowa wersja) to czasami jest problem z aktualizacją, ale po max 2 godzinach powinno działać
