### ISSUE TITLE
zamiast "ó" - "&oacute;"

### ISSUE THREAD

**Issue by drrak** [mrknow/filmkodi#387]
W znalezionych tytułach z cda.pl, zamiast litery `ó`, wyświetla się `&oacute;`. Byłem przekonany, że to błąd Kodi, ale **Exodus** tytuł _"Żółwie Ninja"_ wyświetla poprawnie.

OpenELEC 6.0.3, RPi2, Filmy Online - mrknow.pl 2016.07.02.2

---

PS. Dzięki za naprawę alltube.tv.

**Comment by rysson** [comment]
+1

W logach jest np.
`11:08:02 T:139665961121536 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.mrknow/?service=cdapl&name=playSelectedMovie&category=None&title=[[COLOR yellow]1080p[/COLOR]] - [COLOR yellow]PREMIUM[/COLOR] Zaw&oacute;d gangster (2007) Lektor PL&url=None&icon=http%3A%2F%2Fimg3.cda.pl%2F72d91d436689c225ff6e1ea042aa5672%2Fff9f72a2bd5d19beae3320dd0462ff22.jpg&strona=`


Może puścić tytuł jeszcze raz przez html.unescape a raczej odpowiednika w Python2 (np. HTMLParser?)

**Comment by rysson** [comment]
Na górze pliku (linia 8) dadać `plugin.video.mrknow/host/cdapl.py`
```python
import HTMLParser
```

A następnie gdzieś około linii 200, początek metody cdapl.add() dodać:
```python
title = HTMLParser.HTMLParser().unescape(title)
```

Patch za chwilę, bo ten plik zmieniałem.

**Comment by rysson** [comment]
Patch:

```diff
diff --git a/plugin.video.mrknow/host/cdapl.py b/plugin.video.mrknow/host/cdapl.py
index 059766f..12af99f 100644
--- a/plugin.video.mrknow/host/cdapl.py
+++ b/plugin.video.mrknow/host/cdapl.py
@@ -5,6 +5,7 @@ from urlparse import urlparse, parse_qs
 import urlparse
 from BeautifulSoup import BeautifulSoup
 import time, datetime
+import HTMLParser
 
 scriptID = 'plugin.video.mrknow'
 scriptname = "Filmy online www.mrknow.pl - cda.pl"
@@ -211,6 +212,7 @@ class cdapl:
     
 
     def add(self, service, name, category, title, iconimage, url, desc, rating, folder = True, isPlayable = True,strona=''):
+        title = HTMLParser.HTMLParser().unescape(title or '')
         u=sys.argv[0] + "?service=" + service + "&name=" + name + "&category=" + category + "&title=" + title + "&url=" + urllib.quote_plus(url) + "&icon=" + urllib.quote_plus(iconimage)+ "&strona=" + urllib.quote_plus(strona)
         #log.info(str(u))
         if name == 'main-menu' or name == 'categories-menu':
```

**Comment by rysson** [comment]
@mrknow, dodałem pull-request dotyczący tego zgłoszenia. Zobaczymy jak to pójdzie. 3V się.
