### ISSUE TITLE
Fix for WSOnline not working

### ISSUE THREAD

**Issue by bjgood** [mrknow/filmkodi#391]
**Thought I'd start a new thread so as to get your attention**

Hi Mr. Know,
I found out why source wsonline_tv.py stopped providing any links for TV shows. At line 117, in that line, you changed SD to MQ. If you change MQ to SD wsonline_tv.py works. I discovered it quite by accident. On my Firestick I was running 2016.06.18.1 and when my son went to watch The Adventures of Puss in Boots (only available on WSOnline) it worked. I was surprised to say the least because I knew it didn't work on my raspberry pi which is running the latest version of Specto (2016.07.02.2). I compared files and found that discrepancy.

Hope this helps.

Regards,
Bob

**Comment by bjgood** [comment]
Talk about poorly worded. Sorry about that.

Let's give it another try. In source wsonline_tv.py, at line 117, if you change MQ to SD it will once again provide links for TV shows.

Later...
Bob

**Comment by mrknow** [comment]
Thx, 
Fixed version now is available in a beta directory  http://kodi.filmkodi.com/beta/plugin.video.specto/plugin.video.specto-2016.07.09.1.zip
At the moment I test It . If the tests will be OK, today we release updates

**Comment by bjgood** [comment]
Hi Mr. Know,
Your new version, 2016.07.09.1, with your addition of the urlresolver, seems to be working just fine so far. Congratulations.

Bob
