### ISSUE TITLE
specto on mac can't find file

### ISSUE THREAD

**Issue by mordrid01** [mrknow/filmkodi#395]
Downloaded my favorite flick, but could not find it anywhere.  I did not set up the location, but it said it downloaded.  Now I can not seem to find it.  I went to libraries>application support>kodi>userdata>addon_data>plugin.video.specto>movies and nothing.  there is nothing there.  could anyone please help.
thanks.

**Comment by xxcriticxx** [comment]
check here

specto > tools > specto:downloads

**Comment by mordrid01** [comment]
Yeah the original file it was set as, just said movies and tv shows. And can't find those anywhere on my computer. Wanted to transfer the file to a drive but can't locate it anywhere outside of Kodi. Becoming frustrating. Tried 3 more ransoms and can't find those anywhere either. Changed the DL directory to something specific and found those. But the ones I did prior are just on my Mac invisible apparently.

**Comment by xxcriticxx** [comment]
looks like they never saved to the drive they were probably only streaming

**Comment by mordrid01** [comment]
They saved somewhere because they are taking up space. I just can't find them.

**Comment by xxcriticxx** [comment]
search for *.avi or *.mp4 or *.mkv or *.swf

**Comment by bjgood** [comment]
Hi,
On my Raspberry Pi 2, under userdata>addon_data>plugin.video.specto, I have these folders  listed...Downloads, Movies, and TVShows. If you have it, look in the Downloads folder. In the Downloads folder are two more folders titled Movies and TVShows.

Hope this helps.

Later...

**Comment by mrknow** [comment]
fixed download section.
