### ISSUE TITLE
Stworzenie wtyczki z Openload.co

### ISSUE THREAD

**Issue by Seico** [mrknow/filmkodi#396]
Czy byłby ktoś w stanie stworzyć wtyczkę do kodi z konta na Openload.co , posiadam dosć spory zasób filmowy w wysokiej jakości (1080p/720p - audio 5.1/2.0) i jakby powstała taka wtyczka to mógłbym się tym zasobem podzielić aby wszyscy mogli oglądać

**Comment by mrknow** [comment]
Plugin xbmcfilm.com http://xbmcfilm.com/
To mogę zaproponować jako rozwiązanie
