### ISSUE TITLE
Brak pełnej listy kanałów z telewizja-live.com

### ISSUE THREAD

**Issue by noirrak** [mrknow/filmkodi#397]
Jest problem z wyświetlaniem wszystkich programów z telewizja-live.com. Działają tylko trzy kategorie, tj. filmowe, muzyczne i ogólne (która nie jest pełna). Problem występuję u mnie na wszystkich urządzeniach.
Wszystko jest przedstawione na tym gifie: 

![GIF](https://media.giphy.com/media/3o72F1rq5m4tte4aLm/giphy.gif)

**Comment by xxcriticxx** [comment]
tak jest od dluszego czasu

**Comment by noirrak** [comment]
Tak, ale nie widziałem jeszcze zgłoszenia na ten temat.

**Comment by xxcriticxx** [comment]
kazdy siedzi na platnej tv

**Comment by mrknow** [comment]
poprawione
