### ISSUE TITLE
fork of URLResolver?

### ISSUE THREAD

**Issue by tknorris** [mrknow/filmkodi#398]
You are, of course, free to do so, but any particular reason you forked URLResolver rather than using the existing one? It seems like it just makes it harder on everyone:
1) Your resolver fixes don't make it in to URLResolver benefiting other addons.
2) The fixes made to URLResolver don't benefit users of Specto.
3) Users of specto and other addons have to configure urlresolver twice.

Like I said, you can do whatever you want, the source if GPL, but it doesn't make a lot of sense to me...

**Comment by dracosc** [comment]
Hi tknorris and MrKnow. Great respect to both of you for your great job. I think the reason MrKnow is trying to use his own urlresolver is that he can use some of the existing Specto(Genesis) resolvers that work better than urlresolver version. Maybe something like Openload that breaks with pigeons every now and then, and Mrknow gets a fix faster than urlresolver! I have also found that Filepup resolver of existing Specto(Genesis) is working but urlresolver version doesn't......

**Comment by tknorris** [comment]
Re-using urlresolver wouldn't prevent still using internal resolvers. From what I can tell, he hasn't changed any of the basic function of urlresolver.

On your filepup point, that's kind of exactly the point I'm making. If he has a fix for filepup, why not give back to the whole community rather than just keeping it in Specto? If we know that a resolver is broken, then someone can fix it...

**Comment by dracosc** [comment]
I fixed movienight scraper for specto, and when i use urlresolver for filepup it dosnt work, but when i use internet resolver it works......anyway, you know better for sure!!! 😀

**Comment by dracosc** [comment]
Only resolver that i found it doesnt work in specto internal resolvers, but also doesn't in url resolver is promptfile i think....

**Comment by bjgood** [comment]
Hi tknorris and Mr Know,
I think Mr. Know "borrowed" TVA's urlresolver because it would require that tva-common repository be installed to bring urlresolver in. Over at the TVAddons forum you can't mention Specto without the name being blocked out (out of respect for Lambda I'm sure). Specto is a banned word over there. I doubt also that they would want Specto to use that repository. And they wouldn't welcome him in to make changes to urlresolver (I assume you'd have to be part of the TVA team to do that). Don't get me wrong, I love TVAddons forum. I go there all the time. It's a great source of information and has great coders (like tknorris and others).

Also, at least from what I can tell, Specto is not even using urlresolver yet. It's required to be installed by Specto but I can't see in the code where it's being called. It appears to rely solely on the resolvers in the lib folder. Correct me if I'm wrong, Mr. Know.

Best regards,
Bob

**Comment by tknorris** [comment]
We have no issue with anyone using tva-common. It can be used via a <dir> element so that the repo doesn't have to be installed. I wouldn't be asking if we had an issue w/ it.

As far as fixes go, that has nothing to do with TVA forums, Mr Know can submit PRs back to my github to submit fixes just like everyone else does.

**Comment by bjgood** [comment]
Thanks, tknorris, for the explanation. You have always been, and continue to be, one of my favorite people over at TVAddons. :).

Respectfully,
Bob

**Comment by dracosc** [comment]
True respect to tknorris! But true respect to MrKnow !!!!

**Comment by tknorris** [comment]
@mrknow Can I at least get a response regarding this from you? Your lack of even a response is disheartening to say the least.

**Comment by Thewatchfuleye** [comment]
@tknorris doubt he's ignoring you, from what I've seen he only comes around github when he's ready to push an update, you might have better luck posting a question on the topic on the filmkodi site.

**Comment by tknorris** [comment]
@mrknow wow, talk about lack of respect. I can't believe you can continuously take the code that devs at TVA write and don't even have the decency to respond when asked why you fork things for no reason. Until now I've officially kept an impartial view of Specto and you, but after this experience maybe it is the scam that other have suggested it is.

**Comment by Thewatchfuleye** [comment]
@tknorris I don't think he's actually disrespecting TVA or you, I think you should contact him at his website. Some of it is probably language barriers and lack of time. I doubt he's trying to scam TVA or anyone else, he's basically rewritten most of the addon as it is and removed the reference to its source as TVA wanted. He initially fixed the Openload problem, the URL resolver updated messed it up again, I believe it was Moratel that fixed it again and he credited for the fix. I'm sure he probably forked it to prevent the problem with what happened initially with openload, he fixed it and the URL resolver broke it. I doubt he has any ill motive. I've tried his addon in and it works very well. I don't think he's trying to disrespect anyone and you should really try and get in contact.

**Comment by tknorris** [comment]
@Thewatchfuleye Thanks for the suggestion, but I've already tried contacting him via the website and by @ attentioning him here twice. He has also posted new issues himself here since I posted this original issue. I can only conclude that has no intention of responding. I can only guess why.

As far as the openload issue goes, if he was using the original urlresolver then he could have submitted a PR to fix it instead of maintaining his own and it would have benefited everyone which was my original point. It's a selfish, rude action to fork code that is used by hundreds of addons for your addon only, which is what makes me suspicious of the whole thing.

**Comment by Thewatchfuleye** [comment]
@tknorris Ahh I didn't know you tried contacting him on his website, he really hasn't responded to much of anything on here lately and only a few there just posted some issues he's working on. I was kind of assuming he simply didn't have time to address everything given the number of issues posted here. 

I still doubt it's ill will, it might also be related to how he works on the addon, he sometimes makes several minor corrections in a day and pushes them directly to specto when he's working on them then waits to see if issues come back and fixes them on the fly. It's kind of like he's on the fly beta testing with the users. He could also be using the URL resolver fork in the same way to test potential fixes and see if the users report back.

**Comment by mrknow** [comment]
@tknorris I'll be at the weekend . I read your comments

**Comment by tknorris** [comment]
@mrknow Thanks for responding. I hope we can find a way to make urlresolver work w/ specto without requiring it be forked. The more people working on urlresolver the better for everyone.

**Comment by tknorris** [comment]
@mrknow I never got a response...

**Comment by mrknow** [comment]
Hey @tknorris  sorry for long time no writing, I was on holidays, and then I needed to manage some time to answer your question, but I will try to answer it now. First of all, thank you for your suggestions and questions, here it goes: 
“You are, of course, free to do so, but any particular reason you forked URLResolver rather than using the existing one? It seems like it just makes it harder on everyone”
It’s because I wanted to change it in my own way, and im not even a developer. I’m learning python and I was afraid if I change something, then it will stops working. So, I downloaded (yours?) URLResolver to my repo and changed lines that make it work with websites are popular in my country. I do not feel good enough to fix bugs and push it to your branch, so that’s why I did not do this.
"On your filepup point, that's kind of exactly the point I'm making. If he has a fix for filepup, why not give back to the whole community rather than just keeping it in Specto? If we know that a resolver is broken, then someone can fix it..."
Well, that’s the thing I’ve written up. Im not developer, and I do it in my free-time, besides my job. So it’s like home-made developing.  Then I’m not even into this community, but thanks for your sugestions. If there is any question I did not answer, please comment here.

@Thewatchfuleye – thanks for your comments, and it’s more like that you said - i come here only when i’m publishing new stuff.

**Comment by tknorris** [comment]
@mrknow. Thanks for responding. My strong preference would be for you to submit those resolvers to my repo as PRs. I will be happy to advise you on any issues in them before I merge them. Don't worry about breaking things, I'll take care that your changes don't break anything. The whole point of urlresolver is to be a common module that all addon devs benefit from so the more people maintaining it the better. We are all doing this in our free time.

**Comment by sonaldynho** [comment]
hi mrkonow... i m try to set your urlresolver in my addon, but have no luck can u give me the sep by step how to code it to my addon please??? here is a copy of my addon it is simple:

# -*- coding: utf-8 -*-
import xbmcgui,xbmc,xbmcplugin,xbmcaddon
import os, urllib, re
import sys, urlparse
import urllib, urllib2


HOME = xbmc.translatePath('special://home')
regex1 = os.path.join(HOME, 'regex1.txt')
filmes = 'https://goo.gl/ZGSzzm'
canais = 'https://goo.gl/5gSlkj'
url1 = 'http://www.blogger.com/video-play.mp4?contentId=50137ed65043e664'
icon1 = 'https://goo.gl/vrBXhG'
fanart = 'https://goo.gl/kHYZh8'
player= xbmc.Player()
lexdan_handle = int(sys.argv[1])

import urlresolver





def read_file(filename):
    readfile = open(filename, 'r')
    content = readfile.read()
    readfile.close()
    return content

def open_url(url):
    req = urllib2.Request(url)
    req.add_header('User-agent','Mozilla/5.0 (Windows NT 6.1; WOW64; rv:19.0) Gecko/20100101 Firefox/19.0')
    response =  urllib2.urlopen(req)
    link = response.read()
    response.close()
    return link.replace('\n', '').replace('\t','').replace('\r','')

def addDir(dir_type, mode, url, name, iconimage, fanart):
    base_url = sys.argv[0]
    base_url += "?url="            +urllib.quote_plus(url)
    #xbmc.log('################ BASE 1:%s' %base_url)
    base_url += "&mode="           +str(mode) 
    #xbmc.log('################ BASE 2:%s' %base_url)
    base_url += "&name="           +urllib.quote_plus(name)
    #xbmc.log('################ BASE 3:%s' %base_url)
    base_url += "&iconimage="      +urllib.quote_plus(iconimage)
    #xbmc.log('################ BASE 4:%s' %base_url)
    base_url += "&fanart="         +urllib.quote_plus(fanart)
    #xbmc.log('################ BASE 5:%s' %base_url)


    lista = xbmcgui.ListItem(name, iconImage=iconimage, )

    lista.setInfo(type="video", infoLabels={"Title":name})
    lista.setProperty("fanart_Image", fanart)
    lista.setProperty("IsPlayable", "true")
    lista.setProperty("IsLive", "true")

    if dir_type != '':
        link = xbmcplugin.addDirectoryItem(handle=lexdan_handle,url=base_url,listitem=lista,isFolder=True)
    else:
        link = xbmcplugin.addDirectoryItem(handle=lexdan_handle,url=url,listitem=lista,isFolder=False)

    return link

def resolve_host(url):    
    import urlresolver

    stream_url = urlresolver.resolve(url)

    if stream_url:
        xbmcplugin.setResolvedUrl(lexdan_handle, True, xbmcgui.ListItem(stream_url))
    else:
        xbmcplugin.setResolvedUrl(lexdan_handle, False, xbmcgui.ListItem())

def Menu():
    addDir('folder', 'filmes_lista','','FILMES',icon1,fanart)
   
def Filmes_lista ():
    content = open_url(filmes)
    xbmc.log('#########%s' %content)
    matchs = re.compile('name="(.+?)"path="(.+?)"thumb="(.+?)"fanart="(.+?)"').findall(content)
    for item in matchs:
        name = item[0]
        url = item[1]
        thumb = item[2]
        fanart = item[3]
        
        addDir('', '', url, name=name, iconimage=thumb, fanart=fanart)




def Canais_lista ():
    dialog = xbmcgui.Dialog()
    Addon = xbmcaddon.Addon ('plugin.video.teste')
    if Addon.getSetting("username") == '':
        dialog.ok('[COLOR blue]LISTA PREMIUM[/COLOR]','Por favor entre seu username e password para ter acesso a [COLOR blue]LISTA PREMIUM[/COLOR] press [COLOR red]ok[/COLOR] para ser redirecionado')
        xbmcaddon.Addon('plugin.video.teste').openSettings()

    content = open_url('http://almateciptv.ddns.net:8000/get.php?username='+Addon.getSetting("username")+'&password='+Addon.getSetting("password")+'&type=m3u&output=mpegts')
    x = content.replace('#EXTM3U','LISTA PREMIUM').replace('http', ' "path="http').replace('EXTINF:-1','').replace(',','name="').replace('ts','ts"')
    #xbmc.log('######%s' %x)
    a = re.compile('name="(.+?)"path="(.+?)"').findall(x)
    for name, path in a:
        addDir('', '', path, name, '', '')
    
    

mode = None
args = sys.argv[2]
#xbmc.log(str('@@@@@@@@@@@%s'%args))

if len(args) > 0:
    mode = args.split('mode=')
    #xbmc.log(str(mode))
    mode = mode[1].split('&')
    #xbmc.log(str(mode))
    mode = mode[0]

if mode == None                 : Menu()
elif mode == 'filmes_lista'     : Filmes_lista()



xbmcplugin.endOfDirectory(lexdan_handle)

**Comment by rysson** [comment]
@sonaldynho, please use MarkDown code block in your post.
Example:
````
```python
'code here'...
```
````

**Comment by sonaldynho** [comment]
ok thanks u did for me already

**Comment by tknorris** [comment]
Why would you use this one rather than the real urlresolver?

**Comment by sonaldynho** [comment]
I don't know how to install any one can u please show me I like your better because u resolve upload videos please help I m getting crazy??trying this for so long

Enviado do meu iPhone

Em 30 de nov de 2016, ?s 16:53, tknorris <notifications@github.com<mailto:notifications@github.com>> escreveu:


Why would you use this one rather than the real urlresolver?

-

**Comment by tknorris** [comment]
What you pasted above looks fine. Did you import urlresolver in addon.xml?

**Comment by sonaldynho** [comment]
on this part 
''' python
def Filmes_lista ():
    content = open_url(filmes)
    xbmc.log('#########%s' %content)
    matchs = re.compile('name="(.+?)"path="(.+?)"thumb="(.+?)"fanart="(.+?)"').findall(content)
    for item in matchs:
        name = item[0]
        url = item[1]
        thumb = item[2]
        fanart = item[3]
        
        addDir('', '', url, name=name, iconimage=thumb, fanart=fanart)
'''
if i put resolve_host it will play but it is gonna play all urls ate the same time, u know it wont create a menu...

''' python
def Filmes_lista ():
    content = open_url(filmes)
    xbmc.log('#########%s' %content)
    matchs = re.compile('name="(.+?)"path="(.+?)"thumb="(.+?)"fanart="(.+?)"').findall(content)
    for item in matchs:
        name = item[0]
        url = resolve_host(item[1])
        thumb = item[2]
        fanart = item[3]
        
        addDir('', '', url, name=name, iconimage=thumb, fanart=fanart)
'''
if i do on addDir the same thing happend

''' python 
def Filmes_lista ():
    content = open_url(filmes)
    xbmc.log('#########%s' %content)
    matchs = re.compile('name="(.+?)"path="(.+?)"thumb="(.+?)"fanart="(.+?)"').findall(content)
    for item in matchs:
        name = item[0]
        url = item[1]
        thumb = item[2]
        fanart = item[3]
        
        addDir('', '', resolve_host(url), name=name, iconimage=thumb, fanart=fanart)
'''

**Comment by tknorris** [comment]
If you are the same person from [this thread]( http://forum.kodi.tv/showthread.php?tid=298327) then lets just discus it in that thread.

**Comment by sonaldynho** [comment]
Yes I did other wise it would give me the erro no module name urlresolver

Enviado do meu iPhone

Em 30 de nov de 2016, ?s 19:24, tknorris <notifications@github.com<mailto:notifications@github.com>> escreveu:


If you are the same person from this thread<http://forum.kodi.tv/showthread.php?tid=298327> then lets just discus it in that thread.

-

**Comment by sonaldynho** [comment]
Oh my god it is u there I didn't see ? ask for help every where

Enviado do meu iPhone

Em 30 de nov de 2016, ?s 19:24, tknorris <notifications@github.com<mailto:notifications@github.com>> escreveu:


If you are the same person from this thread<http://forum.kodi.tv/showthread.php?tid=298327> then lets just discus it in that thread.

-
