### ISSUE TITLE
Brak pełnej listy serwisow

### ISSUE THREAD

**Issue by al3ff** [mrknow/filmkodi#399]
Zainstalowałem najnowsza wersje wtyczki mrknow filmy online (datowana 2016.07.2) i nie widzę wszystkich serwisów np. tych sportowych, poniżej screeny. Wcześniej miałem starsze wersję tej wtyczki, aczkolwiek kasowałem folder z addon_data.

http://zapisz.net/images/993_20160719_000257_001.jpg

edit: platforma OSMC, urządzenie: raspberry pi3

**Comment by mrknow** [comment]
Zainstaluj proszę według tej instrukcji http://filmkodi.com/pl/wtyczka-filmy-online-mrknow/
