### ISSUE TITLE
Nieudana instlacja

### ISSUE THREAD

**Issue by Esieczek** [mrknow/filmkodi#40]
Wersja 2016.01.19.2 TV philips 6400, android, wtyczka zatrzymuje się na 3% pobierania i pojawia się komunikat "MR. Know instalacja nieudana".
Do tej pory wszystkie aktualizacje instalowany się bez problemu. Dopiero 2016.01.19.2.
Jeżeli chodzi o LOG to proszę o wskazówkę gdzie go szukać. Kodi jest na ustawieniach domyślnych i nie wiem czy w ogóle coś się zapisuje.

**Comment by marco2602** [comment]
U mnie prawie to samo,tzn.na urządzeniach z androidem powyżej 4.2 i kodi 15.2 aktualizuje sie wtyczka i filmy online chodzą bez problemu.natomiast na urządzeniach z androidem 4.0.3 i kodi 14.2 wtyczka sie nie pobiera,stoi 0% i po jakimś czasie  "instalacja nie udana".wcześniej chodził a wtyczka filmy online na kodi 14.2.oczywiście nie można zainstalować 15.2 bo jak wiadomo potrzebny android od 4.2.tutaj jest problem na goclever android box 500.

**Comment by Esieczek** [comment]
Według informacji systemowych to jest tak:
Android 5.1.0 API level 22 (kernel: Linux 3.10.27)
Kodi 15.2
Jeszcze przedwczoraj wszystko chodziło. Dopiero po pojawieniu się aktualizacji wymienionej powyżej mam problem.
Innym problemem jest to, że podczas przeglądania list z filmami/serialami aplikacja wiesza się po około 3 minutach. TV odbiera sygnały z  pilota, ale nie reaguje i po chwili wychodzi do menu wyboru aplikacji.

**Comment by marco2602** [comment]
W końcu udało sie z logami,po uruchomieniu dodatek flimy online odinstalowany i próba instalacji ponownie nie udana ,czyli stoi 0% i wywala komunikat "instalacja nie udana" a myślałem ze coś się zmieni bo przyszła rano aktualizacja na telefon i mbox s82 tutaj tradycyjnie zaktulizowalo sie bez problemu,goclevery android box 500 ten sam błąd.

**Comment by marco2602** [comment]
http://xbmclogs.com/pzc5wtj9l

**Comment by Esieczek** [comment]
Wersja 2016.01.19.3 zainstalowała się poprawienie i działa. Dziękuję.

**Comment by mrknow** [comment]
Witam
Ja myślę że:
- skończyło się miejsce na dysku twardym na urządzeniach.

Napisz tutaj problem  https://github.com/mrknow/filmkodi/issues i daj mi
numer.

Czy to są urządzenia na androidzie ?  Masz dostęp poprzez ssh ?


W dniu 22 stycznia 2016 07:28 użytkownik marco2602 <notifications@github.com

**Comment by marco2602** [comment]
Napisałem kolejny temat tak jak chciałeś na githubie sa tam logi .nazwa użytkownika taka sama jak tutaj czyli: marco2602Wysłano z telefonu komórkowego Honor 4x-------- Wiadomość oryginalna --------Temat: Re: [filmkodi] Nieudana instlacja (#40)Od: mrknow Do: mrknow/filmkodi DW: marco2602 Witam
Ja myślę że:
- skończyło się miejsce na dysku twardym na urządzeniach.

Napisz tutaj problem  https://github.com/mrknow/filmkodi/issues i daj mi
numer.

Czy to są urządzenia na androidzie ?  Masz dostęp poprzez ssh ?


W dniu 22 stycznia 2016 07:28 użytkownik marco2602 <notifications@github.com

**Comment by mrknow** [comment]
Wgraj ręcznie te wtyczki do katalogu 
1. najpierw - script.module.xbmcfilm.zip
2. następnie - plugin.video.mrknow.zip
3. jako opcje jeszcze raz repozytorium repository.filmkodi.com.zip

[script.module.xbmcfilm.zip](https://github.com/mrknow/filmkodi/files/107510/script.module.xbmcfilm.zip)
[plugin.video.mrknow.zip](https://github.com/mrknow/filmkodi/files/107509/plugin.video.mrknow.zip)
[repository.filmkodi.com.zip](https://github.com/mrknow/filmkodi/files/107511/repository.filmkodi.com.zip)

**Comment by mrknow** [comment]
zmieniłem serwery. Teraz aktualizację powinny zawsze działać poprawnie
