### ISSUE TITLE
Specto error

### ISSUE THREAD

**Issue by kylemckeith** [mrknow/filmkodi#400]
I have been trying to use Specto -...Fork on the Android x8 octacore media player for the last few days but every time I click on a movie it comes up say 'Specto -...Fork error, check the log for more information' I've tried updating it but that doesn't work. What should I do?

**Comment by xxcriticxx** [comment]
provide us with logs

**Comment by kylemckeith** [comment]
Where do I find the logs?

**Comment by xxcriticxx** [comment]
http://kodi.wiki/view/Log_file/Easy

https://howtomediacenter.com/en/how-to-check-kodi-log-file/

https://seo-michael.co.uk/how-to-debug-and-upload-log-files-for-xbmc/

https://www.tvaddons.ag/posting-error-logs-kodi/

http://www.htpcbeginner.com/kodi-log-file/

**Comment by kylemckeith** [comment]
Found it, it says 'CGUIMediawindow::GetDirectory(plugin://plugin.video.specto/?action=open setting&query=0.0) failed' there's stuff that says 'NOTICE:[SPECTO] :->------- Params2 tool navigator' something else says ERROR: static bool XFILE:CDirectory::GetDirectory(const CURL&. I don't understand what half of this means

**Comment by xxcriticxx** [comment]
what os? what box/computer? what ver of kodi? what ver of plugin?

**Comment by kylemckeith** [comment]
Os? And Cyclone Android X8 Octa Core Smart. And V16.1 for Kodi and I'm not sure. Where can I find out the os and version of plug in? Sorry for the late reply aswell

**Comment by xxcriticxx** [comment]
did this plugin work before? you have any other plugins working?

**Comment by kylemckeith** [comment]
What plug in?

**Comment by xxcriticxx** [comment]
did plugin did it work before?

**Comment by kylemckeith** [comment]
If you mean Specto then yes, it worked then a few hours later when I went back on it, it didn't work

**Comment by xxcriticxx** [comment]
did you try old version? did you try to remove and install again?

**Comment by kylemckeith** [comment]
How do I try the old version? And I tried it just pops up saying 'Specto Themepak is used by the following installed add on(s) Specto-...Fork  This add on can't be uninstalled'

**Comment by xxcriticxx** [comment]
you can find older versions here

http://kodi.filmkodi.com/plugin.video.specto/

**Comment by kylemckeith** [comment]
And how do I try these on the box? Just I don't really know much about this kind of stuff

**Comment by xxcriticxx** [comment]
download zip to your desktop then go to system add-ons and install from zip

**Comment by kylemckeith** [comment]
I only got this box to watch movies etc so I have no idea what any of this stuff means?

**Comment by xxcriticxx** [comment]
read my post from 3 days ago

**Comment by kylemckeith** [comment]
Whatever the last update for Specto was, it's working now cheers

**Comment by xxcriticxx** [comment]
cool can you please close this issue
