### ISSUE TITLE
Mrknow filmy online, specto

### ISSUE THREAD

**Issue by hekelezeme** [mrknow/filmkodi#407]
Witam,  mam problemy z alltube filmy, specto tez nie znajduje źródeł czy tylko ja tak mam ?

**Comment by xxcriticxx** [comment]
jaki film?

**Comment by hekelezeme** [comment]
Na alltube nie znajduje zadnego streamu, przynajmniej z pierwszej strony a na specto najnowsze ładuje a nieco starsze padły

**Comment by xxcriticxx** [comment]
alltubie wiemy czekamy na mrknow i fix

**Comment by mrknow** [comment]
Poprawiłem  alltube filmy
