### ISSUE TITLE
Specto partially working tonight!

### ISSUE THREAD

**Issue by dracosc** [mrknow/filmkodi#408]
Specto (and some other addons like Exo.....) are partially working tonight!
Genres, Years, and more are not working! Only People Watching and search works!
Any help??

**Comment by eatch682** [comment]
It appears that most of the search functions are down, with the exception of searching for a apecific movie. Search by actor, year, etc all fail to respond.

**Comment by Konaloa720** [comment]
I am having the same issues..only people watching is working and very specific searches are working for titles.

**Comment by morphus41** [comment]
i am having the same problem here to its pissing me off how do you fix it this has been going on now for a few months

**Comment by mrknow** [comment]
old issue
