### ISSUE TITLE
Specto 

### ISSUE THREAD

**Issue by hitman1804** [mrknow/filmkodi#411]
Hi, from 3 days Specto stop showing many streams. The streams which shows up many of them are not working at all. Genres - Categories not working.

**Comment by gingervince** [comment]
Nothing is coming up for me. No list of movies etc

**Comment by jesussson** [comment]
When i click in theaters it start to load and stops

**Comment by dracosc** [comment]
Guys! Specto s still working fine if you use People Watching and search! Please be patient until MrKnow fixes the rest of the problems!

**Comment by vile80r** [comment]
Love Specto. Great work.

Just one question/comment... I can't figure out how to set Specto to auto import Trakt watchlist. I have to manually go into the Tools section and do it. Where is the setting located to schedule Specto to auto import Trakt TV and Movie Watchlist? I assumed it would be a similar setup to the Auto Library Updater add-on where I could set to import once an hour or every 4 hours etc. 

I can't find anything like that.

**Comment by mrknow** [comment]
yesterday released the update . Please try it again
