### ISSUE TITLE
mrknow.pl alltube.tv nie działa 

### ISSUE THREAD

**Issue by Cerber2000** [mrknow/filmkodi#414]
Witam.
Mam problem z wtyczką mrknow.pl Od jakiegoś czasu nie działają Filmy z serwisu alltube.tv 
Wersja wtyczki mrknow.pl 2016.07.02.02
Pojawia się komunikat  ,może to chwilowa awaria spróbuj ponownie później

**Comment by Cerber2000** [comment]
Czy wtyczka FanFilm ma zastąpić wtyczkę mrknow.pl?

**Comment by xxcriticxx** [comment]
nie

fanfilm jest specto polska

**Comment by Cerber2000** [comment]
Na spectro polska=fanfilm  też nie działa alltube.tv 
Wiem że wtyczka w budowie, czy dacie radę poprawić mrknow.pl?

Przez czas potrzebny na budowę spectro polska, można by było korzystać z mrknow.pl

**Comment by xxcriticxx** [comment]
wszyscy czekamy na mr.know

**Comment by Cerber2000** [comment]
Ok to czekamy

**Comment by borys76** [comment]
Wakacje sa ,mrknow odpoczywa 
Wam tez radze odpoczac od tv :)

**Comment by xxcriticxx** [comment]
@borys76 jak tam sling box?

**Comment by borys76** [comment]
Nie mam teraz, Nie mam nikogo w PL kto by oplacal I  podlaczyl ,wszyscy wyjechali

**Comment by xxcriticxx** [comment]
miales sling box europa czy usa w polandzie?

**Comment by xxcriticxx** [comment]
jest full HD?

**Comment by borys76** [comment]
Slinga mialem w PL podlonczony pod nc+ ogladalem w USA 
Tak full HD

**Comment by borys76** [comment]
W USA mam slinga caly czas

**Comment by xxcriticxx** [comment]
Hyba bende musial wtego slingbox za inwestować 

Ja ma homerun hd w domu

**Comment by xxcriticxx** [comment]
Na sling jest jakis dvr?

**Comment by borys76** [comment]
Jezeli dekoder pod ktory podlonczony jest sling ma pvr to tak

**Comment by borys76** [comment]
Sling daje ci kontrole calkowita nad uzadzeniem pod ktore jest podlonczone czyli uzywasz wszystkich funkcji dekodera jakbys mial ten dekoder w domu

**Comment by xxcriticxx** [comment]
Niemam zadnej cable box umnie wszystko chodzi przez Windows media center

**Comment by xxcriticxx** [comment]
Jaki pakiet w nc+ Potrzebuje? Coś z multi room?

**Comment by borys76** [comment]
Pakiet jaki chcesz ,dekoder najlepiej zeby byl tylko do twojego uzytku Bo  jezeli domownicy beda ogladali TV  I ty wtym samym czasie to bedzie problem czyli najlepiej multiroom I jeden dekoder tylko dla ciebie

**Comment by xxcriticxx** [comment]
Extra dekoder how much mnie kosztuje?

**Comment by borys76** [comment]
Sprawdz na nc+

**Comment by xxcriticxx** [comment]
I w końcu jaki slingbox europa czy z usa?

**Comment by borys76** [comment]
A co za roznica?

**Comment by xxcriticxx** [comment]
Niemam pocięcia tylko prąd inny hyba

**Comment by borys76** [comment]
Wystarczy adaptor plug

**Comment by xxcriticxx** [comment]
Ok to projekt na xmas mam

**Comment by mrknow** [comment]
Witam już po urlopie :). Niestety było za gorąco i ni jak nie mogłem się zmotywować do roboty. 

Może to problem z openload - sprawdzam ...

**Comment by mrknow** [comment]
Wersja 2016.07.30.2 - powinna rozwiązać ten problem. Zaktualizuj

**Comment by mrknow** [comment]
Wersja 2016.07.30.3 - powinna również poprawić alltube seriale  Zaktualizuj

**Comment by xxcriticxx** [comment]
ten ostatni openload fix to hyba jeszcze nie final fix bo w whitecream dalej link nie dzialaja. sorry nie moge teraz nic przetestowac

**Comment by Cerber2000** [comment]
Dzięki alltube filmy działa
