### ISSUE TITLE
Not getting any results when selecting any genre or year using Kodi Krypton.

### ISSUE THREAD

**Issue by woodside007** [mrknow/filmkodi#416]
Not getting any results when selecting a genre or year using Kodi Krypton. If I try to get a list by selecting a year or genre the busy icon comes up for a second and then nothing.  Thanks.

**Comment by Meshuggah2018** [comment]
Yes I had same problem with Kodi jarvis 16.1 on 2 matricom quad core boxes and my windows 10 pc. Must be the 7/30 update?

**Comment by woodside007** [comment]
"Must be the 7/30 update?"

Been broken for a while now. Before 7/30 update.
Exodus was doing the same thing but a fix was implemented. Not sure what was done to fix it.

**Comment by mrknow** [comment]
old issue
