### ISSUE TITLE
iwatchonline zmiana adresu w specto

### ISSUE THREAD

**Issue by Seico** [mrknow/filmkodi#417]
To jest nowy adres : https://www.iwatchonline.cr lub https://www.iwatchonline.lol , można prosić o zmiane w specto , a poza tym zaczynają się tam pojawiać filmy z PL audio , czy jest mozliwość aby po wyszukaniu filmu była widoczna wersja audio przy wyborze serwisu z filmem

**Comment by mrknow** [comment]
Poprawione w plugin.video.specto  v2016.08.23.4
