### ISSUE TITLE
nieudana instalacja filmy online

### ISSUE THREAD

**Issue by marco2602** [mrknow/filmkodi#42]
Piszę oddzielny post to może coś szybciej z tym pójdzie.

W końcu udało sie z logami,po uruchomieniu dodatek flimy online odinstalowany i próba instalacji ponownie nie udana ,czyli stoi 0% i wywala komunikat "instalacja nie udana" a myślałem ze coś się zmieni bo przyszła rano aktualizacja na telefon i mbox s82 tutaj tradycyjnie zaktulizowalo sie bez problemu,goclevery android box 500 ten sam błąd

http://xbmclogs.com/pzc5wtj9l

**Comment by xxcriticxx** [comment]
jest duzo androidow i na wszystkich nie te same teczki kodi to nawiecej pozodujie nieudane instalacjie

**Comment by mrknow** [comment]
Wgraj ręcznie te wtyczki  poprzez opcje zainstaluj z pliku zip
1. najpierw - script.module.xbmcfilm.zip
2. następnie - plugin.video.mrknow.zip
3. jako opcje jeszcze raz repozytorium repository.filmkodi.com.zip

[script.module.xbmcfilm.zip](https://github.com/mrknow/filmkodi/files/107510/script.module.xbmcfilm.zip)
[plugin.video.mrknow.zip](https://github.com/mrknow/filmkodi/files/107509/plugin.video.mrknow.zip)
[repository.filmkodi.com.zip](https://github.com/mrknow/filmkodi/files/107511/repository.filmkodi.com.zip)
