### ISSUE TITLE
Sitem TV

### ISSUE THREAD

**Issue by mar2016** [mrknow/filmkodi#420]
Darmowa TV nawet dziala bez problemow i sporo programow polskich
Czy mozna ja dodac do wtyczki mrknow?
http://sitemtvpl.rf.gd

**Comment by borys76** [comment]
http://nowwatchtvlive.co/poland-tv-channels-live-stream-watch-polish-tv-online-channel-free/

**Comment by mrknow** [comment]
Te serwisy nie zostaną dodane. znalazłem tylko 10% sprawnych kanałów
