### ISSUE TITLE
HORIZON GO

### ISSUE THREAD

**Issue by plumers** [mrknow/filmkodi#423]
Hej Mr mam ogromną prośbę dałbyś radę dodać do płatnych wtyczek taką od HORIZON GO z UPC?? potrzeba silverlighta aby ogladać a na komórkach nie smiga :) może przez kodi pójdzie - pozdro !!!

**Comment by mrknow** [comment]
Na stronie jest informacja że działa na każdym urządzeniu. Ja nie mam tej kablówki więc będzie mi ciężko zweryfikować działanie wtyczki ...

**Comment by soundslikerust** [comment]
Nie dziala na android tv
