### ISSUE TITLE
KODI Android zawiesza się na wtyczne mrknow

### ISSUE THREAD

**Issue by jendrjej** [mrknow/filmkodi#424]
Nigdzie nie znalazłem rozwiązania problemu zawieszania się mrknow na kodi androidowym tak jak by problem wcale nie istniał, posiadam Sony Bravie 50W809C na androidzie 5.1.1 oraz Galaxy S6 również na 5.1.1 wtyczka instalowana dokładnie według wytycznych ze strony mrknow na obu urządzeniach sytuacja analogiczna, po włączeniu jakiegokolwiek działającego kanału po 3 do 5 minut kodi się zawiesza i dostaje komunikat aplikacja nie odpowiada i trzeba ją zamknąć, tylko na windowsie jest wszystko ok tam wszystko działa perfekcyjnie kiedy mi zależy właśnie na androidzie

**Comment by xxcriticxx** [comment]
podaj log

jusz bylo cos takiego tutaj o TV

**Comment by jendrjej** [comment]
[kodi.old.log.zip](https://github.com/mrknow/filmkodi/files/404324/kodi.old.log.zip)
w logu widać że włączyłem comedy central następnie canal+ sport chwilkę pochodził i zawieszka "aplikacja kodi nie odpowiada"

**Comment by jendrjej** [comment]
[kodi.zip](https://github.com/mrknow/filmkodi/files/404358/kodi.zip)
tutaj dam jeszcze jeden log oglądałem kanał chwile nie zawiesił się, wyłączyłem przeleciałem listę włączyłem kolejny i zawias podczas buforowania

**Comment by xxcriticxx** [comment]
sprobuj jakies filmy albo seriale

live tv chodzi w kratke

**Comment by jendrjej** [comment]
dzięki za zainteresowanie ale głównie chodzi mi o live tv filmy lub seriale zgrywam na dysk zawsze lepsza jakość, kurcze na windzie kodi z tą wtyczką chodzi bezbłędnie, ale jakieś pół roku temu szukałem już rozwiązania tej przypadłości ktoś gdzieś na jakimś forum wstawił jakiegoś zipa doinstalowałem i chodziło bez zawieszeń ale niestety miałem aktualizację andka i musiałem mu defaulta zrobić

**Comment by xxcriticxx** [comment]
jest ver platna jak chcesz http://kodi.filmkodi.com/beta/plugin.video.mrknowtv/plugin.video.mrknowtv-2016.06.25.1.zip

**Comment by xxcriticxx** [comment]
ver free jest kaka ostatnio

**Comment by mrknow** [comment]
Wersja FreeTV może się zawieszać. Proponuje wykupić konto premium i wykorzystać wtyczkę MrknowTV http://filmkodi.com/pl/mrknowtv-telewizja-ze-stron-kontami-premium/
