### ISSUE TITLE
mrknow.pl alltube.tv znowu  nie działa 

### ISSUE THREAD

**Issue by Cerber2000** [mrknow/filmkodi#425]
Witam.
Mam znowu problem z wtyczką mrknow.pl Od jakiegoś czasu nie działają Filmy z serwisu alltube.tv aktualizacja do wersji 2016.08.02.1 pomogła na 2 dni. Teraz nie działa : (

**Comment by mrknow** [comment]
Jeżeli był to problem z openload - to już poprawiłem. Sprawdzę jeszcze jutro bo u mnie działa ...

**Comment by Cerber2000** [comment]
Tak był to chyba problem z openload Teraz działa 

Dzięki za fixa
