### ISSUE TITLE
MrKnow czy to w Polsce jest wogole legalne?

### ISSUE THREAD

**Issue by baraka123** [mrknow/filmkodi#429]
Jak funkcjonuje wtyczka MrKnow? Mam nadzieje ze nie przez p2p, okaze sie pozniej ze 
dostanie sie jakas kara za lamanie praw autorskich.

**Comment by xxcriticxx** [comment]
ostra kara ciebie czeka synu min 10000 zl za film

**Comment by mrknow** [comment]
Legalne http://filmkodi.com/pl/ogladanie-telewizji-online-jest-legalne/
