### ISSUE TITLE
new series?

### ISSUE THREAD

**Issue by setonuser** [mrknow/filmkodi#432]
There is a new tv show called Van Helsing, I can find it in specto, but it is empty :/, like it doesn’t have any episodies, but it has. It is a bug? or I have to do something to update the repository?
thanks

**Comment by mrknow** [comment]
This is not bug. Van Helsing will be availble in specto  from  23 Sep. 2016. (date first episode http://www.imdb.com/title/tt5197820/episodes?season=1&ref_=tt_eps_sn_1)
