### ISSUE TITLE
Nowa wersja strony kinoman.tv

### ISSUE THREAD

**Issue by xxcriticxx** [mrknow/filmkodi#434]
Nowa wersja strony: http://lajt.kinoman.tv.
Poprawione rzeczy: listy ulubione/poczekalni, wyszukiwarka, szybsze działanie, dodatkowy pakiet 350pkt za 12 godzin VIP.
Korzystaj codziennie a otrzymasz 70 pkt / dzień (20 za zalogowanie + 50 za korzystanie z nowej wersji)

**Comment by mrknow** [comment]
zamknięty
