### ISSUE TITLE
Wizja.tv 

### ISSUE THREAD

**Issue by djchicagoclub** [mrknow/filmkodi#435]
System operacyjny android i apple tv
Kodi version 16.1
Filmy Online - Mr.Know.pl
Wtyczka WIZJA.TV  zniknęła z ekranu.

**Comment by mrknow** [comment]
wizja.tv jest we wtyczce mrknowtv

**Comment by djchicagoclub** [comment]
Przepraszam. A jak można zainstalować MrKnow tv?

**Comment by mrknow** [comment]
Tutaj masz film z instrukcją - http://filmkodi.com/pl/mrknowtv-telewizja-ze-stron-kontami-premium/
