### ISSUE TITLE
Videostar - nie wczytuje listy kanałów - not authorized - Raspberry Pi 3B z LibreElec 7.0.2

### ISSUE THREAD

**Issue by odziom91** [mrknow/filmkodi#436]
Cześć!
Powracam z problemem dotyczącym Videostar. :)
Posiadam Raspberry Pi 3B wraz z zainstalowanym LibreElec 7.0.2.
Po zainstalowaniu MrKnow TV, wpisaniu danych z Videostara twierdzi, że "Not authorized".
Problem dotyczy tylko tego urządzenia - testowałem na Android Boxie M8S+ i tam działa bez problemu.
Zrzut loga poniżej - polecam również otworzyć jeszcze raz temat odnośnie Videostara.
`01:18:34 1282.958862 T:1360786336  NOTICE: [SPECTO]: ->----------                PARAMS: {'action': 'tv', 'url': 'videostar'}
01:18:35 1283.713623 T:1360786336  NOTICE: [SPECTO]: ResultC videostar.get None
01:18:35 1283.908936 T:1360786336  NOTICE: [SPECTO]: EEEEEEEEEEEE Result videostar.get Not authorized
01:18:36 1285.128418 T:1360786336  NOTICE: [SPECTO]: Error tv.get 'channels'
01:18:36 1285.342285 T:1961922560   ERROR: GetDirectory - Error getting plugin://plugin.video.mrknowtv/?action=tv&url=videostar
01:18:36 1285.343506 T:1961922560   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mrknowtv/?action=tv&url=videostar) failed`

Proszę o jakieś wskazówki, bądź rozwiązanie problemu. Niestety w najbliższy weekend nie będę dostępny, stąd informuję, iż na wszelkie sugestie odpowiem jak tylko to będzie możliwe. :)

**Comment by mrknow** [comment]
a jako login podajesz email ?

**Comment by odziom91** [comment]
Tak. Loginem jest email. :)

**Comment by mrknow** [comment]
Podeślij logi. Bez tego ani rusz
