### ISSUE TITLE
Wizja.tv

### ISSUE THREAD

**Issue by borys76** [mrknow/filmkodi#437]
Witam moze ktos sprawdzic czy dziala wizja na premium? 
Na stronie idzie a przez wtyczke blad no stream available

**Comment by Arek76** [comment]
Witam mam rowniez z tym czesty problem ,
W zeszlym tygodniu zostalo zabnowane IP , po cofniecicu Bana wystepuje owy problem . Czasem jest czasem nie ma strumienia , Ciekawe jest rowniez to ze u mnie gra a dzwoni moj znajomy ktory rowniez uzywa wtyczki MrKnow do wizji tv i u niego nie ma . Wczesniej nie zdarzaly sie takie rzeczy .
Pozdrawiam MrKnow , dobry kawal roboty.

**Comment by borys76** [comment]
Ja mam ten problem od Soboty na wtyczce 
Ip raczej odpada bo moge ogladac na stronie

**Comment by Arek76** [comment]
Ja jestem dystrybutorem Android Boxow , wiem to rowniez od moich klientow . Nie ma zasady gdzie sie wylącza gdzie gra stąd moje przypuszczenia . Moze wtyczka ma zaleznosci z Ip , nie wiem stad moje pytanie.

**Comment by xxcriticxx** [comment]
ja tez mysle ze ip odpada. na stornie sie nic nie zmienilo?

**Comment by Arek76** [comment]
pytasz o strone wizji tv? nie tam jest kompletnie to samo i ogladac mozna . w tej chwili we wtyczce rowniez wszystko jest ok , dziala jak sie nalezy ale w nocy i z rana do godziny 9 nie bylo strumienia . U mnie oczywiscie . Ja zamieszkuje w Berlinie i tu mam swych klientow

**Comment by xxcriticxx** [comment]
server moze padl

napisz do wizji sie zapytaj co bylo po miedzy 9 w nocy a 9 rano

**Comment by Arek76** [comment]
Pisalem , nic sie nie wydazylo . To nie pierwszy raz tak sie stalo , Jak pisalem wyzej u niektorych jest sygnal a u niektorych nie ma , sprawdzajac na stronie smiga az milo tylko we wtycze wystepuja problemy .Borys 76 rowniez ma takowe . Nie mam pojecia wiec pisze tu :)

**Comment by xxcriticxx** [comment]
ok hyba mrknow bendzie musial looknac

**Comment by Arek76** [comment]
Na to licze , sam nie znam jezyka Pythona ((nad czym bardzo ubolewam ) moze wtedy moglbym coś pomoc . Niestety pozostaje poczekac

**Comment by borys76** [comment]
O widze ze Know juz sprawdza 
Dzieki

**Comment by borys76** [comment]
Chyba wina byla po stronie wizjI teraz narazie dziala

**Comment by Arek76** [comment]
Tego nie jestesmy pewni , Bug to bug . Narazie faktycznie nie wystepuje problem . mam nadzieje ze tak zostanie:)

**Comment by Arek76** [comment]
Jednak nie wszystkim dziala wizja tv, mam jeszcze dwoje klientow ktorzy nadal nie maja strumienia = Brak dostepnego strumienia . Mają wykupione konta premium niestety nie mogą ogladac, pomozesz Know?

**Comment by skrzypii** [comment]
Witam od wczoraj 20.08 u mnie tez nie dziala wizja tv na mrknow czy osoba ktora zrobila ten program moze jakos mi pomóc? wizja tv dziaalla super nie pzrerywalo nic na mrknow na kodi ogladam na mboxie, zaczynaja sie ligi pilkarskie tym bardziej wielka prosba o naparwe problemu? wyskakuje mi komunikat - "inny bład" jak wlaczam. co mam zrobić?? pozdrawiam Arek

**Comment by borys76** [comment]
Wejdz na wizje strone I zobacz czy ip jest zbanowane, wizja ma problemy z
systemem i blokuje ip ,tez mialem zbanowane ip po napisaniu email
odblokowali I dodali premium

On Aug 21, 2016 9:45 AM, "skrzypii" <notifications@github.com> wrote:

Witam od wczoraj 20.08 u mnie tez nie dziala wizja tv na mrknow czy osoba
ktora zrobila ten program moze jakos mi pomóc? wizja tv dziaalla super nie
pzrerywalo nic na mrknow na kodi ogladam na mboxie, zaczynaja sie ligi
pilkarskie tym bardziej wielka prosba o naparwe problemu? wyskakuje mi
komunikat - "inny bład" jak wlaczam. co mam zrobić?? pozdrawiam Arek

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mrknow/filmkodi/issues/437#issuecomment-241258598>, or mute
the thread

**Comment by skrzypii** [comment]
oki dzieki BORYS za szybka odpowiedz a;le jak mam sparwdzic ze mam zabanowane IP?? nie wiem jak to zrobic? napsialem do wizja tv by mi odblokowali, zawsze mi ladnie smigalo na MRKNOWTV pzrez kodi a od wczoraj lipa, teraz ligi sie zaczynaja mam konto premium

**Comment by borys76** [comment]
Wejdz na strone wizja  wybiez kanal, jak masz zbanowane IP to bedzie pisalo

**Comment by Arek76** [comment]
Czy zbanowane Ipmozna sprawdzic bardzo prosto . Wchodzisz na strone www.wizja.tv jesli widzisz to co zawsze wszystko jest ok ,jesli nie zobaczysz komunikat tylko nastronie nie zacytuje poniewaz nie potrafie niestety Angielskiego . Do wizji pisanie rowniez mija sie z celem , pisalem i przyslali mi komunikat ze to nie jest oficjalna ich wtyczka i beda dzialac tylko jesli na stronie w przegladarce masz problemy. Nie wspieraja wtyczki MrKnow niestety , W sumie z jednej strony ich rozumiem . 
Z tego wychodzi że albo to blad wtyki jakis albo poprostu wizja zmienia streaming czyli zmienia serewry i Mr Know nie nadaza je podmieniac w skrypcie ale niestety do teraz nie odpowiedzial :) Duzo roboty ma wiec tez rozumiem i czekam grzecznie . 
Mnie tezprzez ostatnie dwa dni wylaczal sie dostep do kanalow ale coz moge zrobic , grzecznie czekac i miec nadzije ze MrKnow to naprawi lub ze pojawi sie szybkojakas oficjalna wtyczka z Wizji TV . pozdrawiam rowniez :)

**Comment by skrzypii** [comment]
oki a jest jakis kontakt do autora mrKNow?? zawsze dziala ta wtyczka i wizja smigala mi na kodi a teraz jak ligi ida pilkarskie i zuzel to nie dziala

**Comment by Arek76** [comment]
jak narazie czekam na jakas reakcje od kilku dni i cisza ale :) Wszyscy mamy swoje zycie prywatne i trzeba to szanowac :)

**Comment by skrzypii** [comment]
no tak ja rozumie a jest jakas inna wtyczka gdzie mozna na kodi ogladac wizja tv???

**Comment by skrzypii** [comment]
no bo z a tydzien gp na zuzlu w Gorzowie ja wykupione mam premium na wizja tv i uwazma tak sie nie powinno robic jesli placi sie to wymaga by bylo oki ??

**Comment by Arek76** [comment]
Nie ma innej wtyczki na ktorej mozna ogladac Wizje , ale pracuja nad tym by byla . Wizja tv gwarantuje tylko ogladanie z poziomu przegladarki i z problemami takimi mozna sie do nich zglaszac . Nie wspiera Kodi jeszcze oficjalnie . Ta wtyczka MrKnow Tv nie jest oficjalna dystrybucja Wizji TV tylko produktem MrKnow ktory chcial Nam zrobic dobrze i dołączyl skrypt Wizji do swojej wtyczki . I tylko oon ma dostep do ustawian i chyba na tyle wiedze by cokolwiek w niej zmieniac i modyfikowac :) My mozemy jedynie prosic i czekac i cieszyc sie jak naprawi :)

**Comment by skrzypii** [comment]
no ale gdzie mozna napsiac do tego autora MRKNOW??

**Comment by borys76** [comment]
Tutaj piszesz jak Know bedzie mail czas to pewnie przeczyta 
Nie zapominajcie ze sa wakacje

**Comment by Arek76** [comment]
WItam ponownie , znalazlem chyba blad oczywiscie nie napisze gdzie i jak napisze jednak jak sobie z nim radze . Zacznę od tego że nigdy nikomu nie dawalem mojego Loginu i hasla wiec ta opcja nie wchodzi w grę by ktos logowal sie za posrednictwem moich danych , dostep mam tylko ja . Kilkukrotnie mialem problem z brak strumienia i grzebalem grzebalem i okazalo sie ze jak wchodze na strone wizji i tam probuje odpalic wyskakuje mi komunikat że ogladam juz z innego IP . Wiem ze tak nie jest wiec klikam rozlacz wszystko i polacz mnie tutaj . Po czym rozlaczam ogladanie w przegladarce i wylogowuje sie i na Tv Boxie juz wszystko dziala w porzadku . Wiem ze to rozwiazanie troszke dziwne ale jesli komus bardzo zalezy by miec wizje w ten sposob moze sobie poradzic , A pewnie i dla MrKnowa ta informacja bedzie przydatna  i podpowie gdzie moze byc Bug . Pozrdawiam serdecznie .

**Comment by borys76** [comment]
Cytat
" Zacznę od tego że nigdy nikomu nie dawalem mojego Loginu i hasla wiec ta opcja nie wchodzi w grę by ktos logowal sie za posrednictwem moich danych , dostep mam tylko ja . "

To wcale nie znaczy ze ktos nie ma twojego loginu/Hasla
Zmien haslo!

**Comment by Arek76** [comment]
w sumie , cos w tym jest . w koncu wtyczka Mrknow jest na otwartych serwerach Githuba :) zmienie ale co to da skoro i tak jakis dostep do tego jest :) czekam na oficjalna wtyczke wizji :)

**Comment by borys76** [comment]
Wtyczka nie ma nic do wycieku login/password 
a strona www wizji jak juz cos

**Comment by xxcriticxx** [comment]
coraz lepsze to sie robi

**Comment by xxcriticxx** [comment]
ja mam wizje ze to jeszcze troche moze potrwac

**Comment by Arek76** [comment]
Jak juz pisalem nie znam sie na tyle by oceniac , wyciagam wnioski tylko czasem moze bledne :) nie wiem . Staram sie poradzic sobie z tą sytuacją nic pozatym .

**Comment by xxcriticxx** [comment]
@Arek76 hyba @borys76 obraziles bo nic nie pisze wiecej

**Comment by borys76** [comment]
A co  mam  pisac?
Glupoty na sile?

**Comment by Arek76** [comment]
Nie no , nic przeciez zlego nie napisalem:)

**Comment by borys76** [comment]
Dokladnie dlatego nie wiem oczym  xxcriticxx mowie, chyba  ma problemy z czytaniem

**Comment by Arek76** [comment]
:) nic nie napisze . Ale faktem jest że tu nie ma co sie klócić:) ewentualnie nawzajem wymieniac doswiadczeniami

**Comment by Arek76** [comment]
Zamnąles temat mimo że nie skonczone? dziwne troszke . Poczekaj troszke jeszcze może MrKnow cos poradzi

**Comment by borys76** [comment]
Moim zdaniem wszystko z wtyczka ok, wina po stronie wizja.tv, ok  poczekam na mrknow

**Comment by Arek76** [comment]
Twoim może tak , moim jednak nie koniecznie ale jak chcesz . Moze MrKnow spojrzy i tak na nią

**Comment by borys76** [comment]
Sorry nie wiem czemu zamknelo drugim razem

**Comment by Arek76** [comment]
hehe nic sie nie stalo wazne by Know rzucil okiem :)

**Comment by mrknow** [comment]
Dobra 
Ja nie mam takiego efektu do tej pory nie zauważyłem. Na razie w nowej wersji:
- dodam logowanie szczegółowe
- stan konta

**Comment by mrknow** [comment]
Dobra 
Proszę zainstalujcie ręcznie najnowszą wersję http://kodi.filmkodi.com/beta/plugin.video.mrknowtv/plugin.video.mrknowtv-2016.08.28.1.zip 
Sprawdźcie czy działa

**Comment by borys76** [comment]
Umnie dziala OK,  ja mialem problem tylko jak mi wizja zbanowala IP po napisaniu email do wizja I odblokowaniu IP nie mialem wiecej problemow z logowaniem

**Comment by Arek76** [comment]
A wiec tak , od wczoraj wszystko smiga jak ta lala , Zalozylem sobie specjalnie jeszcze jedno konto na wizji i wszystko jest ok . Wyskakuje tylko komunikat - uruchamianie wizji , prosze czekac :) pozatym jak do tej pory wszystko gra i buczy :) dzieki Know odezwij sie prosze na F-u mam potrzebuje porady odnosnie nauki programowania :) o ile mozesz mi taka porade dac :) pozdrawiam i dzieki

**Comment by mrknow** [comment]
OK, to zamykam zgłoszenie. 
@Arek76  Jeżeli chodzi o doradzenie jak zacząć programować to najważniejsze programować. https://youtu.be/qaYLrjg359Q

**Comment by Mstenia** [comment]
borys76
Jak wizja.tv tłumaczy blokowanie ip?? Mi zablokowali tydzień temu prawie i nie raczą nawet na maila odpowiedzieć :/

**Comment by borys76** [comment]
Witamy,
przepraszamy, za cała sytuację, ale niestety przechodzimy obecnie mała awarię. Pracujemy nad jej rozwiazaniem. Z cała pewnościa przedłużymy ważność konta premium o czas, w którym korzystanie z usługi było niemożliwe.
