### ISSUE TITLE
Specto fork error

### ISSUE THREAD

**Issue by Evans1990** [mrknow/filmkodi#439]
can anybody help me with these logs errors please?
![13925269_10154389240360350_8455925518323869265_n](https://cloud.githubusercontent.com/assets/21099146/17767128/83614846-6526-11e6-9c54-110e1e77ab56.jpg)

**Comment by mrknow** [comment]
yesterday released the update . Please try it again

**Comment by BankruptEd** [comment]
Yes all good and thanks for closing the thread. Didn't think of it. Love
the add-on Mr. Know. Peace.
