### ISSUE TITLE
nie instaluje sie dodatek "filmy online"

### ISSUE THREAD

**Issue by marco2602** [mrknow/filmkodi#44]

**Comment by marco2602** [comment]
Miałem napisać tutaj,to piszę.jest miejsce na dysku goclevery po resecie jedyna aplikacja wgrana to kodi ,tu masz log:http://xbmclogs.com/pzc5wtj9l

**Comment by marco2602** [comment]
Zapomniałem odpowiedzieć ,tak urządzenia są na androidzie 4.0.4

**Comment by mrknow** [comment]
Wgraj ręcznie te wtyczki do katalogu 
1. najpierw - script.module.xbmcfilm.zip
2. następnie - plugin.video.mrknow.zip
3. jako opcje jeszcze raz repozytorium repository.filmkodi.com.zip

[script.module.xbmcfilm.zip](https://github.com/mrknow/filmkodi/files/107510/script.module.xbmcfilm.zip)
[plugin.video.mrknow.zip](https://github.com/mrknow/filmkodi/files/107509/plugin.video.mrknow.zip)
[repository.filmkodi.com.zip](https://github.com/mrknow/filmkodi/files/107511/repository.filmkodi.com.zip)

**Comment by adZiggz** [comment]
instaliwanie script.module.xbmcfilm.zip wyskakuje zenie moze instalowac dependency beautifulsoup. Czy jest nowa wersja beautifulsoup?

**Comment by marco2602** [comment]
Teraz jest tak,po aktualizacji wtyczka zainstalowala sie z "automatu" czyli tak jak kiedyś od kiedy pojawiły się problemy,odpalam wchodzi do momentu wyboru ze filmy czy telewizja i dalej nic ,mieli kółeczko czekaj i mieli i tak bez końca.na urządzeniach z kodi 15.2 cały czas zero problemów.a tutaj na 14.2 ciągle coś nie tak.chyba będę musiał sie pozbyć tych android boxow bo po nowym roku ciagła kicha z mrknow.myślę ze to jak to dzisiaj jest wszystko nowości tylko a o starszym sprzęcie sie zapomina.oczywiście zainstalowałem tez ręcznie tak jak kazales ale ro samo.

**Comment by mrknow** [comment]
zmieniłem serwery na których były wtyczki do pobrania. Od teraz powinny działać prawidłowo aktualizacje
