### ISSUE TITLE
Pierwsza.TV

### ISSUE THREAD

**Issue by mar2016** [mrknow/filmkodi#440]
TV Sony Android 5.1 Kodi16.1 od paru dni przestala dzialac wtyczka Pierwsza.TV a ponadto nie mozna zaktualizowac wtyczek mrknow przez kodi.filmkodi.com.Po prostu zadnej reakcji

**Comment by xxcriticxx** [comment]
to jest najnowsza ver

http://kodi.filmkodi.com/plugin.video.mrknowtv/plugin.video.mrknowtv-2016.06.25.1.zip

**Comment by mar2016** [comment]
Wlasnie ta wtyczke mam i niedawno pierwsza tv przestala sie otwierac nie tylko na TV ale i na boxach i windowsie ,reszta  dziala normalnie

**Comment by xxcriticxx** [comment]
to samo jest z wizja.tv

https://github.com/mrknow/filmkodi/issues/437

**Comment by Gidzior** [comment]
Wtyczka nie przyjmuje loginu/hasla

**Comment by Arek76** [comment]
Sa ostatnio male problemy z wtyką MrKnow TV , trzeba czekac az MrKnow sie pojawi i znajdzie troszke czasu dla nas

**Comment by gumball1** [comment]
u mnie dziala bez zarzutu

**Comment by mar2016** [comment]
Podaj nr. wtyczki ktora masz jaki  numer Kodi i jaki system,bo u wielu osob przez wtyczke mrknow nie dziala.Faktemjest ze dziala w przegladarkach Mozilla Opera iinnych z flashem

**Comment by Gidzior** [comment]
System Android 5.1.1
Wtyczka MrknowTv 2016.06.25.1
Po wpisaniu loginu i hasła w ustawieniach wybieram zakładkę Pierwsza TV, klikam na program i dostaje info "Podano nieprawidłowy login lub hasło" mimo że są wpisane poprawnie

**Comment by Gidzior** [comment]
W aplikacji na Windows 7 jest ten sam błąd
Po wpisaniu loginu i hasła w ustawieniach wybieram zakładkę Pierwsza TV, klikam na program i dostaje info "Podano nieprawidłowy email lub hasło" mimo że są wpisane poprawnie

**Comment by mar2016** [comment]
Na stronie Pierwszej jest wtyczka do Kodi ale u mnie nie chce sie zinstalowac

**Comment by Gidzior** [comment]
Wtyczka ze strony u mnie działa bez żadnych problemów i z niej póki co korzystam ale chciałem używać wtyczki MrknowTv a ona nie działa.

**Comment by gumball1** [comment]
3 rozne systemy na kazdym kodi 16.1, wersja wtyki mrknowtv najnowsza - pierwszatv dziala elegancko

**Comment by mrknow** [comment]
jeżeli problem będzie się powtarzał, proszę:
- zainstalujcie wersję beta z http://kodi.filmkodi.com/beta/plugin.video.mrknowtv/plugin.video.mrknowtv-2016.08.28.1.zip 
- podeślijcie logi

**Comment by Adam-po** [comment]
Kodi. MrKnow Tv 28.08.2016 wchodzą na wizja.tv a tuuuuu wyskakuje Informacjea( Inny Błąd Wizja Tv) in nie działa nic.😭😭😭😭😭

**Comment by borys76** [comment]
Taki komunikat mialem jak zle password wpisalem
Sprawdz login/password
