### ISSUE TITLE
Specto i filmy z polskim audio

### ISSUE THREAD

**Issue by Seico** [mrknow/filmkodi#447]
Dzieki za zaktualizowanie adresu dla Iwatchonline , ale jest problem z wyszukiwaniem , są na tej stronie filmy HD z audio PL , jak wpisuje w wyszukiwarkę to znajduje film ale nie znajduje z audio PL

Przykładowy link : https://www.iwatchonline.cr/movie/62686-desert-flower-2009

Jest szansa aby to naprawić ?

**Comment by xxcriticxx** [comment]
Iwatchonline alternative domain www.Iwatchonline.lol

**Comment by mrknow** [comment]
Dzięki za ten przykład, zaraz to sprawdzę

**Comment by Seico** [comment]
Dasz radę to poprawić ?

**Comment by Seico** [comment]
Nie wiem czy ta ostatnia aktualizacja miała pomóc w wyeliminowaniu tego problemu , jak tak to nie pomogła , nadal nie wyszukuje filmów z audio PL

**Comment by albineek** [comment]
jakis progress w zwiazku z powyzszym?

**Comment by mrknow** [comment]
Próbowałem, ale to za dużo. Nie będzie polskiej wersji specto. Wycofuje się z tego projektu ze względu na brak czasu. Fan Film zostanie skasowane
