### ISSUE TITLE
Openload Doing the Pigeon Dance Agsin

### ISSUE THREAD

**Issue by BankruptEd** [mrknow/filmkodi#449]
Just letting you know. Those pigeons are maddening. I was trying to view a HD file of the latest Making of the Mob and there they were 😫

**Comment by mrknow** [comment]
This issue is fixed in Mrknow Urlresolver 2016.08.28.1
http://filmkodi.com/en/openload-fix/

**Comment by BankruptEd** [comment]
It was for me for a while. It just started again. Is there something I need
to do? I know the URL resolver just recently updated. I'm not thoroughly
familar with Kodi yet. All I know is the fix you mention was good...for
awhile. Then so.ething must have happened but I don't know what.

**Comment by xxcriticxx** [comment]
@BankruptEd just restart your kodi

**Comment by Seico** [comment]
Po aktualizacji gołębie wróciły , "fix" nie pomógł - można to naprawić ?

**Comment by mrknow** [comment]
Fixed in  version 2016.08.28.3. Update **Mrknow URLResolver**

**Comment by BankruptEd** [comment]
Yes, thank you. You're awesome 😀

**Comment by BankruptEd** [comment]
It didn't come through till a bit after your first reply but is good now.

**Comment by BankruptEd** [comment]
And I will look closer at the date of the fix next time. I didn't clue in
to the 28 part of it, meaning today of course. I thought you were telling
me about an earlier fix. Thanks again.

**Comment by mrknow** [comment]
Openload changed coding functions links video yesterday and today .

Version 2016.08.28.1 solved the problem of yesterday's changes

Version 2016.08.28.3 solves the problem of today's changes.

I wonder if tomorrow openload change anything ...

**Comment by BankruptEd** [comment]
Ya I know what ya mean. Oh well, gotta roll with the punches. I'm just glad
someone is out there trying.
