### ISSUE TITLE
błąd dodatku filmy online mrknow

### ISSUE THREAD

**Issue by wojtas89** [mrknow/filmkodi#45]
Witam!
Po ostatniej aktualizacji nie mogę odpalić wtyczki, gdyż w prawym dolnym rogu wyskakuje błąd. Wcześniej miałem różne problemy z wtyczką np. sama się wyłączała i nie było jej w zbiorze wtyczek zainstalowanych, ale radziłem sobie z tym do tej pory. Teraz nie pomaga reinstal (wtyczka normalnie się instaluje. tzn zawiesza się początkowo na 3%, ale po kilku chwilach się aktywuje i dochodzi do 100%). System windows vista.
Dodam jeszcze, że wtyczka xbmcfilm.com nie odpalała się od samego początku. Jakieś rady? Z góry dzięki za pomoc

**Comment by michalek600** [comment]
Miałem niedawno podobny problem.

1. Jaka jest Twoja nazwa konta w Windowsie? Czy ma polskie znaki np. "Wojtuś"

2. Włącz zapisywanie błędów w Kodi: System>ustawienia>system>diagnostyka>rejestruj informacje diagnostyczne. Powtórz czynności powodujące błąd i podeślij tutaj plik  błędów z X\users\twoja nazwa\AppData\Roaming\Kodi\kodi.log. Będzie możliwość zdiagnozowania problemu.

ps. mi też zawsze instalacja mrknow zatrzymuje się na 3%, ale po czasie kończy i działa.

**Comment by wojtas89** [comment]
1. Nie ma polskich znaków.
2. Po próbie wysłania przez log uploader również wyskakuje błąd, dlatego wrzucam plik z logiem na zs http://www54.zippyshare.com/v/B0bKBNpN/file.html

**Comment by mrknow** [comment]
[mrknow_all.zip.zip](https://github.com/mrknow/filmkodi/files/107475/mrknow_all.zip.zip)
A przegraj ręcznie te 3 katalogi.

**Comment by wojtas89** [comment]
po aktualizacji nastąpiła poprawa i wtyczka już działa

**Comment by Adam-po** [comment]
Nic.nie działa Uruchamia kanał i po krutkim czasie wraca do menu albo się kodi wyłącza.

Gesendet von Yahoo Mail auf Android 
 
 Am Fr., 29. Jan. 2016 um 14:29 hat wojtas89<notifications@github.com> Folgendes geschrieben:  
Closed #45.
