### ISSUE TITLE
Wizja TV  odn 437

### ISSUE THREAD

**Issue by Arek76** [mrknow/filmkodi#450]
Nie wiem czy to wina wtyczki czy nie ale prosze MrKnow spojrz i przeanalizuj posta nr #437

**Comment by mrknow** [comment]
Arek będę dzisiaj od 19:00 to może się złapiemy i pogadamy. 
Na razie spadam

**Comment by Arek76** [comment]
szkoda ze nie udalo sie mi wpasc ale wiesz niedziela ,rodzina itd :) mam nadzieje że uda nam sie jakosc skontaktowac . Potrzebuje kilku rad od Ciebie jako eksperta :)
