### ISSUE TITLE
iwatchonline and cloudflare

### ISSUE THREAD

**Issue by bjgood** [mrknow/filmkodi#452]
Hi Mr. Know,
Just providing some info. If you try to go to https://www.iwatchonline.lol, with javascript turned off in the browser, the page displayed says turn javascript on and DDoS protection provided by CloudFlare.

Not sure if it's needed, but I entered "from resources.lib.libraries import cloudflare" into source iwatchonline_mv_tv.py, but it still didn't help in getting any links from source iwatchonline. This is with the latest release 2016.08.28.1.

Just passing on my experiment and observations.

Have a good day, everyone.

Regards,
Bob

**Comment by mrknow** [comment]
fixed
