### ISSUE TITLE
Turn off subs in 1080 sources

### ISSUE THREAD

**Issue by xxcriticxx** [mrknow/filmkodi#453]
How do I turn of sub in 1080 movies in specto?

For example conjuring 2 from pelispedia 1080p has Spanish subs that I would like to turn off

**Comment by BankruptEd** [comment]
You may not be able to. They may be hard subs. If you can't turn them off
the usual way, I think you may be stuck with them. When it happened to me I
would just pick a different source and often they wouldn't be there. Of
course that may mean not using the 1080

**Comment by xxcriticxx** [comment]
Ok
