### ISSUE TITLE
never see ALLUC sources

### ISSUE THREAD

**Issue by mrknow** [mrknow/filmkodi#454]
I have entered my ALLUC information but never see ALLUC sources, checked the username and password several times, is there presently an issue with this feature?

**Comment by bjgood** [comment]
I have a ALLUC account but I never use it.

I have the same problem with Furk. My username and password is entered (and it is correct), but I never see a Furk link. Real-Debrid, yes, Furk, no.

**Comment by mrknow** [comment]
In specto a lot of videos are from  google video Alluc now is not supported. 
for furk send my invitation code (i don't have account)
