### ISSUE TITLE
Gołębie wróciły

### ISSUE THREAD

**Issue by Seico** [mrknow/filmkodi#455]
Znowu openload przez gołębie  niedostępny

**Comment by xxcriticxx** [comment]
pora na :gun:

**Comment by xxcriticxx** [comment]
tknorris fix openload Latest commit 81a5717 2 hours ago

**Comment by mrknow** [comment]
2016.08.29.1 - naprawia ten bład, pewnie nie na długo, ale...

**Comment by BankruptEd** [comment]
Still having trouble installing specto?

**Comment by xxcriticxx** [comment]
@BankruptEd restart kodi plugin will auto update

**Comment by mrknow** [comment]
fixed
