### ISSUE TITLE
Much movie Files Not Working

### ISSUE THREAD

**Issue by BankruptEd** [mrknow/filmkodi#456]
They start off like it's gonna work but just stops after a few seconds without the video ever starting.

**Comment by MoonieK** [comment]
You need to be more specific as no one here is a fortune-teller

**Comment by MoonieK** [comment]
You can say what video or at least the one title. you can say what plugin are you using. 
If its specto you can say what video source you are using. 

Plugins provide loads of diferent kind of sources so how he will know what the problem is.

**Comment by BankruptEd** [comment]
Okay yes that makes sense. I definitely should have stated it's Specto.
Sorry about that. As far as the file, I have had it happen with many, I
don't think the particular file is important here.

**Comment by BankruptEd** [comment]
Anyway, it's not a big issue for me. I will try and be a little more specific in the future.

**Comment by MoonieK** [comment]
Im using it every day and dont have any problems if you will give axample i can check if got the same issue.

**Comment by BankruptEd** [comment]
Well I closed this issue cause I couldn't think of all the specifics that I
should have provided at the time. I will have to get watching some more
shows to check it out and give you more detail. All I can remember is that
it was sources with the much movie tags. And I decided to post it because I
had never had that issue before. Usually I can get one of the first several
sources (and usually higher quality sources) to play. Now I have to go way
down the list for lower quality sources. Still though, I can watch what I
want without too much hassle. I gotta tell ya, the openload pigeon issue is
much more annoying but I think the people in charge are probably well aware
of that one. Let me know if you come up with anything a d I will give you
more detail when I can sometime soon. Thanks for looking into it.

**Comment by BankruptEd** [comment]
Okay, I tried to watch a boardwalk empire episode 2 of season 5. And as usual the first couple choices were MUCHMOVIES/GVIDEO and MUCHMOVIES/VIDEOMEGA. and the first one acted like I said, that it looked like it was gonna start but didn't and the second one said "no source available". And worse, after they failed it went through the next 10 or more sources without any luck on them either. Is there something I should be doing? Like clearing the sources or manually updating the url resolver? And this is Specto I'm talking about for any new people. Let me know if there is something I left out Moonie. Appreciate the help.

**Comment by BankruptEd** [comment]
Sons of Anarchy s5e3 same thing as Empire I believe. MUCHMOVIES/GVIDEO was just skipped over and then MUCHMOVIES/VIDEOMEGA looked like it was gonna play but didn't. It's pretty much been the story for a few other shows too.

**Comment by BankruptEd** [comment]
Seems to be working much better now.
