### ISSUE TITLE
wizja.tv zablowali ip

### ISSUE THREAD

**Issue by Mstenia** [mrknow/filmkodi#459]
Zablokowali mi adres ip, mam wykupione premium do listopada a od soboty 20 08 2016 nie mogę oglądać, pisałem maile żeby mi odblokowali ale zero odzewu. Czy kogoś też tak zrobili??

**Comment by borys76** [comment]
Maja jakis problem ze ich system blokuje ip,pracuja nad tym zeby naprawic

**Comment by borys76** [comment]
chcielibyśmy najmocniej przeprosić za awarie, która miała miejsce w weekend.
Osoby nadające kanały dokonały ostatecznych zmian i wszystko wróciło do normy.
W ramach rekompensaty przesyłamy darmowy kod, który przedłoży ważność pakietu premium o 5 dni.
Dodatkowo, gdyby w dalszym ciągu występować problem to prosimy o przesłanie adresu IP w poprawnej formie, czyli 1.23.456.78.
Jest to niezbędne aby ostatecznie rozwiązać problem. Swój adres IP należny sprawdzić na stronie http://whatismyipaddress.com/

**Comment by rafcik1985** [comment]
a jak przeslac IP bo tez mam taki sam problem
