### ISSUE TITLE
Yoy.tv brak strumieni

### ISSUE THREAD

**Issue by pee111** [mrknow/filmkodi#460]
Wtyczka Know TV dzialala do polowy sierpnia bezblednie. Teraz jednak nie mozna obejrzec wiekszosci kanalow na yoy.tv  przez niezaktualizowane zrodla strumienia.
Na innych urzadzeniach (PC, android) wszystko dziala.
Pracujecie nad tym problemem?
Dzieki!

**Comment by borys76** [comment]
Cytat
" Na innych urzadzeniach (PC, android) wszystko dziala"
To na jakich nie dziala?

**Comment by pee111** [comment]
Nie dziala na Kodi na wtyczce MrKnowTV.
Najnowsza wersja Kodi, wtyczka automatycznie aktualizowana.

**Comment by borys76** [comment]
Na kodi 17 nie dziala 
Na 16.1 wszystko ok

**Comment by marekodfiranek** [comment]
na 16.1 tez bez problemu. 

pee111  zrob sobie reinstal.

**Comment by mrknow** [comment]
U mnie na 17 nie działają streamy rtmp. Działa tylko na 16.1
