### ISSUE TITLE
Brak napisów a niby są

### ISSUE THREAD

**Issue by slawek12** [mrknow/filmkodi#462]
Witam.
na wtyczce filmy online włączam serial Halt & Catch Fire przez alltube.tv(sprawdzone na s02) to się włącza ale bez napisów.
Jak wchodzę przez laptopa na strone www to są odcinki z napisami z serwera vidto.
Z tego co wiem to napisy nie są wbudowane w odcinek i pewnie dlatego nie ładują się przy starcie.
mrknow - możesz to jakoś zmienić aby napisy się ładowały?

**Comment by borys76** [comment]
W wtyczce ustawienia wlancz napisy

**Comment by slawek12** [comment]
W ustawieniach wtyczki nie widzę nic związanego z napisami.
Jak już włączę odcinek to w ustawieniach dźwięku i napisów mam włączone pokazywanie napisów. Poniżej jest: wybierz napisy, ale tam nic nie da się zrobić.

**Comment by xxcriticxx** [comment]
http://kodi.wiki/view/HOW-TO:Set_up_subtitle_services

**Comment by slawek12** [comment]
Mam to ustawione,  specto pobiera samo napisy więc jest dobrze skonfigurowane. W innych serialach czy filmach z alltube napisy wyświetlają się a w tym konkretnym halt...  już nie.

**Comment by slawek12** [comment]
Przez wtyczki mogę pobierać napisy ale interesuje mnie dlaczego poprzez www napisy są od razu i jest zaznaczone że dane źródło jest z napisami a kodi tego nie widzi.

**Comment by xxcriticxx** [comment]
pierwszy stream niema napisow drugi ma ale trzeba przycinac CC na stronie mr know moze zrobic poprawke jak ladnie zapytasz

**Comment by mrknow** [comment]
stare zgłoszenie, zamykam
