### ISSUE TITLE
Missing movie posters

### ISSUE THREAD

**Issue by Mark-Ann** [mrknow/filmkodi#463]
All the TV Show posters are there, but when I look at the movies all I see is the titles with no artwork of any sort. I've tried re-installing both Kodi and Specto but it just comes back the same. It's running on an Amazon Fire TV Box. How do I fix this as I know it's working on other people's boxes, just not mine. I don't think it's Kodi as Exodus is working fine and showing the movie posters, so it's something going on with Specto.

**Comment by BankruptEd** [comment]
Could you have accidentally changed the "view" to "list"? I've done that
before. You know when you go to the left of the screen and a side bar pops
out with some options? You will see "View" at the top.

**Comment by Mark-Ann** [comment]
No, it's definitely in thumbnail mode, it's just the space where the poster/artwork should be is empty leaving just the title at the bottom of the empty space on each movie. It seems to me that Specto is somehow not picking up on the artwork (why I don't know) which is even stranger when you see it working perfectly well for TV Shows, but not Movies. Weird!

**Comment by BankruptEd** [comment]
Ya that is weird. Hopefully it resolves itself. Good luck brother. Have you
tried deleting the thumbnails then restart to repopulate them yet? Probably
won't do anything but if you haven't tried it yet....

**Comment by Mark-Ann** [comment]
How do you delete thumbnails? I thought they came from a separate source.

**Comment by BankruptEd** [comment]
You can delete thumbnails in the Area Wizard in program add-ons

**Comment by BankruptEd** [comment]
Once in ares wizard, go to maintenance

**Comment by Mark-Ann** [comment]
I used Raw Maintenance to remove the thumbnails and although it made them all refresh in Exodus, Specto behaved as it's always done and didn't show any artwork in the Movies section. Thanks for the input though, even if it didn't work. :(

**Comment by BankruptEd** [comment]
Shitty. No problem brother, was worth a shot. Good luck with it. Sounds
like an annoying problem for sure. If I can think of anything else I let
you know

**Comment by Mark-Ann** [comment]
Does MrKnow have any ideas or pointers as to how I might fix this?

**Comment by Mark-Ann** [comment]
You'll no doubt be glad to know I solved the problem. I had to do a factory reset on Amazon Fire TV Box, re-install Kodi 16.1 and then finally re-install Specto-Fork. And damn me if it didn't finally work as expected. Only took wiping the entire device to do it, but I got there! :)

**Comment by BankruptEd** [comment]
I hear ya. Factory resets are always the last resort. Sometimes one simply
has no choice. Glad to hear you're back in action brother. Peace.
