### ISSUE TITLE
wizja tv

### ISSUE THREAD

**Issue by rafcik1985** [mrknow/filmkodi#464]
Witam posiadam konto premium w Wizja.tv. Telewizje ogladam na dekoderze kodi, gdy chce otworzyc Wizja tv wyskakuje mi Inny bląd-Wizja tv. Kiedy otwieram strone w internecie przez kompa wyskakuje mi Error 1006, The owner of this website (wizja.tv) has banned your IP address (79.67.134.199).
 Czy jest to prawdopodobne ze usunieto strone? czy moze jest to jakis blad na dekoderze?
Prosze o odpowiedz jesli jest to mozliwe

**Comment by borys76** [comment]
Napisz email do wizja
Zeby odbanowali ip

**Comment by Arek76** [comment]
dokladnie tak jak kolega napisal napisz maila do nich , choc wiem ze nawet nie da sie maila znalezc wiec Ci podam .pomoc@wizjatv.freshdesk.com napisz tam  a napewno odblokują . pozdrawiam

**Comment by rafcik1985** [comment]
wielkie dzieki juz mi dziala ,zalatwili to bardzo szybko
