### ISSUE TITLE
specto isnt working

### ISSUE THREAD

**Issue by keithsstuff** [mrknow/filmkodi#465]
I tried reinstalling it from  blink Kodi  meaning new kodi frash  and  specto  from http://kodi.filmkodi.com/
it doesn't work is their going to be a fix soon

**Comment by xxcriticxx** [comment]
http://kodi.filmkodi.com/plugin.video.specto/plugin.video.specto-2016.09.01.1.zip

**Comment by keithsstuff** [comment]
I just tried to load it in kodi on windows 10  and from system addons and install from zip it says says failed to install dependency http://kodi.filmkodi.com

**Comment by keithsstuff** [comment]
HOW EVER IT WORKS ON MY IPHONE

**Comment by keithsstuff** [comment]
I'M willing to do a remote session with you right now or say 9:00 pm tomorrow please email me

**Comment by keithsstuff** [comment]
my email is keithsstuff@att.net

**Comment by xxcriticxx** [comment]
download and install specto theme pack as well as url resolver then try zip file

**Comment by keithsstuff** [comment]
specto doesn't work   http;//kodi.filmkodi.com i'm juseing the new bata verision of kodi

**Comment by keithsstuff** [comment]
specto doesn't work   http;//kodi.filmkodi.com i'm juseing the new bata verision of kodi

**Comment by keithsstuff** [comment]
specto doesn't work   http;//kodi.filmkodi.com i'm juseing the new bata verision of kodi

**Comment by keithsstuff** [comment]
specto doesn't work   http;//kodi.filmkodi.com i'm juseing the new bata verision of kodi

**Comment by mrknow** [comment]
install instructions http://filmkodi.com/en/specto-1080p-kodi-add/

**Comment by keithsstuff** [comment]
specto isn't working will maybe one or to movies are working in specto   is their a fix yet

**Comment by BankruptEd** [comment]
I wouldn't hold your breath. MrKnow may never come back. Or he might. No
one knows. He's been MIA for some time now.

**Comment by keithsstuff** [comment]
does any one know when kodi 18 is going out of bata
