### ISSUE TITLE
"Aktualizuj LIBRTMP" na Apple TV 4

### ISSUE THREAD

**Issue by tomabo** [mrknow/filmkodi#47]
Używam wtyczki mrknow na ATV4 i niestety nie działa telewizja. Zakładam, że muszę zaktualizować librtmp. Nie da się tego zrobić, brakuje urządzenia na liście. Wybieram ATV2, ale pojawia się błąd.

**Comment by tomabo** [comment]
Macie pomysł jak rozwiązać ten problem? Poniżej screen z treścią komunikatu

![img_3016](https://cloud.githubusercontent.com/assets/16875554/12637678/632b04a6-c597-11e5-81d1-ff67f223fef3.JPG)

**Comment by mrknow** [comment]
Nie planuję tego naprawiać. Na razie nie mam ATV4, więc nie potrafię tego błędu powtórzyć

**Comment by Adam-po** [comment]
Heh Mam pytanie. Jest możliwość zainstalować Addon lub IPTV z nimieckimi kanałami. Ich nie działają....
