### ISSUE TITLE
yoy.tv not working

### ISSUE THREAD

**Issue by Predator02** [mrknow/filmkodi#471]
Witam,

serwis yoy.tv przestał działać przez wtyczkę MrKnow, lista kanałów jest poprawnie ładowana jednak żaden się nie uruchamia. Serwis działa poprawnie ponieważ przez stronę internetową można oglądać TV.
Czy jest możliwość poprawy serwisu?

**Comment by borys76** [comment]
Cos pozmieniali rano nic nie dzialalo teraz na www dziala ale na wtyczce juz nie

**Comment by quatro7** [comment]
Wiadomo coś kiedy znów zacznie wtyczka działać?

**Comment by kyrioos** [comment]
premium :(

**Comment by kyrioos** [comment]
chyba :(

**Comment by quatro7** [comment]
Ja mam Premium a i tak nie działa

**Comment by borys76** [comment]
Jak mrknow bedzie mial czas to pewnie naprawi
Musicie czekac

**Comment by pee111** [comment]
Niestety 8.9. rano nic nie dzialalo. Poza tym tylko niektore kanaly.
Nie przez wtyczke dziala...

**Comment by kyrioos** [comment]
stronka działa :) w flash'u

**Comment by lubiejazz** [comment]
Yoy.tv również nie działa przez wtyczkę. Używam Konto Premium .
Przez strone działa. Mrknow czekamy :) Wybaw nas :):)

**Comment by lubiejazz** [comment]
Dodam ze przez aplikację na androida APK od YOY.TV Telewizja Działa...

**Comment by quatro7** [comment]
A u mnie nie

**Comment by borys76** [comment]
Quatro7
On mowi o app na android nie kodi

**Comment by mrknow** [comment]
Yoy.tv coś pozmieniał. Ukrywają adres IP serwera rtmp. Jeszcze nie potrafię ko odkodować

**Comment by mrknow** [comment]
ok. Odkodowane

Za max 15 minut puszczę aktualizację

**Comment by mrknow** [comment]
ok Wersja 2016.09.09.1 naprawia ten bład

**Comment by Predator02** [comment]
Wielkie dzięki!

**Comment by borys76** [comment]
Stawiam piwo
