### ISSUE TITLE
pierwsza.tv not working

### ISSUE THREAD

**Issue by lubiejazz** [mrknow/filmkodi#472]
Pierwsza TV nie działa .Lista się wczytuje a kanały nie odpalają ale to problem chyba z nimi coś?
Jak jest u was?
Trochę kicha gdyż yoy.tv tez leży więc nie ma TV :)

**Comment by Predator02** [comment]
Pierwsza leży przez problemy z serwisem - na stronie też nie działa.

**Comment by mrknow** [comment]
- pierwsza.tv - sprawdź na stronie. jeżeli kanał nie działa to we wtyczce też nie będzie
- yoy - poprawione
