### ISSUE TITLE
prośba o dodanie do wtyczki mrknow.pl

### ISSUE THREAD

**Issue by Cerber2000** [mrknow/filmkodi#475]
1) prośba o dodanie do wtyczki mrknow.pl sekcja alltube tv filmy
Pozycji
popularne
Najwyżej oceniane
Rok
Wersja językowa lektor/dubbing/napisy/PL/Eng

2) Teraz jak wchodzimy w alltube filmy jakiś film brakuje opisów filmów o czym jest oraz informacji o roku wersji językowej jak w innych wtyczkach

Proponuję dodanie tytułu w jednym kolorze a pozostałe informację w innym

3) dodanie widoków do wtyczki o mediach/tapeta/miniatura/kolekcja plakatów

4) dodanie oceny filmów np. z filmweb, imdb z możliwością wyboru

5) dodanie oceny filmów poprzez kodi

6) dodanie sortowania filmów najlepiej oceniane wg gatunku i dekady np. horror lata 80-te

9) dodanie zwiastunów fimów jak np. we pluginie Exodus

10)dodanie wyświtlania oceny linków

**Comment by xxcriticxx** [comment]
to wszystko jest w fanfilm aka specto polska

**Comment by Cerber2000** [comment]
Niektóre rzeczy są w fanfilm, ale wtyczka w budowie
Punkty od 4 do 10 brak w fanfilm do tego pkt. 2 jest ale tylko tytuł i rok wersji językowej brak, dopiero w głębszych ustawieniach są

**Comment by xxcriticxx** [comment]
przetestuj trakt.tv

**Comment by mrknow** [comment]
FanFilm jest rozgrzebane i działa w 10% procentach. 
Ale teraz  skupiam się aby poprawić FanFilm i aby działał jak najlepiej
