### ISSUE TITLE
lista do smart iptv

### ISSUE THREAD

**Issue by xxcriticxx** [mrknow/filmkodi#476]
jaka tv ma dostepna liste kanalow co mozna by dodac do smart iptv?

**Comment by borys76** [comment]
1x22portal@gmail.com
Popros o test 
Daja na jeden dzien

**Comment by xxcriticxx** [comment]
sa polskie kanaly?

**Comment by xxcriticxx** [comment]
wyglonda wszystko na made in russia

**Comment by borys76** [comment]
Jest 150 Polskich 
Wszystkich ponad 1000
Jakosc obrazu Super

**Comment by xxcriticxx** [comment]
@borys76 wykupiles to?

**Comment by borys76** [comment]
Tak

**Comment by quatro7** [comment]
Coś więcej w tym temacie?

11.09.2016 01:51 "borys76" <notifications@github.com> napisał(a):

**Comment by borys76** [comment]
Wez test

**Comment by xxcriticxx** [comment]
podaj linka do wykupienia

**Comment by borys76** [comment]
Toz pisalem tylko przez email

**Comment by xxcriticxx** [comment]
gdzies znalazlem ze $10 za misciac
