### ISSUE TITLE
Specto Beta Test

### ISSUE THREAD

**Issue by mrknow** [mrknow/filmkodi#479]
New version Specto:
http://kodi.filmkodi.com/beta/plugin.video.specto/plugin.video.specto-2016.09.11.2.zip

Changelog:
- trakt.tv - full integration (set as watched fixed, add Trakt Manager)
- local library synced with trakt
- now  language is set from kodi settings 

Please test it

**Comment by sekuras** [comment]
Hello. My favourites disappeared after updated to this version. Im using Jarvis in android version.
Thank you.

**Comment by guaitiao** [comment]
Please Add “Documentaries” as Genre in TV Shows and Movies….
