### ISSUE TITLE
Niedziala telewizjada?

### ISSUE THREAD

**Issue by borys76** [mrknow/filmkodi#48]
Zaden kanal niedziala na telewizjada zanim bede kombinowal moze ktos potwierdzic ze dziala?

**Comment by widgetpl** [comment]
potwierdzam, nie działa :/

    15:39:05 T:140695352350656   ERROR: GetDirectory - Error getting plugin://plugin.video.mrknow/?item=project%3dtw%26catcher%3dstreams%26tmp.prior%3d38%26description%3d2014%2btvpolsatfilm%26catid%3d2%26title%3dPolsat%2bFilm%26url%3dhttp%253A%252F%252Fwww.telewizjada.net%252Flive.php%253Fcid%253D36%26videoTitle%3dPolsat%2bFilm%26director%3dTelewizjada%26multibit%3d0%26url.tmp%3d36%26referer%3dhttp%253A%252F%252Fwww.telewizjada.net%252Flive.php%253Fcid%253D36%26definedIn%3dtv%252Ftelewizjada.net.cfg%26tmp.name%3d2014tvpolsatfilm%26url.my%3d%255C%252Ftw%255C%252F2014tvpolsatfilm%255C%252Fplaylist.m3u8%26icon.tmp%3d%255C%252Fmedia%255C%252Fstream%255C%252Fimg%255C%252Fpolsatfilm_big.png%26icon%3dhttp%253A%252F%252Fwww.telewizjada.net%252F%255C%252Fmedia%255C%252Fstream%255C%252Fimg%255C%252Fpolsatfilm_big.png&mode=110
15:39:05 T:140695352350656   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mrknow/?item=project%3dtw%26catcher%3dstreams%26tmp.prior%3d38%26description%3d2014%2btvpolsatfilm%26catid%3d2%26title%3dPolsat%2bFilm%26url%3dhttp%253A%252F%252Fwww.telewizjada.net%252Flive.php%253Fcid%253D36%26videoTitle%3dPolsat%2bFilm%26director%3dTelewizjada%26multibit%3d0%26url.tmp%3d36%26referer%3dhttp%253A%252F%252Fwww.telewizjada.net%252Flive.php%253Fcid%253D36%26definedIn%3dtv%252Ftelewizjada.net.cfg%26tmp.name%3d2014tvpolsatfilm%26url.my%3d%255C%252Ftw%255C%252F2014tvpolsatfilm%255C%252Fplaylist.m3u8%26icon.tmp%3d%255C%252Fmedia%255C%252Fstream%255C%252Fimg%255C%252Fpolsatfilm_big.png%26icon%3dhttp%253A%252F%252Fwww.telewizjada.net%252F%255C%252Fmedia%255C%252Fstream%255C%252Fimg%255C%252Fpolsatfilm_big.png&mode=110) failed
    15:39:06 T:140694552549120   ERROR: CDVDPlayer::OpenInputStream - error opening [{|Cookie=msec=DGPvLs6yZVDxR79zA8Qk6SnODtCJR40%252BNaN9iqRT43UBTegxS20YvNvzrp8NymxYaI%252Fe1kHD844sjYpxCpBBA5Hul6y%252BvNrKljHB;sessid=vmcee0s4305tm7ifg3hre91so4;statid=56ureb4sa07dhq74pkm8o2qrk0]

**Comment by ebot2007** [comment]
potwierdzam nie dziala

**Comment by mrknow** [comment]
Naprawiłem nowa wersja powinna działać poprawnie

**Comment by aplok** [comment]
Niestety dalej nie działa :( . Kręci kółko kręci jakby miało zaskoczyć i nic , wraca.
