### ISSUE TITLE
Lack of HD in tv streaming in mrknow

### ISSUE THREAD

**Issue by saladin10** [mrknow/filmkodi#481]
Can somebody tell me please whether it's a possibility to change the quality of TV streaming from SD to HD for sites like yoy.tv, weeb.tv in Mrknow addon?
I noticed no possibility to reconfigure this in the addon.  No issues when I'm watching directly from websites on PC.

I'm using tv box MXQ pro. 

Any comments are very welcome, thanks.

**Comment by xxcriticxx** [comment]
we never had HD streams it was always SD

**Comment by saladin10** [comment]
Does it mean that mrknow addon never had capability to streaming in HD from websiteslike yoy or weeb?
Can you please clarify? If so how can I stream HD from these websites instead?

**Comment by xxcriticxx** [comment]
you wont be able to. you have to find supplier that will transmit hd signal first and i don't think one exist
