### ISSUE TITLE
Mr.knowTv

### ISSUE THREAD

**Issue by teleman82** [mrknow/filmkodi#482]
Nie wiem czy tylko u mnie czy u innych nie działa poprawnie z yoy.tv Premium. W ogóle nie odpala ...Ale np. eskaGo dziala bez zająknięcia czy videostar.. Wiadomo pierwsza.tv padła chociaż miesiąc temu jeszcze działała(ale to inna para kaloszy ), można by wsunie ją usunąć  z tej wtyczki..

Dodam ze zaktualizowana wtyczka do najnowszej wersji..
Yoy.tv na ich stronie działa..

**Comment by teleman82** [comment]
Dobra okazało się że nie działa na wersji 17. wzwyż ... Powrót do 16.1 pomogło..

**Comment by mrknow** [comment]
Tak nie działa z Kodi 17

**Comment by BankruptEd** [comment]
Mr. Know, I was thinking you might wanna mention somewhere on the add-on
that it's for Polish or Ukrainian speaking folks. All it says is Mr. Know
TV. Sounds pretty English. I was fooled and installed it.. briefly. Just a
thought.
