### ISSUE TITLE
Specto and Exodus outdated content.

### ISSUE THREAD

**Issue by nortonuser** [mrknow/filmkodi#484]
My M8 box is only showing pre 1970 content where all my other android devices work fine.

Done factory resets uninstall and reinstall Specto but all to no avail.

Other addons work fine on the M8 . 

Help would be appreciated.

Thanks nortonuser

**Comment by mrknow** [comment]
http://filmkodi.com/en/kodi-specto-faq/

**Comment by mrknow** [comment]
Q. Specto only gives me movies and shows up to 1970s!!! Why is this happening?
A. You have to set your clock in your tv box. Go to settings, set your correct date and time. On some tv boxes, clock has to be set evertime it is disconnected from power source.

**Comment by nortonuser** [comment]
Many thanks for you help as it solved the problem
