### ISSUE TITLE
Problem z yoy.tv kanały

### ISSUE THREAD

**Issue by patkoooo** [mrknow/filmkodi#485]
Witam,

Sama wtyczka bardzo fajna, niestety nie ściąga z yoy wszystkich kanałów, aktualnie na przeglądarce jest 138, zaś na wtyczce 120 :(

Jakieś rozwiązanie ?

**Comment by mrknow** [comment]
sprawdze to zaraz ...

**Comment by mrknow** [comment]
A wiesz może jakich kanałów brakuje ?

**Comment by patkoooo** [comment]
Kurcze, nie wiem teraz niestety, bo już odesłałem tego boxa do tv.
Ale brakowało około 20, na pewno coś z discovery, chyba tvn-y też.

**Comment by mrknow** [comment]
ok - patrze na tvny i discovery

**Comment by mrknow** [comment]
nie udało mi się namierzyć różnic. Wyczyść cache MrknowTV-> Ustawienia->Wyczyść cache
