### ISSUE TITLE
Specto fork

### ISSUE THREAD

**Issue by megaladon33** [mrknow/filmkodi#486]
Hi there, 
I've been trying to install the new specto fork for my minix system, but no matter what I do it keeps saying "incompatible, dependencies not met. Please contact addon author" 
I'm not anywhere near advanced with operating systems but as far as I can tell everything is up to date. Please help!

**Comment by mageorge** [comment]
Are you try to install specto plugin or the repository.
You mast install the repository to get the dependencies.

Go to http://kodi.filmkodi.com/ and get the repository file.
After install the repository all the dependencies will be ok

**Comment by megaladon33** [comment]
Yes I installed the repository, and that's where I get the error message

**Comment by megaladon33** [comment]
The repository installs fine, but then when I go to install the specto addon it says dependencies not met

**Comment by mrknow** [comment]
http://filmkodi.com/en/specto-1080p-kodi-add/
