### ISSUE TITLE
Specto- Openload links to softcore porn

### ISSUE THREAD

**Issue by vile80r** [mrknow/filmkodi#488]
Suddenly every Openload link plays the same softcore porn film. Openload has been a real issue. First it was pigeons now softcore porn. I had to move Openload so far down the list so it never comes up. I couldn't find a way to just disable it.

**Comment by BankruptEd** [comment]
Ya openload blows more than it works I'm afraid. I can't remember which
source it was, but there is another one that gives you a Rick Astley music
video. I think that's worse than the pigeons. It's painful lol
😨🔫

**Comment by willowz** [comment]
Damn, that really sucks...for all of us.  Thanks for the heads up.

**Comment by BankruptEd** [comment]
Ain't that the truth

**Comment by mrknow** [comment]
It works for me. Give me examples
