### ISSUE TITLE
Telewizja -> i-hqtv.com [NOWY] przestała działac

### ISSUE THREAD

**Issue by hero2017** [mrknow/filmkodi#489]
Pokazuje mi:

**SPORTSDEVIL INFO: "No stream available"**

Kilka dni temu jeszcze działało.

Sprawdzilem na dwóch innych systemach (Kodi na PC i Android). Jestem w Kanadzie.

Szkoda bo najlepsze były te kanały jak chodzi o wiadomości na żywo...ITVN24 lub ITVN.info.

Fajnie jak byśmy mogli tesz oglądac TV Polonia ale nie ma linku do tego.

(Kurde, przestała mi działac polska literka 'c' z kreską.)

**Comment by xxcriticxx** [comment]
oglondaj dalej na stronie http://i-hqtv.com/ dziala bez problemu. jak wpadie mrknow to poprawke zrobi

**Comment by hero2017** [comment]
Tak tylko to nie jest dobre rozwiązanie dla rodziców co się kompletnie nic nie znaja na kompie :-(
Poczekam kiedy MrKnow to naprawi.

Ale wygląda mi na to że to bedzie się często zdażało to by bylo dobrze wiedziec jak ja to mogę sam naprawic.

**Comment by hero2017** [comment]
Druga rzecz to tam i tak nie ma tych kanalow co w spomnialem.

**Comment by mrknow** [comment]
Naprawione w nowej wersji

**Comment by mrknow** [comment]
Wtyczka MrknowTV pozwala na oglądanie telewizji np z Videostara (wystarczy tylko zarejestrować konto)
Sprawdź jeżeli potrzebujesz stabilnej telewizji
http://filmkodi.com/pl/mrknowtv-telewizja-ze-stron-kontami-premium/

**Comment by hero2017** [comment]
Niestety dalej nie działa. Zrobiłem update do wersji 2016.09.17.1 i jak wchodze do i-hqtv [NOWY] pokazuje błąd:

"SportsDevil error: Web request failed."

A jak chodzi o videostar.pl to tesz nie działa bo jest błąd:

"Wystąpił problem: Wybrany kanał jest niedostępny w Twojej lokalizacji"

Również spróbowałem nową opcje w MrKnow (Typer TV) ale tam to żaden kanał nie działa - "No stream available"

**Comment by hero2017** [comment]
Zapomnialem w spomnąc że byłem i dalej jestem zarejestrowany na videostar.pl ale to nie pomaga.

**Comment by Hostile** [comment]
ta stronka padla http://i-hqtv.com/ ? wtyczka dziala ?

**Comment by hero2017** [comment]
Ah no wlasnie. Ta strona padla ale wtyczka dziala jak chodzi o kilka innych kanalow. Szkoda...trudno znalesc teraz te kanaly i zeby dzialaly.
