### ISSUE TITLE
Dodawanie kanałów do ulubionych

### ISSUE THREAD

**Issue by aqwerq** [mrknow/filmkodi#49]
Witam
Próbuje dodać kanały telewizyjne do ulubionych klikając prawym i wciskając ,,Dodaj do ulubionych" ale kanałów nie ma w ulubionych, jest tylko: Add item... 
Może ktoś pomóc ?

**Comment by mrknow** [comment]
Jasne w weekend sprawdzę

**Comment by aqwerq** [comment]
Sprawdzałeś bo u mnie dalej nie działa, na Windowsie (Błąd dodatku Filmy Online) w ogóle się nie włacza a na androidzie dalej nie mam możliwości dodania kanałów.

**Comment by mrknow** [comment]
MrknowTV - tu dziala
