### ISSUE TITLE
Telewizja -> i-hqtv.com [NOWY] dalej nie działa

### ISSUE THREAD

**Issue by hero2017** [mrknow/filmkodi#491]
Niestety dalej nie działa. Zrobiłem update do wersji 2016.09.17.1 i jak wchodze do i-hqtv [NOWY] pokazuje błąd:

"SportsDevil error: Web request failed."

A jak chodzi o videostar.pl to tesz nie działa bo jest błąd:

"Wystąpił problem: Wybrany kanał jest niedostępny w Twojej lokalizacji" - a jestem w Kanadzie i niestety nie mam dostępu do polskiego vpn.

Również spróbowałem nową opcje w MrKnow (Typer TV) ale tam to każdy jeden kanał nie działa - "No stream available"

**Comment by mrknow** [comment]
Zmieniają ciągle coś na stronie. Teraz mają odnośniki do innych stron ze strumieniami

**Comment by hero2017** [comment]
A czy nie mozna jakos dodac te ich linki tak jak np:

http://static.u-pro.fr/vod/static/upro/player/uplayer/107/u-player.html?prot=akamaihd&source=rtmp://50.7.176.132/stream/2411&live=1&chapter=disable&autoplay=0&scrubber=1&play=1&fullscreen=1&volume=1&time=1&bgColor=000000&img=http://tv-live.esy.es/livetv.png&controlColor=66,127,204,0.5&controlGradient=none&leftSliderColor=ffffff&rightSliderColor=427fcc&bufferSliderColor=d4d4d4&timeTextColor=ffffff&durationTextColor=333333&bgTooltipColor=427fcc&textTooltipColor=333333&buttonOverColor=ffffff

lub samo tylko to: rtmp://50.7.176.132/stream/2411

Na kompie urochamiam VLC i otwieram Network Stream: rtmp://50.7.176.132/stream/2411 i wszystko chodzi.

**Comment by mrknow** [comment]
Działa

**Comment by hero2017** [comment]
Dzieki MrKnow!


Widze "poprawione" teraz ale nie da sie wejśc do żadnych nazywając się *Kategoria...Naukowe, Informacyjne itd.*


Tylko pokazuje *Working* i zostawia mnie w głównym menu.


Ale chociasz wszystkie poniżej (TVN24) działają [😊]

________________________________

**Comment by hero2017** [comment]
Wiekszasc wszystko dziala. Jeszcze raz wielkie dzieki. Jak ci mozna titak wyslac prywatny message? Chcial bym ci sie chociasz troche od wdzieczyc.

**Comment by mrknow** [comment]
Tu masz formularz kontaktowy ze mną http://filmkodi.com/pl/kontakt/.
