### ISSUE TITLE
Problem z MR Know Specto

### ISSUE THREAD

**Issue by karol78** [mrknow/filmkodi#494]
Zainstalowałem najnowsze wtyczki MrKnow i Specto. Wchodząc do zasobów np. filmów, pokazuje listy, miniatury, ale po kliknięciu na konkretny link strumienia lub telewizji jest komunikat "Proszę czekać", chwilę "mieli" i nic się nie włącza. Ani filmy, ani telewizja. 
Dla porównania wtyczki anglojęzyczne np. exodus włączają się i działają. 
Co może być przyczyną? 
Z góry dzięki za pomoc.

**Comment by mrknow** [comment]
Zainstluj według instrukcji tutaj. Może brakuje repo i nie może doinstalować zależnych  dodatków
