### ISSUE TITLE
Nieudane połączenie z repozytorium.

### ISSUE THREAD

**Issue by lukaszek1** [mrknow/filmkodi#495]
Witam, posiadam telewizor Philips 55PUS7170/12. Pobrałem kodiego, potem dodaje krok po kroku wtyczkę Mrknow. Wszystko działa do momentu, kiedy wchodzę w zakładkę zainstaluj z repozytorium. Klikam Filmkodi.com.. po czym wyskakuje komunikat ,,Nieudane połączenie z repozytorium". Wcześniej kodi działał normalnie. Problem zaczął się ok 3 miesięcy temu. Co mogę zrobić, żeby to naprawić?

**Comment by mrknow** [comment]
Zainstaluj jeszcze raz według instrukcji tutaj 
http://filmkodi.com/pl/wtyczka-filmy-online-mrknow/

Może problemem było cloudflare. Teraz wyłączyłem cloudflare
