### ISSUE TITLE
project radio

### ISSUE THREAD

**Issue by xxcriticxx** [mrknow/filmkodi#496]
mr know jak tam project radio?

**Comment by BankruptEd** [comment]
What Jak tam radio all about? It's an add-on?

**Comment by xxcriticxx** [comment]
old project that was going link up radio stations

**Comment by BankruptEd** [comment]
Sounds cool, or would have been cool.

**Comment by mrknow** [comment]
Nie mam czasu na  kolejny projekt,  niestety. / I do not have time for another project, unfortunately.
