### ISSUE TITLE
automatyczne uruchamianie Yoy.tv

### ISSUE THREAD

**Issue by quatro7** [mrknow/filmkodi#497]
jak powinien wyglądać plik autoexec.py by po uruchomieniu KODI automatycznie uruchamiało się Yoy.tv?

**Comment by mrknow** [comment]
Na razie nie udało mi sie uruchomić yoy, ale można automatycznie uruchomić wtyczkę

Plik .kodi/userdata/autoexec.py
u mnie wygląda tak

```
import xbmc
xbmc.executebuiltin("RunAddon(plugin.video.mrknowtv)")
```
