### ISSUE TITLE
SD Hosts Missing

### ISSUE THREAD

**Issue by wolf01d** [mrknow/filmkodi#498]
After the latest update of specto 2016.09.20.2 the SD Hosts tab is missing from the settings menu.
So now when i try to watch a tv series or movie there are only HD streams available.
I use LQ streams all the time, will this be restored soon.

**Comment by bjgood** [comment]
Yeah, I've noticed that too. What do we do now?

**Comment by ikolinahr** [comment]
Yes, I am seeing this too. In fact I exclusively use MQ or LQ, so I am dead in the water right now. I hope this will get fixed very soon.

**Comment by targetindex** [comment]
Same here.  I watch a lot of older shows 90s- early 2000s, most of which only work with MQ and LQ links.  Right now it's not showing any sources for most of my shows since they are all MQ.  I'm sure he knows about it and is hopefully working on a fix.  :) 

BTW...  Thx for all the hard work you put in for all of us to enjoy our watching! Best kodi addon out there!

**Comment by BankruptEd** [comment]
Hi targetindex. Do you ever try to watch older content and get completely
different shows than what it's supposed to be? I run into that alot. I find
Kodi can be frustrating for older content.

I also appreciate the work you do Mr. Know. I've checked out all kinds of
add-ons now and I always come back to Specto. It's my mainstay.

**Comment by dax7** [comment]
I too am seeing this problem, it's been removed from settings completely!....makes the program unusable for me because of my limited bandwidth
Would very much appreciate if you could add SD/MD playback back


Very much appreciate the work on this fork

**Comment by bjgood** [comment]
Just switch to an older version for the time being. Disable the repo so it will not auto update to the 2016.09.20.2 version.

I'm sure Mr. Know knows about it.

**Comment by dax7** [comment]
Think I'll just wait for the update, don't want to have to reset all my favorites again

**Comment by BankruptEd** [comment]
Ya, it's a big problem for us high bandwidth users too. It chops off a huge
chunk of possible shows to watch. Anything older and not super popular is
now unavailable. I was going through my favorites and there are all kinds
of shows I can't get working sources for now.

**Comment by mrknow** [comment]
Hi 
This change in Specto was not planned so quickly. I had to update the add-on mrknow url resolver and solve the problem of openload .
Now  SD hosts should be visible. Check the version 2016.09.24.1

**Comment by dax7** [comment]
Thank you mrknow, much appreciated!

Very appreciative of all your hard work mate :)

**Comment by BankruptEd** [comment]
Fix just came through about 12:40am in Canada. Back in business.Thanks Mr.
Know.

**Comment by bjgood** [comment]
SD Hosts is still not showing in the latest version (2016.09.24.1), at least for me. Is it showing for the everyone else? I do not know why it is not.

Best regards, Mr. Know.

Bob

**Comment by BankruptEd** [comment]
I'm not sure how it is for everyone, but the update that fixed it for me is
update number two dated for the 20th -2016.09.20.1. I have two that look
like that and it was the second one that has hosts fix. I'm curious, on the
update you have does it say "sd hosts are now working"? If it doesn't say
that then you are still awaiting the update with hosts fix.

**Comment by bjgood** [comment]
Yeah, it says that. I have the latest update 2016.09.24.1.

2016.09.20.1
    fix - wsonline
    fix - sd hosts now are showing

was the last Changelog entry.

Later...

**Comment by BankruptEd** [comment]
Ya then that's what I have as well. Did you restart your device? Anyway,
hope you get it sorted out

**Comment by bjgood** [comment]
Thanks. Other than SD Hosts not showing it seems to work fine. In Mr Know's urlresolver you can open its config setting and prioritize the resolvers to your liking. All were set to priority 100 but if you lower that number (starting at 10 for my first preferred resolver, in my case, then 15 for my second, 20 for my third, and so forth, up through 99), then urlresolver will check those in that order. Like I said, it seems to be working in that manner.

Later...

**Comment by mrknow** [comment]
Limit video quality in settings 
http://filmkodi.com/en/specto-limit-video-quality/
