### ISSUE TITLE
Dodanie do FanFilm

### ISSUE THREAD

**Issue by Seico** [mrknow/filmkodi#499]
Czy można dodać do wtyczki FanFilm stronki z filmami HD  : http://segos.es

**Comment by mrknow** [comment]
Planuje w przyszły weekend poprawić działanie wtyczki, tj 2-10-2016.

**Comment by Seico** [comment]
Dzieki za dodanie "segos" , ale jest mały problem, chyba "Fan film" nie obsługuje hosta http://greevid.com , po wyszukaniu filmu i kliknięciu w źródło greevid.com wyskakuje błąd , druga sprawa na segos sa filmy mają po kilka źródeł danego filmu , a jak w "Fan film" wyszukuje film to pokazuje tylko jedno źródło a reszty nie , jest szanasa na poprawienie tych błędów ?

**Comment by mrknow** [comment]
Próbowałem, ale to za dużo. Nie będzie polskiej wersji specto. Wycofuje się z tego projektu ze względu na brak czasu. Fan Film zostanie skasowane
