### ISSUE TITLE
Wtyczka juz dziala na androidzie :)

### ISSUE THREAD

**Issue by gumball1** [mrknow/filmkodi#5]
v2015.11.29 nie dziala na androidzie jak poprzednia wersja.

**Comment by xxcriticxx** [comment]
v2015.11.28.1 nie dziala na minix x8h

**Comment by adaski8** [comment]
Potwierdzam  2015.11.29 nie daje sie uruchomic na androidzie.

**Comment by adaski8** [comment]
Link do  kodi.log: http://xbmclogs.com/prdcc78wz  moze cos pomoze bo po aktualizacji dalej nie odpala

**Comment by aniadanieln** [comment]
u mnie też nie działa na androidzie po aktualizacji

**Comment by ip5d** [comment]
Hej ;) w default.py widze ptv2 = xbmcaddon.Addon('script.module.xbmcfilm')

Upewnijcie sie ze na andku jest zainstalowany modul xbmcfilm.

Pozdrawiam

**Comment by xxcriticxx** [comment]
xbmcfilm to jest ten drugi plugin do xbmcfilm.com

**Comment by ip5d** [comment]
Tak, zainstalowac z Kodi filmkodi.com repository -> Wtyczki video -> xbmcfilm.com. I powinno smigac. Chociaz moge sie mylic bo o pythonie mam mgliste pojecie ;)

**Comment by adaski8** [comment]
Xbmcfilm.com mam zainstalowane od poczatku  i dalej wtyczka mrknow nie dziala. A jak kolega nie sprawdzil niech nie podaje info.

**Comment by gumball1** [comment]
modul jest instalowany razem z wtyczka i aktualizowany za kazdym razem jak wyjdzie update, takze nie w tym problem

**Comment by ip5d** [comment]
Sprawdziem wczoraj na androidzie i ze smutkiem musze przyznac ze nie dziala

**Comment by adaski8** [comment]
Zostaje tylko czekac az autor zrobi fixa.

**Comment by ip5d** [comment]
Zeby nie bylo, ze znowu podaje niesprawdzona informacje. Jestem w pracy i nie mam jak sprawdzic.

ale w 

```
\Kodi\addons\script.module.xbmcfilm\lib\
```
znajduje sie pliczek

```
parser.py
```

moze mu ktos zmienic nazwe na **parser.py.bak** i sprawdzic czy wtedy wtyczka ruszy.

**Comment by widgetpl** [comment]
niestety to samo:

    16:54:39 T:q  NOTICE: -->Python Interpreter Initialized<--
    16:54:40 T:2079182928  NOTICE: ('pluginDataDir', u'/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/script.module.xbmcfilm/')
    16:54:41 T:2079182928  NOTICE: [xbmcfilm.com  1] Filmy online www.mrknow.pl
    16:54:41 T:2079182928  NOTICE: Cache directory purged
    16:54:41 T:2079182928   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                            - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                           Error Type: <type 'exceptions.AttributeError'>
                                           Error Contents: 'Parser' object has no attribute 'getParams'
                                           Traceback (most recent call last):
                                             File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mrknow/default.py", line 864, in <module>
                                               init.showListOptions(sys.argv)
                                             File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mrknow/default.py", line 189, in showListOptions
                                               params = self.parser.getParams()
                                           AttributeError: 'Parser' object has no attribute 'getParams'
                                           -->End of Python script error report<--
    16:54:41 T:1902422784   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.mrknow/
    16:54:41 T:1902422784   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mrknow/) failed
    16:54:41 T:2121945232  NOTICE: Thread BackgroundLoader start, auto delete: false
    16:54:43 T:2116155304  NOTICE: Thread Timer start, auto delete: false

**Comment by ip5d** [comment]
Ok, wieczorkiem jak bede w domku to sprawadze na Androidzie i dam znac.

**Comment by aniadanieln** [comment]
DZIAŁA!!!
Po zmianie nazwy na parser.py.bak oraz parser.pyo.bak wtyczka zaczęła działać.
Dzieki. 
Tylko zastanawia mnie do czego był ten plik bo jest też parser2.py?
Ma ktoś może sposób na te librtmp na androida z ARM7 bo próbowałem już podmianę różnych librtmp.so i KODI nie chce się odpalić.

**Comment by adaski8** [comment]
Po zmianie nazw w obu pliczkach wtyczka odpala  
I chodzi bez problemu. Dzieki kolego ip5d. :)

**Comment by widgetpl** [comment]
potwierdzam. Poniżej to co znalazłem:

    plugin.video.mrknow/default.py:from parser2 import Parser2, ParsingResult
    plugin.video.mrknow/default.py:        import mrknow_pLog, settings, Parser, mrknow_pCommon
    plugin.video.mrknow/default.py:        self.parser = Parser.Parser()
    plugin.video.mrknow/default.py:        self.parser2 = Parser2()
    plugin.video.mrknow/default.py:        params = self.parser.getParams(

**Comment by adaski8** [comment]
Wyglada ze nic nie przestalo dzialac. A po tym co kolega podal jest uzywany parser2.

**Comment by ip5d** [comment]
Juz tlumacze, moge sie mylic bo o ile zarabiam na zycie programowaniem to jednak o pythonie mam zerowe pojecie.

```
http://filmkodi.com/repository/plugin.video.mrknow/resources/lib/
```
jest **Parser.py**

a w nim classa **Parser** z **getParam** ktorej wlasnie wtyczka potrzebuje

natomiast w 
```
http://filmkodi.com/repository/script.module.xbmcfilm/lib/
```
 znajduje sie tez **parser.py**  ale classa **Parser** niz jak ma sie tego co wtyczka probuje robic ;)
 
chodzi o ten fragment 

```python
def showListOptions(self,argv=None):
        params = self.parser.getParams()
        mode = self.parser.getIntParam(params, "mode")
        name = self.parser.getParam(params, "name")
        service = self.parser.getParam(params, "service")
```

Ciekawosta jest to ze pod Windowsem dzialalo. Wiec przychodzi mi to glowy ze wymienione pliki sa ladowane w innej kolejnosci pod Androidem i pod Windowsem i wtedy klasa nie jest nadpisywana :wink:

**Comment by gumball1** [comment]
@aniadanieln gitara ! thx

**Comment by kstrzelec** [comment]
Witajcie,
Jestem zupełny świeżak, google mnie tu przyprowadziło.
Mam na win8.1 ver 2015.11.29.2 i działa
na sony x3 compact android mam 2015.11.14 i działa
ale od wczoraj mam mediaboxa stb fbox3tv android 4.4 i nie działa. 
powiedzcie łopatologicznie zielonemu co zrobić, żeby ruszyło... plizz

**Comment by adaski8** [comment]
Kolego pare postow wyzej masz rozwiazanie

**Comment by kstrzelec** [comment]
Chyba za mało wiem nt androida i kodi. Potrzebuję bardziej łopatologicznie.
Parser.Py to plik w systemie plików androida? W jakim katalogu? Nie mogę go
znaleźć ani na telefonie,  ani na fbox...
1 gru 2015 8:25 PM "adaski8" <notifications@github.com> napisał(a):

**Comment by adaski8** [comment]
Plik na telefonie to w katalogu android/data/org.xbmc.kodi/files/kodi/addons/script.module.xbmcfilm/lib i tam masz te pliczki

**Comment by adaski8** [comment]
Polecam total comandera na androida do zarzadzania plikami

**Comment by kstrzelec** [comment]
android/data/org.xbmc.kodi/files  i .... kurde, trzeba było włączyć widoczność ukrytych plików
zaraz patrzę dalej. Tylko dziecko umyję :-D
dzięki na razie

**Comment by aniadanieln** [comment]
Zapytam jeszcze raz. Czy istnieje librtmp.so na androida z ARM7? Czy udało się komuś go zaktualizować? Dzięki za odpowiedzi.

**Comment by adaski8** [comment]
librtmp.so jest i owszem ale po co aktualizowac prosze o wyjasnienie

**Comment by xxcriticxx** [comment]
na nowe kanaly tv

**Comment by kstrzelec** [comment]
No to potwierdzam, że po zmianie nazw-rozszerzeń u mnie na fbox3tv też wtyczka ruszyła.
Bardzo dziękuję za pomoc.
Idę do działu donate :-)

**Comment by adaski8** [comment]
Ok link do plikow http://filmkodi.com/repository/librtmp/Android/ARM/XBMC-Gotham-13/

**Comment by adaski8** [comment]
http://www.mediafire.com/?owc5jchm51nrba1

**Comment by adaski8** [comment]
Miejsce gdzie podmienic plik lub jesli go brak to wrzicic                                                                 Android: /data/data/org.xbmc.kodi/lib/librtmp.so  
Oczywiscie wymagany root urzadzenia by miec dostep do plikow

**Comment by aniadanieln** [comment]
Dzięki. Roota mam. Sprawdzę i dam znać czy działa.

**Comment by adaski8** [comment]
Ok. Nowszy jest ten z mediafire

**Comment by xxcriticxx** [comment]
jest jakis sposób zeby to wgrac na minix 8h?

**Comment by widgetpl** [comment]
Jeśli dobrze przeszukałem google-a to jest na nim android.
Zatem wystarczy samo adb i będzie to wyglądać mniej więcej tak:

    adb connect <adres_ip_minix>

tutaj powinno Ci wyskoczyć coś w stylu:

    successed

potem tylko:

    adb install /sciezka/do/kodi.apk

chwilę to zajmuje, ale ostatecznie dostajesz również potwierdzenie o pozytywnym zainstalowaniu.

UWAGA: musisz włączyć debugowanie usb oraz instalację z nieznanych źródeł na androidzie.
Mam nadzieję że Ci się uda.
pzdr

**Comment by xxcriticxx** [comment]
jak mam otworzyć konsole na androidzie?

**Comment by xxcriticxx** [comment]
potrzebny do tego root?

znalazlem jakis how to

http://www.howtogeek.com/125769/how-to-install-and-use-abd-the-android-debug-bridge-utility/

**Comment by widgetpl** [comment]
Musisz ściągnąć sdk, najlepiej od googl-a:

http://developer.android.com/sdk/index.html#Other

i całą resztę wykonujesz na kompie. Nic nie robisz na minix.
Jedyne co musisz zrobić na minix to włączyć debugowanie usb i instalację z nieznanych źródeł.

**Comment by newjimmie** [comment]
Witam! mam problem co do zmiany nazw plików parser.py, wchodze w sciezke plikow (mam zrootowane urzadzenie android tv cs918 4.4 kodi 15.2) android/data/data/org.xbmc.kodi/files i tam nie ma nic (mam włączoną widocznosc plikow ukrytych) dałem nawet opcje szukaj na cały ten folder i wpisałem parser ale nic nie znalazło, zupełnie nie wiem jak mam znaleźć te pliki, z góry dzięki za pomoc

**Comment by ip5d** [comment]
```
Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.xbmcfilm/lib/
```

jakos tak, pisze z pamieci

**Comment by newjimmie** [comment]
tak jak pisałem w folderze files nie ma zadnych plikow, ewentualnie wszedłem Android/data/org.xbmc.kodi/cache/apk/assets/ i tam jest folder addons ale to chyba nie to a w folderze files nie ma nic, nie wiem moze mam jakąs złą wersje kodi (15.2) moze musze sciagnac 14.2 albo 16 ?

**Comment by adaski8** [comment]
android/data/org.xbmc.kodi/files/kodi/addons/script.module.xbmcfilm/lib to jest dokladna sciezka

**Comment by adaski8** [comment]
Prosze zaintalowac sobie total comandera  i w nim wejsc do podanej lokalizacji

**Comment by newjimmie** [comment]
Dzięki chłopaki już dałem rade, nie chodziło tu o comandera tylko musiałem najpierw wejsc w folder sd card (co było dla mnie dziwne bo nie mam w swoim tv box-ie,karty sd!) ale po wejsciu w sd card cała w/w ściezka juz sie zgadza, dzieki wszystkim za pomoc, tak jak wczesniej wszyscy pisali dopisałem końcówki i wtyczka działa.

**Comment by ip5d** [comment]
No to wolamy @mrknow :wink:

**Comment by adaski8** [comment]
Tak zapomnialem dopisac ze nazwa partycji uzytkowej na androidzie jest widziana jako sdcard

**Comment by gumball1** [comment]
ta podmiana nic wam nie da po restarcie wroci do oryginalu

**Comment by adaski8** [comment]
Do kolegi gumball1 poczytaj zanim zaczniesz pisac ze nic nie da http://kodi.wiki/view/HOW-TO:Update_librtmp

**Comment by gumball1** [comment]
@adaski8 post nr91:
http://forum.kodi.tv/showthread.php?tid=162307&pid=1407758#pid1407758

**Comment by adaski8** [comment]
Owszem tak bylo w wczesniejszych wersjach kodi obecnie uzywam 16 beta3 przed podmiana plik mial wage 1.5mb a podmieniany 1.4 mb  .uruchamiane juz ze setki razy i waga pliku ta sama 1.4 mb z data podmiany ta sama

**Comment by gumball1** [comment]
Oczywiscie piszac uruchamianie miales na mysli restart urzadzenia nie kodi ?

**Comment by adaski8** [comment]
Wlaczanie i wylaczanie kodi oraz urzadzenia

**Comment by mrknow** [comment]
Działa, zamykam
