### ISSUE TITLE
Buforowanie problem

### ISSUE THREAD

**Issue by amgloclg** [mrknow/filmkodi#50]
Cześć.
Mam problem oglądam telewizje przeważnie wieczorem i co kilka minut przerywa obraz i buforuje na górze widać procenty buforowania, jak skończy buforowac to się przez chwile przewija bez głosu, czy to może być wina za wolnego internetu czy sprzętu. Mam prędkość 10 Mb/s. Modem: TD-W8960N, Android Tv:M8S+ taki jak ten: http://allegro.pl/show_item.php?item=5887226996 telewizor LG 42 cali. Android tv jest w odległości około 10 metrów od modemu i ma około 75-80% zasięgu.

**Comment by mrknow** [comment]
spróbuj innych serwisów telewizyjnych, np TyperTV, lub VidTV. Daj informację czy na wszystkich serwisach masz buforowanie. Telewizjada jest strasznie obciążona wieczorami

**Comment by amgloclg** [comment]
Dzisiaj jest wszystko w porządku na wszystkich serwerach, na telewizjadzie też. Może przez kilka dni dużo ludzi oglądało mecze piłki ręcznej i wszystkie serwery się mi zacinały. Dzięki za odpowiedź
