### ISSUE TITLE
specto is becoming a cluster f*ck

### ISSUE THREAD

**Issue by vile80r** [mrknow/filmkodi#501]
What is going on with this Add-on lately? Every update creates more issues than it fixes. I've had to reauthorize Specto in Trakt after the last three updates. The TV watchlists are importing all wrong now. Its a disaster. 

TEST YOUR UPDATES BECOFE YOU RELEASE THEM TO US.

**Comment by bjgood** [comment]
First of all, why don't you watch your language, pal.

Second, I'm sure Mr. Know is doing the best he can, so, show some appreciation.

Third, Trakt is working just fine for me.

Later...

**Comment by vile80r** [comment]
I censored my language, Pal. So fuck off!
