### ISSUE TITLE
Brak dostepnego strumienia danych - Videostar

### ISSUE THREAD

**Issue by Kaajav** [mrknow/filmkodi#502]
Hej! 

Przepraszam z gory za brak polskich znakow - mieszkam za granica i mam jezyk szwecji automatyczny a niestety nie umiem zmienic klawiatury.

Mam problem z wtyczka Videostar.pl. Zainstalowalama na Android TV Kodi i wtyczke MrKnowTV, nastepnie wpisalam dane konta na Videostar.pl ale niestety zaden z kanalow nie dziala i wyswietla sie jedynie komunikat "brak dostepnego strumienia danych". Zrobilam aktualizjace i dalej to samo. 
Jaki moze byc powod i jak moglabym to rozwiazac?

Pozdrawiam, 
Kaja

**Comment by borys76** [comment]
Blokada regionalna, jak jestes za granica musisz uzyc VPN I ustawic lokalizacje na Polske

**Comment by Kaajav** [comment]
Nawet w Kodi? Czy da sie takie VPN zablokowac w telewizorze z androidem?
Dziekuje za odpowiedz!

2016-09-27 13:54 GMT+02:00 borys76 <notifications@github.com>:

**Comment by borys76** [comment]
VPN musisz zainstalowac nie blokowac

**Comment by borys76** [comment]
Nie dlugo wszystko I tak bedzie p2p ruscy tak tv juz dawno ogladaja tak samo dziala Hola

**Comment by borys76** [comment]
a VPN moze se wziasc jaki chce

**Comment by xxcriticxx** [comment]
@borys76 jakie rekomendacje?

**Comment by borys76** [comment]
Ipvanish

**Comment by mrknow** [comment]
spróbuje dodać obsługę bezpłatnych serwerów proxy. 
W ten lub przyszły weekend. To powinno rozwiązać te problemy

**Comment by Kaajav** [comment]
Dziękuje za odpowiedzi. Spróbuje poczutac i to rozwiązać bo, powiem szczerze, ze brzmi to dla mnie trochę jak czarna magia. W każdym razie, Kodi używamy na telewizorze i to chyba jest największy problem, bo nie wszystko da sie zainstalować.. jak na przykład ipvanish. Dziękuje jednak za pomoc!

**Comment by xxcriticxx** [comment]
ip zmienisz w tv albo ip zmienisz na router na ip z ipvanish

**Comment by mrknow** [comment]
Dobra 
Dodałem jako opcję proxy, zweryfikuj czy działa. Tutaj instrukcję jak ustawić 
http://filmkodi.com/pl/videostar-nowa-opcja-polskie-proxy/

**Comment by Kaajav** [comment]
O! Bardzo dziękuje! Jutro sprawdzę i dam znać! Jeszcze raz dziękuje!

Skickat från min iPhone

**Comment by Kaajav** [comment]
Filmik instruktażowy zniknął czy to tylko u mnie?

Skickat från min iPhone

**Comment by mrknow** [comment]
Tutaj film https://www.youtube.com/watch?v=Q9NgYQPGwRg

**Comment by mrknow** [comment]
Film na youtube https://www.youtube.com/watch?v=Q9NgYQPGwRg

**Comment by Kaajav** [comment]
Probuje różne proxy ale działa tylko na pierwszym z listy ale wybrane kanały. Większość, takich jak Polsat i TVP, nie działa..

Skickat från min iPhone
