### ISSUE TITLE
Ipla 

### ISSUE THREAD

**Issue by Arek76** [mrknow/filmkodi#504]
witaj Know moze udalo by Ci sie zamiescic Iple w swoim repo ? 
pozdrawiam Cie serdecznie i dzieki za dobra robote

**Comment by mrknow** [comment]
@Arek76, czy ty mówisz o telewizji z ipla ?

**Comment by xxcriticxx** [comment]
http://www.ipla.tv/start

**Comment by mrknow** [comment]
Ipla jako telewizja zrobiona. Czy o to chodziło ?
