### ISSUE TITLE
SPECTO Incompatible

### ISSUE THREAD

**Issue by Escobar9** [mrknow/filmkodi#505]
Hello, i need assistance. My specto is incompatible. When I select it, the only thing highlighted is Change Log. I cant install or configure and it says dependencies not met. any thoughts how i can make it compatible

**Comment by xxcriticxx** [comment]
install from repository not from the plugin zip

**Comment by Escobar9** [comment]
i tried that but it says dependencies not met. Specto says incompatible. I cant even install it or update or configure. What do I do in order to get those areas highlighted so I can then try again and install from repository

**Comment by xxcriticxx** [comment]
kodi 16 or 17? and what os?
