### ISSUE TITLE
myfavourites is not show up 

### ISSUE THREAD

**Issue by bloodydom666** [mrknow/filmkodi#507]
favourites not show up
look like bug in plugin.video.specto-2016.09.01.1\plugin.video.specto\resources\lib\indexers\tvshow.py and movies.py that is why myspecto is show up blank.

**Comment by bloodydom666** [comment]
did find quick fix that was to use old indexers file of tvshow.py and movies.py.
need fix memory leak because error exceptions return null for list favouritestvshow

**Comment by mrknow** [comment]
update to latest version, and restore  manually favorites movies
