### ISSUE TITLE
MrKnowTV - Kodi 17 beta 3 - weeb.tv nie działa.

### ISSUE THREAD

**Issue by rafsko1** [mrknow/filmkodi#508]
Czy byłaby możliwość zaktualizowania wtyczki a konkretniej weebtv by mogła działać z Kodi 17 beta 3?

**Comment by mrknow** [comment]
sprawdze ...

**Comment by mrknow** [comment]
a napisz mi tylko czy o jakim systemie mowa Windows/Mac/Linux/Android ?

**Comment by mrknow** [comment]
Dobra 
W wersji beta nie działa rtmp. Tu info

będzie działać w finalnej wersji tu masz info http://forum.kodi.tv/showthread.php?tid=282158
