### ISSUE TITLE
itivi z mr know tv

### ISSUE THREAD

**Issue by marekodfiranek** [mrknow/filmkodi#509]
hey, czy itivi powroci do mr know tv.
Ucieszylem sie jak to zobaczylem w mr know tv a teraz przy ostatniej aktualizacji zniknelo: (.
Wykupilem na 90dni bo itivi bardzo stabilnie umnie dziala...

Czy itivi wroci do nas?

**Comment by mrknow** [comment]
Nie wiedziałem że ktoś korzysta. Zaraz przyrócę ...

**Comment by marekodfiranek** [comment]
Czekan z uteskniemy ...I proszę by juz zostal z nami na zawsze:)

**Comment by mrknow** [comment]
no przywróciłem, ale nie polecam tej strony. Często coś nie działa ...
