### ISSUE TITLE
Telewizjada nie działa dalej

### ISSUE THREAD

**Issue by aplok** [mrknow/filmkodi#51]
Niestety chyba jest jakiś problem od wczoraj. Telewizjada nie działa na Android .
Jak się wybierze odpowiedni program to próbuje i powraca do listy programów.

**Comment by mazukin** [comment]
Wczoraj wieczorem mrknow wypuścił poprawioną wersję, próbowałeś przeinstalować?

**Comment by borys76** [comment]
Dziala po najnowszym update

**Comment by mrknow** [comment]
Tak. Tylko jeszcze nie zauważyłem że brakuje kilku kanałów, jeżeli włączony jest filtr filmów dla dorosłych. Kanały których brakuje to 
TVN24 Biznes i Świat
TV Republika
 Super Stacja
 TV6
 Canal+ Seriale
 FilmBox Premium
 13 Ulica
 Sci Fi
 TNT
 Universal Channel
 Extreme Sports
 Boomerang Central
 National Geopraphic Polska
 ATM Rozrywka
 Comedy Central
 comedy Central Family
 Polsat Viasat Explore
 Polsat Viasat History
 Polsat Viasat Nature
 TTV

**Comment by mrknow** [comment]
Wgrałem wersję 2016.01.28.1. Problem powinien byc rozwiązany. U mnie po wstępnych testach działa

**Comment by Adam-po** [comment]
Nic nie dziala....
