### ISSUE TITLE
Logchanger keep pop out

### ISSUE THREAD

**Issue by tdcompuservices** [mrknow/filmkodi#510]
Specto 10.4.1 had an issue, the log changer keep pop out when click to open movies 
And the logchanger continues pop, pop and pop......
Tried on: kodi 15.2, 16.1
 M8, M8n, M8s, M8s+ , Android Samsung table & smartphone.....

**Comment by mrknow** [comment]
I will check this

**Comment by mrknow** [comment]
Can you put  a video to show me  this problem
