### ISSUE TITLE
Brak filmów - Kodi Apple TV 2

### ISSUE THREAD

**Issue by cskamper** [mrknow/filmkodi#511]
Mam problem z odtwarzaniem filmów we wtyczce **FanFilm - MrKnow**. Otórz po wybraniu jakiegokolwiek filmu pojawia się informacja: "Brak dostęponego strumienia danych" i nic sie nie laduje... co to moze oznaczac?

**Comment by mrknow** [comment]
Sprawdzę w ten weekend

**Comment by mrknow** [comment]
Powinno działać.
