### ISSUE TITLE
adblock why?

### ISSUE THREAD

**Issue by xxcriticxx** [mrknow/filmkodi#513]
Adblocker detected! Please consider reading this notice.

We've detected that you are using AdBlock Plus ore some other adblocking software which is preventing the page from fully loading.

We need money to operate the site, and almost all of it comes from our online advertising.

Please add filmkodi.com to your ad blocking whitelist or disable your adblocking software.

**Comment by BankruptEd** [comment]
If that's true, it's a part is some other app cause I didn't install
anything. I have no programs dealing with add blocking specifically. I
would certainly exempt you if I knew how to go about it.
