### ISSUE TITLE
Favorites missing

### ISSUE THREAD

**Issue by soltje** [mrknow/filmkodi#514]
Hi, once I updated specto I lost all my favourite tvshows. They are just gone bc when I try to add a new favorite i dont need to remove it first. Now I already tried to get specto on the version before version 2016.10.06.2 but that ain't working. I really could use some help bc I don't want to favourite my 100+ series again.

**Comment by bloodydom666** [comment]
there bug in indexer when come to read sqlite leak memory.
temp fix is download 2016.10.06.2 and 2016.09.01.1.zip from http://kodi.filmkodi.com/plugin.video.specto/  and copy  tvshows.py from plugin.video.specto-2016.09.01.1\plugin.video.specto\resources\lib\indexers and paste in zip 2016.10.06.2\plugin.video.specto\resources\lib\indexers.
and in kodi install addon from zip.
one more thing you may lose text when pause

**Comment by troulla** [comment]
How do you do all that?

**Comment by mrknow** [comment]
fixed.
