### ISSUE TITLE
MrKnowTV WizjaTV - Kodi 17 beta

### ISSUE THREAD

**Issue by xanaxor** [mrknow/filmkodi#515]
Witam, posiadam problem z wtyczką MrKnownTV, konkretnie problem z WizjaTV, opłacone konto premium. Odpalam wtyczkę, widzę listę kanałów, aczkolwiek jak próbuję któryś włączyć to widzę " MrknowTV: uruchamianie Wizja TV, proszę czekać" i nic więcej się nie dzieje. Dodam, że na stabilnej wersji Kodi 16 działa wszystko jak należy, gdyż na komputerze mam zainstalowane dwie wersje programu. Nie jest to także związane z blokadą IP, gdyż tak jak mówiłem na Kodi 16  działa, jak i przez przeglądarkę. Czekam na jakieś rozwiązanie, gdyż nie chciałbym wracać już do Kodi 16, a nie ukrywam, że korzystam z tej wtyczki dosyć często więc uciążliwy problem dla Mnie.

**Comment by mrknow** [comment]
#508 

W wersji kodi 17  beta nie działa rtmp. Będzie działać w finalnej wersji tu masz info http://forum.kodi.tv/showthread.php?tid=282158
