### ISSUE TITLE
Looknij.in (Not Supported python version 2.6.5 Minimum 2.7.9)

### ISSUE THREAD

**Issue by marekodfiranek** [mrknow/filmkodi#517]
Witam,
Przy wyborze Looknij.in wyskakuje kommunikat :  Not Supported python version 2.6.5 Minimum 2.7.9
Co powoduje ze nie da sie wejsc do tego serwisu

KODI 16.1 na S905X (Android 6.0)

**Comment by mrknow** [comment]
#521 

Loknij,in - ma dodatkowe zabezpieczenie SSL (chyba chodzi o SNI...)

Obsługa tego zabezpieczenia została wdrożona w wersji pythona 2.7.9. Jeżeli masz wcześniejszą wersje pythona to nie zadziała.
Niestety nie można wykorzystać Kodi 17 - bo ten skolei nie obsługuje RTMP. Trzeba czekać na stabilną wersję kodi 17 z obsługą protokołu RTMP
