### ISSUE TITLE
cda nie działa

### ISSUE THREAD

**Issue by drrak** [mrknow/filmkodi#518]
Od wczoraj cda.pl nie odtwarza filmów. "Nie znaleziono streamingu. itd."

Wersja wtyczki: 2016.10.14.1

OpenELEC 6.0.3, RPi2

---

Zdaje się, że w wersji 2016.10.15.1 już jest ok. Dzięki.

**Comment by mrknow** [comment]
Naprawiłem, powinno śmiagć
