### ISSUE TITLE
Specto just gets Error message.

### ISSUE THREAD

**Issue by mclellab** [mrknow/filmkodi#519]
For some reason Specto is not working. Just getting error message, any ideas? Is Specto still working? It is my favourite addon.

**Comment by BankruptEd** [comment]
Mines still working. I can tell you from experience though, that if you
want help you will need to offer up a few more details. These guys need a
little more to go on than the fact it's not working (what version of Kodi,
what sort of device are you using, does the error message say anything
specific, a link to your error log that sort of thing). I cant remember the
terminology for what I called an error log, but it's when you run a little
diagnostic that spits out some technical results. Good luck brother.

**Comment by mrknow** [comment]
Please, give me your logs http://kodi.wiki/view/Log_file/Easy
