### ISSUE TITLE
Telewizjada na kodi

### ISSUE THREAD

**Issue by Adam-po** [mrknow/filmkodi#52]
Czesc musze zawiadomic ze aktualna aktualizacja nie dziala.......telewizjada nie Startuje zadnego kanalu.

**Comment by borys76** [comment]
Umnie wszystko dziala

**Comment by Adam-po** [comment]
Wyskakuje mi blâd dodatku filmu online mrknow.pl

Co mam zrobic

**Comment by Adam-po** [comment]
Umnie wyskakuje błąd dodatku filmy online mrknow.pl
A na wtyczce sd-xbmc też już nie działa
Co mam zrobić?

Gesendet von Yahoo Mail auf Android 
 
  Am Do., 28. Jan. 2016 um 13:50 hat borys76<notifications@github.com> Folgendes geschrieben:   
Umnie wszystko dziala

**Comment by Adam-po** [comment]
Mogę coś zapytać jest jakas możliwość na live.tv

Gesendet von Yahoo Mail auf Android 
 
  Am Do., 28. Jan. 2016 um 15:32 hat Adam Giesa<giesaadam@yahoo.de> Folgendes geschrieben:   Umnie wyskakuje błąd dodatku filmy online mrknow.pl
A na wtyczce sd-xbmc też już nie działa
Co mam zrobić?

Gesendet von Yahoo Mail auf Android 
 
  Am Do., 28. Jan. 2016 um 13:50 hat borys76<notifications@github.com> Folgendes geschrieben:   
Umnie wszystko dziala

**Comment by xxcriticxx** [comment]
Telewizjada ma wtej chwili jakos awarie i nie nadaje

**Comment by borys76** [comment]
Nadaje,nadaje telewizjada dziala wlasnie ogladam

**Comment by Adam-po** [comment]
Na czym : mrknow albo xbmc

Gesendet von Yahoo Mail auf Android 
 
  Am Do., 28. Jan. 2016 um 18:41 hat borys76<notifications@github.com> Folgendes geschrieben:   
Nadaje,nadaje telewizjada dziala wlasnie ogladam

**Comment by Adam-po** [comment]
Zauwazylem ale po czasie wyłącza mi się kodi

Gesendet von Yahoo Mail auf Android 
 
  Am Do., 28. Jan. 2016 um 18:57 hat Adam Giesa<giesaadam@yahoo.de> Folgendes geschrieben:   Na czym : mrknow albo xbmc

Gesendet von Yahoo Mail auf Android 
 
  Am Do., 28. Jan. 2016 um 18:41 hat borys76<notifications@github.com> Folgendes geschrieben:   
Nadaje,nadaje telewizjada dziala wlasnie ogladam

**Comment by em82** [comment]
A ktoś wie czym moze byc spodowany taki problem ze ogladaja dany kanał na telewizjadzie przy szybkim ruchu kamery czy to w filmi czy podczas ogladania sportu zaczynaja się pojawiać przeskoki obrazu i piksele na pól ekranu?

**Comment by xxcriticxx** [comment]
internet albo cpu power

**Comment by mrknow** [comment]
U mnie działa. Może to były przejściowe problemy
