### ISSUE TITLE
looknij.in nie działa na 2 tabletach z androidem..

### ISSUE THREAD

**Issue by the4anoni** [mrknow/filmkodi#521]
Witam :)
Dodam iż wszystko działa w porządku na rpi 3 ,a na androidzie nie :(

**Comment by mrknow** [comment]
Loknij,in - ma dodatkowe zabezpieczenie SSL (chyba chodzi o SNI...)

Obsługa tego zabezpieczenia została wdrożona w wersji pythona 2.7.9. Jeżeli masz wcześniejszą wersje pythona to nie zadziała. 
Niestety nie można wykorzystać Kodi 17 - bo ten skolei nie obsługuje RTMP. Trzeba czekać na stabilną wersję kodi 17 z obsługą protokołu RTMP
