### ISSUE TITLE
multimediago 

### ISSUE THREAD

**Issue by seba99317** [mrknow/filmkodi#522]
witam jest szansa dodac multimedia go

**Comment by mrknow** [comment]
Witam 
nie posiadam takiej kablówki, oraz nie mam tam konta. A mają aplikację na iphone ?

**Comment by seba99317** [comment]
Mają na androida mogę udostępnić konto bo nie wiem czy jest na iPhone

17.10.2016 20:23 "MrKnow" <notifications@github.com> napisał(a):

**Comment by mrknow** [comment]
OK 
Myślę że mogę dodać - ale zacznę prace nad tym za 2,3 tygodnie
