### ISSUE TITLE
fmovies, muchmovies and putlocker links not resolving

### ISSUE THREAD

**Issue by raymond4400** [mrknow/filmkodi#523]
I noticed code changed on fmovies and muchmovies which is preventing urls from resolving

**Comment by mrknow** [comment]
muchmovies - fixed, 
putlocker-  working ok
fmovies - I'll fix it later

**Comment by BankruptEd** [comment]
Thanks MrKnow. Glad you're around and fixing things for us in Spector - the
best add-on there is.

**Comment by willowz** [comment]
@ mrknow today's update brought back the pigeons from openload....so I'm having to stream my shows from exodus.  :(

**Comment by mrknow** [comment]
:) Try to update add-on, this is fixed http://filmkodi.com/en/openload-fix/

**Comment by mrknow** [comment]
OK. I will try to fix it
