### ISSUE TITLE
Specto - Pigeons are back

### ISSUE THREAD

**Issue by willowz** [mrknow/filmkodi#524]
@ mrknow today's update brought back the pigeons from openload....so I'm having to stream my shows from exodus. :(

**Comment by mrknow** [comment]
I fix it. Update add-on http://filmkodi.com/en/openload-fix/

**Comment by willowz** [comment]
Thanks, I will update on my lunch break.

**Comment by willowz** [comment]
@mrknow I rebooted my raspberry pi 3 and since it did not auto update, followed your instructions to manually update.  System locked up during 0% downloaded on the urlresolver update.  Now I can't seem to prompt it to detect the update for the plugin and when I pick an episode (which should autoplay) I receive the error   "Specto-...Fork error   Check the log for more information". I tried uninstalling specto and re-installing but experience the same result.

**Comment by willowz** [comment]
@mrknow I manually downloaded the URLResolver from your repo so now specto is working again but I'm getting the pigeon videos again.  I tried to update add-on as you suggested here  http://filmkodi.com/en/openload-fix/ but there is no update.  Do you have any other suggestions?

**Comment by willowz** [comment]
@mrknow I fixed the issue on my rpi3 but removing the plugin, script, and repo.  Then added them all back.  Now I can auto play items without the pigeons.  Thank you for the Specto add-on.  It's my favorite on Kodi.
