### ISSUE TITLE
Ipla i Cyfrowy Polsat

### ISSUE THREAD

**Issue by lesiaczek** [mrknow/filmkodi#526]
Mam pakiet programów w ipli i TV Philips, na którym nie można ich oglądać.
Jedyna nadzieja w tej wtyczce.
Mam tylko jeden problem.
Loguję się na stronie ipla.pl jako abonent cyfrowego polsatu, a w tej wtyczce nie ma takiej możliwości 🙁
Czy można prosić o dodanie takiej funkcjonalności?

**Comment by mrknow** [comment]
@lesiaczek - witam 
Zdobyłem konto do cyfrowego Polsatu i u mnie działa. Nie wiem dlaczego ale jako login podaje adres mailowy  i hasło jak do cyfrowego Polsatu (wcześniej trzeba połączyć konta na stronie ipla.tv )

**Comment by lesiaczek** [comment]
Wielkie dzięki.
W jakiej wersji to wyjdzie?

**Comment by lesiaczek** [comment]
Aaa, rozumiem, chodzi o to że nie trzeba nic zmieniać w oprogramowaniu tylko powiązać konta.
Próbowałem to zrobić, ale kierunek chyba nie ten :)
Od samego początku do IPLA logowałem się jako abonent Polsatu, przez co nie mam konta do IPLA.
Próbowałem zrobić odwrotnie, czyli najpierw utworzyć konto na IPLA i później powiązać z kontem Polsatu.
Niestety dostaję komunikat, że to konto już jest powiązane.
W razie potrzeby mogę udostępnić swoje konto do Polsatu.

**Comment by lesiaczek** [comment]
Doszedłem do tego jak uzyskać login IPLA i teraz mam zintegrowane konto IPLA z Polsatem.
Na obu mam ten sam login (e-mail) i hasło.
Na stronie ipla.tv loguje się jako zwykły użytkownik IPLA, oraz w zakładce Cyfrowego Polsatu tymi samymi danymi.
Niestety w MrknowTV po wpisaniu tej konfiguracji konta i próbie uruchomienia IPLA, kręci się tylko kółko, po czym bez komunikatu przestaje i nic się nie dzieje.

**Comment by lesiaczek** [comment]
Zainstalowałem Kodi też na Ubuntu i próbując tam odpalić IPLA do logów sypnęło coś takiego:
11:38:57 T:140341697935808   ERROR: GetDirectory - Error getting plugin://plugin.video.mrknowtv/?action=tv&url=ipla
11:38:57 T:140341697935808   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mrknowtv/?action=tv&url=ipla) failed

**Comment by lesiaczek** [comment]
Niestety wciąż mi nie działa, jakby ktoś chciał się pochylić nad moimi logami, to będę bardzo wdzięczny :)

[kodi.log.txt](https://github.com/mrknow/filmkodi/files/550232/kodi.log.txt)

**Comment by lesiaczek** [comment]
Problem rozwiązany :)
IPLA wywaliła mi aktywny pakiet.
Zgłosiłem reklamację i przyznali mi go od nowa :)
