### ISSUE TITLE
W Kodi  nie mogę oglądać z płatnego kąta YOY.TV

### ISSUE THREAD

**Issue by maniekok3** [mrknow/filmkodi#527]
Jak w temacie zakupiłem konto premium w  YOY.TV  i logując się milem - hasłem wyskakuje abym kupił konto premium w przeglądarce działa . A w Kodi nie co jest wole Kodi mam edycje specjalną  http://www.techmaniachd.pl/2016/09/aktualizacja-multimedia-master-10092016.html .

**Comment by maniekok3** [comment]
Alo tu coś się dzieje napisałem że powyższy post i bez odzewu , kiedy ta niedogodność zostanie naprawiona ?

**Comment by mrknow** [comment]
@maniekok3 
proszę zaktualizuj wtyczkę i sprawdź jeszcze raz.

**Comment by mmalinowski123** [comment]
Witam po aktualizacji jest prawie tak samo wyświetlają się powiadomienia: kup konto Premium, następnie: Premium aktywne do .... No i zły login lub hasło a odtwarzanie dalej nie idzie

**Comment by JAkey90** [comment]
Wszystko działa. Dzięki za wasz trud :) Niech wam ziemia lekką będzie 💃 Teraz tylko czekam aż IPLA będzie działać :) 👍

**Comment by borys76** [comment]
@maniekok3 zaplaciles za premium techmaniac to zglos sie do niego

**Comment by maniekok3** [comment]
( borys76 commented 12 hours ago
@maniekok3 zaplaciles za premium techmaniac to zglos sie do niego ) 
Zapłaciłem za prace jaką włożył w dodanie rożnych wtyczek itp . On nie jest odpowiedzialny za działanie poszczególnych wtyczek .

**Comment by borys76** [comment]
@maniekok3 to mam nadzieje ze dla mrknow tez cos przelales
Techmaniac I inni biora kase a potem umywaja rece I odsylaja do autorow wtyczek jak nie umieja zrobic wtyczek to niech nie sprzedaja czyjejs pracy

**Comment by mrknow** [comment]
@maniekok3 - prześlij logi z błędem (tu info jak https://github.com/mrknow/filmkodi/wiki/Jak-przes%C5%82a%C4%87-logi-z-kodi) 
@borys76 - dzięki za zrozumienie.

**Comment by marekodfiranek** [comment]
maniekok3 .. skoro potrafiłeś zainstalować "builda" od Techmaniac do co w tym trudnego znaleźć inne wtyczki plus korzystać z pokaźnych zbiorów MrKnow? 
Opłaciłeś Techmaniac to taką samą sumę wyślij do MRKnow http://filmkodi.com/pl/darowizna/

**Comment by mrknow** [comment]
Darowizna jest opcjonalna i dla chętnych wspomóc projekt. Podeślijcie logi z błędem - to naprawimy

**Comment by maniekok3** [comment]
Teraz działa 


Wysłano z telefonu Samsung
-------- Oryginalna wiadomość --------Od: MrKnow <notifications@github.com> Data: 22.10.2016  17:09  (GMT+01:00) Do: mrknow/filmkodi <filmkodi@noreply.github.com> DW: maniekok3 <zmaniekok3@gmail.com>, Mention <mention@noreply.github.com> Temat: Re: [mrknow/filmkodi] W Kodi nie mogę oglądać z płatnego kąta YOY.TV (#527) 
@maniekok3 

proszę zaktualizuj wtyczkę i sprawdź jeszcze raz. 

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mrknow/filmkodi","title":"mrknow/filmkodi","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mrknow/filmkodi"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mrknow in #527: @maniekok3 \r\nproszę zaktualizuj wtyczkę i sprawdź jeszcze raz. \r\n"}],"action":{"name":"View Issue","url":"https://github.com/mrknow/filmkodi/issues/527#issuecomment-255533738"}}}

**Comment by mrknow** [comment]
@maniekok3 - ok
