### ISSUE TITLE
yoy.tv - wtyczka nie dziala poprawnie.

### ISSUE THREAD

**Issue by JAkey90** [mrknow/filmkodi#528]
Witam,
Posiadam konto premium  w serwisie yoy.tv. Mam zainstalowana wtyczke na kodi jednak po wybraniu kanału, zaden z nich niestety sie nie laduje. W przegladarce wszystko dziala bez problemu. Prosze o probe rozwiazania issue. Dzieki wielkie

**Comment by mmalinowski123** [comment]
Witam. Mam ten sam problem.

**Comment by mrknow** [comment]
@JAkey90 , @mmalinowski123 
Dzisiaj wypuszczam nową aktualizację do MrknowTV. Zaktualizujcie i powiedzcie czy jest lepiej
W razie co link do wideo jak zaktualizować wtyczkę http://filmkodi.com/pl/openload-fix-2/

**Comment by mmalinowski123** [comment]
Witam po aktualizacji jest prawie tak samo wyświetlają się powiadomienia: kup konto Premium, następnie: Premium aktywne do .... No i zły login lub hasło a odtwarzanie dalej nie idzie.

**Comment by JAkey90** [comment]
Wszystko działa. Dzięki za wasz trud :) Niech wam ziemia lekką będzie 💃 Teraz tylko czekam aż IPLA będzie działać :) 👍

**Comment by mrknow** [comment]
@mmalinowski123 
- wpisz jeszcze raz w ustawieniach na yoy adres email (nie nazwę uzytkownika) i hasło
- wejdź w ustawienia i naciśnij  wyczyść cache

![zrzut ekranu z 2016-10-23 01-37-00](https://cloud.githubusercontent.com/assets/7198249/19623216/ccd4a986-98c1-11e6-94e0-2907a345c2e8.png)

**Comment by borys76** [comment]
Wszystko dziala dobrze, zle login/password  wpisujecie

**Comment by JAkey90** [comment]
Borys76 czytaj ze zrozumieniem. napisałem że po aktualizacji wszystko działa poprawnie. Poza tym naprawdę uważasz że jesteśmy tak tępi i nie umiemy wpisać loginu i hasła ? Pelase... Jeszcze raz dzięki za rozwiązanie problemu.

**Comment by borys76** [comment]
Ale dla kolegi wyzej dalej nie dziala po update czyli zle cos robi np . Wpisuje password zle

**Comment by mmalinowski123** [comment]
Witam. Ja dalej mam problem nie wiem o co chodzi... Zrobiłem tak jak mówicie mam wpisany e-mail i hasło. Wpisuje na pewno dobrze bo wyświetla się powiadomienie do kiedy mam aktywne Premium po czym włączam listę kanałów i nic niestety... Używam kodi na Philips tv (android) wersja beta Kodi. Pozdrawiam
