### ISSUE TITLE
Tylko dla dorosłych

### ISSUE THREAD

**Issue by luki199112** [mrknow/filmkodi#53]
Witam. Chciałbym zgłosić problem. Po ostatniej aktualizacji pomimo odznaczonej opcji "Tylko dla dorosłych" wsród kanałów telewizjady znajduje sie Hustler.

**Comment by mrknow** [comment]
Dzięki 
Sprawdzam dlaczego ...

**Comment by mrknow** [comment]
ok problem udało mi się rozwiązać 
W razie co zaktualizuj wtyczkę http://filmkodi.com/pl/aktualizacja-wtyczki-zrobic/
