### ISSUE TITLE
Telewizjada dziala

### ISSUE THREAD

**Issue by mar2016** [mrknow/filmkodi#531]
Telewizjada dziala pod nowym adresem http://telewizjada.bid , czy mozna ja dodac?

**Comment by mrknow** [comment]
Witam 
Wersja 2016.10.24.1 obsługuje tą telewizję. Więcej informacji tutaj
http://filmkodi.com/pl/telewizjada-powrot-serwisu/

**Comment by mrknow** [comment]
@mar2016 - dzięki za informację
