### ISSUE TITLE
script.mrknow.urlresolver conflicting with script.module.urlresolver

### ISSUE THREAD

**Issue by tknorris** [mrknow/filmkodi#535]
@mrknow I'm hearing from people that sometimes when an addon imports urlresolver, if they have mrknow.urlresolver installed it picks it up instead of script.module.urlresolver as the devleoper intended.

if you are going to continue insisting on maintaining your own version, can you fix that? The most straightforward way would be to rename lib/urlresolver in mrknow.urlresolver to something different so that it doesn't match `import urlresolver`. If not, we'll be forced to make your repo incompatible with TVA addons.

**Comment by mrknow** [comment]
@tknorris 
OK i fix this i this weekend

**Comment by mrknow** [comment]
Done, renamed to  urlresolver9
