### ISSUE TITLE
Ipla eleven

### ISSUE THREAD

**Issue by Miki29** [mrknow/filmkodi#536]
Witam. Eleven i Eleven sports we wtyczce Ipli nie działa. Reszta ok.

Pozdrawiam.

**Comment by mrknow** [comment]
@Miki29 zaktualizuj wtyczke i sprawdź czy teraz jest eleven 
Tu masz instrukcję jak wymusić aktualizację http://filmkodi.com/pl/openload-fix-2/

**Comment by Miki29** [comment]
@mrknow  zrobiłem jak napisałeś i niestety nie  uruchamiają się, wyświetla się komunikat, "uruchamiam Ipla proszę czekać " i nic się nie dzieje,  w przeglądarce  sprawdziłem i działają. Może zaktualizować Kodi do wersji beta najnowszej ?  Mam teraz tą 16.1

**Comment by mrknow** [comment]
Faktycznie, wykupiłem ten pakiet i u mnie też nie działa. Pracuję nad tym.

**Comment by mrknow** [comment]
OK w Wersji 2016.10.29.1 został poprawiony ten błąd. Zaktualizuj wtyczkę (tu więcej informacji jak wymusić aktualizację jeżeli się nie wykonała http://filmkodi.com/pl/openload-fix-2/)
