### ISSUE TITLE
Alltube Nie do końca działa

### ISSUE THREAD

**Issue by netavx** [mrknow/filmkodi#54]
Hej, Chciałbym zgłosić, że alltube nie do końca działa. Tzn np CSI Las Vegas niedziała 4,5,6 sezon reszty nie sprawdzałem. Przez www działa. Można prosić o interwencję. Tyle ode mnie. Dziękuję za uwagę.

**Comment by mrknow** [comment]
ok, sprawdzę ..

**Comment by mrknow** [comment]
aha widzę video.tt, np http://video.tt/watch_video.php?v=oU4XdCoOI

**Comment by netavx** [comment]
Spoko;) mam nadzieje na szybkie rozwiazanie tematu. Pozdro;)

**Comment by Adam-po** [comment]
Co znowu z tą telewizjadą? S tak super chodziło na xmbc.... Od kiedy jest na mrknow są same kłopoty......

Gesendet von Yahoo Mail auf Android 
 
  Am Fr., 29. Jan. 2016 um 1:08 hat mrknow<notifications@github.com> Folgendes geschrieben:   
ok, sprawdzę ..

**Comment by mazukin** [comment]
Adam-po więcej pokory. Umiesz zrobić lepiej to zrób i pokaż.

**Comment by mrknow** [comment]
OK dodałem resolver. Będę wrzucał na ranem poprawkę
