### ISSUE TITLE
Specto fork

### ISSUE THREAD

**Issue by aml64** [mrknow/filmkodi#542]
Od ostatniej aktualizacji jest problem z napisami do filmów. OpenSubtitles.org zgłasza błąd pobierania.

**Comment by mrknow** [comment]
To raczej wynika z działania serwisu open Subtitles. 
Czasami nie działa  a czasami działa, tu link do weryfikacji czy błąd 
http://api.opensubtitles.org/xml-rpc

**Comment by mrknow** [comment]
teraz działa

**Comment by aml64** [comment]
Fakt coś się ruszyło. Dzięki. Też podejrzewałem problem z serwisem ale zbieżność w czasie z ostatnią aktualizacją skłonila mnie do podniesienia tej kwestii.
