### ISSUE TITLE
MrKnowTV other error on wizja.tv

### ISSUE THREAD

**Issue by bytomiak45** [mrknow/filmkodi#543]
taki oto meldunek ukazuje się przy każdorazowej próbie zalogowania się na wizja.tv, by móc tę stację oglądać poprzez MXR TV-Box. Nike do przeskoczenia.

**Comment by mrknow** [comment]
Daj link do logów - tu instrukcja https://github.com/mrknow/filmkodi/wiki/Jak-przes%C5%82a%C4%87-logi-z-kodi

**Comment by mrknow** [comment]
Zaktualizuj kodi do wersji 16.1 i zainstaluj wtyczkę według instrukcji http://filmkodi.com/pl/mrknowtv-telewizja-ze-stron-kontami-premium/

**Comment by bytomiak45** [comment]
Jeszcze raz serdeczne dzięki! A jeśli zgłaszając mój problem udało mi 
się przyczynić do poprawy usterki w oprogramowaniu tym bardziej msię cieszę.

Pozdrawiam i wielu sukcesów życzę,

Theo


Am 26.10.2016 um 20:56 schrieb MrKnow:

**Comment by bytomiak45** [comment]
Witam!

To znowu ja, Theo z Dortmundu. Przypominasz sobie, kiedy pomagałeś mi 
przez Skypa uruchomić na wtyczce MrKnowTV wizję.tv. Cały czas potem 
hulało bardzo dobrze, do dzisiaj. To znaczy wizja.tv jest wciąż na 
liście obsługiwanych stacji przez MrKnowTV, ale... nie łączy. Jakiś czas 
trwa info "proszę poczekać", które znika ale połączenia nie ma. Może 
problem leży po stronie wizji.tv?

Byłbym szalenie wdzięczny za odpowiedź.

Pozdrawiam,

Theo Nawrocki
