### ISSUE TITLE
[dev] cookies are in repo not in addon_data apth

### ISSUE THREAD

**Issue by rysson** [mrknow/filmkodi#548]
Very low priority. 

Wszystkie ciasteczka są w repo, co chyba nie jest najlepszym pomysłem.
Poza tym lądują w paczce a nie w userdata/addon_data/plugin.video.mrknow/...

Kiedyś w wolnej chwili warto to zmienić. Np. dodać w funckcję mrknow_urlparser do pobierania nazwy katalogu czy pliku ciasteczka.

**EDIT:** Mogę się tym zająć, o ile pomysł zostanie rozpatrzony pozytywnie.

**Comment by xxcriticxx** [comment]
@rysson potrzebuje pomocy z java znasz sie natym troche?

**Comment by rysson** [comment]
@xxcriticxx ja się na Pythonie nawet za mocno nie znam ;-)

Jak coś połatać w Javie, to może się uda, robiłem już tak. Jak od nowa projekt z wytłumaczeniem to nie do mnie. Napisz co trzeba. 

Mail–hangout [przez chwilę]:  r kropka kalinowski małpa sharkbits a dalej com

**Comment by xxcriticxx** [comment]
@rysson napisalem do ciebie w innym projekcje

**Comment by rysson** [comment]
@xxcriticxx, a widzę, ale to dopiero jutro wieczorem przejrzę.

**Comment by rysson** [comment]
@xxcriticxx, skoro tak offtopujemy, to zerknąłem jednym okiem. To nie Java tylko JavaScript. W dodatku potraktowany „zamętniaczem” (obscurer). Obawiam się, że nie dam rady pomóc. Raz, że JS nie jestem super biegły, dwa, że MrKnow mnie tu do wtyczki zagonił ;-) a trzy, że robota wisi.

**Comment by xxcriticxx** [comment]
ok
