### ISSUE TITLE
Swierza instalacja filmkodi na ATV2 nie dziala

### ISSUE THREAD

**Issue by murugurus** [mrknow/filmkodi#55]
Witam,
Wlasnie przeladowalem od nowa moj Apple TV2 bo wtyczka filmkodi nie dziala i chaialem sie upewnic ze to nie problem z Kodi.  A wiec, reposytorium sie instaluje, ale nie ma nic pod "Get Video Add-ons".  Na probe zainstalowalem weeb.tv i hula.

Z gory dziekuje!

**Comment by murugurus** [comment]
Znalazlem przyczyne po wylaczeniu filtra.  Pokazuje ze wtyczka jest "incompatible or marked broken in repo".  To samo z xmbc-sd.

**Comment by mrknow** [comment]
uuu a jaka wersja kodi ?
to trochę nie możliwe. Może zainstalowałeś stare xbmc ?

**Comment by murugurus** [comment]
To bylo na Kodi 14.2 - wydaje mi sie ze zle trafilem w czasie.  Akurat wtyczka nie dzialala.  Nastepnego dnia zainstalowalem ja ponownie, zrobilem uaktualizowanie i zaczelo dzialac.  Kodi 14.2 jest malo stabilny na ATV2, wlasnie robie downgrade do xbmc 12.3, podobno lepiej chodzi.

**Comment by mrknow** [comment]
Co do pudełka to się nie wypowiem. Ja mam w domu atv2 + kodi 14.2 - fakt od czasu do czasu się wywala, ale na razie nie mam pomysłu na co mam to wymienić :)
