### ISSUE TITLE
specto cannot update, including URL resolver, kodi 17 beta 5

### ISSUE THREAD

**Issue by fate8383** [mrknow/filmkodi#551]
specto cannot update, including URL resolver, kodi 17 beta 5
any suggestions?

**Comment by mrknow** [comment]
This is Kodi bug, i think. 

On  https://kodi.tv/kodi-v17-krypton-beta-5/ 

[..]
Known problems

• Upgrading the skin you are currently using fails on Windows.
**• Upgrading any add-on currently fails on Windows.**
• Possible video freezes on Raspberry Pi and Android.

**Comment by fate8383** [comment]
I am using mac if that makes any difference. Other add-ons are updating just fine.

**Comment by vile80r** [comment]
I can confirm that all other add-ons update fine on Kodi 17 Beta 5 on Windows, Mac, and Android except the following 2 add-ons that both fail trying to update online or manually. I also get server timeouts now trying to import my Trakt TV Watchlist and no new episodes of the previously added shows in my library have appeared.

Mrknow URLResolver 2016.11.12.1
Specto-...Fork 2016.11.11.1
