### ISSUE TITLE
No more Openload resolving by you?

### ISSUE THREAD

**Issue by dracosc** [mrknow/filmkodi#552]
After the last update, openload sources react just like URLresolver. You cannot fix it anymore?

**Comment by mrknow** [comment]
You can pair with any device on the same network, so if you have a phone or computer in the house on the same network (wifi) you can use that to pair.  it only takes 30 seconds

**Comment by dracosc** [comment]
Yes, i know that. But specto used to be the ONLY addon that didn't need that! Is there a way to fix or not? If there is for personal use, i am willing to hear!
Thanks again for your great addon!

**Comment by mrknow** [comment]
@dracosc - technically I can do it, it is not complicated. I need to think about it, I will answer you tomorrow

**Comment by dracosc** [comment]
Fixed already???? You are the best!!

**Comment by mrknow** [comment]
Openload  working in 9 cases out of 10. Now i'm trying to fix this. 
I released the update of add-on script.mrknow.urlresolver
Version  2016.10.30.2 should fix this problem
