### ISSUE TITLE
WizjaTV nie działa po aktualizacji

### ISSUE THREAD

**Issue by Lukas699CK** [mrknow/filmkodi#555]
Dziś dodatek MRKnowTV automatycznie się zaktualizował i przy uruchamianiu wizja.tv pojawia się komunikat : Błąd dodatku MRKnowTV. Wiecej informacji na ten temat znajdziesz w pliku rejestru. Na telefonie ze starszą wersją dział bez problemu.

**Comment by seba741** [comment]
Potwierdzam mam konta na wizji tv i yoy tv obydwa nie dzialaja po aktualizacji  ver.2016.10.29.2

**Comment by zusto82** [comment]
u mnie to samo, po aktualizajci zadna telewizja nie dziala

**Comment by mrknow** [comment]
zaraz to sprawdzę i poprawię. Potrzebuje 15 minut

**Comment by mrknow** [comment]
a możecie wkleić logi ?

**Comment by mrknow** [comment]
Dobra 
Uciekły mi pliki i już poprawiłem. Proszę zaktualizujcie wtyczkę - tutaj w razie co film jak wymusić aktualizację dodatków w kodi http://filmkodi.com/pl/openload-fix-2/

**Comment by zusto82** [comment]
Wielkie dzieki, wszystko dziala jak wczesniej
