### ISSUE TITLE
specto - problemy z napisami

### ISSUE THREAD

**Issue by drrak** [mrknow/filmkodi#556]
Od jakiegoś czasu (tygodnia albo dwóch) do niektórych filmów nie może pobrać napisów z OpenSubtitles.org. Można wpisać tytuł ręcznie i wtedy napisy się znajdą, ale do niedawana nie trzeba było tak kombinować. Np. _Star Trek The Next Generation_ miał chyba z 6 różnych plików z napisami, teraz nie może znaleźć ani jednego.

Wersja wtyczki: 2016.10.28.2
OpenELEC 6.0.3, RPi2

---

Byłem zmuszony do instalacji LibreELEC. Po sprawdzeniu Specto i _Star Trek The Next Generation_ na nowym systemie, okazało się, że problem z napisami zniknął.

Przepraszam za zamieszanie, wątek można zamknąć.

**Comment by mrknow** [comment]
ok zamykam. Weź pod uwagę że opensubtitles czasami tak mają. Serwis nie działa przez 30 minut, a później jak ręką odjął
