### ISSUE TITLE
Falnfim

### ISSUE THREAD

**Issue by gosiaiunia1** [mrknow/filmkodi#557]
Po ostatniej aktualizacji nieuruchamia sie. Blad scryptu. To samo jest filmy online

**Comment by mrknow** [comment]
Fanfilm nie działa, bo muszę poprawić. Filmy online powinny działać. 
zrestartuj i spróbuj jeszcze raz z filmami online. 

Fanfilm będę w tym tygodniu poprawiał...

**Comment by gosiaiunia1** [comment]
Wiitan. Restart nic nie pomogl dalej jest to samo . pozdrawiam

30 paź 2016 23:47 "MrKnow" <notifications@github.com> napisał(a):

**Comment by mrknow** [comment]
Będziemy się wycofywać z tej wtyczki. Nadchodzi nowa lepsza mam nadzieje ...
