### ISSUE TITLE
Source Watchfree not working

### ISSUE THREAD

**Issue by bjgood** [mrknow/filmkodi#558]
Hi Mr. Know,
It appears, at least on my end, that source watchfree is not providing any links any longer. It use to, not long ago, but now...nothing.

It's a great source which provided a lot of links for movies and tv shows. It would be nice to have it working again.

Thanks for all your efforts, Mr. Know. :).

Best regards,
Bob

**Comment by mrknow** [comment]
fixed

**Comment by bjgood** [comment]
Thanks, Mr. Know.

Best regards,
Bob
