### ISSUE TITLE
latest episodes and TV calendar not working in specto

### ISSUE THREAD

**Issue by dax7** [mrknow/filmkodi#562]
latest episodes tab has stopped working
TV calendar has stopped on Sunday, which ordinarily wouldn't be a problem but it seems to be interfering with search functions
'Your pretty face is going to Hell' searching for the show for example, which aired on Monday cannot be found by search engine, yet if I search something like Venture Bros it works ok
Maybe a problem at my end, would like to know if anybody else is experiencing this problem?

**Comment by crashguard** [comment]
Mine has stopped working too ... 
Yesterday watched some of my favorites, this afternoon i wanted to check if there are new episodes ..
So i went to 'latest episodes', but only thing i got is 2 dots after waiting for a long time.
I went back to factory settings. Installed everything like i always do and i have the same problem ..
Lost all my favorites in the process :( 
Movies section does work ok.

**Comment by mrknow** [comment]
Specto for this uses trakt.tv. Today trakt.tv was down (database issue). More info here https://twitter.com/trakt

**Comment by crashguard** [comment]
Isn't it possible to get connection info messages in Kodi ? 
Would be great .. then i wouldn't reset my entire machine knowing that server is down ..  

this functionality would be apreciated ;)

**Comment by dax7** [comment]
Thanks for the reply mrknow

**Comment by mrknow** [comment]
I was wrong. Calendar will be fixed today.

**Comment by dax7** [comment]
Nice one mate!
