### ISSUE TITLE
Kodi Crashes

### ISSUE THREAD

**Issue by hahabla** [mrknow/filmkodi#57]
Hello,

I am trying to use Kodi on my Fire TV Stick.
I tried Version 15 and the RC 16. I also tried an clean install, an install with FireStarter and starting with Llama.
I also tried to shut down Hardware Accelleration, turn off the RSS-Feed, and (with Firestarter) to turn off the ADB-Options.
But none of that worked:
Everytime I try to use Kodi, it crashes.
Sometimes at browsing trough lists, sometimes while watching streams, sometimes by starting streams, and sometimes even while doing nothing! It just crashes, and I'm back at the main menu.
When Kodin crashes and FireStarter is installed, it crashes FireStarter, too.

So, I didn't found a possibility, to use Kodi on the FireTV Stick.

If you know how to solve the issue, please let me know.

Here's the log file with the part of the crash:

http://xbmclogs.com/pxj3ulgwv

Thanks for any help 

PS: Nie dziala takze aktualizacja Libtmp. Pokazuje ze nien ma tych danych.
A na najnowszym Kodi, nie dziala ta wtyczka w ogole.

**Comment by xxcriticxx** [comment]
jak stary masz tv?

zmien hdmi kabel na nowy

co jest podlonczone pod stick?

**Comment by hahabla** [comment]
TV ma dwa lata.
Kazda inna wtyczka dziala, tylko przy mrknow ten Stick wraca do glownego menu po jakims czasie.
Pod stick nic nie jest podloczone, tylko Fire TV Stick do TV, a Stick do pradu jeszcze.
Pod ten stick tez nie da sie nic wiecej podlaczyc...

Ten sam problem mialem tez z moja komorka z Androidem.
Jest to Galaxy S4.
Libtrmp nie da sie zaktualizowac, a Kodi sie wylaczalo uzywajac wtyczke mrknow.

Po najnowszej aktualizacji wtyczki, wtyczka sie wcale nie dala wlaczyc. Teraz cos tam zaktualizowalo sie, i dziala. 
Libtrmp nadal sie nie daje zaktualizowac, ale Kodi juz sie samo nie wylacza...
To bardzo dziwnie, przesiadlem sie jak narazie na inna wtyczke...

**Comment by xxcriticxx** [comment]
dziwna sprawa jak mowisz ze wszystko inne dziala

mr know bendzi musial spojrzec na logi

**Comment by mrknow** [comment]
Prosze o ponowną weryfikacje po aktualizacji
