### ISSUE TITLE
Unable to sync with Trakt

### ISSUE THREAD

**Issue by azrin1972** [mrknow/filmkodi#570]
Hi, I'm new to Specto and has it installed successfully. Now I'm trying to integrate it with trakt but I could not get it to sync with my tv collection. The activation was done successfully.

Thank you 

I'm using:
Kodi krypton b5
Android box with android 6.0

**Comment by azrin1972** [comment]
From My Specto, 

I'm able to get list only form these options:
TRAKT : Movies Featured
TRAKT : TV Featured
TRAKT : Episodes
Movie Lists

Other options returns nothing. 

Hope this help.

**Comment by mrknow** [comment]
old issue, fixed
