### ISSUE TITLE
Furk.net scraper - no search results shown in Specto

### ISSUE THREAD

**Issue by PapaPow** [mrknow/filmkodi#571]
I have a Furk.net account setup in Specto (Kodi), however I am not seeing labeled "FURK" search results for any TV Shows and Movies.  Should I be seeing labeled search results like I do with my Easynews account?  ("EASYNEWS" is shown when links are available)

I know that in the SALTS addon for Kodi that I see labeled "FURK" search results and I didn't know if I should be seeing the same in Specto.

Thanks in advance for any feedback that can be provided.

**Comment by mrknow** [comment]
Will be fixed in #585
