### ISSUE TITLE
Telegram jako źródło mediów. 

### ISSUE THREAD

**Issue by MeDeVILe** [mrknow/filmkodi#577]
Witaj. W ciągu ostatnich miesięcy pojawiło się wiele kanałów z filmami i serialami na Telegramie. Na linuxie zauważyłem, że można odtwarzać pliki (sprawdzałem mp4) w trakcie ich pobierania. Serwery telegrama zawsze są dostępne i uważam, że byłby dobrym źródłem. Sądzisz, że byłoby możliwe wykorzystać to tak jak mówię?

**Comment by mrknow** [comment]
Sprawdzę to w przyszły weekend

**Comment by mrknow** [comment]
nie ma szans na razie
