### ISSUE TITLE
Mr. Know repozytorium

### ISSUE THREAD

**Issue by rybciam** [mrknow/filmkodi#58]
Potrzebuję pomocy z instalacją wtyczki Mr Know. Kodi w wersji 15.2 na androidzie. W czasie instalacji mówi, że instalacja nieudana, brak zależnego dodatku... Co to W ogóle jest? Ten zależny dodatek? Próbowałem siegacopo różne opcje - od SuperRepo, przez iptv aż do pliku pobranego z filmkodi. 
Co robić?
Pozdrawiam i z góry dziękuję

**Comment by rybciam** [comment]
Dodam, że na komputerze działa. Ta sama wersja kodi;)

**Comment by xxcriticxx** [comment]
podaj wiecej info? podaj logi?

jaka box? os? czy kiedys dzialalo?

**Comment by rybciam** [comment]
Dzięki wielki ale już naprawiłem. Nie wiem co się stało, ale pomogło
zainstalowanie kodi i wtyczek od nowa. A Mr.Know chciałem włączyć po raz
pierwszy.
Teraz wszystko pięknie działa.

Pozdrawiam i powodzenia

rybciam
31 sty 2016 17:51 "xxcriticxx" <notifications@github.com> napisał(a):

**Comment by xxcriticxx** [comment]
you welcome
