### ISSUE TITLE
Problem z Mr.know addons

### ISSUE THREAD

**Issue by gumcio74** [mrknow/filmkodi#580]
Witam 
Mam mam mały problem z aplikacja Mr.know  kupilem nowy tv sony z android tv i po zainstalowaniu kodi i aplikacji Mr.know nie dziala zadna aplikacja mr.know  dziala tylko weeb tv. wizjaTV po podanie loginu i hasla zaczyna sie otwierac ale nie potrafi otworzyc programu i pokazac stacji jest to dla mnie bardzo dziwne poniewaz mam drugi tv sony tylko troche mniejszy juz od dawna i na nim wszystko dziala bez zastrzeżen nie wiem czym to moze byc spowodowane , reinstalowalem kodi oraz wszystkie pluginy i to samo . prosze o sugestie jak rozwiazac ten problem , oprócz tego tv mam jeszcze kodi na nvidia shild tv oraz na macbooku pro i wszystko działa bez zarzutu  tylko problem jest na nowym tv sony . z gory dziękuje za pomoc

**Comment by mar2016** [comment]
Tez mam sony z androidem i u mnie Kodi dziala ze wszystkimi dodatkami.
Usun Kodi i zainstaluj na nowo, zainstaluj repository i z niego zainstaluj wtyczki.Wersja 2: jezeli masz na innym androidzie kodi to zrob BACKUP wszystkich ustawien wacznie z ustawieniami personalnymi i wgraj do Kodi na sony  przez program Backup

**Comment by gumcio74** [comment]
dzieki za szybką odpowiedz zainstalowałem kodi na nowo i pobrałem wtyczke mr.know z serwera http://kodi.film.kodi.com najnowsze wtyczki i jest to samo nic nie chce działać .po wejściu do katalogów np filmu najpierw pokazywał pusty katalog z dostepnym tylko "nastepna strona"  tak we wszystkich serwisach alltube.tv czy  cda etc. podaje wersje wtyczek filmy online 2016.10.29.1 marknow TV 2016.10.31.1 fanfilm 2016.11.01.1 a na drugim sony tv mam te same wtyczki i dzialaja nie mam pojecia co jest grane sony kdl-50w809c jest ok a na kdl-75w855c te wtyczki nie dzialaja .
Jesli chodzi o probe przeniesienia ustawien z jednego tv na drugi to nie wiem jak do tego podejsc co potrzebuje  jaki pendrive etc prosze o instrukcje bo nie spotkałem sie nigdy z taka sytuacja aby na jednym działało wszystko a na drugim tej samej firmy i na tym samym systemie nie .z gory dzieki za pomoc pozdrawiam

**Comment by mar2016** [comment]
Jezeli na pierwszym sony wszystko dziala to:  otworz kodi na listwie jest dzial PROGRAMY w nim jest wtyczka BACKUP jezeli jej nie ma to musisz ja zainstalowac a nastepnie ustawic gdzie masz zapisac dane z backupu nastepnie wskazac pendraiwa do zapisu , nastepnie to samo zrobic na drugim sony 
Zobacz ten link z filmem jak zrobic backup : https://www.youtube.com/watch?v=523HL0TBHFo

**Comment by mrknow** [comment]
poprawiłem 
Prosze zweryfikuj

**Comment by gumcio74** [comment]
Witam
Już od dwóch czy trzech dni wszystko jest OK wszystko działa na wszystkich urządzeniach dziękuje za pomoc i pozdrawiam gorąco .
Adam

Sent from iPhone

Dnia 10.11.2016 o godz. 00:20 MrKnow <notifications@github.com> napisał(a):

**Comment by mrknow** [comment]
problem chyba był z script.module.metahandler. Dodałem go do mojego repo
