### ISSUE TITLE
Trakt:Progress not working after latest update

### ISSUE THREAD

**Issue by Tw3ak** [mrknow/filmkodi#582]
When i click on TRAKT:Progress i just get the "Working..." at bottom of the screen for a few seconds then nothing happens stays on my specto page, I thought maybe it was a trakt issue so i tried it on exodus and trakt progress loaded fine so then tried again on specto and nothing still.

Deleted data+cache and tried again and still didn't work, Then completely deleted and reinstalled specto and still not working.

**Comment by bjgood** [comment]
Trakt.tv wasn't working for me as well. What I did to get it working was to delete the trakt information found in userdata>addon_data>plugin.video.specto>settings.xml. Then, reactivated trakt in specto settings under accounts.

Later...
Bob

**Comment by fogotten** [comment]
Tried the above fix. Did not work for me. To be clear. Trakt works on Specto but the Progress feature does not

**Comment by Crunch69** [comment]
Trait progress is not working with the last update.

The fix uncheck auto update and install a older version

**Comment by fogotten** [comment]
Do you have a link to the previous version?

**Comment by fogotten** [comment]
http://kodi.filmkodi.com/plugin.video.specto/

**Comment by azrin1972** [comment]
Trakt does not work for me. Authorisation is working but  could not event download my TV Collection. Tried it on two separate boxes (one with Kit Kat and one with marshmallow). Please help.

Thank you

**Comment by mrknow** [comment]
fixed
