### ISSUE TITLE
Probelm z Szukaj

### ISSUE THREAD

**Issue by KarolPysklo** [mrknow/filmkodi#588]
"Szukaj" nie odpowiada gdy w historii znajduje się znak wykraczający poza ascii (do - x7F) np. ó
`UnicodeEncodeError: 'ascii' codec can't encode character`
Proponuję:
`query=query.encode('utf-8')` -> https://github.com/mrknow/filmkodi/blob/master/plugin.video.mrknow/lib/search.py#L130

**Comment by mrknow** [comment]
Dzisiaj ok 22:00 puszczę aktualizację
