### ISSUE TITLE
Specto Crashing

### ISSUE THREAD

**Issue by rneck7** [mrknow/filmkodi#591]
The specto keeps crashing on me for some unknown reason any advice here is my logs

http://paste.filmkodi.com/pp9mor3oo

**Comment by rneck7** [comment]
Also Kodi is on a firestick if thats any help sorry new to all this stuff but it crashes from specto to firestick home page

**Comment by rneck7** [comment]
Oh another thing it quit playing openload sources for me too i dont know if there is anything that can be done on that part but it will try to load and say working then never does anything which is a shame because this is my favorite addon and most the sources are from openload

**Comment by mrknow** [comment]
@rneck7 
Please send me the logs again, Websita paste.filmkodi.com I had to move to another server and do not have access to the old logs
