### ISSUE TITLE
Wizja.TV - RTPM 

### ISSUE THREAD

**Issue by bugi777** [mrknow/filmkodi#593]
Witam.

Na razie wyłączone jest doładowywanie kont premium dlatego nie mogę odpalić wizja.tv z poziomu kodi.

Chciałem spróbować wydobyć link bezpośrednio ze strony i odpalać z poziomu Kodi jako plik .strm ale mam z tym problem.

Doszedłem do etapu:

link bezpośrednio na stronę:
http://wizja.tv/watch.php?id=68

Za pomocą "Zbadaj element" z poziomu Opery znalazłem źródło, które przerobiłem za pomocą konwertera HEX na text

z

rtmp%3A%2F%2F93.115.60.6%3A1875%2FjuchaSPub3erexef%2FthuYuNuTe4%3Fevent=68%26token=DrTzvCeEPjXZ2M3H6OJ5NhF7notKy9&streamType=live

na

rtmp://93.115.60.4:1875/juchaSPub3erexef/thuYuNuTe4?event=68&token=jPQ2mCzTHVyXvOwheRWGU1rFc5gYps&streamType=live

Mając taki link jednak mam nadal problem odpalić kanał z poziomu kodi lub VLC. Próbowałem go skracać jeszcze ale też nie pomogło. Dałbyś radę coś podpowiedzieć ?

Z góry dzięki.

**Comment by bart7890** [comment]
Wtyczka livepolishtv z repo ramic, tam wizję.tv odpalisz i bez premki. :)

**Comment by bugi777** [comment]
Działa jak należy. Wtyczka ma ogrom kanałów. Dzięki za pomoc.
