### ISSUE TITLE
Delta Login/password not working in telewizjada.net

### ISSUE THREAD

**Issue by olliefu** [mrknow/filmkodi#594]
Delta Login/password not working in telewizjada.net.  I have a paid subscription.  I cleared cache and updated to the latest version of mr know. Please advise.

**Comment by mrknow** [comment]
@olliefu - please check your login on https://www.deltamediaplayer.com/ page.
If You have problem in MrknowTV add-on, please send me logs

MrknowTV->Tools->Send diagnostic logs

**Comment by olliefu** [comment]
dzięki Mr Know.  Login works great on the site. Maybe its fresh new login? Ill send the diagnostic when I get home. dzięki again for your fine work!

**Comment by olliefu** [comment]
Does it make a difference i am using amazon stick for this?

**Comment by olliefu** [comment]
here is my log: [http://paste.filmkodi.com/pojo0gigi](http://paste.filmkodi.com/pojo0gigi)

**Comment by krysek17** [comment]
Login or password incorrect

W delta player nie ma problemu.
Probowalem na dwoch komputerach na kodi i nie daje rady.

http://paste.filmkodi.com/view/735f7774
