### ISSUE TITLE
CBSN NEWS APP

### ISSUE THREAD

**Issue by BankruptEd** [mrknow/filmkodi#595]
This isn't an issue. Well maybe for me. Can anyone tell me which repo has the stand alone CBSN news app? I had this on a previous box of mine but have been unable to find it again. I love it for its live feature (CBS news add-on  doesn't have it, has to be CBSN). Any help much appreciated.

**Comment by BankruptEd** [comment]
Or the name of a good forum for these kinds of non issue issues would be good too.

**Comment by mrknow** [comment]
I added to Filmkodi.com  repository
Go to System > Add-ons > install from repository -> Filmkodi.com repository -> Video Add-ons

Here is more info about this add-on 
http://forum.kodi.tv/showthread.php?tid=216234&page=5

**Comment by BankruptEd** [comment]
Awesome, thank you very much. I appreciate all your efforts.
