### ISSUE TITLE
Getting "no stream available" for telewizjada.net on Amazon Stick

### ISSUE THREAD

**Issue by olliefu** [mrknow/filmkodi#597]
Mr Know or anyone - It is me again. Everything worked on my Amazon Stick with my DeltaMedia/telewizjada.net login & password. No problems. 

However I am running into problems with my Uncle's Amazon Stick. I am helping him load up telewizjada.net on his stick. He got his own account and paid for it. Everything is working great on the browser end. When I enter his login & password in kodi - I am constantly getting "no stream available".  What is odd is that I tried to use my account on his stick and I also got the same message. I tried reinstalling kodi and everything. I even cleared cache. Is there something I am missing? I was trying to get a diagnostic log but it was not working as well. Any tips would help.

**Comment by olliefu** [comment]
One other thing, my uncle has a wizja account as well and that is working fine.

**Comment by oomek** [comment]
Same thing here. No stream available.

**Comment by mrknow** [comment]
please install MrknowTV from http://kodi.filmkodi.com/beta/plugin.video.mrknowtv/plugin.video.mrknowtv-2016.11.8.7.zip
Then call an error and send me diagnostic logs form
MrknowTV > Tools> Send diagnostic logs

**Comment by olliefu** [comment]
@mrknow http://paste.filmkodi.com/view/b499f6c9

**Comment by olliefu** [comment]
@oomek from @mrknow OK, i found bug - Exception telewizjada.net login global name 'paramslog' is not defined
Please install new version http://kodi.filmkodi.com/beta/plugin.video.mrknowtv/plugin.video.mrknowtv-2016.11.8.8.zip, and try again.

**Comment by mrknow** [comment]
Fixed
