### ISSUE TITLE
Telewizjada.net

### ISSUE THREAD

**Issue by krolik88** [mrknow/filmkodi#598]
Nie działa na kodi, wyskakuje bląd z informacją brak dostępnego strumienia, zaś na www działa bardzo dobrze..

**Comment by mrknow** [comment]
@krolik88 - sprawdzam ...

**Comment by olliefu** [comment]
I am getting the same issue for a different account & amazon stick.  #597 My own personal account & amazon stick works great. When I apply my login to the other stick, it does not work. :(

**Comment by mrknow** [comment]
@krolik88 - zainstaluj MrknowTV z tego źrudła http://kodi.filmkodi.com/beta/plugin.video.mrknowtv/plugin.video.mrknowtv-2016.11.8.7.zip 
Wywołaj błąd i wyślij mi logi MrknowTV > Narzędzia > Wyślij logi diagnostyczne

**Comment by mrknow** [comment]
@olliefu - please install MrknowTV from  http://kodi.filmkodi.com/beta/plugin.video.mrknowtv/plugin.video.mrknowtv-2016.11.8.7.zip
Then call an error and send me diagnostic logs form 
MrknowTV > Tools> Send diagnostic logs

**Comment by olliefu** [comment]
@mrknow that's the other problem, I could not generate a diagnostic log file. It kept giving me a can not connect to server. :( I can do it on my stick but not my Uncle's stick. :(

**Comment by olliefu** [comment]
@mrknow let me try. last night i had trouble generating a log file. I kept getting a "can not connect to server"

**Comment by olliefu** [comment]
@mrknow http://paste.filmkodi.com/view/b499f6c9 Dziękuję bardzo

**Comment by mrknow** [comment]
OK, i found bug -  Exception telewizjada.net login global name 'paramslog' is not defined
Please install new version http://kodi.filmkodi.com/beta/plugin.video.mrknowtv/plugin.video.mrknowtv-2016.11.8.8.zip, and try again.

**Comment by mrknow** [comment]
@krolik88 wersja http://kodi.filmkodi.com/beta/plugin.video.mrknowtv/plugin.video.mrknowtv-2016.11.8.8.zip powinna naprawiać ten błąd. Proszę sprawdź.

**Comment by olliefu** [comment]
@mrknow Dziękuję - That worked! My uncle's stick works now. Out of curiosity, why did my login worked  but his did not. Thank you again. I'm assuming new update today?

**Comment by krolik88** [comment]
@mrknow dziękuje teraz wszystko działa 👍

**Comment by mrknow** [comment]
@olliefu - this error impacts only new installation(in version  2016.11.08.05 I forgot to uncomment one line) . 
If you configure your account before version 2016.11.08.05, it works OK (all needed variables was saved in cache)

**Comment by olliefu** [comment]
@mrknow interesting and good to know. dzięki! I just sent you a donation. You the Man!

**Comment by mrknow** [comment]
@olliefu - thank you very much for your donation.
