### ISSUE TITLE
IPLA 

### ISSUE THREAD

**Issue by eko5** [mrknow/filmkodi#599]
Próbuję wejść w iple we wtyczce mrnow tv i wyskakuje mi komunikat 

`13:11:44 T:140159721142016  NOTICE: Mrknow URLResolver: Initializing URLResolver version: 2016.11.4.1
13:11:44 T:140159721142016  NOTICE: [plugin.video.mrknow] Filmy online www.mrknow.pl
13:11:44 T:140159721142016  NOTICE: [plugin.video.mrknow] ?mode=110
13:11:44 T:140159721142016  NOTICE: [plugin.video.mrknow] Base: plugin://plugin.video.mrknow/
13:11:44 T:140159721142016  NOTICE: [plugin.video.mrknow] Handle: 14
13:11:44 T:140159721142016  NOTICE: [plugin.video.mrknow] Parameter: ?mode=110
13:11:44 T:140159721142016  NOTICE: [plugin.video.mrknow] LEN: 9
13:11:44 T:140159721142016  NOTICE: [plugin.video.mrknow] mode: 110
13:11:44 T:140159721142016  NOTICE: [plugin.video.mrknow] Local file mainMenu.cfg opened
13:11:44 T:140159721142016  NOTICE: [plugin.video.mrknow] End of directory
13:11:55 T:140159211271936 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.mrknow/?mode=20
13:11:55 T:140159211271936   ERROR: InputStream: Error opening, plugin://plugin.video.mrknow/?mode=20
13:13:03 T:140159144130304  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
13:33:25 T:140159717734144  NOTICE: Previous line repeats 4 times.
13:33:25 T:140159717734144  NOTICE: [MrknowTV]: ->----------                PARAMS: {}
13:33:27 T:140159717734144  NOTICE: [MrknowTV]: ->----------                PARAMS: {'action': 'tv', 'url': 'ipla'}
13:33:32 T:140160498272256   ERROR: GetDirectory - Error getting plugin://plugin.video.mrknowtv/?action=tv&url=ipla
13:33:32 T:140160498272256   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mrknowtv/?action=tv&url=ipla) failed
13:33:33 T:140159717734144  NOTICE: [MrknowTV]: ->----------                PARAMS: {}`

**Comment by mrknow** [comment]
Witam 
Logi są nie opd tej wtyczki. Tutaj masz instrukcję instalacji MrknowTV. Napisz jeżeli nie zadziała. Pogadamy na czacie
