### ISSUE TITLE
Nieudane wykonanie skryptu 

### ISSUE THREAD

**Issue by nica81** [mrknow/filmkodi#6]
Witam,  mam mediabox (android 4.4.2 z kodi 14.2 ) i od ok 3 czy 4 dni wtyczka mrknow.pl nie działa :-( nie mam problemu z otwieraniem na laptopie ale problem wystąpił na urządzeniu z androidem. Czy ktoś mógłby mi pomóc ? nie wiem czy to wina aktualizacji i czy mogę coś zrobić aby spróbować to sama naprawić. Zależy mi aby oglądać polskie programy na dużym ekranie :)

wersja mrknow: 2015.11.29.2

**Comment by xxcriticxx** [comment]
nie jestes sam/sama umnie tez na minix 8h nie pracuje

**Comment by nica81** [comment]
znalazłam już jakieś tymczasowe rozwiązanie wtyczki z polskimi kanałami ;( ale nadal czekam na szybki powrót mrknow.pl do mojego mediabox :) więc sprawdzam co jakiś czas czy działa ale jeśli muszę to naprawić jakoś sama to potrzebuję wytycznych hehe

**Comment by nica81** [comment]
https://www.youtube.com/watch?v=Yocd_I-ZKBE teraz korzystam z tej wtyczki tu filmik jak zainstalować  i jeszcze " zeus video " tam trzeba pogrzebać ale część kanałów działa

**Comment by nica81** [comment]
https://www.youtube.com/watch?v=PhPLYygsoxc tu jak zainstalować zeusa :) tam później trzeba wejść w zeusie w country wybrać polską flagę i górny drugi link ( chyba) i już jakieś kanały będą

**Comment by nica81** [comment]
a jeśli jesteś fanem sportu to polecam sportdevil

**Comment by xxcriticxx** [comment]
uzywam tylko sd-xbmc i mr know plugins

**Comment by mrknow** [comment]
wersja 2016.01.03 - powinna to poprawić. jeżeli nie to prosze pokaż mi logi według tej instrukcji https://github.com/mrknow/filmkodi/wiki/Jak-przes%C5%82a%C4%87-logi-z-kodi
