### ISSUE TITLE
Problem z własnym EXE instalatorem kodi...

### ISSUE THREAD

**Issue by oizoRafal** [mrknow/filmkodi#602]
Witam...Korzystałem z poradnika jak stworzyc własny instalator dla programu kodi... Instalator się stworzył-gorzej z jego uruchomieniem... Wyskakuje bład : Error 123:nazwa pliku nazwa katalogu lub składnia etykiety woluminu jest niepoprawna(jak poniżej)...
Czesto wgrywam nowego windowsa a ze chcialbym zaoszczedzić sobie kupę czasu i nie wgrywać miliony wtyczek i od nowa bawić się w strojenie kodi szukam jakiegos rozwiazania...Jak stworzyc taki instalator albo bulid swojego upiększonego programu? Ktoś coś?
![przechwytywanie23](https://cloud.githubusercontent.com/assets/23422899/20240510/5dde9384-a91a-11e6-8f64-1a9faa50a70a.JPG)

**Comment by mrknow** [comment]
Najszybciej wykorzystać wtyczkę Kodi Backup (http://kodi.wiki/view/Backup)

Tutaj howto - https://www.youtube.com/watch?v=ySLsTCjySlE
