### ISSUE TITLE
kodi version

### ISSUE THREAD

**Issue by mariocito** [mrknow/filmkodi#603]
hi mrk, 
I'm runnig different versions of kodi on my pc's. some of the streams are not working on certain devises. I presume that's cos of different version of kodi. running all of them on same ubuntu. do you have any advice on how to get them all working/?

**Comment by rysson** [comment]
Hi.

Could you send more information? 
Kodi versions on your devices. Log from Kodi, where the stream failed.

**Comment by mariocito** [comment]
ubuntu 14.10 kodi 15.0 works ok but ubuntu 14.04.4lts kodi 15.2 get's web request failed on the same addon. M

**Comment by mariocito** [comment]
basicly channels on my laptop running kodi 15.0 work fine but on my pc plugged to my tv with ubuntu 15.2 fail to play

**Comment by rysson** [comment]
@mariocito, I've installed Ubuntu in both versions. Could you help me a little and send links to old Kodi packages (15.0 and 15.2).
