### ISSUE TITLE
FanFilm - ginące źródła

### ISSUE THREAD

**Issue by l33ber** [mrknow/filmkodi#606]
Po wybraniu filmu którego wtyczka nie może znaleźć, np odcinka serialu który jeszcze nie leciał,    nie są już później znajdowane żadne źródła, mimo że wcześniej były dostępne. Dopiero pomaga opcja "Wyczyść źródła" w narzędziach. Tak jakby po pierwszej porażce wtyczka uznawała dane źródło za nieaktywne.
Pozdr

**Comment by mrknow** [comment]
Fanfilm będę wycofywał. Nie mam czasu na ten projekt
