### ISSUE TITLE
Telezon

### ISSUE THREAD

**Issue by iwan051772** [mrknow/filmkodi#607]
Czy mozesz dodac telezon

**Comment by xxcriticxx** [comment]
ok widze ze kolega z usa

**Comment by iwan051772** [comment]
Tak , mam telezon w domu a fajnie by bylo ogladac w kodi na telefonie.Czy
to jest mozliwe?

On Nov 14, 2016 10:40 AM, "xxcriticxx" <notifications@github.com> wrote:

ok widze ze kolega z usa

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mrknow/filmkodi/issues/607#issuecomment-260369601>, or mute
the thread

**Comment by iwan051772** [comment]
A poza tym to swietną robotę robisz z mrknowtv.

**Comment by xxcriticxx** [comment]
zapytaj @mrknow

**Comment by mrknow** [comment]
Nie wiem jak na ten telezon się dostać. Ja z polski mam "pusto". To działa ?
