### ISSUE TITLE
Specto not working as of yesterday

### ISSUE THREAD

**Issue by ajglitch** [mrknow/filmkodi#609]
Http://paste.filmkodi.com/view/5c2095dd

Specto stopped working yesterday. I cannot get any file to open. When I try  I get an error that tells me to check the log. When I open the diagnostic log the URL above is what it says I should paste into the MrKnow forum. So here I am. Any ideas?

**Comment by WestWorldMarshalUS1** [comment]
Yeah mines been offline 4 days- even clearing cache and doing the standard fixes off youtube do not work.
increased the cache size, clearing cache do not work. will keep checking here :(

**Comment by WestWorldMarshalUS1** [comment]
Sorted it - increased cache size - then go into SYSTE, add ons, my add ons -video add ons- select specto- then select update, do not select auto update - in new window select update Jarvis 11..11.1 then update. after update reboot.

then every thing should work :)

**Comment by mrknow** [comment]
Specto version 2016.11.18.1 has bug. Please update it to2016.11.18.3
