### ISSUE TITLE
Would like to speak if you have a moment.

### ISSUE THREAD

**Issue by s7eele** [mrknow/filmkodi#61]
Greetings, hope I am not bothering or intruding. I work closely with lambda and when he and I discussed your fork of genesis we had a couple questions we hoped you could answer or address. If you happened to see the tweet released by main TVADDONS account I want to explain that it did not reflect our thoughts on the matter, we realise this is how open source works. I don't know If you have Twitter but I can be reached @OG_s7eele there, you can also reach me me by sending a PM to s7eele on the TVADDONS forum. If some other communication platform works better just let me know and I will try to accommodate.

Thanks!

**Comment by mrknow** [comment]
Ok. I send you PM on the  tvaddons forum. My nick is mrknow

**Comment by s7eele** [comment]
Thx much, apology for slight delay but I responded. Talk there. I'll go ahead and close this issue, appreciate the response.
