### ISSUE TITLE
Problem z Logowaniem (CDA.pl)

### ISSUE THREAD

**Issue by marqius2** [mrknow/filmkodi#612]
Witam,
Mam wtyczkę mrknow. Dodałem Login i Hasło do konta premium w CDA.pl. Niestety, nie mogę odtworzyć żadnego filmu z sekcji Premium pomimo ,że na stronie CDA chodzi bez problemu. Po próbie włączenia filmu, po prostu nic się nie dzieje.

Czy jest może gdzieś jakaś opcja, którą powinienem uaktywnić dodatkowo ?
Z góry dziękuję za pomysły.

**Comment by maniek750** [comment]
Ja mam podobny problem z CDA Premium.... Jak wejde w zakladke Premium nic mi sie nie wyswietla :( Dodam ze usluge Premium mam aktywna ;)

**Comment by rysson** [comment]
Czołem.

Proszę o wersję wtyczki, wersję Kodi i logi (tryb debug).

**Comment by marqius2** [comment]
U mnie to jest KODI na Android TV- wersja 16.1. tylko nie wiem jak pobrać te logi z tej wersji :)

To nawet nie chodzi o menu premium.
Chodzi o to ,ze wyświetlając listę filmów klikam w film z dopiskiem premium (wpisałem w ustawieniach login i hasło ze strony CDA) i kompletnie nic się nie dzieje. Jak klikam w inny (nie premium) normalnie odtwarza.

**Comment by marqius2** [comment]
za chwile zainstaluję także KODI na kompie i dodam wtyczki + login + hasło. Zobaczymy czy pójdzie wtedy wykluczymy wersję systemu :)

**Comment by marqius2** [comment]
zrobiłem test. 
Ta sama wersja na lapku 16.1 + dodatek + login i hasło z CDA i również nic się nie dzieje. NAtomiast rusza cos (strumieniowanie) jak kliknę PPM i wybiorę "odtwórz z tego miejsca" to coś zaczyna się dziać i wyskakuje komunikat ,że nie może odtworzyć etc więcej info w dzienniku diagnostycznym. Ale w dziennikku nie mam zapisanych żadnych zdarzeń, chyba ,ze gdzieś jeszcze powinienem szukać

**Comment by maniek750** [comment]
@rysson tak, chodzi mi o menu PREMIUM.

**Comment by maniek750** [comment]
Jak wejdę w menu PREMIUM to mam wybór rodzaju filmu tzn. Akcja, Dramat itd, a później już pustka jest :(
Mam Kodi 16.1 na Nvidia Shield  TV z Androidem TV.

**Comment by rysson** [comment]
@marqius2 – Proszę o wersję wtyczki. Tak było 2..3 tygodnie temu. Sprawdź czy na pewno masz aktualną wtyczkę.

MrKnow napisał na wiki jak się dostać do logów: https://github.com/mrknow/filmkodi/wiki/Jak-przesłać-logi-z-kodi. Możne też ręcznie, logi są w pliku `$HOME/.kodi/temp/kodi.log`. Albo w podobnym miejscu dla Windowsa.

@maniek750, aha, czyli samo menu „PREMIUM” działa, tylko linki w jego pod-menu już nie. **Potwierdzam**. Na stronie cda.pl jest zawartość, we wtyczce nie. To jest bug. Ale to inny problem niż zgłoszony tutaj przez marqius2. Otwieram nowe zgłoszenie #618.

**Comment by marqius2** [comment]
Wtyczka 2016.11.05.2 logo później, zerknę jak w Tv je wyciągnąć

**Comment by rysson** [comment]
@maniek750, poprawione, Jak @mrknow wyda wtyczkę, to będzie działać.

@marqius2, hmm. Dziwne. Poprawka było w końcówce października. Teraz sprawdzam i działa. Bez logów się nie obejdzie. Na wiki jest metoda, działa przez jakiś dodatek.

**Comment by marqius2** [comment]
Trochę zreasumuję:
Zaktualizowałem wtyczkę na obu urządzeniach do osttniej.
I tak:

Mam KODI z mrknow na TV SOny z Androidem TV- filmy premium nie działają pomimo wpisania loginu i hasła
Zaintalowałem KODI i tą samą wtyczkę na kompie (WIN10)- te same kroki, i filmy premium również nie startują.
Zgrałem logi z kompa: https://paste.ubuntu.com/23492339/

Pojawiają się komunikaty : CDA.pl- PREMIUM- none

Dziwne :(

**Comment by rysson** [comment]
@marqius2, dzięki. Problemem jest
```
[plugin.video.mrknow] CDA.PL - PREMIUM NIE
```

Czy Ty możesz jeszcze raz sprawdzić ,czy hasło jest na pewno poprawne? Masz je zapisane w ustawieniach:
```bash
grep cdapl_pass $HOME/.kodi/userdata/addon_data/plugin.video.mrknow/settings.xml 
```

Ewentualnie, może masz jakieś dziwne krzaczki (np. polskie litery) w haśle?

**Comment by marqius2** [comment]
Zmienię jutro na cda hasło i wpisze inne. Dam znać o wyniku zmian.

**Comment by marqius2** [comment]
Nie wytrzymałem i sprawdziłem.  Zmiana hasła nic nie dała. Ale... Jako, że nie działa na 2 różnych urządzeniach wnioskuję, że sam serwis Cda może nie dopuszczać logowania poza ich strona bezpośrednio. Ciekaw jestem czy komuś to premium działa.

**Comment by rysson** [comment]
No mi działa bez problemu. Na razie nie mam pomysłu co może być nie tak. Może zwiększę ilość debug info w logu. 
A właśnie, możesz włączyć debug w kodi (gdzieś w ustawieniach) i jeszcze raz sprawdzić logi? W sensie okolicę `CDA.PL - PREMIUM NIE`.

**Comment by marqius2** [comment]
Napisałem do CDA z prośbą o sprawdzenie logów. Tak jakby ich serwer zwracał brak premium poprzez wtyczkę. Bo przez stronę jest OK

**Comment by rysson** [comment]
@marqius2, zobaczymy co odpowiedzą. To jest o tyle ciekawe, że przez wtyczkę (nieautoryzowaną) logowanie odbywa się przez ten sam formularz www co przez przeglądarkę.

Czy na stronie cda.pl po zalogowaniu widać tekst „Premium aktywne przez:”?

**Comment by marqius2** [comment]
Logując się na CDA.pl mam ikonę gwiazdki i jak wchodzę w ustawienia to jest aktywne premium. Nie mam ograniczenia czasowego.

**Comment by rysson** [comment]
O! Kiedyś był kod, który wykrywał „aktywne premium”, ale posiłkując się swoim kontem zmieniłem na „Premium aktywne przez”. Prześlij mi, proszę, zapisaną stronę HTLM tuż po zalogowaniu. Praz drugą, tę z ustawieniami, gdzie piszesz, że masz „aktywne premium”. Możesz dołączyć te strony tutaj (sam HTML).

P.S. Jak się uzyskuje bezterminowe premium?

**Comment by marqius2** [comment]
nie wiem czy się dobrze zrozumieliśmy. Teraz dodajesz jak w Ntflixie- karta kredytowa i po prostu jest premium. Nigdzie nie widzę do kiedy. Aż anuluję subskrypcję po prostu.

**Comment by marqius2** [comment]
hahahah...odpowiedź CDA Witam,
Dziękuje za wiadomość.
Serwis Cda.pl nie wspiera aplikacji KODI. Proszę kontaktować się z twórcami aplikacji.

Ze swojej strony mogę polecić technologię Chromecast.

W razie jakichkolwiek pytań służę pomocą.

Pozdrawiam,
Daniel Bochna

**Comment by rysson** [comment]
@marqius2 – karta kredytowa – rozumiem, sami pobierają. Ja wybrałem przelew stąd termin. Zaczyna być jasne.

Odpowiedzi się spodziewałem podobnej :-)

Dobra, naprawiając jedno, zepsułem drugie. Na 99%. Podeślij mi te strony jeśli możesz. To zaraz naprawię.

**Comment by marqius2** [comment]
tzn chcesz ,żebym stronę zapisał jako plik html ?

**Comment by rysson** [comment]
Dokładnie. Albo znalzł fragment 
```
<span class="menu-info-txt-content">
```
i co tam jest w okolicy, szczególnie co jest dalej.

**Comment by marqius2** [comment]
<span class="menu-info-txt-content">Twoje konto:<br/> premium</span>
</span>
</li>
<script>
var clickar=false;
jQuery('#moreOptionUser .tarrowhover').click(function(){
  jQuery('#moreOptionUserDropBox').attr('style','display:none');
});


jQuery('#clickarrow').click(function(){
	jQuery('.naviLoginArea').attr('style','display:none');
  jQuery('#moreOptionUserDropBox').attr('style','display:block');
  
  clickar=true;
  return false  
  }
);
</script>
</div>
</div>
<div class="second-top">
<span class="wrapper-counter"><span class="counter-people"><span id="guest_cntr"></span><span id="guest_cntr2"></span></span></span>
<span class="pull-right" style="height: 26px;line-height: 26px;vertical-align: middle">
<a href="/uploader" class="btn-mono-top-inl mono-sendgamevideo" style="margin-top:5px">dodaj grę lub wideo</a>
</span>
</div>
</div></div>
<script>

**Comment by rysson** [comment]
@marqius2, Dobra dodałem obie metody premium. Powinno działać. Jak tylko @mrknow wyda wtyczkę. 

Ewentualnie możesz pobrać jeden plik bezpośrednio z repo 
https://github.com/mrknow/filmkodi/blob/master/plugin.video.mrknow/lib/mrknow_urlparser.py
i wrzucić do kodi.

**Comment by marqius2** [comment]
Wielkie dzięki za zaangażowanie. 
Poczekam chyba na wtyczkę bo aż tak "biegły" nie jestem ,żeby pobrać ten jeden plik z repo. Po prostu nie mam pewności jak to zrobić a wolałbym już czegoś nie rozwalić ;)

**Comment by rysson** [comment]
Nie ma sprawy. Tym bardziej, że to ja sam popsułem, dodając drugą metodę premium.

Plik pobiera się prosto, ale nie namawiam. Zawsze też możesz zmienić jedną linię :-)
Commit: https://github.com/mrknow/filmkodi/commit/9865114af71bbb0dc55573835e0e89fdbbf505a6

**Comment by marqius2** [comment]
Jako ,że ja chętnie uczę się nowych rzeczy to gdyby "chciało " Ci się podpowiedzieć jak to pobrać byłoby super. Tzn plik pobrałem na pulpit ale nie wiem co dalej.
Bardziej mnie zastanawia czy na android tv jest to wykonalne (pewnie nie) 

A tak z ciekawości:  @mrknow ile wydanie poprawionej wtyczki może trwać ? Jestem z "wami" od niedawna więc te terminy są mi jeszcze obce.

Pozdr.
M

**Comment by rysson** [comment]
Ekstra. MrKnow robi to w wolnym czasie, z reguły wieczorem albo w weekendy. Ale może zaniknąć na parę dni, jak jest bardziej zajęty. Ja też jestem tu nowy, od miesiąca może.

Jak pobrałeś surowy plik (znaczy mrknow_urlparser.py) to teraz trzeba go przesłać jakoś na tego Androida do katalogu `$HOME/.kodi/addons/plugin.video.mrknow/lib/`. Nie wiem co tam masz, ja w smartphonie mam TotalCommandera i mogę sobie pliki przerzucać. 

Ewentualnie jak masz jakikolwiek edytor tekstowy na tym Androidzie, to możesz edytować plik `$HOME/.kodi/addons/plugin.video.mrknow/lib/mrknow_urlparser.py`, linię 1919 i zmienić tak jak w commit na zielono.

Jak się MrKnow nie odezwie dzisiaj to pomyślę co dalej zrobić. Teraz znikam na godziną, dwie..

**Comment by marqius2** [comment]
Wszystko jasne. WIELKIE DZIĘKI !!!!

**Comment by marqius2** [comment]
Informuję ,ze po Twojej instrukcji (zminiłem linię 1919) DZIAŁA !!!!! na kompie. A na TV pomyślę jak to zmienić , jak się nie uda, poczekam na aualizację wtyczki.

Teraz pojawiła się dodatkowo sekcja PREMIUM z posegregowanymi rodzajami filmów (horror, komedia, etcc.) Ale...nie ma tam filmów. Nie mniej jednak już się otwierają.

Szacun za pomoc.

**Comment by rysson** [comment]
Świetnie!

Puste podkatalogi wczoraj załatałem (#618), commit: e76f89464d4e5a7722a947fbe07703763d796dee. Tam jest parę linijek do poprawy. Chyba łatwiej na PC podmienić cały plik: https://github.com/mrknow/filmkodi/blob/master/plugin.video.mrknow/host/cdapl.py

**Comment by maniek750** [comment]
Ja chyba jednak poczekam  na aktualizację, bo jestem laikiem w tych rzeczach :D

**Comment by rysson** [comment]
@maniek750, a kolega zaglądał na http://kodi.filmkodi.com/beta/plugin.video.mrknow/? Tam leżą wersje testowe. MrKnow wczoraj zbudował paczkę plugin.video.mrknow-2016.11.18.1.zip

**Comment by maniek750** [comment]
Dzieki @rysson ale jeszcze nie zagladalem :( Dzisiaj to wieczorem zrobie i sprobuje ta wersje testowa zaladowac do KODi ;)

**Comment by marqius2** [comment]
@rysson Ja na android tv dzięki exploratorowi podmienilem pliki i na tv także działa ;-)

**Comment by maniek750** [comment]
Zaladowalem wersje testowa i teraz dziala ;)
