### ISSUE TITLE
proszę o kontakt 

### ISSUE THREAD

**Issue by Innyczlowiek** [mrknow/filmkodi#615]
## Issue / Zgłoszenie
- [ ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [x] Other / Inne

---
proszę o kontakt w sprawie współpracy 

contact@yoy.tv

**Comment by rysson** [comment]
@mrknow działa głównie weekendami. On jest zarządcą.

**Comment by rysson** [comment]
@Innyczlowiek, a najlepiej kontaktować się przez stronę http://filmkodi.com/pl/wtyczki/

**Comment by mrknow** [comment]
@Innyczlowiek 
Mail poszedł ...
