### ISSUE TITLE
Yoy.tv nie dziala

### ISSUE THREAD

**Issue by rootsterisk** [mrknow/filmkodi#619]
Witam, 
Nie dziala telewizja Premium yoy.tv, nawet po wpisaniu dobrego hasła, dostaje komunikat, ze user albo hasło jest złe, czy problem jest znany?

**Comment by koladka** [comment]
Tez to mam ;) Tymczasowo przezucilem sie na videostar i na dodatek Adrian List znalazlem dzialajacy serwer z mnustwem Polskich kanalow!

**Comment by mrknow** [comment]
W wersji 2016.11.18.2 powinno działać poprawnie

**Comment by koladka** [comment]
Niestety nadal niedziala!;( Teraz nawet videostar niedziala!!! Cos niechula po aktualizacji;) Nawet na darmowej  przedtem  Filmy online-mr know cos sie znalazlo a po aktualizacji nawet na tym lipa $$$

**Comment by rootsterisk** [comment]
Potwirdzam , ze nie dziala 

Mit besten Grüßen,

Sebastian Zasadzinski

**Comment by rootsterisk** [comment]
Potwierdzam, ze nie dziala w najnowszej wersji

**Comment by rootsterisk** [comment]
@koladka zadzaialo Tobie moze?

**Comment by koladka** [comment]
Niestety nie dziala! Ogladam na serwerach iptv np Adrian List lub dzis nowy na tom raiden repo jest video app- piramid i tam tez pelno serwerow na world iptv z polskimi kanalami

**Comment by mrknow** [comment]
Dzięki - zatem plan B. Prosze o cierpliwość. pracuję nad tym.

**Comment by koladka** [comment]
http://repo.adryanlist.org/plugin.video.adryanlist-2.6.8.zip

**Comment by marekodfiranek** [comment]
hey gdzie w adryanlist sa PL kanały?Pozdrawiam

**Comment by koladka** [comment]
Sprubuj serwer 1019 !  Trzeba szukac!  A pozatym  pyramid iptv z tom raider
repo

20.11.2016 12:43 PM "marekodfiranek" <notifications@github.com> napisał(a):

**Comment by rootsterisk** [comment]
Dziala yoy.tv

**Comment by koladka** [comment]
Dalej lipa nie dziala Mr know pisal ze pracuje nad poprawka

**Comment by mrknow** [comment]
Teraz puściłem wersję  2016.11.21.1. Ta wersja powinna działać. Było kilka problemów, ale myśle że już wszystkie rozwiązane. 
Proszę wyczyśćcie cache MrknowTV>Ustawienia> Wyczyść cache

Problemem były
- polskie znaki - jeżeli w tytule były polskie znaki to nie działało 
-  cookies (ciasteczka) nie były dobrze obsługiwane

**Comment by koladka** [comment]
Jest coraz gorzej .wszystko siadlo , niewiem jak u innych ale u mnie wywala calkiem nic niedziala

**Comment by daria0607** [comment]
Czy działa komus yoy bo mi przez miesiac udalo sie wlaczyc tylko 2 razy nikc jr. i jestem rozczarowana bo mam dzieci i nie moga ogladac bajek bo na weeb tv to prawie juz nic nie ma ;/

**Comment by koladka** [comment]
Na Adrian List masz cale serwery codzien upd. Z nowym iptv a pozatym na
zwyklym mr.know jest mnustwo dzialajacych Polskich kanalow

25.11.2016 12:01 "daria0607" <notifications@github.com> napisał(a):

**Comment by mrknow** [comment]
Prosze o przesłanie logów yoy.tv powinno śmigac od tygodnia dla kont premium

**Comment by rootsterisk** [comment]
Ogolnie u mnie wszystko działa!!! Trzeba cache wyczyścić tylko!!!

**Comment by daria0607** [comment]
ja wyczyscilam cache i nie dziala ;/

**Comment by daria0607** [comment]
i pisze teraz nieudane wykonanie skryptu mr know;/

**Comment by rootsterisk** [comment]
A zrobiłaś update wtyczki?

**Comment by daria0607** [comment]
a jak mam to zrobic nie bardzo sie na tym znam ?;/

**Comment by koladka** [comment]
Poprostu ja odinstaluj i zainstaluj od nowa! Tak czy inaczej u mnie nadal
nie dziala!

26.11.2016 20:46 "daria0607" <notifications@github.com> napisał(a):

**Comment by daria0607** [comment]
ok

**Comment by daria0607** [comment]
u mnie tez dalej nie dziala ;/

**Comment by daria0607** [comment]
dzialalo mi yoy przez tydzien a od dzis nawet w yoy wejsc nie idzie czy znowu cos jest nie tak?

**Comment by koladka** [comment]
Juz pisalem na forum nic nie dziala;)  Ja szulam po necie i korzystam z
zagranicznych wtyczek iptv zeby ogladac Pl tv



08.12.2016 06:40 "daria0607" <notifications@github.com> napisał(a):

**Comment by mrknow** [comment]
poprawiłem. Prosze o weryfikację

**Comment by koladka** [comment]
Niestety cos tam zaczelo dzialac pare kanalow ale przy opcji wyboru stram
np z wizja czy web i td. ,otwiera tylko z iklub!;)

11.12.2016 19:56 "MrKnow" <notifications@github.com> napisał(a):

**Comment by daria0607** [comment]
Mam takie pytanie caly czas mi dzialalo i kupilam abonament na rok i nie dziala znowu pisze brak dostepnego strumienia danych ale konto wazne do  2018 ;/ wyczyscilam cache i nic

**Comment by koladka** [comment]
Ja przeszlem na epg --- m-tv guid  i tam w opcjach masz np . yoy tv! Mi teraz tak dziala z premium .

**Comment by daria0607** [comment]
nie wiem jak ainstalowac na boxie to mtv guide predzej mialam teraz nie mam;/

**Comment by koladka** [comment]
repository.mods-kodi-0.1.1.zip
Masz tu repo a dokladne instrukcje na stronie :: kodi w pigulce:: wpisz w przegladarke dalej reszta prosta

**Comment by daria0607** [comment]
ok dziekuj zobaczymy czy mi zadziala :)

**Comment by frijerz** [comment]
Zadziala, wszystkim dziala to i Tobie zadziała :)

**Comment by daria0607** [comment]
zrobilam mam ale niestety kanaly co sa na yoy to w tym mtv guide nie otwieraja mi sie wszystkie najbardziej mi na kanalach dzieciecych zależało to na stronie yoy mam duzo a tu tylko 1 ;/

**Comment by daria0607** [comment]
jest nadzieja ze ten mr know zacznie znow dzialac czy raczej nie bo przez ten mtv guide okropnie sie zacina ;/ nawet nic obejrzec nie idzie;/ i co chwile bez glosu ;/

**Comment by koladka** [comment]
Ja mam wszystko cud miod! A nastawilas w opcjach wedlug filmiku  ultimate kodi ;) Tam mozesz dodac rowniez tele-wizje lub weeb i prorytet sie nastawia ;)  i strefe czasowa ;)  Mozesz rowniez sprobowac przyspieszyc bufering na Ares wizard  jest taka opcja. A pozatym moze masz slaby net stad moze tak zacina ja mam 50 mega i tylko raz na jakis czas przytnie

**Comment by daria0607** [comment]
zrobiłam wszystko jak ten pan na filmie i nie wiem czemu nie mam wszystkich kanalow z yoy np z bajek mam tylko CN ale dziala bardzo zle co chwile bez glosu  , abc . nick  i disney junior ale nei dziala;/ a na yoy jest jeszcze duzo innych

**Comment by daria0607** [comment]
mieszkam w niemczech wzielismy najszybszy internet z unitymedia kupilam nowego boxa do telewizora i bylo super lepiej niz na starym boxie na starym bylo katastroficznie ale bylam 3 tygodnie na urlopie i przyjezdzam i nie dziala mi ten mr know ;/

**Comment by koladka** [comment]
Ja w Uk i dziala wiec niewiem;)Moze sprobuj przeinstalke zrobic wizarda ja zainstalowalem na tv boxa durex bu.a na projektorze z andkiem mam puls i smiga;)

**Comment by daria0607** [comment]
a masz moze yoy? jesli tak to jakie masz kanaly dla dzieci ?

**Comment by koladka** [comment]
Na yoy niedzialaja kanaly dzieciece nawet na ich stronie widocznie nikt nie transmituje tak jak pisalem daj prorytet wysoki na weeb tv i zaznacz tez telewizja tv na wysoki wpisz w chasle byle co ja tam nie mam premium i dozuca mi reszte kanalow na m-tv guid z tych serwisow i full wypas  teraz mam mala corcie i oglada disney junior bumerang , jest tez cn, nick j.,cbbc a czasem baby tv

**Comment by daria0607** [comment]
predzej jak wchodzilam przez mr know dzialaly mi wszystkie bajki teraz nawet jak wchodze przez ten m tv guide tak po paru minutach wywala mnie z kanalu;/  ta wizja tv co niby konto darmowe nawet mi nie dziala;/

**Comment by daria0607** [comment]
a iptvlive idzie ustawic w tym m tv guide ? bo nie wiedze tam takiej opcji ;/

**Comment by daria0607** [comment]
w ogole to dlaczego np weeb tv mi dziala przez mr know a tylko to yoy nie dziala ;/

**Comment by koladka** [comment]
Bo jest wtyczka popsuta;) Niewiem co u ciebie jest nie tak mi przez  to Epg m - guid Yoy dziala ;)

**Comment by daria0607** [comment]
ja tez nie wiem ale mam nadzieje ze niedlugo znowu bedzie wszystko dzialac bo yoy wykupilam na rok a szkoda ze nie moge wszystkiego ogladac;/

**Comment by frijerz** [comment]
Jest problem z ogladaniem serwisu YOY na wtyczkach. Na mTvGuide dzialaja aktualnie trzy kanaly dla dzieci: CN, Disney XD i Junior bez zacięć. Warto sprawdzac mTvGuide, bo administratorzy często poprawiaja wtyczkę, duzo czesciej nic MrKnow czy inni. Wiec jest szansa.
Na czym ogladasz? Jesli na Androidzie to moge Ci podeslac wtyczke YOY.TV, ale nie wiem czy dziala, musisz sprawdzic. Jakie kanaly Cie interesują?

**Comment by koladka** [comment]
U mnie dzialaja prawie wszystkie z bajek jeszcze tvp abc, to na boxie 3 gb ram z andkiem 6!  Probowalem na smarfonie andka apke yoy tv lecz niedziala jest tam jakis blad:)

**Comment by daria0607** [comment]
mi na mtv guide odbieraj z weeb ale na weeb nie mam juz konta doladowanego wiec dlugo sie nie da ogladac z yoy dzialaja mi tylko polsat itp ale z bajek nic ;/ ogladam na boxie podłączonym do telwizora

**Comment by daria0607** [comment]
czy ktos wie gdzie napisac zeby oni zrobili cos z wtyczka ? mam zaplacone ogladac nie moge nawet przez ten mtv guide ;/  dzisiaj dziala mi tylko tvp abc i polsat tvn hbo nawet nie dziala przez ten mtv gudie w ogole katastrofa;/

**Comment by koladka** [comment]
Dario niewiem gdzie tkwi problem u ciebie  ale zapewniam cie ze ja ogladam yoy tv przez mtv- gv i jest ok

**Comment by daria0607** [comment]
ja np dzis mam disney chanel ,xd , CN , nick hd i abc i dziala tylko abc ;/ CN wlaczyl sie na chwile i bez glosu ;/  rano 5 minut bylo nick junior ;/ a przez tableta mam wszystkie kanaly ;/ wiec ja nie wiem gdzie jest problem przedej przez mr know dzialalo super a teraz nie wiem nic nie moge dzieciom włączyć ;/

**Comment by koladka** [comment]
Bo Mr know co jakis czas wtyczke naprawia czyli zmienia serwery streamu:) Na to nic nieporadzisz dlatego jest darmowa i robi to z pasji kiedy ma tylko czas;)
