### ISSUE TITLE
Wizja

### ISSUE THREAD

**Issue by Arek76** [mrknow/filmkodi#621]
## Kodi & OS
- Kodi verison: _____
- OS version: _____

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [x] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis

witaj Know , wlasnie jestem u klienta i zainstalowalem na kilku urzsadzeniach Kodi wraz z Twoja wtyczka, Niestety nie da sie zalogowac do wizji tv na rzadnym urzadzeniu . Na komputerze rowniez nie . po wpisaniu danych klikajac pozniej button wizja tv nie ma zadnej reakcji tak jakby bylo nie czynne co to moze byc jesli jestes odpowiedz szybko bo wlasnie nad tym pracuje . pozdrawiam Know

**Comment by mrknow** [comment]
Może problem z internetem, może kodi 17 i nie ma zainstalowanej obsługi RTMP. Trochę po tym opisie ciężko stwierdzić. 

Zawsze dołączaj logi, wtedy jestem w stanie precyzyjnie odpowiedzieć. Dołączamy logi następująco 
MrknowTV > Tools /Ustawienia > Send diagnostics logs / Wyślij logi do diagnostyki 

I wklejasz link jaki ci się wyświetlił

**Comment by Arek76** [comment]
Sorry Know za nie wklejenie , Bylem u klienta i troszke czasowo nie wyrabialem . Teraz nawet nie mam dostepu do Loga ale postaram sie zorganizowac i go tu wkleic . Problem wystepowal na wielu urządzeniach tak jak pisalem , Laptop z systemem 8 , Box z windowsem 10 , Box z Androidem 5 . Kodi zawsze 16.1 poniewaz tylko tego narazie instaluje . Dziwnie to wszystko wyglądalo ponieważ wszystkie wtyczki dzialaly bezproblemowo , Chocby Eska  Tv czy Weeb w MrKnowTV, Tylko jedynie wizja nie reagowala . Najdziwniejsze jest to że to samo urządzenie po jakiejs godzinie uruchomilem u innego klienta i dzialal bez problemow , Pomyslalem że moze jakas zapora windows czy coś no ale czy zapora instaluje sie na routerze skoro nie dzialają wszystkie urządzenia i blokuje tylko skrypt wizji ? Ma Avire free antywisrus . Uruchomilem u niego w mieszkaniu moj telefon z kodi i sprawdzilem rowniez nie dzialal , po czym u mnie w domu juz wszystko wrocilo do normy . Ciekawe to jest bardzo , Na poczatku myslalem że moze to wina wtyczki stad moj post ale napewno nie , Jak sie uda poprosze klienta by wyslal mi log i go tu wstawie ale do tego czasu i tak bede sie zastanawial co moze byc przyczyną ze akurat tylko ta wtyka nie dzialala :) masz jaką idee ? pozdrawiam Know

**Comment by Arek76** [comment]
Nie umiem sobie z tym poradzic , Ciekawostką jest że zdarzylo sie to ponownie u mojego drugiego klienta , mieszka bardzo daleko i sam nie umie wyslac mi logow , Ja niestety nie bede jechał bo kosztowalo by mnie to zbyt wiele czasu . Jest jeszcze jedna informacja nowa do tego co napisalem wczesniej a mianowicie , Gdy wchodzi sie bezposrednio na strone wizji (obojetnie na jakim urzadzeniu nalezy wpisac Capcha kod , Niegdy tego nie bylo teraz jest . Dopowiem tyle że oby dwoje klientow maj,ą internet od tego samego providera i te same routery . Z tego co mi klient probowal przeczytac z loga jest to problem ze strefą czasową ... Cholerka nie rozumiem tego :) Moze masz jakis pomysl?
