### ISSUE TITLE
"No stream available" message

### ISSUE THREAD

**Issue by caaviana** [mrknow/filmkodi#623]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: 16.1
- OS version: Windows 10 x64

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [ ] MrknowTV
- [x] Specto
- [ ] FanFILM
- Version / Wersja: 2016.11.18.1

---
## Issue / Zgłoszenie
- [x] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Hello MrKnow,

Past days I'm getting the message "no stream available" all the times I try to watch any movie.
Here is the log link after three times tried: http://paste.filmkodi.com/view/9a30b0d2

Thank you.

**Comment by royweurt** [comment]
Hello,

I have the same issue...
http://paste.filmkodi.com/view/ec3c7d35

**Comment by maroc2** [comment]
I have the same issue now all links now saying no streams this now along with favourite episodes not working

**Comment by hubertjacson** [comment]
I'm also having the same issue.

**Comment by caaviana** [comment]
And with Kodi 17 the same thing...
Link log: http://paste.filmkodi.com/view/50d57295

**Comment by lazyprince** [comment]
Same issue, v16.1

**Comment by ookami007** [comment]
Same issue since the last update.

Kodi 17.0-BETA6
Amazon Firestick

**Comment by mrknow** [comment]
Specto version 2016.11.18.1 has bug. Please update it to2016.11.18.3

here are instructions,  how to update kodi add-on manualy http://filmkodi.com/en/openload-fix/
