### ISSUE TITLE
Lookinij.in - Not Supported python version 2.6.5 Minimum 2.7.9

### ISSUE THREAD

**Issue by marekodfiranek** [mrknow/filmkodi#625]
Hey,
Już o to pytałem ale teraz rozwijam .

W MR KNOW TV podczas włączenia Looknij.in pokazuje się 
.." Lookinij.in - Not Supported python version 2.6.5 Minimum 2.7.9 "..
Jednak we wtyczce LIVEPOLISHTV działa Looknij.in niestety tam tam nie ma opcji do logowania się i zostaje to co darmowe.

Czy da rade coś "zakombinować z tym"?

Kodi :16.1
Android: 6.0

**Comment by xxcriticxx** [comment]
@marekodfiranek narazie strona jest offline

**Comment by mrknow** [comment]
A spróbuj zainstalować kodi 17 beta i przetestować jeszcze raz ..

**Comment by mrknow** [comment]
W razie co Kodi17 beta nie wspiera domyślnie protokołu rtmp

Tu masz info jak to włączyć http://filmkodi.com/pl/wlaczyc-rtmp-kodi-17-beta-5-lub-wyzszym/
