### ISSUE TITLE
Wizja.tv przerywa

### ISSUE THREAD

**Issue by mokaluzna** [mrknow/filmkodi#629]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: __x___
- OS version: _____

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [x] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: _2016.11.18.2____

---
## Issue / Zgłoszenie
- [x] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

Problem jest taki, że po 5-10 minutach wizja.tv przerywa program, wyrzuca do spisu kanałów. Następnie po wybraniu kanału kilka razy pod rząd przerywa. 

[http://paste.filmkodi.com/view/ab23ffb2](url)

**Comment by mrknow** [comment]
Może to było chwilowe. Teraz u mnie działa OK
