### ISSUE TITLE
How to reset the marked as watched in movies 

### ISSUE THREAD

**Issue by iznogud88** [mrknow/filmkodi#631]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: 16.1
- OS version:Android 5.1

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [ ] MrknowTV
- [x] Specto
- [ ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [ ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [x] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

**Comment by rysson** [comment]
Google? https://www.google.pl/search?client=opera&q=kodi+reset+watched+status&sourceid=opera&ie=UTF-8&oe=UTF-8

It's feature of kodi, not addon. 
See first link: http://forum.kodi.tv/showthread.php?tid=256019

**Comment by mrknow** [comment]
status of watched movie is stored in Metahandler plugin 
In user data find file addon_data/script.module.metahandler/meta_cache/video_cache.db and remove it.

In linux this file is in  .kodi/userdata/addon_data/script.module.metahandler/meta_cache/video_cache.db

Userdata folders - http://kodi.wiki/view/Userdata
