### ISSUE TITLE
Wtyczka mrknow a tvguide.

### ISSUE THREAD

**Issue by rafsogmail** [mrknow/filmkodi#636]
Po ostatnich aktualizacjach ( prawie cały listopad ) wtyczka nie współpracuje iamguide i mtvguide. wcześniej działało świetnie. W miarę poprawnie działa z tvguide, który jednak ma mocno ograniczone możliwości.

**Comment by pat1970** [comment]
Do you speak english

**Comment by mrknow** [comment]
Na razie nie planujemy integracji być może powrócimy do tego za kilka miesięcy. Proszę się dowiadywać w lutym 2017

**Comment by rafsogmail** [comment]
Witam. Dzikuję za info. Obecnie MrKnowTv bardzo fajnie współpracuje z
TV Guide Fullscreen.We wtyczce MrKnowTv dodaję do ulubionych
interesujące mnie programy, a później wybieram je z ulubionych poprzez
wtyczkę TV Guide Fullscreen. Taka opcja nie działa już z innymi epg
oprócz wymienionego wyżej i oryginalnego TV Guide. Pozdrawiam.

26.11.2016, MrKnow <notifications@github.com> napisał(a):

**Comment by mrknow** [comment]
Dzięki za opis obejścia problemu
