### ISSUE TITLE
player.pl on MrknowTV not working

### ISSUE THREAD

**Issue by Daszek** [mrknow/filmkodi#638]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: 16 Jarvis
- OS version: OSMC na RaspberryPi

---
## Addon / Wtyczka
- [x] Filmy online - Mrknow
- [x] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: 18.11.2016

---
## Issue / Zgłoszenie
- [x] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis

Filmy z player.pl w ogóle nie działają - od jakichś 2 tygodni. Jeśli to możliwe to proszę napraw :+1: 
Korzystając z okazji dziękuję Ci za twoją pracę.

**Comment by rysson** [comment]
To jest to samo co #583, czy coś dodatkowo?
Może by połączyć te zgłoszenia.

**Comment by pat1970** [comment]
Can you reply in english

**Comment by pat1970** [comment]
What do i do  now

**Comment by eko5** [comment]
install repo http://sd-xbmc.org/repository/repository.sd-xbmc.org/repository.sd-xbmc.org-2.0.0.zip
install telewizja polska ( kanaly,VOD,filmy,seriale )
changes settings is platform on panasonic

**Comment by rysson** [comment]
@eko5 , pat1970 puts comments in random way. He create issue 3 times. And request solution in ANY thread.

BTW, you have translate your post to "english", see https://github.com/mrknow/filmkodi/issues/632#issuecomment-262793976

**Comment by Daszek** [comment]
@eko5
Thank you. This solved my problem..

**Comment by mrknow** [comment]
Poprawione w wersji 2016.11.26.1
