### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by PijanyMistrz** [mrknow/filmkodi#64]
Witam,
Jestem zielony w kwestiach związanych z informatyką i czy ktoś może mi pomóc. Mianowicie dzisiaj zainstalowałem program kodi i chciałem wgrać wtyczke mrknow. Niby zrobiłem wszystko zgodnie z instrukcją ale przy próbie włączenia wyskakiwał mi zawsze komunikat "błąd dodatku filmy online - mrknow.pl. Więcej informacji na ten temat znajdziesz w pliku dziennika diagnostycznego". Próbowałem jeszcze raz wszystko instalować ale nic to nie dało ktoś może pomóc?

**Comment by xxcriticxx** [comment]
podaj info 

jaki system 
jaki sprzent 
jak montowales
czy inne plugin dzialaja

sprobuj odmontowac i zamontowac jeszcze raz

**Comment by PijanyMistrz** [comment]
No to tak 
Windows 7 Home Premium sp1
procek intel i5 3350p
karta radeon hd 7850
płyta główna to asrock b75 pro3
coś jeszcze podać?
Montowałem tak jak jest podane na stronie głownej sciągnąłem te repozytorium póżniej zainstaluj repozytorium przez zip pozniej wziąłem zainstaluj tą wtyczke filmy online.
Tak działają nawet dołączone w tym repoztytorium działały np specto genesis fork

**Comment by xxcriticxx** [comment]
masz polskie znaki w user name?

podasz log?

**Comment by PijanyMistrz** [comment]
Logi czego nie wiem o co chodzi mówiłem że jeśli chodzi o informatykę to jestem zielony. Z tym user name też nie wiem o co chodzi ale windows wszytko jest polskie. Dodam tylko że teraz jak uruchamiam kodi to wyskakuje że "błąd dodatku common cache" nie wiem czy to się odnosi do tego.

**Comment by xxcriticxx** [comment]
https://github.com/mrknow/filmkodi/wiki/Jak-przes%C5%82a%C4%87-logi-z-kodi

**Comment by mrknow** [comment]
Proszę zaktualizuj wtyczke i sprawdź czy działa
