### ISSUE TITLE
Specto not working

### ISSUE THREAD

**Issue by azzergooner** [mrknow/filmkodi#641]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: _____
- OS version: _____

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [ ] MrknowTV
- [x] Specto
- [ ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [x] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

**Comment by azzergooner** [comment]
8

**Comment by azzergooner** [comment]
I cant see my issue.

Specto won't load anything up past the menus at all.
The log is http://paste.filmkodi.com/view/d160071d

Any ideas on how to fix. I have uninstalled and reinstalled lots of times

**Comment by eko5** [comment]
yes deleted all files in .kodi folder manually and install specto

**Comment by mrknow** [comment]
@eko5 is right. Install Specto on a clean install. It should work
