### ISSUE TITLE
Filmy online - Mrknow - error 

### ISSUE THREAD

**Issue by uicsog** [mrknow/filmkodi#646]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: 16.1
- OS version: OSMC 2016.10-2

---
## Addon / Wtyczka
- [x] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: 2016.11.26.1

---
## Issue / Zgłoszenie
- [x] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis

Wtyczka nie uruchamia się.
Pojawia się komunikat 'Filmy online - Mrknow - error'

W logu:

09:45:25  60.040825 T:1479537648   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named plugins
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.mrknow/default.py", line 111, in <module>
                                                import wykop, filmbox,vodpl, filmydokumentalne, efilmyseriale
                                              File "/home/osmc/.kodi/addons/plugin.video.mrknow/host/wykop.py", line 14, in <module>
                                                import mrknow_pLog, mrknow_pCommon, mrknow_Parser,mrknow_urlparser
                                              File "/home/osmc/.kodi/addons/plugin.video.mrknow/lib/mrknow_urlparser.py", line 18, in <module>
                                                import urlresolver9 as urlresolver
                                              File "/home/osmc/.kodi/addons/script.mrknow.urlresolver/lib/urlresolver9/__init__.py", line 39, in <module>
                                                from plugins import *
                                            ImportError: No module named plugins
                                            -->End of Python script error report<--
09:45:25  60.186256 T:1956176816   ERROR: GetDirectory - Error getting plugin://plugin.video.mrknow/
09:45:25  60.192379 T:1956176816   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mrknow/) failed

Disable/Enable, Reboot, Reinstall nie pomogło

Dzięki

**Comment by mrknow** [comment]
nie zainstalował  się dodatek zależny prawidłowo 
ściągnij plik http://kodi.filmkodi.com/script.mrknow.urlresolver/script.mrknow.urlresolver-2016.11.4.1.zip

I zainstaluj ręcznie 
System>Dodatki>Zainstaluj z pliku zip 
http://filmkodi.com/wp-content/uploads/2016/05/Zrzut-ekranu-z-2016-05-31-00-24-10.png

**Comment by uicsog** [comment]
Pomogło :)

Dzięki za szybką pomoc!
