### ISSUE TITLE
wizja.tv - brakujace kanaly

### ISSUE THREAD

**Issue by jakunow** [mrknow/filmkodi#647]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: _____16.1 Git:2016-04-24-c327c53
- OS version: _____Android 5.1.1 API level 22 (kernel: Linux 3.10.61+)

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [X ] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: _____2016.11.21.1

---
## Issue / Zgłoszenie
- [ X] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>

Na liscie kanalow nie sa wyswietlane niektore z nich. Przykladem brakujacych sa: TVN, TVP1. Przykladem obecnie dostepnych sa: VIVA, TVN7
Uzywajac strony wizja.tv bezposrednio w przegladarce kanaly sa dostepne.

**Comment by mrknow** [comment]
proszę przeslij logi, za pomocą wtyczki i wklej tu link
wchodzisz w MrknowTV> Ustawienia > Wyślij logi diagnostyczne

**Comment by Arek76** [comment]
Czyzbys uzywal Kodi w wersji 16.0? Jeden z moich klientow rowniez takowy problem mial że po wcisnieciu danego programu kanal znikal z listy . Przeinstalowanie do stabilnej wersji 16.1 rozwiazuje problem

**Comment by jakunow** [comment]
Mój błąd. Okazuje się, że nie było żadnego problemu i że to moje przeoczenie.

Kanały, które zostały obejrzane zaczęły być oznaczone jako "Obejrzane" (Watched). Zapewne przez przypadek włączyłem opcje w Kodi "Ukryj obejrzane" (Hide watched). Opcja ta jest dostępna w menu po lewej stronie ekranu.

Po wyłączeniu tej opcji wszystkie kanały są na liście.
