### ISSUE TITLE
Problem z przewijaniem filmów

### ISSUE THREAD

**Issue by makakut** [mrknow/filmkodi#65]
Witam wszystkich wczoraj zainstalowałem dodatek MRknow z linku http://filmkodi.com/repository/repository.filmkodi.com.zip

Obecnie mam Kodi z paczki dpkg w wersji 15.2 (Debian Backports) uruchomione na Debian 8.3 (Jessy).

Wszystko działa co do odtwarzania. Jednak jeśli podczas odtwarznaia wystąpi błąd. Nie mogę wrócić do momentu odtwarzania. Nie mogę też przewijać nowych filmów. Testowałem w serwisach cda.pl oraz zalukaj.tv. Próbowałem zmienić w ustawieniach playera z domyślnego na mplayer. Bez zmian.

Czy komuś działa przewijanie filmów?

**Comment by xxcriticxx** [comment]
android czy win7?

czy masz hard drive w maszynie?

**Comment by makakut** [comment]
Linux debian 8. Tak mam harddrive :) i 4gb pamięci. Dodam że we w tyczce
specto genesis przewijanie dziala.

android czy win7?

czy masz hard drive w maszynie?

—
Reply to this email directly or view it on GitHub
<https://github.com/mrknow/filmkodi/issues/65#issuecomment-180136279>.

**Comment by xxcriticxx** [comment]
odpal serwise co uzywasz firefox i zobacz czy przewijanie dziala

podaj najlepjej link ja sprawdze

**Comment by makakut** [comment]
zalukaj.tv lub cda.pl

Przez przeglądarkę chrome uruchamianą z tego samego kompa działa. 

Zerknę w logi kogi.log. 

Nie działa mi też wyszukiwanie. To znaczy zwraca pusty wynik. 

Przy przewijaniu widać że wywala się na prcesie buforowania.

A komuś przewijanie działa? Jeśli tak to pod jakim systemem?

**Comment by makakut** [comment]
Zainstalowąłem tą samą wersję KODI 15.2 na drugim komputerze z Windows. Czysta instalacja Kodi + dodatek MrKnow. To samo przewijanie filmów w zalukaj.tv lub cda.pl nie działa. To chyba jednak coś z pluginem.

**Comment by xxcriticxx** [comment]
umnie cda.pl dziala a w zalukaj.tv niestety nie 

testowalem w firefox z zalukaj i dziala czyli mrknow bendzie musial cos poprawic

**Comment by mrknow** [comment]
Na Zalukaj, nie będzie działało przewijanie. To jest sterowane przez kodi i nie potrafie tego programowo poprawić 
Dodałem cda.pl, oraz efilmy.tv - więc mozna zawsze filmy oglądac na innych serwisach
