### ISSUE TITLE
yoy tv nie reaguje

### ISSUE THREAD

**Issue by gigi8512** [mrknow/filmkodi#651]
Mam problem z wtyczką yoy tv nie łączy się z żadnym kanałem wyskakuje mi komunikat "Nieudane odtwarzanie jednej lub więcej pozycji"

**Comment by borys76** [comment]
Masz premium  wykupione-wpisane?

**Comment by gigi8512** [comment]
wszystko działało dzisiaj nic nie idzie

**Comment by Eva2204** [comment]
Mam to samo od paru godzin. Sprawdzalam haslo itp a premium mam wykupione

**Comment by Eva2204** [comment]
A normalnie przez strone dziala  i bez zacinania.

**Comment by pee111** [comment]
Mam to samo. Dawno nie bylo aktualizacji wtyczki.
Znacie jakas alternatywe do odtwarzania YOY.tv na Kodi albo ogolnie na Androidzie?

**Comment by mar2016** [comment]
Maja na stronie app dla androida

**Comment by gigi8512** [comment]
Mój log http://paste.filmkodi.com/view/a2959a21

**Comment by Corbatus** [comment]
Ja tez mam to samo: Nieudane odtwarzanie jednej lub wiecej pozycji. Wiecej informacji na ten temat znajdziesz w pliku dziennika diagnostycznego a w niedziele jeszcze bylo wszystko ok  ktos wie jak to naprawic????

**Comment by mmalinowski123** [comment]
U mnie to samo.

**Comment by marekodfiranek** [comment]
Czy dało by radę naprawić dostęp do yoy.tv ?

**Comment by mrknow** [comment]
Poprawione
