### ISSUE TITLE
Nowe kanały do EskaGO

### ISSUE THREAD

**Issue by bart7890** [mrknow/filmkodi#653]
Witaj,
Dałoby radę dorzucić może 8TV i Nową TV do działu EskaGO?
http://www.eskago.pl/tv/8tv
http://www.nowa.tv/player/
Pozdrawiam. :)

**Comment by rysson** [comment]
Może kiedyś. Niestety mamy mało czasu, a projekt wymaga sporej reorganizacji.
Cierpliwości.

**Comment by mrknow** [comment]
http://www.eskago.pl/tv/8tv - dodałem. Nowa.tv trzeba będzie poczekać w kodi
