### ISSUE TITLE
Last update broke fmovies

### ISSUE THREAD

**Issue by raymond4400** [mrknow/filmkodi#655]
For some reason the last update broke fmovies. Update 11-30

**Comment by raymond4400** [comment]
Moved to specto

**Comment by mrknow** [comment]
Unfortunately. Fmovies  changed the way to access the video links. 
Try to work it out but it is not easy.

**Comment by raymond4400** [comment]
That sucks.... Your addon is the only one that had fmovies working. Content is quite a bit different then 123. Probably why Mucky never fixed his original addon. Hopefully there is a work around.

**Comment by mrknow** [comment]
Fixed
