### ISSUE TITLE
weebtv-nie laduje kanalow

### ISSUE THREAD

**Issue by oldnorda** [mrknow/filmkodi#659]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: ____16_
- OS version: _____

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [ x] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [ x] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Jak w temacie, kreci sie kolko ladowania, po chwili przestaje i nic sie nie zmienia. Login i haslo sprawdzone i wpisywane poprawnie.

**Comment by mrknow** [comment]
u mnie załadował, ale długo to trwało ....

**Comment by oldnorda** [comment]
Dzisiaj przeladowalem kilka razy weeba na tej wtyczce i za ktoryms razem zaskoczylo :)
