### ISSUE TITLE
alltube

### ISSUE THREAD

**Issue by duszabar** [mrknow/filmkodi#66]
Przydało by się wyszukiwanie w alltube, przeczesywanie wtyczki to męka.

**Comment by plumers** [comment]
popieram ,coś ala cda wyszukaj :) pozdro

**Comment by xxcriticxx** [comment]
+1

**Comment by mrknow** [comment]
@xxcriticxx napisz do mnie maila  na mrknow[małpa]interia.pl

**Comment by xxcriticxx** [comment]
@mrknow 

xxcritic2001xx[małpa]hotmail.com

pisalem kilka razy zobacz usiebie w spam folder

**Comment by mrknow** [comment]
dodałem wyszukiwanie w filmach
