### ISSUE TITLE
MrknowTV yoy.tv

### ISSUE THREAD

**Issue by hellboy2** [mrknow/filmkodi#660]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: 16.1
- OS version: windows

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [x] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [ ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [x] Other / Inne

---
## Descryption / Opis
yoy.tv nie ma wszystkich programów

**Comment by hellboy2** [comment]
Czy jakoś da się rozwiązać problem

**Comment by hellboy2** [comment]
Czy ktoś to czyta w ogóle

**Comment by rysson** [comment]
Tak, czasem. Wyobraź sobie gościa, który od rana do nocy zasuwa i czasem jak ma siłę to w weekend swój czas poświęca. I drugiego, który zajęty jest podobnie, a w dodatku jeszcze nie zna kodu, bo od niedawna próbuje pomóc.

**Comment by mrknow** [comment]
@hellboy2 - tak jak napisał @rysson. Działamy w wolnym czasie. Zwykle błędy i problemy usuwamy w weekendy. Tak więc w przeciągu maksymalnie 7 dni dostaniesz odpowiedź. 

Sprawdź nową wersję 2016.12.09.2 wtyczki MrknowTV 
Ona powinna rozwiązać ten problem

**Comment by hellboy2** [comment]
Nada jest to samo
