### ISSUE TITLE
Błąd dodatku Filmy Online - mrknow.pl

### ISSUE THREAD

**Issue by drrak** [mrknow/filmkodi#663]
## Kodi & OS
- LibreELEC 7.0.2, RPi2

---
## Addon / Wtyczka
- [x] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: 2016.11.26.2

---
## Issue / Zgłoszenie
- [x] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Nie można uruchomić wtyczki, pojawia się tylko komunikat:
_"Błąd dodatku Filmy Online - mrknow.pl"_

**Comment by rysson** [comment]
Poproszę o log: https://github.com/mrknow/filmkodi/wiki/Jak-przesłać-logi-z-kodi

**Comment by drrak** [comment]
Wolałbym tego nie robić, przez "wrażliwe dane" itp. sprawy. Może ten kawałek wystarczy:

13:53:32 57032.066406 T:1963069440 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
13:53:32 57032.214844 T:1963069440  NOTICE: ActiveAE DSP - starting
13:53:32 57032.234375 T:1963069440  NOTICE: initialize done
13:53:32 57032.234375 T:1963069440  NOTICE: Running the application...
13:53:32 57032.871094 T:1963069440  NOTICE: starting zeroconf publishing
13:53:32 57032.871094 T:1963069440  NOTICE: WebServer: Started the webserver
13:53:32 57032.871094 T:1963069440  NOTICE: starting upnp client
13:53:32 57032.890625 T:1684009888  NOTICE: ES: Starting UDP Event server on 127.0.0.1:9777
13:53:32 57032.890625 T:1684009888  NOTICE: UDP: Listening on port 9777
13:53:33 57033.460938 T:1805644704  NOTICE: ## LibreELEC Addon ## 0.7.3
13:53:33 57033.476562 T:1805644704 WARNING: CSkinInfo: failed to load skin settings
13:53:34 57034.156250 T:1649263520  NOTICE: [SPECTO]: ->----------                PARAMS: {'action': 'service'}
13:53:44 57044.347656 T:1640874912   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named plugins
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.mrknow/default.py", line 111, in <module>
                                                import wykop, filmbox,vodpl, filmydokumentalne, efilmyseriale
                                              File "/storage/.kodi/addons/plugin.video.mrknow/host/wykop.py", line 14, in <module>
                                                import mrknow_pLog, mrknow_pCommon, mrknow_Parser,mrknow_urlparser
                                              File "/storage/.kodi/addons/plugin.video.mrknow/lib/mrknow_urlparser.py", line 18, in <module>
                                                import urlresolver9 as urlresolver
                                              File "/storage/.kodi/addons/script.mrknow.urlresolver/lib/urlresolver9/__init__.py", line 39, in <module>
                                                from plugins import *
                                            ImportError: No module named plugins
                                            -->End of Python script error report<--
13:53:44 57044.503906 T:1963069440   ERROR: GetDirectory - Error getting plugin://plugin.video.mrknow/
13:53:44 57044.507812 T:1963069440   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mrknow/) failed

**Comment by hellboy2** [comment]
Mi działa tylko nie działa iptak i zalukaj

**Comment by rysson** [comment]
@drrak, powinien dzięki. Tak na szybko możesz odinstalować plugin, wyczyścić cache i zainstalować jeszcze raz?

**Comment by drrak** [comment]
Nie ma sprawy, tylko proszę mi wytłumaczyć jak wyczyścić cache. Póki co odinstalowałem i zainstalowałem wtyczkę, ale ciągle jest ten błąd.

**Comment by mrknow** [comment]
w razie co zainstaluj ręcznie ten dodatek i sprawdź czy pomogło. Tu masz wtyczkę http://kodi.filmkodi.com/script.mrknow.urlresolver/script.mrknow.urlresolver-2016.12.10.1.zip

Jak zainstalować wtyczkę z pliku zip tu instrukcje http://kodi.wiki/view/HOW-TO:Install_add-ons_from_zip_files

**Comment by drrak** [comment]
Teraz działa. Wielkie dzięki **mrknow**.
