### ISSUE TITLE
Looknij.in problem

### ISSUE THREAD

**Issue by hellboy2** [mrknow/filmkodi#664]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: __16.1___
- OS version: __windows___

---
## Addon / Wtyczka
- [x] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [x] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Nie działa

**Comment by mrknow** [comment]
A o której wtyczce mowa ? napisz nazwę i daj logi proszę

**Comment by hellboy2** [comment]
A gdzie je znajdę w Android

**Comment by hellboy2** [comment]
Chodzi o lodi gdzie znajduje w Android

**Comment by hellboy2** [comment]
Chodzi o filmy online mrknov telewizja i looknij.in

**Comment by hellboy2** [comment]
20:54:39 T:18446744073498179888  NOTICE: special://profile/ is mapped to: special://masterprofile/
20:54:39 T:18446744073498179888  NOTICE: -----------------------------------------------------------------------
20:54:39 T:18446744073498179888  NOTICE: Starting Kodi (16.1 Git:2016-04-24-f6ceced). Platform: Android ARM 32-bit
20:54:39 T:18446744073498179888  NOTICE: Using Release Kodi x32 build
20:54:39 T:18446744073498179888  NOTICE: Kodi compiled Apr 24 2016 by GCC 4.8.0 for Android ARM 32-bit API level 17 (API level 17)
20:54:39 T:18446744073498179888  NOTICE: Running on HUAWEI ALE-L21 with Android 6.0.0 API level 23, kernel: Linux ARM 32-bit version 3.10.86-gd9a2b44
20:54:39 T:18446744073498179888  NOTICE: FFmpeg version: 2.8.6-kodi-2.8.6-Jarvis-16.0
20:54:39 T:18446744073498179888  NOTICE: Host CPU: AArch64 Processor rev 3 (aarch64), 8 cores available
20:54:39 T:18446744073498179888  NOTICE: Product: ALE-L21, Device: hwALE-H, Board: BalongV8R1SFT - Manufacturer: HUAWEI, Brand: Huawei, Model: ALE-L21, Hardware: hi6210sft
20:54:39 T:18446744073498179888  NOTICE: External storage path = /storage/emulated/0; status = ok
20:54:39 T:18446744073498179888  NOTICE: ARM Features: Neon enabled
20:54:39 T:18446744073498179888  NOTICE: special://xbmc/ is mapped to: /data/user/0/org.xbmc.kodi/cache/apk/assets
20:54:39 T:18446744073498179888  NOTICE: special://xbmcbin/ is mapped to: /data/user/0/org.xbmc.kodi/cache/apk/assets
20:54:39 T:18446744073498179888  NOTICE: special://masterprofile/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata
20:54:39 T:18446744073498179888  NOTICE: special://home/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi
20:54:39 T:18446744073498179888  NOTICE: special://temp/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp
20:54:39 T:18446744073498179888  NOTICE: The executable running is:
20:54:39 T:18446744073498179888  NOTICE: Local hostname: localhost
20:54:39 T:18446744073498179888  NOTICE: Log File is located: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log
20:54:39 T:18446744073498179888  NOTICE: -----------------------------------------------------------------------
20:54:39 T:18446744073498179888  NOTICE: load settings...
20:54:39 T:18446744073498179888   DEBUG: CSettings: loaded settings definition from special://xbmc/system/settings/settings.xml
20:54:40 T:18446744073498179888 WARNING: CSettingInt: unknown options filler "audiocdactions" of "audiocds.autoaction"
20:54:40 T:18446744073498179888   DEBUG: CSettings: loaded settings definition from special://xbmc/system/settings/android.xml
20:54:40 T:18446744073498179888   DEBUG: AESinkAUDIOTRACK - 44100 supported
20:54:40 T:18446744073498179888   DEBUG: AESinkAUDIOTRACK - 48000 supported
20:54:40 T:18446744073498179888   DEBUG: AESinkAUDIOTRACK - 96000 supported
20:54:40 T:18446744073498179888   DEBUG: AESinkAUDIOTRACK - 192000 supported
20:54:40 T:18446744073498179888  NOTICE: Found 1 Lists of Devices
20:54:40 T:18446744073498179888  NOTICE: Enumerated AUDIOTRACK devices:
20:54:40 T:18446744073498179888  NOTICE:     Device 1
20:54:40 T:18446744073498179888  NOTICE:         m_deviceName      : AudioTrack
20:54:40 T:18446744073498179888  NOTICE:         m_displayName     : android
20:54:40 T:18446744073498179888  NOTICE:         m_displayNameExtra: audiotrack
20:54:40 T:18446744073498179888  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
20:54:40 T:18446744073498179888  NOTICE:         m_channels        : FL,FR,FC,LFE,BL,BR,SL,SR
20:54:40 T:18446744073498179888  NOTICE:         m_sampleRates     : 48000,44100,48000,96000,192000
20:54:40 T:18446744073498179888  NOTICE:         m_dataFormats     : AE_FMT_S16LE,AE_FMT_AC3,AE_FMT_DTS
20:54:40 T:18446744073498179888   DEBUG: CSkinSettings: no <skinsettings> tag found
20:54:40 T:18446744073498179888  NOTICE: No settings file to load (special://xbmc/system/advancedsettings.xml)
20:54:40 T:18446744073498179888  NOTICE: No settings file to load (special://masterprofile/advancedsettings.xml)
20:54:40 T:18446744073498179888  NOTICE: Default DVD Player: dvdplayer
20:54:40 T:18446744073498179888  NOTICE: Default Video Player: dvdplayer
20:54:40 T:18446744073498179888  NOTICE: Default Audio Player: paplayer
20:54:40 T:18446744073498179888  NOTICE: Disabled debug logging due to GUI setting. Level 0.
20:54:40 T:18446744073498179888  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
20:54:40 T:18446744073498179888  NOTICE: CMediaSourceSettings: loading media sources from special://masterprofile/sources.xml
20:54:40 T:18446744073498179888  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
20:54:40 T:18446744073498179888  NOTICE: Loaded playercorefactory configuration
20:54:40 T:18446744073498179888  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
20:54:40 T:18446744073498179888  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
20:54:40 T:18446744073498179888  NOTICE: Running database version Addons20
20:54:40 T:18446744073498179888  NOTICE: ADDONS: Using repository repository.xbmc.org
20:54:40 T:18446744073498179888  NOTICE: ADDONS: Using repository repository.filmkodi.com
20:54:40 T:18446744073498179888  NOTICE: ADDONS: Using repository repository.xbmchub
20:54:40 T:18446744073498179888  NOTICE: ADDONS: Using repository repository.ramic
20:54:40 T:18446744073498179888  NOTICE: ADDONS: Using repository repository.whitecream
20:54:40 T:18446744073498179888  NOTICE: virtual bool CWinSystemEGL::InitWindowSystem(): Using EGL Implementation: android
20:54:40 T:18446744073498179888  NOTICE: CEGLNativeTypeAndroid: Switching to resolution:
20:54:40 T:18446744073498179888  NOTICE: Current resolution: 1280x720 @ 60.00 - Full Screen
20:54:40 T:18446744073498179888  NOTICE: Previous line repeats 1 times.
20:54:40 T:18446744073498179888  NOTICE: Found resolution 1280 x 720 for display 0 with 1280 x 720 @ 60.000004 Hz
20:54:40 T:18446744073498179888  NOTICE: Found (1280x720@60.000004) at 16, setting to RES_DESKTOP at 16
20:54:40 T:18446744073498179888  NOTICE: Checking resolution 16
20:54:40 T:18446744073498179888  NOTICE: Current resolution: 1280x720 @ 60.00 - Full Screen
20:54:40 T:18446744073498179888  NOTICE: CEGLNativeTypeAndroid: Switching to resolution: 1280x720 @ 60.00 - Full Screen
20:54:40 T:18446744073498179888  NOTICE: GL_VENDOR = ARM
20:54:40 T:18446744073498179888  NOTICE: GL_RENDERER = Mali-450 MP
20:54:40 T:18446744073498179888  NOTICE: GL_VERSION = OpenGL ES 2.0
20:54:40 T:18446744073498179888  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 1.00
20:54:40 T:18446744073498179888  NOTICE: GL_EXTENSIONS = GL_EXT_debug_marker GL_OES_texture_npot GL_OES_vertex_array_object GL_OES_compressed_ETC1_RGB8_texture GL_EXT_compressed_ETC1_RGB8_sub_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_depth24 GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth_texture GL_OES_packed_depth_stencil GL_EXT_texture_format_BGRA8888 GL_OES_vertex_half_float GL_EXT_blend_minmax GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_rgb8_rgba8 GL_EXT_multisampled_render_to_texture GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_ARM_mali_program_binary GL_EXT_shader_texture_lod GL_EXT_robustness GL_OES_depth_texture_cube_map GL_KHR_debug GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_OES_mapbuffer
20:54:40 T:18446744073498179888  NOTICE: Current resolution: 1280x720 @ 60.00 - Full Screen
20:54:40 T:18446744073498179888  NOTICE: Running database version Addons20
20:54:41 T:18446744073498179888  NOTICE: Running database version ViewModes6
20:54:41 T:18446744073498179888  NOTICE: Running database version Textures13
20:54:41 T:18446744073498179888  NOTICE: Running database version MyMusic56
20:54:41 T:18446744073498179888  NOTICE: Running database version MyVideos99
20:54:41 T:18446744073498179888  NOTICE: Running database version TV29
20:54:41 T:18446744073498179888  NOTICE: Running database version Epg11
20:54:41 T:18446744073498179888 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
20:54:41 T:18446744073498179888  NOTICE: ActiveAE DSP - starting
20:54:41 T:18446744073498179888  NOTICE: initialize done
20:54:41 T:18446744073498179888  NOTICE: Running the application...
20:54:42 T:18446744073498179888  NOTICE: starting zeroconf publishing
20:54:42 T:18446744073498179888  NOTICE: starting upnp client
20:54:42 T:18446744073034795312  NOTICE: ES: Starting UDP Event server on 127.0.0.1:9777
20:54:42 T:18446744073034795312  NOTICE: UDP: Listening on port 9777
20:54:42 T:18446744073498179888  NOTICE: Current resolution: 1280x720 @ 60.00 - Full Screen
20:54:42 T:18446744073498179888  NOTICE: GL_VENDOR = ARM
20:54:42 T:18446744073498179888  NOTICE: GL_RENDERER = Mali-450 MP
20:54:42 T:18446744073498179888  NOTICE: GL_VERSION = OpenGL ES 2.0
20:54:42 T:18446744073498179888  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 1.00
20:54:42 T:18446744073498179888  NOTICE: GL_EXTENSIONS = GL_EXT_debug_marker GL_OES_texture_npot GL_OES_vertex_array_object GL_OES_compressed_ETC1_RGB8_texture GL_EXT_compressed_ETC1_RGB8_sub_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_depth24 GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth_texture GL_OES_packed_depth_stencil GL_EXT_texture_format_BGRA8888 GL_OES_vertex_half_float GL_EXT_blend_minmax GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_rgb8_rgba8 GL_EXT_multisampled_render_to_texture GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_ARM_mali_program_binary GL_EXT_shader_texture_lod GL_EXT_robustness GL_OES_depth_texture_cube_map GL_KHR_debug GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_OES_mapbuffer
20:54:42 T:18446744073032706352  NOTICE: [fanfilm]: ->----------                PARAMS: {'action': 'service'}
20:54:42 T:18446744073032706352  NOTICE: [fanfilm]: ->----------                originaltitle: None
20:54:43 T:18446744073020242224  NOTICE: [SPECTO]: ->----------                PARAMS: {'action': 'service'}
20:54:43 T:18446744073020242224   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.specto/TVShows/
20:54:47 T:18446744073064970544   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc

**Comment by hellboy2** [comment]
Taki błąd jest na looknij.in 
http://imgur.com/a/flT0D

**Comment by hellboy2** [comment]
Halo czyta ktoś to

**Comment by koladka** [comment]
Tak czyta! Z tym ze autor czyli Mr know ma ograniczony czas , i ma troche do ogarniecia! Odpisuje kiedy moze! I dzieki mu za to;) Dobra robota Mr.know

**Comment by mrknow** [comment]
Witam 
Do looknij używaj kodi 17.0
