### ISSUE TITLE
TV z http://www.wp.pl/tv/

### ISSUE THREAD

**Issue by cr4shydlo** [mrknow/filmkodi#665]
## Kodi & OS
- Kodi verison: 16.1
- OS version: LibreElec

---
## Addon / Wtyczka
- [X] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [ ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [X] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis

Witam, może udało by się doportować streamy z wp.pl/tv ? Nadają tam za darmo podstawowy pakiet TVP1,TVP2,Polsat ? Może nie za wiele, ale zawsze to lepsze niż serwisy z 100 kanałami które co chwilę znikają.

Dzięki.

**Comment by mrknow** [comment]
Ale to jest to samo co  videostar. Videostar  jest dostepny we wtyczce mrknowTV
