### ISSUE TITLE
Some Favorites still not show after they are added.

### ISSUE THREAD

**Issue by antonech** [mrknow/filmkodi#667]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: 2016.12.03.1
- OS version: Ubuntu 16.04

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [ ] MrknowTV
- [X] Specto
- [ ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [X] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
I has some favorites are added from last bug when the favorites disappeared,
I removed one of them on latest version 2016.12.03.1, but still after addition the this specific tv show did not appear in favorites

**Comment by handsomened** [comment]
When saving TV shows from latest episodes they do not appear in my Specto.
However, when I try to save them again the menu choice is remove from favorites.

**Comment by antonech** [comment]
Not relevant anymore

**Comment by BankruptEd** [comment]
Not relevant anymore? No shit. I don't even remember sending this cause it
had to be ages ago. Thanks for the reply though.
