### ISSUE TITLE
Problem po ostatniej aktualizacji wtyczki

### ISSUE THREAD

**Issue by em82** [mrknow/filmkodi#67]
Po ostatniej aktualizacji pojawił się problem. W ogole nie moge wejsc w tą wtyczke Mrknow. Wywala czerwony krzyzyk i pojawia się bład. Probowalem odinstalowac i zainstalowac na nowo i zawsze to samo. wczesniejsze wersje dzialaly bez problemu. Ktos wie co moge jeszcze sprobowac zrobic?

**Comment by xxcriticxx** [comment]
stara wersie zamotowac i wylonczyc auto update

**Comment by mrknow** [comment]
Dodałem 4 serwery do mojej farmy. Już nie powinno być problemów
