### ISSUE TITLE
Zablokowane porty dostawcy internetu 

### ISSUE THREAD

**Issue by kamil1899** [mrknow/filmkodi#670]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: 16.1 Git 2016-04-24 f6ceced
- OS version: Android 5.1.1 Api level 22 

---
## Addon / Wtyczka
- [x ] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: 2016.11.26.2

---
## Issue / Zgłoszenie
- [ ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ x] Question / Pytanie
- [ x] Other / Inne

---
## Descryption / Opis

Mam problem, bo najprawdopodobniej mój dostawca internetu "fine media" zablokował porty, jest to internet po kablu. Nie działa ta wtyczka ani w tv, ani w lapku, ani w telefonie. 
Podłączając te urządzenia do internetu mobilnego wszystko działa. 

Czy jest na to jakiś sposób na omicięcie tej blokady, bo podejrzewam, że nie pójdą mi na rękę i nie odblokują tych portów.

**Comment by mrknow** [comment]
Nie napisałeś co dokładnie ci nie działa. Jaka wtyczka i jakie materiały

Tego typu ograniczenia można ominąć na kilka sposobów, w tym:
- serwery proxy 
- vpn 

Niestety nie potrafię ci doradzić jakiego dostawce masz wybrać. Wypróbuj darmowe rozwiązania.
