### ISSUE TITLE
Wtyczka Anime IPTV

### ISSUE THREAD

**Issue by Misamaru** [mrknow/filmkodi#671]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: 16.1
- OS version: _____

---
## Addon / Wtyczka
- [ x] Filmy online - Mrknow
- [x ] MrknowTV
- [x ] Specto
- [ x] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [x ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ x] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
<br>Wtyczka anime w anime online pokazuje spis alfabetyczny, ale dalej już nic nie ma, jest pusto. W repozytorium po aktualizacji zniknęła i nie chce się aktualizować ręcznie. W innych wtyczka chyba wymienionych wyżej albo brak źródeł albo błędy podczas próby załączenia <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

**Comment by mrknow** [comment]
Witam 
To nie nasza wtyczka.
