### ISSUE TITLE
Specto not showing films after 2014

### ISSUE THREAD

**Issue by mygithub2k17** [mrknow/filmkodi#678]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: 16.1
- OS version: Android 5

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [ ] MrknowTV
- [x] Specto
- [ ] FanFILM
- Version / Wersja: n/a (Latest)
## Issue / Zgłoszenie
- [ ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [X] Question / Pytanie 
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

Specto fork is not showing videos after the year 2014. It only displays upto 2014. No new movies are in "In Theaters" only movies from 2014. No tv episodes are displayed after the year 2014.
I have tried reinstalling the addon. Nothing
I have tried reinstalling Kodi. Nothing

Please help as I use Specto as one my my main sources of entertainment.

Kind Regards,

Blade

**Comment by mrknow** [comment]
set corect date on your tv box http://filmkodi.com/en/kodi-specto-faq/
