### ISSUE TITLE
Not getting any response from the build

### ISSUE THREAD

**Issue by jamstewart83** [mrknow/filmkodi#679]
---
## Kodi & OS
- Kodi verison: 16.1
- OS version: Fire OS 5.2.1.1

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [ ] MrknowTV
- [x] Specto
- [ ] FanFILM
- Version / Wersja: 2016.12.10.1

---
## Issue / Zgłoszenie
- [x] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
I've just completed a fresh install on a new firestick but whenever I try to access a category or do a search I get a working spinner and the nothing not even an error. Tried multiple installs and still no joy.

Log: http://paste.filmkodi.com/view/24170f24

**Comment by mrknow** [comment]
setup corect date and time on your tv box http://filmkodi.com/en/kodi-specto-faq/
