### ISSUE TITLE
Addon Autostart mrknow/telewizjada

### ISSUE THREAD

**Issue by siouxxx83** [mrknow/filmkodi#68]
Witam.
Mam maly problem, a mianowicie chcialem zrobic dziadkom za granica prezent i wrzucic kodi z telewizjada na fire tv sticka. Jak sama nazwa wskazuje, owi dziadkowie, to starzy ludzie i sa z nowoczesna technika na bakier, dlatego chcialem im to jakos tak skonfigurowac, zeby po wlaczeniu tv i odpaleniu sticka z hdmi najlepiej od razu pojawil sie wybor kanalow z telewizjady. Jest takie cos w ogole mozliwe? Jesli tak, to co powinno sie znajdowac w autoecec.py? 

import xbmc
xbmc.executebuiltin('RunPlugin(plugin://?????????????????/???????????')

Pozdrawiam

**Comment by mrknow** [comment]
Plik .kodi/userdata/autoexec.py
u mnie wygląda tak 
```
import xbmc
xbmc.executebuiltin("RunAddon(plugin.video.mrknow)")
xbmc.executebuiltin('RunPlugin(plugin://plugin.video.mrknow/?mode=110)')
```

**Comment by quatro7** [comment]
a co dopisać żeby od razu uruchamiał się yoy.tv?
