### ISSUE TITLE
telewizjada.net wie ktos co sie stalo 

### ISSUE THREAD

**Issue by wlochaty1983** [mrknow/filmkodi#680]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: _____
- OS version: _____

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [ ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

**Comment by koladka** [comment]
Wszystko padlo

**Comment by mrknow** [comment]
Pytaj o szczegóły na ich stronie

**Comment by wlochaty1983** [comment]
witam możesz mi pomuc z poprawnym uruchomieniu KODI

**Comment by mrknow** [comment]
@wlochaty1983 - mogę w czym masz problem ?

**Comment by wlochaty1983** [comment]
po instalacji kodi nie mam pojęcia jak ustawić żeby to smigalo
