### ISSUE TITLE
E-filmy.tv

### ISSUE THREAD

**Issue by talar666** [mrknow/filmkodi#684]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: 16.1
- OS version: _____

---
## Addon / Wtyczka
- [x ] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [ x] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Żaden z filmów z efilmy.tv się nie odtwarza. Dostaję informację, że nie ma strumienia. Wcześniej wszystko działało dobrze.

**Comment by hellboy2** [comment]
Mam to samo

**Comment by koladka** [comment]
Dokladnie padly wtyczki Mr know
