### ISSUE TITLE
Please Update Real-Debrid to V3 

### ISSUE THREAD

**Issue by karnage11** [mrknow/filmkodi#69]
Hey Need to update Real-Debrid to V3 i think it is still on V2  or something like that , just want to get more HD or 1080 links

**Comment by mrknow** [comment]
OK 
I will try to update this next weekend(21/02/2016)

**Comment by karnage11** [comment]
Hey Mrknow I can't install your repo atm

**Comment by karnage11** [comment]
Thank you Mrknow

**Comment by karnage11** [comment]
Your doing an awesome job , keep up the work

**Comment by ECKoBASE** [comment]
Thanks Dude! Cant wait till Trakt & Real-Debrid are updated!

**Comment by karnage11** [comment]
any news on the update? Thank you

**Comment by karnage11** [comment]
Hey any news on the update MrKnow? Thank you

**Comment by mrknow** [comment]
I'm going today add support for real debrid . Keep your fingers crossed. :)

**Comment by karnage11** [comment]
Thanks a lot for everything , your doing an awesome job .. and one more thing can you fix some of the sources that have the wrong movies please .. Thank you

**Comment by karnage11** [comment]
Please get back to me as Soon as possible , Thank you
