### ISSUE TITLE
MrKnow Fanfilm

### ISSUE THREAD

**Issue by kokosz168** [mrknow/filmkodi#690]
Witam.

Nie mam pojęcia czemu nie moge zaisntalować wtyczki Mrknow Fanfilm?
Cały czas podczas instalacji  z pliku zip pojawia mi sie wiadomość o błędzie dodatku.Tak cały czas czy to nowsza wersja wtyczki czy starsza cały czas to samo jakieś pomysły czemu?

**Comment by kokosz168** [comment]
ohhhh widze ze odpowiedzi aż nadto.

**Comment by mrknow** [comment]
@kokosz168 - przepraszam za brak odpowiedzi, ale ostatnio pochłonęły mnie sprawy osobiste. 

Niestety nie planujemy rozwijać tej wtyczki i niebawem usuniemy wszystkie informacje o niej
