### ISSUE TITLE
Specto addon Install issue-Failed to install a dependency

### ISSUE THREAD

**Issue by echelon33** [mrknow/filmkodi#693]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: 16.1
- OS version: Windows 10 Pro 64 Bit

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [ ] MrknowTV
- [ X] Specto
- [ ] FanFILM
- Version / Wersja: 2016.12.24.1

---
## Issue / Zgłoszenie
- [ ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ X] Other / Inne

---
## Descryption / Opis
When trying to install the Specto -...Fork Video Addon from the filmkodi.com Repository-MRKNOW,<br>
I get the following error message: "Failed to Install a dependency". <br>
I am not sure what dependency is missing and I do not know how to find that out.
I saw another post saying the user found the missing one in an addon.xml file but I do not 
know where to locate this.  Any help would be much appreciated.  Let me know if you need more info.

**Comment by fcalan** [comment]
I am getting the same error message when I hit install. Anyone have a clue?

**Comment by fcalan** [comment]
It is actually preceded by the error METAHANDLER - "Failed to install a dependency"  then Specto - fork "Failed to install a dependency." These two errors happen when I click to Install Specto- Fork.

**Comment by davel2k6** [comment]
Same problem here. Tried installing on both my Android boxes and got the same result. Bye bye Specto?

**Comment by davel2k6** [comment]
Update! Suddenly Specto started working again..
Anyone who tried and failed... try again!
It seems to have been fixed
Thanks!

**Comment by anscottinnaples** [comment]
Suddenly Specto is gone from my installed Addons. Have tried to reinstall. Keep getting error message after 5% install saying "install failed" . No reason given. How do I work around this?

**Comment by RenEdi** [comment]
You must install too "script.mrknow.urlresolver-2016.12.24.1.zip"

**Comment by mrknow** [comment]
I have a problem with the servers. Now there should be OK

**Comment by pradeshc** [comment]
I had a similar problem, when adding from Video -> Add Ins - Get More.
I was able to install after navigating to System -> Add Ins -> From Repository -> All 
I cannot say how these two navigation paths are different,
