### ISSUE TITLE
Posters and Thumbnails on Trakt Episodes

### ISSUE THREAD

**Issue by KarelDeBruine** [mrknow/filmkodi#694]
Hello Mr Know, i wanted to ask you if you could add Posters and Thumbnails to "/My Specto/TRAKT:Episodes"

For the rest, this addon is actually better than Exodus now.
Widgets load up faster than other addons, the links are up to date.

So respect and gratitude! Thank you.
---
## Kodi & OS
- Kodi verison: 16.1
- OS version: Any

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [ ] MrknowTV
- [x] Specto
- [ ] FanFILM
- Version / Wersja: 2016.12.24.1

---
## Issue / Zgłoszenie
- [ ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [x] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

No logs neccesary.

**Comment by ronakg** [comment]
Came here to post exactly this. I also use library integration from Specto and because of lack of thumbnails in "my specto -> episodes", all the recently added episodes in library don't have thumbnails either.

Please fix this.

**Comment by mrknow** [comment]
ok 
I fix it to the end of this week
