### ISSUE TITLE
Specto - Napisy / Subtitles

### ISSUE THREAD

**Issue by krisoomerta** [mrknow/filmkodi#695]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: __17___
- OS version: _____

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [ ] MrknowTV
- [x ] Specto
- [ ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [ ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [x ] Feature request / Prośba o nową funkcję
- [ x] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

Wyszukiwanie napisów kiepsko działa. Np. w przypadku serialu "Gra o tron" wttyczka exodus jest w stanie znaleźć dużo więcej plików napisów, bo szuka po angielskim tytule czyli "Game of thrones", natomiast w specto żadne pliki napisów nie są wyszukiwane, albo znajdzie 1 góra 2 pliki o spolszczonej nazwie - stąd sugeruje, że specto wysyła inne zapytanie niż exodus. Czy mogę ustawić w jaki sposób wtyczka ma szukać napisów.

**Comment by mrknow** [comment]
Nie wiem dlaczego tak się dzieje. Napisy są wyszukiwane po imdb. 
Napisz w jakich serialach masz takie efekty. Może dla seriali niepoprawnie przypisuję numer imdb

**Comment by krisoomerta** [comment]
Sprawa zdaje się rozwiązana. W dodatku widnieją dwie pozycję (przynajmniej jeżeli chodzi o ten serial) a mianowicie "Gra o tron" i "Game of thrones". W drugim przypadku napisy są wyszukiwane prawidłowo.
