### ISSUE TITLE
MrKnow TV dluzszy czas nie dziala :-(

### ISSUE THREAD

**Issue by hero2017** [mrknow/filmkodi#697]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: _____v16.1
- OS version: _____Android

---
## Addon / Wtyczka
- [ X] Filmy online - Mrknow
- [ X] MrknowTV
- [ ] Specto
- [X ] FanFILM
- Version / Wersja: _____najnowsza

---
## Issue / Zgłoszenie
- [ X] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

Niestety zadna polska telewizja nie dziala a tu jusz prawie Nowy Rok. Fajnie by bylo miec na sylwestra ale wiem ze puzno to zglaszam. Caly czas mialem nadzieje ze jusz bedzie OK lada dzien. Jestem w Toronto.

Nie ma bledow...tylko wraca z powrotem do wtyczki po wyborze kanalu..dziennik lub co kolowiek; TVN24, itd :-(

**Comment by koladka** [comment]
Polish Ramic Kodi Add-ons

**Comment by mrknow** [comment]
OK 
Ale który serwis nie działa ?

**Comment by koladka** [comment]
Wiekszosc tak jak kolega wyzej pisal z niektorych poprostu calkiem wyzuca nie da sie wejsc

**Comment by koladka** [comment]
Popatrz na ta wtyczke Polish Ramic jaki wypas koles zrobil tv i serwisow.
