### ISSUE TITLE
Alltube problem logowaniem

### ISSUE THREAD

**Issue by ska0ska** [mrknow/filmkodi#698]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: _____16.1
- OS version: ___android__

---
## Addon / Wtyczka
- [ x] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [ ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ x] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.
Korzystalem z alltube przez amazon fire tv box. Do 28.12. wszystko dzialalo bezblednie, ale teraz juz w ogole nie mozna przeglafac plikow. Probowalem przez komputer i tablet i strona alltube jak i openload dzialaja, ale przed polaczeniem nalezy dokonac autoryzacji, zaznaczyc box"I'm not a robot" i wybrac kwadraciki z zadanym tematem. Uzywajac kodi na tv box takiej mozliwosci nie mam i wczesniejsza autoryzacja na kompie lub tablecie nie pomaga. Prosze o pomoc w rozwiazaniu problemu.

**Comment by kokosz168** [comment]
hmmm mi działa wszystko normalnie....wiem,że głupie ale może nie łączysz sie przez to samo IP?

**Comment by ska0ska** [comment]
Komp i tablet wireless, tv box na kablu wszystko podlaczone do tej samej sieci domowej, w kodi wyswietla sie standardowe info X B " wiecej informacji znajdziesz w pliku rejestru". Na pewno kazde z urzadzen ma inna koncowke adresu IP. 
Poczekam kilka dni moze sie cos zmieni, jak nie to bede uzywal mirroring albo airplay
Dzieki

**Comment by raalek** [comment]
potwierdzam , Alltube nie dziala , nie mozna przegladac plikow. Moze tylko z poza granic blokuje ?

**Comment by mrknow** [comment]
poprawiłem wtyczkę. Proszę o aktualizację i ponowną weryfikację

**Comment by ska0ska** [comment]
Sprawdzilem i filmy i seriale; nie mozna nic przegladac wyskakuje blad i odsyla do pliku rejestru (uzywam wtyczki na multimedia master edycja specjalna, kodi ver.16.1, amazon fire tv box android)


Sent from my Galaxy Tab® A
-------- Original message --------From: MrKnow <notifications@github.com> Date: 1/19/17  6:55 AM  (GMT-05:00) To: mrknow/filmkodi <filmkodi@noreply.github.com> Cc: ska0ska <ska0ska@yahoo.com>, Author <author@noreply.github.com> Subject: Re: [mrknow/filmkodi] Alltube problem logowaniem (#698) 
poprawiłem wtyczkę. Proszę o aktualizację i ponowną weryfikację

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mrknow/filmkodi","title":"mrknow/filmkodi","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mrknow/filmkodi"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mrknow in #698: poprawiłem wtyczkę. Proszę o aktualizację i ponowną weryfikację "}],"action":{"name":"View Issue","url":"https://github.com/mrknow/filmkodi/issues/698#issuecomment-273757927"}}}
