### ISSUE TITLE
FanFilm - problem z autoryzacją TRAKT

### ISSUE THREAD

**Issue by locoslaw** [mrknow/filmkodi#699]
Witam, na wstępie chce podziękować za tak wspaniały addon :) Ale do rzeczy...

W ustawieniach , konta, chcę autoryzować trakt, ale kiedy przyciskam autoryzacja to nic się nie pojawia (przykładowo w Exodusie wyskakuje okienko z informacją żeby wejść na stronę traktu i wpisać kod)

Bardzo bym poprosił o poprawkę.
(W Specto autoryzacja z traktem przebiegła bez problemu)

Pozdrawiam

Log z momentu wejścia w ustawienia - konta - trakt autoryzacja:

22:53:01.276 T:7740   ERROR: Unable to find plugin plugin.video.specto.polska
22:53:01.598 T:7740   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.fanfilm/?action=openSettings&query=5.1
22:53:01.605 T:7740   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.fanfilm/?action=openSettings&query=5.1) failed
22:53:01.851 T:5504  NOTICE: [fanfilm]: ->----------                PARAMS: {'action': 'toolNavigator'}
22:53:01.851 T:5504  NOTICE: [fanfilm]: ->----------                originaltitle: None

Kodi 17b7 , Windows 10 x86, Acer W1-810

## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: _____
- OS version: _____

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [x] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [x] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

**Comment by mrknow** [comment]
fanfilm na razie nie będzie rozwijane
