### ISSUE TITLE
plugin for freedisc.pl

### ISSUE THREAD

**Issue by xxcriticxx** [mrknow/filmkodi#7]
to jest request prosze o napisanie plugin to freedisc.pl

**Comment by mrknow** [comment]
OK. W najbliższym czasie dodam wtyczkę do freedisc.pl.

**Comment by mrknow** [comment]
dodałem obsługę freedisc.pl. Sprawdź czy działa poprawnie

**Comment by xxcriticxx** [comment]
nigdie nie widze pluginu

**Comment by mrknow** [comment]
Napisałem nie precyzyjnie. Dodałem obsługę odtwarzania filmów z freedisc.pl. Plugin jest w trakcie budowy

**Comment by xxcriticxx** [comment]
pod filmami sie nic nie pokazujie

**Comment by mrknow** [comment]
nie będzie realizowany plugin. Na razie brak czasu
