### ISSUE TITLE
yoy.tv nie działa

### ISSUE THREAD

**Issue by pee111** [mrknow/filmkodi#702]
Witam!

Znów przestał działać yoy.tv na waszej wtyczce.
Kanały się nie ładują z komunikatem "Brak dostępnego strumienia danych" 
Android box, Kodi 16x
Dzięki za pomoc :-)

**Comment by Dragonfly77** [comment]
Mam to samo, używam v16 na Malince 3. Mam konto premium ale komuniakt mówi o braku dostępu do strumienia.

**Comment by gigi8512** [comment]
a u mnie nie wyświetla wszystkich kanałów które są na stronie

**Comment by mrknow** [comment]
@gigi8512 - jakich kanałów brakuje, podaj przykład

**Comment by gigi8512** [comment]
wszystkich z platformy tvn, id

**Comment by mrknow** [comment]
Stare zgłoszenie. już powinno działać. zamykam
