### ISSUE TITLE
Yoy.tv nie działa

### ISSUE THREAD

**Issue by pee111** [mrknow/filmkodi#703]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: 16.1
- OS version: Android 5

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [x ] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [x ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis

Witam!

Znów przestał działać yoy.tv na waszej wtyczce.
Kanały się nie ładują z komunikatem "Brak dostępnego strumienia danych"
Android box, Kodi 16x
Dzięki za pomoc :-)

**Comment by hellboy2** [comment]
Potwierdzam mam to samo

**Comment by koladka** [comment]
Polish Ramic Kodi Add-ons

**Comment by mrknow** [comment]
Może jakieś problemy z serwerami. A teraz też jest problem ?

**Comment by koladka** [comment]
Caly czas tv niedziala sporadycznie czasem jakis kanal
