### ISSUE TITLE
Filmy online - Mrknow nie dziala (filmy, seriale itd)

### ISSUE THREAD

**Issue by wacek-11** [mrknow/filmkodi#706]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: ___x__
- OS version: _____

---
## Addon / Wtyczka
- [x ] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [x ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.
filmy online - mrknow.pl nie dziala ani w zakladce filmy ani seriale....w kazdym z serwisow (alltube, cda itd...) pokazuje ze jest blad I kaze isc do log (error - check the log for more information)

**Comment by koladka** [comment]
Niestety potwierdzam . Rowniez tv mr.know tak samo. Ale na pocieszenie mam informacje Mr.know pracuje nad zupelnie nowa wtyczka!;) Wiec badzmy cierpliwi , robi naprawde swietna robote , zwlaszcza ze te wtyczki sa darmowe.

**Comment by cortez7676** [comment]
strona tez...

**Comment by koladka** [comment]
Zaraz sprawdze ! Ja obecnie kozystam z wtyczek zagranicznych na yt.jest od groma  iptv  z Polska tv trzeba poszukac!

**Comment by cortez7676** [comment]
czyzby koniec wtyczki?

**Comment by koladka** [comment]
Wtyczka totalnie niedziala , mam nadzieje ze Mr know pracuje nad czyms nowym tak jak mowil;) A tymczasem jade na zagranicznych wtyczkach z iptv wiec jakos tam mam kolo 40 kanalow pl

**Comment by cortez7676** [comment]
jakich?

**Comment by koladka** [comment]
Polish Ramic Kodi Add-ons
Nowa Mega Polska wtyczka polecam

**Comment by hero2017** [comment]
Wtyczka dziala jak jusz miales zainstalowana...Probuje na drugim nowym android box i nie da sie wtyczki zainstalowac. 

**Filmy Online - mrknow.pl "Failed to install a dependency"**

Potem sprubowalem na komputerze i to samo.

Kodi 16.1 / Android lub PC

**Comment by hero2017** [comment]
Zauwazylem ze przed instalacja Filmy Online "Beautiful Soup" nie instaluje sie tak ze to jest chyba ten "dependency" co psuje instalacje Filmy Online wtyczki.

Czy jest jakis sposob to jakos inaczej zainstalowac?

**Comment by koladka** [comment]
Jak juz wspomnialem Mr know pracuje nad poprawka , a tymczasem podalem wyzej nowa nazwe innej Mega wtyczki *ramica* polecam instalacje.

**Comment by hero2017** [comment]
Dzieki. Ta wtyczka dziala bo niema zadnych "dependencies."

Odkrylem ze mi prawie zadne wtyczki niechca sie zainstolawac..ciagle "failed to install dependency." Nie wiem co sie stalo ale nawet 'factory reset' mojej skrzynki nie pomaga...nowy Kodi 16.1 tesz.

Ale mam sposob chociasz jak zainstalowac MrKnow Filmy Online:

Zciagnij te wtyczki:

-script.mrknow.urlresolver-2017.01.14.3.zip
-script.module.simplejson-3.3.0.zip
-script.module.requests-2.9.1.zip
-script.module.beautifulsoup-3.2.1

A teraz normalnie za instaluj Filmy Online wtyczke z http://kodi.filmkodi.com repo i sie zainstaluje bez tego dependency error.

Albo zainstaluj wtyczke z tad: http://kodi.filmkodi.com/plugin.video.mrknow/plugin.video.mrknow-2016.12.24.1.zip

Wtyczki do Kodi 16.1 Jarvis sa tutaj:

http://mirrors.kodi.tv/addons/jarvis/

**Comment by mrknow** [comment]
Witam 
zaktualizuj wtyczkę do najnowszej wersji 2017.01.18.1

**Comment by koladka** [comment]
Niestety niepokazuje tej aktualizacji . Gdzie znalezc repo z ta aktualizacja

**Comment by koladka** [comment]
Juz znalazlem zaktualizowalem i niestety :( -- not strem awanable --na kanalach.

**Comment by mrknow** [comment]
Ok
U mnie na kodi działają te kanały 
 telewizja -> looknij -> Discovery Channel
lub  
telewizja -> telewizja-live.com -> c+hd

To są darmowe streamy więc może nie działają dzisiaj, lub moja wtyczka nie daje rady. 

Napisz dokładniej co ci nie działa, nadal nie wiem co konkretnie

**Comment by koladka** [comment]
Looknij.in- web reqest failed. Telewizyjka- to samo. Telewizja-live.com-- chodza c+ i hbo i tyle.!
