### ISSUE TITLE
Nowa wtyczka do KODI/moje-filmy.tk

### ISSUE THREAD

**Issue by eko5** [mrknow/filmkodi#71]
Bardzo ciekawa wtyczka :) do strony http://www.moje-filmy.tk/

http://www.moje-filmy.tk/plugin.video.moje-filmy.tk-ver-1-3-0.zip

**Comment by Adam-po** [comment]
Aby super działało trzeba wykupić VIP.
Bo przy normalnej rejestracji nic nie działa...
Gesendet von Yahoo Mail auf Android 
 
  Am Sa., 6. Feb. 2016 um 11:07 hat eko5<notifications@github.com> Folgendes geschrieben:   
Bardzo ciekawa wtyczka :) do strony http://wwwmoje-filmytk/

http://wwwmoje-filmytk/pluginvideomoje-filmytk-ver-1-3-0zip

**Comment by mrknow** [comment]
Dokładnie, jak napisał @Adam-po . To płatna wtyczka i na razie nie planuję jako takiej dodawać. 
No chyba że było by więcej chętnych

**Comment by plumers** [comment]
To oni własnie zabili neopacka wtyczkę i podlinkowane mają streamy do telewizjady lol --- żałosny serwis - nie warto

**Comment by gumball1** [comment]
hehe neopack poszedl na latwizne i podpial sie na trzeciego do telewizjady poprzez tk 
w grudniu sie chwalil ze do swiat ogarnie telewizjade , nie dal rady to na okretke , cwaniaczek :)

**Comment by xxcriticxx** [comment]
site went invitation only i think its time to close this

**Comment by zjac** [comment]
nie mówiąc o tym, że ten admin z m-f.tk to gbur i cham.

**Comment by plumers** [comment]
taki jak Ty --- teraz teleszajsjade masz za $$$ he he nic nie ma za free w PL :)

**Comment by zjac** [comment]
@plumers spierdalaj wsiowy głupku z tymi docinkami, typowa kurwa internetowa... Od męki z Tv rzuciłem w końcu przez pół mieszkania kabel od kabla i mam w TV te pseudo TV

**Comment by plumers** [comment]
co za bełkot - posłuchaj siebie :)  nie przeklinaj ,boś za mały :D

**Comment by zjac** [comment]
@plumers dziwne, że Cie tu jeszcze debilu nikt nie zbanował - bo to kolejny raz, gdy wchodzisz w jakiś temat przeze mnie dopisany i po prostu się przypierdalasz. Masz problem to rozwiążmy go po męsku, dojadę w każde miejsce w PL. Może to Cię nauczy pokory internetowy cwelu schowany za monitorkiem i IP. Baba Ci nie daje, czy szefo w robocie jebie, że musisz być takim chujem w internecie ?

**Comment by plumers** [comment]
KWP Katowice Lompy zapraszam !!!

**Comment by Arek76** [comment]
Ja mysle że choc dodanie do platnych telewizji M-f.tk nikomu by nie zaszkodzilo , choc z drugiej strony wspieranie takich projektow powinno by zainicjowane ze strony admina z m-f,tk .
