### ISSUE TITLE
Yoy.tv streamy same sie wylaczaja

### ISSUE THREAD

**Issue by michaelpan1** [mrknow/filmkodi#710]
Witam,
Mam dziwna przypadlosc na yoy.tv, steamy dosc czesto same sie wylaczaja badz po bufforowaniu sa jakby w slow motion bez dzwieku. Czy ktos ma tez taka przypadlosc?
Moja instalka dziala na androidzie i Kodi 16.1.

//Mi

**Comment by mrknow** [comment]
Sprawdzę to ...

**Comment by mrknow** [comment]
Tak racja, tylko na razie nie umiem tego naprawić
