### ISSUE TITLE
Specto: I found a fix for Trakt collection import bug

### ISSUE THREAD

**Issue by azrin1972** [mrknow/filmkodi#714]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: 17 RC
- OS version: Android 6

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [ ] MrknowTV
- [x] Specto
- [ ] FanFILM
- Version / Wersja: 2016.12.24.1

---
## Issue / Zgłoszenie
- [ ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [x] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

The bug can be produced by clicking at "Tools->Library->Trakt : Import TV Collection"
And you can see that Specto seem to try to get the list from Trakt but nothing is imported.

To fixed this: open and edit "tvshows.py" in the "plugin.video.specto/resources/lib/indexer"

Go to line 78 and you'll find these lines of codes:
```python
 self.traktlists_link = 'http://api-v2launch.trakt.tv/users/%s/lists' % self.trakt_user
 self.traktlist_link = 'http://api-v2launch.trakt.tv/users/%s/lists/%s/items' % (self.trakt_user, '%s')
 self.traktcollection_link = 'http://api-v2launch.trakt.tv/users/%s/collection/shows' % self.trakt_user
 self.traktwatchlist_link = 'http://api-v2launch.trakt.tv/users/%s/watchlist/shows' % self.trakt_user
 self.traktfeatured_link = 'http://api-v2launch.trakt.tv/recommendations/shows?limit=20'
 self.traktratings_link = 'https://api-v2launch.trakt.tv/users/%s/ratings/shows' % self.trakt_user
```

Simply change the codes to these:
```python
self.traktlists_link = 'http://api-v2launch.trakt.tv/users/me/lists'
self.traktlist_link = 'http://api-v2launch.trakt.tv/users/me/lists/%s/items' % '%s'
self.traktcollection_link = 'http://api-v2launch.trakt.tv/users/me/collection/shows' 
self.traktwatchlist_link = 'http://api-v2launch.trakt.tv/users/me/watchlist/shows' 
self.traktfeatured_link = 'http://api-v2launch.trakt.tv/recommendations/shows?limit=40'
self.traktratings_link = 'https://api-v2launch.trakt.tv/users/me/ratings/shows' 
```

I've made a PR at https://github.com/mrknow/specto/pull/16

Also a fix for Trakt TV progress at https://github.com/mrknow/specto/pull/17

Hope this will help and also properly close #570 which was closed prematurely

**Comment by mrknow** [comment]
Ok. THX

I will change it, and release update  today

**Comment by azrin1972** [comment]
I submitted 2 PR at the specto GitHub repo. 

Thanks MrKnow
