### ISSUE TITLE
Wizja.tv nie działa

### ISSUE THREAD

**Issue by krolik88** [mrknow/filmkodi#717]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: 16.1
- OS version: 5.1.1

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: 2016.12.09.2

---
## Issue / Zgłoszenie
- [ ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [x] Other / Inne

---
## Descryption / Opis
Wizja nie działa poprzez wtyczkę, webowo działa jak ta lala lecz poprzez kodi niestety nie, prosze o pomoc :)

**Comment by Arek76** [comment]
Dodam jeszcze że są jakies modernizacje na stronie Wizji , Pokazuje sie teraz format EPG czyli wprowadzili jakies zmiany , Mam nadzieje że nie bedzie to mialo wplywu na wtykę MrKnowa i wszystko wroci do normy . Wielu moich klientow oglada Wizje przez tę wtyczke wiec jak co to ratuj MrKnow :))

**Comment by borys76** [comment]
@Arek76 to czemu sprzedajesz cos czego nie umiesz naprawic? 
Nastepny buisnessmen

**Comment by mrknow** [comment]
Może przez weekend były jakieś problemy. Teraz u mnie na linuksie i ATV działa prawidłowo.

Jeżeli sprzedajecie moje wtyczki, umieszczajcie w widocznym miejscu następujące  informację:
autor: mrknow
strona: http://filmkodi.com/

W resztę nie wnikam

**Comment by Arek76** [comment]
borys76 sprzedaje urzadzenia , Dlaczego ? w sumie nie che sie tlumaczyc osobom ktore zamiast pomoc wpisuja tylko negatywny komentarz ale napisze Ci moze to powstrzyma Cie nastepnym razem . Mieszkam w Berlinie gdzie wprowadzono zakaz wystawiania anten sat (jeszcze nie wszedzie ) Wiec usiadlem nad kompem i zacząlem szukac co mozna w tej sprawie zrobic by ogladac polska tv , Kupilem sobie kilka urzadzen i szukalem wtyczek , Bylo to okolo 2 lata temu . Po wielu nieudanych probach w koncu udalo mi sie porzadnie skonfigurowac Kodi i wtyczki . Hurra moglem ogladac polska tv . Gdy moja rodzina zobaczyla jak to u mnie dziala poprosila rowniez o takie urzadzenia co zrobilem , Pozniej znajomi itd , Samo sie nakrecilo . Teraz mam okolo 200 klientow ktorym pomoglem w tej kwestii ( tak wziąlem za to kase ) czy robie źle pomagajc odplatnie polakom w Berlinie przy zakupie i ustawianiach Android Boxow ?? Mysle że nie poniewaz mam wielu starszych klientow ktorzy sami by sobie z tym nie poradzili . Nie jestem Biznesmenem a normalnym czlowiekiem wiec nastepnym razem prosze zastanow sie zanim cos napiszesz . 
MrKnow do Ciebie znowu mam wielki szacunek i szanuje Twa prace jak malo kto . Zawsze i wszedzie ludzie bedą mogli uslyszec z mojej strony o Tobie tylko pozytywy aczkolwiek ja nie sprzedaje wtyczek :) sprzedaje urzadzenia Android Box na ktorych instaluje wszystko co dostepne w necie . Ostatnio zrobilem sobie skorę (bulid czy jak to nazywają :) ) Są w niej rowniez Twoje wtyczki i obiecuje że nie dosc ze same wtyki nie zmienia nazw (wszedzie jest MrKnow) to jeszcze zrobie specjalne podmenu tylko wylacznie pod Twoje dodatki . Naprawde szanuje Twoją prace i dziekuje Ci za wszelką pomoc jaką udzieliles mi do tej pory . Pozdrawiam bardzo serdecznie :)
