### ISSUE TITLE
Videostar - sslv3 handshake problem

### ISSUE THREAD

**Issue by michaelpan1** [mrknow/filmkodi#719]
Witam,
Mam taki problem:
http://paste.filmkodi.com/view/6bcc64ea
Cos da sie z tym zrobic?

//Mi

**Comment by mrknow** [comment]
Tak 
Zainstaluj kodi 17 https://kodi.tv/kodi-v17-0-krypton-release-candidate-3/ 
W tej wersji będzie działać poprawnie

**Comment by michaelpan1** [comment]
Hi MrKnow,
No sprawdzilem, dziala na innych urzadeniach ale niestety na boxie ktory mam podlaczony do Tv nie moge zainstalowac Kodi 17 bo Android tam to Kitkat ktory nie jest juz supportowany.
Jest na to jakies obejscie? mozna wymusic np. TLS zamiast SSL?
//Mi

**Comment by mrknow** [comment]
Niestety nie ma obejścia. 
Videostar - ma dodatkowe zabezpieczenie SSL, chyba  chodzi o SNI... ale głowy nie dam. 

Obsługa tego zabezpieczenia została wdrożona w wersji pythona 2.7.9. Na kodi 16 masz pewnie  wcześniejszą wersje pythona to nie zadziała.

Może oficjalna ich apka na androida ?
