### ISSUE TITLE
Videostar Not authorised

### ISSUE THREAD

**Issue by ooklamook** [mrknow/filmkodi#720]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: 17_____
- OS version: OE 7_____

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [ x] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [x ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

Przy probie zastartowania videostar (ktory juz pare miesiecy normalnie funkcjonowal) otrzymuje blad not authorised. Konto dziala na aplikacji androida i przez przegladarke.

Tutaj wyciag z logow
16:45:41 159222.125000 T:1447031712  NOTICE: [MrknowTV]: ->----------                PARAMS: {}
16:45:49 159229.734375 T:1459614624  NOTICE: [MrknowTV]: ->----------                PARAMS: {'action': 'tv', 'url': 'videostar'}
16:45:49 159230.406250 T:1459614624  NOTICE: [MrknowTV]: Client Error <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>
16:45:49 159230.406250 T:1459614624  NOTICE: [MrknowTV]: ResultC videostar.get None
16:45:50 159230.734375 T:1459614624  NOTICE: [MrknowTV]: EEEEEEEEEEEE Result videostar.get Not authorized
16:45:51 159231.875000 T:1459614624  NOTICE: [MrknowTV]: Client Error <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>
16:45:51 159231.890625 T:1459614624  NOTICE: [MrknowTV]: Error tv.get expected string or buffer
16:45:51 159232.000000 T:1964179456   ERROR: GetDirectory - Error getting plugin://plugin.video.mrknowtv/?action=tv&url=videostar
16:45:51 159232.000000 T:1964179456   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mrknowtv/?action=tv&url=videostar) failed
16:45:51 159232.093750 T:1459614624  NOTICE: [MrknowTV]: ->----------                PARAMS: {}
16:48:30 159390.812500 T:1430254496  NOTICE: [MrknowTV]: ->----------                PARAMS: {'action': 'toolNavigator'}
16:48:38 159399.218750 T:1430254496  NOTICE: [MrknowTV]: ->----------                PARAMS: {'action': 'loguploader'}

Jesli potrzebne wiecej to moge zrobic ponowna probe.

Dzieki z gory
Dobroslaw

PS. Nie wiem czy to ma jakies znaczenie ale uzywam vpn aby wtyczka funkcjonowala.

**Comment by mrknow** [comment]
Musisz zainstalować Kodi wersję 17. Wersja 16 nie obsługuje poprawnie protokołu SSL
