### ISSUE TITLE
Bład dodatku mrknow

### ISSUE THREAD

**Issue by pawel1945** [mrknow/filmkodi#723]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: _____
- OS version: _____

---
## Addon / Wtyczka
- [x] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [x] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

**Comment by pawel1945** [comment]
Mam problem z wtyczką mrknow i wskakuje bład dodatku i nic nie pisze na pliku rejestr zdarzeń i nie wiem co mam zrobić aktualizowałem oczywiście

**Comment by talar666** [comment]
Mi też po aktualizacji przestała działać

**Comment by mikon4322** [comment]
Problem jest chyba w nazewnictwie pluginu, w repo leżą NOWE paczki podpisane 2016.01... zainstalujcie sobie ręcznie i powinno działać. Dodaj źródło > http://kodi.filmkodi.com > zainstaluj z zip.

**Comment by souacz** [comment]
Nic to nie dało niestety... Ciekawe, że zainstalowałem też w Kodi 17 jako nowy plugin z repo i działa.
A na SPMC za chińskiego boga nie chce odpalić, do aktualizacji było OK.

**Comment by mrknow** [comment]
Zaraz poprawię ...

**Comment by souacz** [comment]
A jak to teraz zainstalować? Dodać repo i instalacja?

**Comment by mrknow** [comment]
zainstaluj repo, bo jest potrzebne. Następnie zainstaluj wtyczkę z repo.
Napisz czy jest teraz ok. Jak będzie błąd -> to dorobię funkcję do przesyłania logów i wtedy będzie na 100% jasne w czym problem

**Comment by mrknow** [comment]
o czekaj u mnie też jest błąd. Sprawdzam ...

**Comment by souacz** [comment]
OK

**Comment by mrknow** [comment]
Zainstaluj lub zaktualizuj wersję wtyczki do 2017.01.14.7

Sprawdź czy jest lepiej. Przy kopiowaniu funkcji byteify w pliku __generic_host__.py wkradły się jakieś krzaki i wyskakiwał błąd SyntaxError. Teraz powinno działać

**Comment by souacz** [comment]
działa, dzieki

**Comment by mrknow** [comment]
Uff. To dobrze. 

Dzięki za info i testy
