### ISSUE TITLE
Mam problem

### ISSUE THREAD

**Issue by pawel1945** [mrknow/filmkodi#724]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: _____
- OS version: _____

---
## Addon / Wtyczka
- [x] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [x] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

**Comment by pawel1945** [comment]
Nadal pokazuje bląd dodatku na tablecie aktualizowałem kilka razy na wtyczce mr know prosze coś z tym zrobić

**Comment by mikon4322** [comment]
Spróbuj zainstalować ponownie, a nie aktualizować. pobierz sobie tą wersję http://kodi.filmkodi.com/plugin.video.mrknow/plugin.video.mrknow-2017.01.14.8.zip i zainstaluj z zip.
