### ISSUE TITLE
Wszystkie kanały

### ISSUE THREAD

**Issue by pawel1945** [mrknow/filmkodi#725]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: _____
- OS version: _____

---
## Addon / Wtyczka
- [x] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [x] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

**Comment by pawel1945** [comment]
Wszystkie kanały nie działają w tej wtyczce

**Comment by mrknow** [comment]
A proszę więcej szczegółów 
może screenshot

**Comment by pawel1945** [comment]
Wszystkie kanały nie działają w wtyczce nie działa np canal + tvn 24
19 sty 2017 12:47 "MrKnow" <notifications@github.com> napisał(a):

A proszę więcej szczegółów
może screenshot

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mrknow/filmkodi/issues/725#issuecomment-273756052>, or mute
the thread
