### ISSUE TITLE
Specto fork not giving selection of movies

### ISSUE THREAD

**Issue by neil-rc30** [mrknow/filmkodi#726]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: _____
- OS version: _____

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [ ] MrknowTV
- [X ] Specto
- [ ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [ ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [X ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.#

Just loaded Specto on  fire stick. Opens ok but when i select for example latest movies it shows it is working briefly but then just stays at menu, does not show any film options. Same with all, movies, TV Shows etc. I have it installed on a different fire stick in the house and it works fine.  Any help appreciated

**Comment by neil-rc30** [comment]
Just loaded Specto on fire stick. Opens ok but when i select for example latest movies it shows it is working briefly but then just stays at menu, does not show any film options. Same with all, movies, TV Shows etc. I have it installed on a different fire stick in the house and it works fine. Any help appreciated
Kodi version 16.1, Specto version 2017.01.15.1

**Comment by mrknow** [comment]
Setup date and time on your tv box
http://filmkodi.com/en/kodi-specto-faq/

**Comment by neil-rc30** [comment]
Checked Time/Date and they are correct but still will not offer up any films. Just stays at the menu. Anything in tools i might have wrong?
