### ISSUE TITLE
No More Changelog Entries?

### ISSUE THREAD

**Issue by BankruptEd** [mrknow/filmkodi#729]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: _____
- OS version: _____

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [ ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.
Nice to know what's going on, what's been fixed and such.

**Comment by BankruptEd** [comment]
Not sure I was clear. 

In past few updates there has been no changelog entries, indicating what's been fixed. Not sure about anyone else, but I kinda like knowing what's been worked on. Just my two cents worth.

**Comment by mrknow** [comment]
OK.
Next time I will be placed in the changelog  things that I change in specto

**Comment by BankruptEd** [comment]
Thanks Mr. Know. I know its not very significant, but your attention to
detail is one of the things that make you and your Specto, The Best. Peace.

On Jan 21, 2017 7:23 AM, "MrKnow" <notifications@github.com> wrote:

OK.
Next time I will be placed in the changelog things that I change in specto

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mrknow/filmkodi/issues/729#issuecomment-274258539>, or mute
the thread
