### ISSUE TITLE
Brak streamingu w kodi we wtyczce xbmcfilm.com z cda.pl

### ISSUE THREAD

**Issue by Seico** [mrknow/filmkodi#73]
Filmy na stronie xbmcfilm.com otwierają się z reklamą , a w kodi jest błąd streamingu

**Comment by mrknow** [comment]
Sprawdzę i postaram się naprawić

**Comment by plumers** [comment]
seico pisałeś już to na mods kodi forum odpisałem Ci ,że u mnie działa poszukaj u siebie problemu :) pozdro mr looknij mój topic :p

**Comment by mrknow** [comment]
Mam już u siebie działające dekopery. Od teraz już z górki. 
Za kilka godzin wrzuce aktualizację, która poprawnie odczytuję filmy z cda.pl

**Comment by mrknow** [comment]
Nowa wersja działa poprawnie,
