### ISSUE TITLE
Trakt.tv for MrKnow

### ISSUE THREAD

**Issue by gzenio22** [mrknow/filmkodi#731]
Witam ja nie w sprawie bugow ani nic ale  z propozycją dodania mozliwosci sparowania wtyczki MrKnow z serwisem Trakt.tv :) Bylo by to mozliwe? :)

**Comment by mrknow** [comment]
jeżeli chcemy korzystać z trakt.tv - to trzeba moim zdaniem podejść do tego inaczej. Aby móc oznaczać filmy jako obejrzane to muszę znać jego numer imdb (identyfikator filmu)

Wznowię działanie wtyczki FanFilm, ok ?

Wtyczka FanFilm działa podobnie jak Specto - tylko że wyszukuje filmy na polskich stronach

**Comment by gzenio22** [comment]
Tak dziala tak samo jak Specto czy Exsodus natomiast jej rowniez nie da sie sparowac z Traktem mimo ze jest taka opcja gdy w nia klikam nie pokazuje sie kod do przepisania na strone trakt.tv/activate

**Comment by mrknow** [comment]
A to nie wiem dlaczego ... 
Tu masz instrukcję http://filmkodi.com/pl/fanfilm-uzywac-trakt-kodi/

Jeżeli nadal nie pokaże się kod - to podeślij mi logi z menu Narzędzia -> Diagnostic: Log uploader

**Comment by gzenio22** [comment]
Teraz zadzialalo :) do hostingow proponuje dodac jeszcze CDAx :)
