### ISSUE TITLE
Filmy Online - Mr Know - Telewizja Online - brak kanalów

### ISSUE THREAD

**Issue by Moni1975** [mrknow/filmkodi#733]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: _16.1_
- OS version: _____

---
## Addon / Wtyczka
- [x ] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: _2017.01.21.01

---
## Issue / Zgłoszenie
- [ ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ x] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

W zakładce Telewizja - telewizja OnLine - wczoraj miałam całą liste kanałów, które działały i mogłam z nich korzystać. Dzisiaj w tej zakładce Telewizja OnLine mam - kontakt, regulamin i rejestracja, z tym ,że na żaden z tych rekordów nie mogę wejść.

Nie wiem czy to problem telewizji OnLine czy wtyczki.
Proszę o info.

**Comment by mrknow** [comment]
OK, zmienili układ strony, zaraz naprawię

**Comment by mrknow** [comment]
na szybko poprawiłem i zaraz wrzucę nową wersję.

**Comment by Moni1975** [comment]
Bardzo dziękuję za szybką odpowiedź.
