### ISSUE TITLE
GVIDEO not working

### ISSUE THREAD

**Issue by oleats** [mrknow/filmkodi#737]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: _____
- OS version: _____

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [ ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

**Comment by oleats** [comment]
anyone know why GVIDEO wont work in Specto ?

**Comment by pishcakes** [comment]
Today all the sources I have are primewire but it seems disabling the ipv6 of kodi does the trick. At least it did til the gvideo sources disappeared

**Comment by mrknow** [comment]
OK
Today I'll try to fix it

**Comment by oleats** [comment]
It's working great now thanks a lot appreciate your work
