### ISSUE TITLE
can't update

### ISSUE THREAD

**Issue by karnage11** [mrknow/filmkodi#74]
having a problem updating its been stuck on 3% for about 5mins or so for Specto

**Comment by Delwashy** [comment]
You're not on your own pal you're lucky i can't get past 0% it must be that theres an issue with the addon it's self or theres that many people trying to update it can't cope?

**Comment by karnage11** [comment]
ohh alright

**Comment by karnage11** [comment]
just have to wait , thats all we can do , hopefully it will be fixed today

**Comment by Delwashy** [comment]
Hopefully i will give you the heads up when i get to hear any news

Date: Sat, 6 Feb 2016 15:48:00 -0800

**Comment by karnage11** [comment]
Thanks

**Comment by karnage11** [comment]
i get update failed on the other mr.know addons too

**Comment by Delwashy** [comment]
I have a feeling that the update was to remove it from our systems as there's been a problem with the name Genesis in it so i think he's took it down lets hope it gets replaced  

Date: Sat, 6 Feb 2016 15:52:54 -0800

**Comment by mrknow** [comment]
Right now we have problem wit server performance. Try install add-on tomorrow

**Comment by Delwashy** [comment]
Thank you for your speedy reply and i look forward to having this fine addon back 
Date: Sat, 6 Feb 2016 15:58:53 -0800

**Comment by karnage11** [comment]
Delwashy i guess let me know about the artwork for the addon , Thank you
