### ISSUE TITLE
FanFilm nie działa ?

### ISSUE THREAD

**Issue by a2best** [mrknow/filmkodi#741]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: 16.1
- OS version: Android 6.01
---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [x] FanFILM
- Version / Wersja: 2017.01.26.4

---
## Issue / Zgłoszenie
- [x] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Od kilku dni nie działa mi fanfilm. Jakiegokolwiek źródła bym nie odpalił wyskakuje komunikat "Brak dostępnego strumienia danych". "Filmy Online - MRknow" też nie działają którykolwiek z serwisów uruchamiam to wyskakuje błąd " B Więcej informacji na ten temat znajdziejsz w pliku rej". Próbowałem reinstalować wtyczki bez skutku. Inne wtyczki działają bez problemu.
PS Może by dodać MTV Play ?
Dzięki za pracę przy wtyczce i pozdrawiam.

**Comment by a2best** [comment]
log:
https://drive.google.com/file/d/0B0r9sRExKecqY3hITnFaMEt0Z1E/view

**Comment by hellboy2** [comment]
I nie chce odtwarzać z openload.co

**Comment by locoslaw** [comment]
Potwierdzam, u mnie też nie znajduje żadnych źródeł.

W10x86 , Kodi 17

**Comment by locoslaw** [comment]
Wszystko wróciło do normy. Można zamknąć.
