### ISSUE TITLE
Genesis -Fork "update failed"

### ISSUE THREAD

**Issue by madnesuk** [mrknow/filmkodi#75]
Hi, unable to update the addon. 
Perhaps an update awaiting to be released?

**Comment by Delwashy** [comment]
Same here as soon as it starts you get 0% then after several minutes updated failed?Any feed back would appreciated thank you

**Comment by karnage11** [comment]
i am stuck on 3% when trying to update it

**Comment by mrknow** [comment]
Right now we have problem wit server performance. Try install add-on tomorrow

**Comment by karnage11** [comment]
alright Thank you , and do you have new artwork for the addon at all ?

**Comment by Delwashy** [comment]
thank you

**Comment by karnage11** [comment]
and i been trying to ask for that for awhile now too , Thank you

**Comment by mrknow** [comment]
Try install  update manualy 
[plugin.video.specto.zip](https://github.com/mrknow/filmkodi/files/120518/plugin.video.specto.zip)

**Comment by Delwashy** [comment]
Thank you worked a treat magic once again thank you pal

Date: Sat, 6 Feb 2016 17:21:34 -0800

**Comment by karnage11** [comment]
it worked like a charm

**Comment by karnage11** [comment]
Delwashy any new arkwork for Specto for the addon , message me please

**Comment by Delwashy** [comment]
yeah we're all buzzin now

Date: Sat, 6 Feb 2016 17:46:07 -0800

**Comment by Delwashy** [comment]
I had to uninstall the repo as it was still trying to update then if failed to install which had a knock on effect on the plugin so by removing the repo the plugin works fine.I will reinstall the repo when things are back to normal

Date: Sat, 6 Feb 2016 17:46:07 -0800

**Comment by madnesuk** [comment]
Worked! Thanks dude. Let's give you lots of support to keep this going

**Comment by Delwashy** [comment]
Glad you've manually installed the plugin successfully let's past it on to those who are in need of support

Date: Sun, 7 Feb 2016 02:12:44 -0800

**Comment by madnesuk** [comment]
Yes we shall

**Comment by kev7414** [comment]
Hi all, where do I need to put this plugin in at. Thanks

**Comment by madnesuk** [comment]
What device are you using

**Comment by kev7414** [comment]
Androd device

**Comment by madnesuk** [comment]
I'm not sure sorry.  I used ADB Fire to push it to my FireTV box.

**Comment by karnage11** [comment]
anyone else having problems with the Filmkodi repo saying can't not connect to repository ?

**Comment by karnage11** [comment]
i am having a problem updating it to 2016.02.06.3

**Comment by romarvillon** [comment]
the zip above doesnt work anymore.

**Comment by romdogg** [comment]
the zip above doesnt work anymore

**Comment by karnage11** [comment]
where can I get the new one ?

**Comment by romdogg** [comment]
On top of this topic. You'll see the previous version that is working. Bur the problem is after during its update. It will get stuck at 3%

**Comment by karnage11** [comment]
I am on version 2016.02.06.02 atm

**Comment by romdogg** [comment]
mine is now updated now. install the zip files on within this thread.

**Comment by soulreeverz** [comment]
Installed it from the zip worked for a few minutes then said update failed and now it's not working again :-/

**Comment by karnage11** [comment]
working for me fine here

**Comment by karnage11** [comment]
have you tried the Repo - http://filmkodi.com/repository

**Comment by madnesuk** [comment]
Delete the repo to stop it from updating and try reinstalling the zip again

**Comment by soulreeverz** [comment]
Yeah I've tried to download the zip but it never finishes downloading it goes till it's almost done then just stops not sure what's going on

**Comment by madnesuk** [comment]
I've removed it from my set up, re-pushed the zip and installed it. It's failing. I'm guessing to many updating / installing is crippling the servers.

**Comment by saknox** [comment]
I can't install from either zip or repo

**Comment by karnage11** [comment]
I think they are having problems atm , there trying to fix it

**Comment by Delwashy** [comment]
I did mention this at the beginning that the new plugin was conflicting withe original repo so if you renove the repo you'll find that the new zip plugin works fine

**Comment by Delwashy** [comment]
Please remove the original repo and addon then install the new plugin

**Comment by saknox** [comment]
I'm using the new repo

**Comment by Delwashy** [comment]
nice one but there's still people not removing everything before installing the plugin even clear cache and packages from maintenance reboot your device then install the zip plugin

**Comment by saknox** [comment]
Ok now that's one thing I don't know how to do and have never done is clear the cache

**Comment by Delwashy** [comment]
if you've got a maintenance addon which you will have under Programs open it then click on maintenance depending on which maintenance but they are the same just worded different you will see delete/clear cache click on and click on yes the delete/purge packages click on yes then that's it all done and do this regularly

**Comment by saknox** [comment]
What's the purpose of doing this. I've seen ppl mention it b4 but never paid any attention to it

**Comment by jeanguy2** [comment]
Saknox, 

Some add-ons, Phoenix in particular will load lots of icons on your SSD and take up a significant amount of disk space. Clearing cache,and deleting and purging packages will get you back that space. Some Kodi devices have small SSD, 8 gigs or less, and 2 gigs or less memory leaving only 1 to 2 gig of free disk space. If maintenance is not routinely carried out, SSD will fill up and device become inoperative. Usually system will freeze & black screen only will show on re-boot. Restart Kodi after cleanup and Phoenix will start rebuilding its icon an OS its packages. You should carry out this maintenance once a month or if you see your SSD free space getting low.

**Comment by Delwashy** [comment]
i couldn't of said it any better Saknox once people start to read up and learn how their device works and how to maintain and update then they we how less issues and more enjoyment

**Comment by karnage11** [comment]
@Delwashy , i have an Amazon fire stick , do you think if i get the Amazon fire TV box is better since i can add a 128GB micro sd card and wont have lag or buffering issues with anything ?

**Comment by madnesuk** [comment]
I have the Amazon Fire box without the an SD card. I have no lag but still have the occasional buffer. The stream is only as good as the source

**Comment by karnage11** [comment]
ahh alright

**Comment by Delwashy** [comment]
what XML settings are you using?and as comment you'll always get buffering it all depends on what device which B/band you use i could go on try reading up on xml setting and check you tube for tutorials on this issue

**Comment by Delwashy** [comment]
We're starting to have problems with 1080 movies no streams available will this get resolved?

**Comment by madnesuk** [comment]
Select MQ. A few apps are going the same way

**Comment by Delwashy** [comment]
Don't get me wrong most of the HD streams work but thanks for the heads up

**Comment by mrknow** [comment]
Update problem solved. Added some new  servers to may cdn
