### ISSUE TITLE
Cda.pl puste wyniki wyszukiwania

### ISSUE THREAD

**Issue by miskz** [mrknow/filmkodi#755]
## Kodi & OS
- Kodi verison: 17.0 / Krypton
- OS version: OSMC - ArmHF Debian, 2017.01-1 + http://download.osmc.tv/dev/gmc apt repo (Krypton)

---
## Addon / Wtyczka
- [X] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: 2016.01.14.3 (ostatnie z repo)

---
## Issue / Zgłoszenie
- [X] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis

Problem dotyczy cda.pl, wyniki wszytkich wyszukiwań są puste. Pozostała funkcjonalność wygląda prawidłowo, możliwe jest przeglądanie kategorii i odtwarzanie filmów.

**Comment by rysson** [comment]
@miskz , czy dalej problem występuje? Ostatnio Mrknow dużo poprawiał.
Jak występuje to czy przy wszystkich wyszukiwaniach czy np. przy filmach?
