### ISSUE TITLE
błąd dodatku mrknow na androidzie!!!!

### ISSUE THREAD

**Issue by rekin65** [mrknow/filmkodi#756]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: _____
- OS version: _____

---
## Addon / Wtyczka
- [x] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [x] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

**Comment by rekin65** [comment]
dziś przestała działać wtyczka mrknow na androidzie przy próbie otwarcia któregokolwiek z odnośników wyskakuje błąd

**Comment by rekin65** [comment]
Zaczęło coś działać, ale openload dalej wyrzuca błąd...

**Comment by wilq66** [comment]
Openload zdechł

**Comment by ddawid7** [comment]
dokładnie openload zdechł , a jak u was CDA na mrknow ? u mnie nie dziala

**Comment by mrknow** [comment]
poprawiłem
