### ISSUE TITLE
NIE DZIAŁA YOY.TV ORAZ ESKAGO . PROSIMY O NAPRAWĘ

### ISSUE THREAD

**Issue by marekodfiranek** [mrknow/filmkodi#760]
Nie działa już poprawnie yoy.tv nie włącza z połowy kanałów oraz EskaGo nie odpala się w ogóle.Prosimy o naprawę.Pozdrawiam.

**Comment by koladka** [comment]
U mie eska go chodzi! Wiec moze przeinstaluj wtyczke. A co do yoy tv rozumiem ze masz wykupiona bo tylko tak dziala.?

**Comment by mrknow** [comment]
poprawiłem
