### ISSUE TITLE
Kodi 17 krypton - wsparcie

### ISSUE THREAD

**Issue by karbovski** [mrknow/filmkodi#761]
Witam, po update do wersji 17 kodi na raspberry nie działają wtyczki mrknow. Jak rozumiem wtyczki nie są przystosowane do wersji 17 bo jest nowa, ale czy planujecie wprowadzić wsparcie dla wersji 17 i ew. kiedy? Czy muszę wrócić do 15.2? :( Pozdrawiam.

**Comment by koladka** [comment]
Polecam wrocic do wersji 16. Tak czy siak widac ze mr know ostatnio jest zajety bo nieodpowiada na problemy z wtyczka:) Trzeba cierpliwosci moze zaskoczy nas nowa wtyczka  na kodi 17.??

**Comment by mrknow** [comment]
Chwilowo mam zawirowania w życiu prywatnym i zawodowym. Wrócę za ok 3 tygodnie

**Comment by koladka** [comment]
Dzieki za odpowiedz! Czekamy na powrot

**Comment by mrknow** [comment]
OK
Co mogłem to poprawiłem.
