### ISSUE TITLE
Error establishing a database connection

### ISSUE THREAD

**Issue by xxcriticxx** [mrknow/filmkodi#762]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: _____16.1
- OS version: _____ubuntu16.04

---
## Addon / Wtyczka
- [X] Filmy online - Mrknow
- [X] MrknowTV
- [X] Specto
- [X] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [X] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [X] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

Error establishing a database connection

**Comment by mrknow** [comment]
fixed site paste.filmkodi.com
