### ISSUE TITLE
Telewizjada prosi o login

### ISSUE THREAD

**Issue by Kubackjeee** [mrknow/filmkodi#767]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: _____17
- OS version: _____android TV

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [x ] MrknowTV
- [ ] Specto
- [ x] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [x ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ x] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
1.Kiedy probuje ogladac telewizje przez telewizjade prosi mnie o podanie loginu i hasla (o dziwo od pierwsza.tv). Na stronie telewizjady nie widze nigdzie mozliwosci zalogowania sie.

2. Fajnie jak w fanfilmie byscie dodali podzial na rozdzielczosc tak jak w specto. CZyli tam mamy do wybory 1080p albo 720. W Fan film sa tylko oznaczenia HD i HQ itd. A mam wrazenie ze niektore filmy oznaczone jakos HD sa w 720. Porownywalem te same filmy ze specto w 1080 do tych z fanfilma w HD i te ze specto wygladaja lepiej jakosciowo.

**Comment by mrknow** [comment]
FanFilm i Specto połączę w jedną wtyczkę, 
Chwilowo mam zawirowania w życiu prywatnym i zawodowym. Wrócę za ok 3 tygodnie

**Comment by koladka** [comment]
Polecam aplikacje z telewizja z google store dzialaja fenomenalnie;)

**Comment by Kubackjeee** [comment]
Jaka nazwa aplikacji?

**Comment by koladka** [comment]
OWL TV  lub TV LINE

**Comment by mrknow** [comment]
Telewizjada nie działa na kodi. Używają p2p, co wydaje mi się że nie jest legalne w Polsce. 
http://filmkodi.com/pl/delta-media-player-ze-strony-telewizjada-net/

**Comment by koladka** [comment]
Vpn zapora i wszystko w temacie;)Acha informuje ze po poprawce nic nie dziala?
