### ISSUE TITLE
Problem z yoy.tv

### ISSUE THREAD

**Issue by quatro7** [mrknow/filmkodi#768]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: 17
- OS version: android mm

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [ x ] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: najnowsza

---
## Issue / Zgłoszenie
- [ x ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

Występuje problem z obsługą yoy.tv. Nie pokazuje wszystkich kanałów

**Comment by nicram13** [comment]
Witam podobny problem brakuje czesci kanalow wersja MrKnowtv 2017.03.06.1 Kodi Jarvis wersja 16.1 Git:2016-04-24-c327c53 Przy nowszych wersjach kodi streamy z Yoy.tv nie ladowaly sie poprawnie badz wcale. Przede wszystkim zalezy mi na obsludze Hgtv w serwisie Yoy.tv. Aktualnie powyzszego streamu nie ma w grupie kanalow.

**Comment by mrknow** [comment]
Poprawiłem. Sprawdź w nowej wersji MrknowTV. Powinno działac
