### ISSUE TITLE
streamy tv nie dzialaja 

### ISSUE THREAD

**Issue by xxcriticxx** [mrknow/filmkodi#77]
dziala tylko telewizjada

to samo mam na androidzie, openelec, win7 kodi

**Comment by mrknow** [comment]
Tak 
Już mam poprawkę na typer tv, iklub i inne, ale boje się że znowu serwer się rozwali. 
Wrzucę po 2:00 nową wersję, która powinna załatać błędy streamów TV.

**Comment by mrknow** [comment]
O jednak dzisiaj nie wrzucę poprawki. Przechodzę na zipy, bo serwer do końca tygodnia całkiem padnie

**Comment by plumers** [comment]
MR wierzymy w ciebie - bo jednego wykop załatwił na amen :D pozdro ziom

**Comment by mrknow** [comment]
looknij - dodane, pozostałe streamny naprawione
