### ISSUE TITLE
Nie ma iklub na kodi w wtyczce mrknow

### ISSUE THREAD

**Issue by pawel1945** [mrknow/filmkodi#771]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: _____
- OS version: _____

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [x] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [ ] Bug report / Błąd
- [x] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

**Comment by pawel1945** [comment]
Dlaczego nie ma iklub w wtyczce mrknow i niedziała telewizyjka i telewizja live i nie dziala kanały canał +

**Comment by mrknow** [comment]
Te strony zostały zamknięte, ale nie wiem dlaczego. Telewizje będę w tym tygodniu robił w zgłoszeniu #830
