### ISSUE TITLE
Stop/abort file download

### ISSUE THREAD

**Issue by wbinek** [mrknow/filmkodi#772]
---
## Kodi & OS
- Kodi verison: 17
- OS version: libreelec v7.95.3 

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [ ] MrknowTV
- [x] Specto
- [ ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [ ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [x] Feature request / Prośba o nową funkcję
- [x] Question / Pytanie
- [ ] Other / Inne

---
## Description / Opis
I am new Specto user and I like it a lot - thanks for a great work!

I was just wondering if there is a possibility to stop/abort a file download? I can't find it.

**Comment by mrknow** [comment]
Restart kodi. Then the files will not download again
