### ISSUE TITLE
Fanfilm - nie działa - "brak dostępnego strumienia danych" 

### ISSUE THREAD

**Issue by Kubackjeee** [mrknow/filmkodi#775]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: _17____
- OS version: _____

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [ x] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [x ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis

Wtyczka fanfilm która jeszcze parę dni temu działała świetnie dzisiaj już nie działa. Gdy wyszukam film oraz źródła jest ok, ale jak już chce włączyć jedno ze źródel wyskakuje komunikat "bram dostępnego strumienia danych". Mam najnowsza aktualna wersję wtyczki. Specto działa bez problemu, fanfilm niestety nie. 
![screenshot_2017-02-24-22-52-49-498_com miui gallery](https://cloud.githubusercontent.com/assets/25844928/23322503/9228e3c6-fae4-11e6-9c2e-a3aa075e40f9.png)

**Comment by hellboy2** [comment]
Mam to samo też nie działa

**Comment by ddawid7** [comment]
u mnie też to samo

**Comment by hellboy2** [comment]
Może to ktoś naprawić

**Comment by Wawrzor** [comment]
W repozytorium kodu GitHub w ścieżce filmkodi/script.mrknow.urlresolver/lib/urlresolver9/plugins/ jest poprawiony 2 dni temu plik openload.py i cda.py. 
Niestety nie jest poprawiony w FanFIlm. 

Żeby zadziałało trzeba pobrać ten plik z GitHub i wkopiować go do ścieżki:
kodi/addons/plugin.video.fanfilm/resources/lib/resolvers

U mnie po podmianie pliku działa wszystko elegancko

**Comment by hellboy2** [comment]
A gdzie je znajdę

**Comment by Wawrzor** [comment]
Ale co konkretnie ?

**Comment by hellboy2** [comment]
Te pliki aby podmienić może masz możliwość dania ich gdzie na serwer ten cda i openload

**Comment by Wawrzor** [comment]
Tak jak napisałem są tutaj - na GitHub.
Wchodzisz w menu w zakładkę <code> I zgodnie ze ścieżką którą podałem odnajdujesz plik i ściągasz do siebie.

**Comment by hellboy2** [comment]
Nie mogę tego znaleźć

**Comment by Wawrzor** [comment]
Realy ?

https://github.com/mrknow/filmkodi/blob/master/script.mrknow.urlresolver/lib/urlresolver9/plugins/cda.py
https://github.com/mrknow/filmkodi/blob/master/script.mrknow.urlresolver/lib/urlresolver9/plugins/openload.py

Klikasz prawym na RAW i pobierz źródło.

**Comment by hellboy2** [comment]
Dzieki

**Comment by hellboy2** [comment]
Jakoś to słabo działa nadal brak dostępnego źródła

**Comment by hellboy2** [comment]
Ok działa sorki

**Comment by Gazownik** [comment]
Witam jestem totalnie słaby mam kodi zainstalowane i mam ten sam problem ze strumieniem danych może ktoś podpowiedzieć jak krok po kroku mam to wkleić wiem że to żałosne ale nie umiem. Prosze o pomoc

**Comment by hellboy2** [comment]
Chyba znowu coś jest nie tak, czy wam działa FanFilm

**Comment by Wawrzor** [comment]
Nie działa

**Comment by hellboy2** [comment]
No właśnie podmiana nic już nie daje

**Comment by hellboy2** [comment]
Rozwiązał może ktoś to

**Comment by hellboy2** [comment]
Nie wiem nikt czy da się to jakoś naprawić, czy trzeba czekać

**Comment by hellboy2** [comment]
Mr. Jeszcze to popraw

**Comment by hellboy2** [comment]
Czasami jest tak że z 2014 pokazuje że dostępny jest film i na czym.ale nie ładuje

**Comment by Wawrzor** [comment]
widzę, że Filmy Online doczekały się większej aktualizacji z poprawkami. Pytanie czy coś będzie robione z FanFIlm - u mnie już właściwie nic nie działa - większość linków nie odpala streama. 
Czy da się to jakoś poprawić, albo obejść ?

**Comment by mrknow** [comment]
poprawiłem. Powinno działać
