### ISSUE TITLE
CDA nie działa na androidzie (nie znaleziono streamingu)  , nie działa również openload .  Proszę o pomoc.

### ISSUE THREAD

**Issue by ddawid7** [mrknow/filmkodi#776]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: _____
- OS version: _____ANDROID

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [ x] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [x ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
CDA nie działa na androidzie (nie znaleziono streamingu)  , nie działa również openload .  Proszę o pomoc.

**Comment by polex9** [comment]
U mnie tez ani CDA ani Fan Film

**Comment by ddawid7** [comment]
a działa u ciebie openload z alltube ?

**Comment by hellboy2** [comment]
Mam to samo

**Comment by ddawid7** [comment]
macie namiary na autora to się zapytamy?

**Comment by Jackenmen** [comment]
Autor wtyczki ma chwilowo zawirowania w życiu prywatnym i zawodowym. Wróci za ok 3 tygodnie.

**Comment by hellboy2** [comment]
No to sobie poczekamy

**Comment by Jackenmen** [comment]
Niestety :/

**Comment by hellboy2** [comment]
Szkoda że wersji wtyczki cofnąć nie można

**Comment by Jackenmen** [comment]
Jak się znasz na GitHubie, to raczej możesz.

**Comment by hellboy2** [comment]
No właśnie się nie znam

**Comment by ddawid7** [comment]
Ja cofnelem i openload dalej leży

**Comment by hellboy2** [comment]
Skoro wiesz jak to zrobić to cofnij jeszcze FanFilm

**Comment by pqncy** [comment]
look here:
https://github.com/mrknow/filmkodi/issues/777

**Comment by ddawid7** [comment]
great !

**Comment by ddawid7** [comment]
openload dead : /

**Comment by Maariiusz** [comment]
Aby działał openload trzeba pobrać plik openload.py z tego linku:
https://megawrzuta.pl/download/e5f0366e2ed2fb8ec83b3f1a6b93edb5.html
i podmienić go w katalogu:
Kodi\addons\script.mrknow.urlresolver\lib\urlresolver9\plugins\

**Comment by ddawid7** [comment]
nie działa po podmienieniu pliku wyskakuje blad dodatku .

**Comment by Maariiusz** [comment]
faktycznie po wrzuceniu na serwer megawrzuta.pl plik zmienił swoją zawartość już jest nowy link z działającym plikiem 
http://host1gb.net.pl/download.php?file=926d9d9abe257f120c64bdc8991ca668

**Comment by ddawid7** [comment]
teraz działa :) dzięki !

**Comment by rekin65** [comment]
Jak podmienić ten plik w moim tablecie nie mogę znaleźć katalogu kodi. Proszę o dokładną instrukcję. Z góry dziękuję

**Comment by rekin65** [comment]
Cofam pytanie już mam.

**Comment by mrknow** [comment]
zaktualizowałem pliki. Powinny działać te 2 streamy
