### ISSUE TITLE
Nie działa CDA i Fan Film 

### ISSUE THREAD

**Issue by polex9** [mrknow/filmkodi#777]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: _____Krypton
- OS version: _____Android

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [x ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [ ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

**Comment by ddawid7** [comment]
u mnie również nie działa

**Comment by hellboy2** [comment]
mi też

**Comment by drrak** [comment]
Sprawdzaliście filmy z cda w przeglądarce? Wydaję się, że problem jest po stronie cda, a nie wtyczki.

**Comment by Jackenmen** [comment]
No działają.

**Comment by drrak** [comment]
U mnie nie działają przez Flash Player, ale przez player HTML5 już tak. To problem z Flashem na cda.pl

**Comment by mateusz-szafraniec** [comment]
To nie problem tylko CDA zakodowało linki prostym szyfrem. Bez ingerencji we wtyczkę się nie obejdzie. Ktoś kto zna Pythona sobie poradzi.

**Comment by drrak** [comment]
W takim razie jesteśmy zgubieni. **mrknow** chwilowo nie ma, a innych speców ze świecą szukać.

**Comment by pqncy** [comment]
CDA.PL Workaround:
http://pastebin.com/aXPbQ6Ty
replace file mrknow_urlparser.py in plugin.video.mrknow/lib

**Comment by Jackenmen** [comment]
Thanks man! I didn't try it already, but thanks for helping us. :D

**Comment by pqncy** [comment]
No problem bro!
http://wikisend.com/download/357434/plugin.video.mrknow.zip
Download, do not unpack, install from zip (in Kodi).

**Comment by ubvlhng** [comment]
Kodi wersja 16.1 (laptop z windows 10) wtyczka FanFilm nie działa.
Kodi 17 bez żadnych nakładek, laptop (też z windows 10) tu wtyczka FanFilm działa.
Może ktoś to wyjaśnić ?

**Comment by pqncy** [comment]
copy&paste logs here.

**Comment by Jackenmen** [comment]
@pqncy Just tried your workaround version of plugin and it works! Really thanks!

**Comment by drrak** [comment]
@pqncy Działa, dzięki. Zastanawiam się dlaczego nie edytowałeś tego pliku na _github.com_, tylko na _pastebin.com_.

**Comment by hellboy2** [comment]
A Fan Film też będzie działać

**Comment by krv69** [comment]
sorrka jestem ciemniakiem i nie mam zielonego pojecia co mam zrobić.. pomoże ktos? :)

**Comment by drrak** [comment]
@krv masz do wyboru:
a. podmienić plik _mrknow_urlparser.py_ w katalogu _/storage/.kodi/addons/plugin.video.mrknow/lib_ - tak wygląda ścieżka w LibreELEC
b. odinstalować wtyczkę **mrknow** i zainstalować nową z przygotowanego przez **pqncy** pliku _plugin.video.mrknow.zip_ (nie rozpakowywać!)

**Comment by Jackenmen** [comment]
Nie musisz odinstalowywać wtyczki.

**Comment by ddawid7** [comment]
CDA działa jak należy ;) jakiś pomysł na openload ?

**Comment by hellboy2** [comment]
A FanFilm nie działa

**Comment by Kubackjeee** [comment]
Czyli wchodzę w ten pierwszy link na pastebin i daje download. I ten plik axpbq6ty.py wstawiam zamiast mrknow_ulparer.py. Fanfilm będzie działal?

**Comment by Medonix** [comment]
Dałby ktoś radę zrobić z tym fanfilmem na gotowo tak aby działało po zainstalowaniu z zipa?

**Comment by Maariiusz** [comment]
Aby działał openload trzeba pobrać plik openload.py z tego linku:
https://megawrzuta.pl/download/e5f0366e2ed2fb8ec83b3f1a6b93edb5.html
i podmienić go w katalogu:
Kodi\addons\script.mrknow.urlresolver\lib\urlresolver9\plugins\

**Comment by rekin65** [comment]
Nie mogę znaleźć katalogu kodi na moim tablecie. proszę o dokładną instrukcję, z góry dziękuję. Tablet z Androidem

**Comment by mrknow** [comment]
zainstaluj lub zaktualizuj. Powinno działać, zrobiłem aktualizację
