### ISSUE TITLE
MrKnow dalej nie dziala :-((

### ISSUE THREAD

**Issue by hero2017** [mrknow/filmkodi#778]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: _16.1____
- OS version: _Android 6____

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [X ] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: _____2017.1.23

---
## Issue / Zgłoszenie
- [ X] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

Niestety teraz zadne kanaly nie dzialaja w MrKnow (TVN24, TVP1, TVP2, itd.). Sports Devil error: Web request failed. To jusz od dawna ale reportuje jeszcze raz. Prosil bym o poprawke. Jak moge pomoc jakos to prosze mi dac znac.

**Comment by mrjamescole** [comment]
kodi 16,1
os: Linux  3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u1 (2017-02-22) x86_64 GNU/Linux
addons: Filmy online - Mrknow

[kodi.log.zip](https://github.com/mrknow/filmkodi/files/802224/kodi.log.zip)

**Comment by koladka** [comment]
Juz Mr. Know pisal  mamy cierpliwie czekac;) Jest zajety moze znajdzie czas za 2 tygodnie;) A tym czasem proponuje dzialajaca wtyczke : ramic repository! Z Polska tv i cala gama wtyczek takich jak cda .zalukaj serialosy itp.; Rowniesz na android market aplikacja OWL tv  full i chodzi od sztycha,,,,

**Comment by hellboy2** [comment]
Wiesz może kiedy Mr. Będzie mógł poprawić wszystko

**Comment by koladka** [comment]
Niestety liczymy na to ze powroci wczoraj pisalem z Dimitrologii slynny yutubowicz kodi postara sie cos wygrzebac dla polskiej iptv;) Tymczasem znalazlem aki z tv na androida OWL TV  i  TV LINE

**Comment by hellboy2** [comment]
No to czekamy na Mr.

**Comment by hero2017** [comment]
Fajny jest OWL LIVE TV ale jest bardzo wolne i wiekszosc programow przerywa. Nie da sie ogladac...napszyklad lubie ogladac dziennik na TVN24 ale okropnie przerywa. Moj internet jest dosyc szybki, 100 Mb/s przez ethernet kabel tak ze to nie problem u mnie.

Poza tym to chociasz wszystko dziala i jest duzo polskich kanalow ale co z tego jak sie nie da ogladac. Szkoda!

**Comment by hero2017** [comment]
@helloboy2:  chyba nie ma na co czekac. MrKnow jusz sie nie stara od kilka tygodni...kiedys to jeszcze ale jusz dlugo nie mam dobrych polskich kanalow.

**Comment by koladka** [comment]
Ja mam 30 mg i ogladam wlasnie na tvn gwiezdne wojny:) wiec niewiem to moze zalezy od zakresowosci wifi!! Mi czasem przytnie ale nie na dlugo;) Polecam wtyczke ramic repository z Polska telewizja

**Comment by hero2017** [comment]
tv to jeszcze ale tvn24 lub wiekszosc inny popularnych kanalow to po prostu sie nie da ogladac. 30 mg czy 30 Mb...a gdzie mieszkasz? Ja w Toronto.

**Comment by koladka** [comment]
Uk;) teraz ogladam hushama na zywo na youtube koles razem ze slynnym dimitrologi  tlumacza najnowsze zagadnienia w kodi ! Aplikacje i buldy

**Comment by hero2017** [comment]
Zainstalowalem wtyczke Ramic ale co potem? Opcja "Run" widze ale nie moge wybrac. A w Video nie widze nigdzie Ramic. Cos mi tu brakuje.

**Comment by koladka** [comment]
Ja niewiem co ty masz z tym kodi ja wlasnie ogladam telewizje? Moze powinienes zainwestowac w vpn  czy cos z przesylem;)

**Comment by hero2017** [comment]
Ja nic mam z tym kodi. Prawdopodobnie nie dziala poza Europa lub z Kanady. Jak chodzi o placenie vpn to mi sie nie oplaca. Tylko moj ojciec chce ogladac dziennik od czasu do czasu. Ja to prawie nigdy. Trudno. Moze cos innego sie uda znalesc.

**Comment by koladka** [comment]
Dokladnie warto pogrzebac w internecie jest mnustwo streamow lub list  z kanalami ;) ja mam durzo czasu to szukam i mam na bierzaco linki ktore odtwarzam z aplikacji lub wrzucam w kodi , ale to juz osobna sprawa

**Comment by hero2017** [comment]
Grzebalem jusz. Mam pare linkow ale sa za wolne niestety, nawet na moim super szybkim kompie z szybkim internetem. Na skrzynce Mini II to nie znalem aplikacji co potrafi otworzyc te linki ale chyba Owl Live TV pozwala w pisac manualnie tak ze to kiedys wyprubuje jak znajde czasu. Ale chcial bym wyprubowac twoje linky jak ci dobrze dzialaja. Ojciec moze narescie sie ucieszy.

**Comment by koladka** [comment]
Vlc player jest bardzo prosty do plikow m3u;),Tak jak pisalem co jakis czas wychodza nowe , tak juz bywa z regoly ze przez jakis czas dzialaja potem lipa i odnowa szukanie. A co do buferu to tez jest roznie raz streaming dziala raz nie wszystko jest obciazony tak bywa i juz

**Comment by mrknow** [comment]
telewizję będę robił w tym tygodniu w zgłoszeniu #830 

Na cuda jednak bym nie liczył - bo te darmowe strony to tak sobie działają teraz
