### ISSUE TITLE
Nie działa YOY.TV 

### ISSUE THREAD

**Issue by rafalutek** [mrknow/filmkodi#780]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: 17
- OS version: Android TV

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [x ] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [x ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Niestety w tej wtyczce telewizja YOY nie działa, mam wykupione konto premium, na stronie online wszystko działa, kanały można oglądać a poprzez wtyczke mrknowtv działa tylko kilka kanałów, mimo że na stronce działają wszystkie.

**Comment by rafalutek** [comment]
Dodam jeszcze że jestem zalogowany do serwisu, najpierw pokazuje mi komunikat do kiedy konto premium aktywne a potem: Brak dostępnego strumienia danych.
Dodam jeszcze że ten sam kanał poprzez stronę internetową jest dostępny.

**Comment by Kolegamax20** [comment]
Mam ten sam problem już od dłuższego czasu, i nie ma poprawy.

**Comment by mrknow** [comment]
Poprawiłem. Proszę o sprawdzenie
