### ISSUE TITLE
Nie działa HipHop tv w EskaGo wtyczka MrKnow Tv

### ISSUE THREAD

**Issue by TOm84** [mrknow/filmkodi#783]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: 17.1
- OS version: OSMC

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [X] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: 2016.12.09.2

---
## Issue / Zgłoszenie
- [X] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [X] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.
Przy kliknięciu HipHop tv mieli, udaje że się ładuje ale się ładuje i nie włącza. Zero komunikatów o błędzie itp. Inne kanały w eskaGo również nie działają.

**Comment by mrknow** [comment]
poprawione w wersji 2017.03.06.01
