### ISSUE TITLE
Openload znowu padł!!!!!:-(

### ISSUE THREAD

**Issue by rekin65** [mrknow/filmkodi#784]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: _____
- OS version: _____

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [ ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

**Comment by hellboy2** [comment]
Chyba nikomu nie działa

**Comment by gallna** [comment]
Dopoki MrKnow nie naprawi bledow, moja **dzialajaca wersja FanFilm** - przygotowana na potrzeby demonstracji [pull request](https://github.com/mrknow/filmkodi/pull/779) z podmienionym wadliwym komponentem (_youtube_dl_ zamiast  _urlresolver9_).
- repozytorium **Kodi:** [plugin.video.fanfilm.dl](http://kodi.wrrr.online:888/addons.xml)
- repozytorium **git**: [pull request](https://github.com/mrknow/filmkodi/pull/779), [plugin.video.fanfilm](https://github.com/gallna/plugin.video.fanfilm)

Wersja robocza, jednak dziala na moim fire-stick przez ostatni tydzien. Dzisiaj naprawilem irytujacy niedzialajacy cancel button + [Openload](https://github.com/rg3/youtube-dl/issues/10408)

**Comment by s9215** [comment]
Potwierdzam Openload nie działa od dobrego tygodnia a może nawet dwóch.

**Comment by gallna** [comment]
Nie gwarantuje, ze bedzie dzialac, ale dzialajcy FanFilm [fork](https://github.com/gallna/filmkodi/tree/fanfilm/youtube-dl) znajdziecie w [repozytorium Kodi](http://kodi.wrrr.online:888) - stworzonym aby umozliwic przetestowanie zmian sugerowanych w [pull request](https://github.com/mrknow/filmkodi/pull/779).

**Comment by Wawrzor** [comment]
Możesz sprawdzić ścieżkę do repozytorium ?
Kodi twierdzi że nie istnieje. Z przeglądarki dostaje timeout

**Comment by hellboy2** [comment]
Kiedy ten Mr. wróci i poprawi to wszystko

**Comment by mrknow** [comment]
Poprawiłem openload. Biorę się za następne błędy

**Comment by s9215** [comment]
Dziękuję

**Comment by gallna** [comment]
kodi repo dostepne (icmp, tcp:888) http://kodi.wrrr.online:888
