### ISSUE TITLE
Mr. FanFilm znów nie działa brak strumienia 

### ISSUE THREAD

**Issue by hellboy2** [mrknow/filmkodi#788]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: _17____
- OS version: __windows 10___

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [x] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [x] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

**Comment by rekin65** [comment]
Przestał działać openload, o telewizji i relacjach nie wspomnę.....

**Comment by rekin65** [comment]
Na androidzie oczywiście....

**Comment by Wawrzor** [comment]
Na OSMC (RPi) też nie działa. W logach dostaję coś takiego

`00:46:29.623 T:1417036784  NOTICE: [FanFILM]: CDA-ONLINE RESOLVE URL https://openload.co/f/2lf4HLsK9KA
00:46:29.623 T:1417036784  NOTICE: [FanFILM]: #RESOLVER#  my url 1 ************ https://openload.co/f/2lf4HLsK9KA
00:46:29.624 T:1417036784  NOTICE: [FanFILM]: !!!!!!!!! ERROR #urlresolver2#  URL global name 'urlresolver' is not defined
00:46:30.534 T:1417036784  NOTICE: [FanFILM]: FilmyTO RESOLVE URL https://openload.co/embed/T-LQSk-5Y0M
00:46:30.535 T:1417036784  NOTICE: [FanFILM]: #RESOLVER#  my url 1 ************ https://openload.co/embed/T-LQSk-5Y0M
00:46:30.535 T:1417036784  NOTICE: [FanFILM]: !!!!!!!!! ERROR #urlresolver2#  URL global name 'urlresolver' is not defined`

**Comment by wojtas2323** [comment]
Na android applikacja sie zaktualizowala ale I tak nie robi; (

**Comment by hellboy2** [comment]
Mr. Jesteś napraw jak możesz

**Comment by mrknow** [comment]
Naprawione, sprawdź aktualizację

**Comment by mrknow** [comment]
Powinno działać, jak zaktualizujesz wtyczkę

**Comment by wojtas2323** [comment]
Jest zaktualizowana na najnowsza wersje nie robi nic

**Comment by Wawrzor** [comment]
Mr know - jest kilka błędów. Nie jest dodana do repo biblioteka pyaes.py - leci błąd od razu na dzień dobry. Po dodaniu do liba jest lepiej ale openload dalej nie robi. Z logu wynika że jakiś problem z kodowaniem urla.

**Comment by hellboy2** [comment]
Mr. Narazie działa dobrze

**Comment by hellboy2** [comment]
Mr.Fanfilm już nie działa brak strumienia

**Comment by mrknow** [comment]
poprawiłem wtyczkę. Sprawdź po aktualizacji
