### ISSUE TITLE
Witam nie dziala Wizja tv 

### ISSUE THREAD

**Issue by Baz5zz** [mrknow/filmkodi#790]
Witam wczesniej korzystalem Juz z tej wtyczki i wszystko pięknie grało.Nic się nie zacinało .Az do pewnego momentu  gdy po 3 miesiącach wykupiłem znów na 3 miesiące. Przełom października Listopada.odbieram tv przez boxy z Chin zamówiłem już drugi wykupiłem premium a dalej nie działa wyświetla się proszę czekać i znika mam kodi 17.1 Proszę o pomoc mieszkam w Szwecji a nie mogę mieć anteny sat na zewnątrz .Jakies pomysły  porady ???

**Comment by iwan051772** [comment]
Juz działa

**Comment by Baz5zz** [comment]
Niestety nadal nie działa wyświetla się proszę czekać i tyle .Sprawdze jeszcze raz po pracy może coś zle ustawiłem ???

**Comment by borys76** [comment]
Wczoraj wizja padla na lidze mistrzow

**Comment by iwan051772** [comment]
Tak dokladnie ale juz jest ok

**Comment by Baz5zz** [comment]
Witam a mi nie działa nadal ,może jakieś sugestie ???

**Comment by borys76** [comment]
Nie dziala na www masz komunikat ze awaria

**Comment by Baz5zz** [comment]
Dzięki wiec pozostaje czekać.

**Comment by mrknow** [comment]
Sprawdziłem. Wtyczka działa poprawnie
