### ISSUE TITLE
Po aktualizacji dalej nie działają sekcje:

### ISSUE THREAD

**Issue by king10000** [mrknow/filmkodi#792]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: _____
- OS version: _____

---
## Addon / Wtyczka
- [x ] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [x ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [ ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

Po aktualizacji dalej nie działają sekcje: 
Cda - wyszukiwanie nie działa 
E - filmy - wszystko można przeglądać, ale nic nie można odtworzyć
Fan film - nie działa openload, ale po aktualizacji kilka godzin działał.

Android TV - Kodi 17.0

**Comment by hellboy2** [comment]
Ja ma zainstalowany tylko sam FanFilm na telefonie i mi działa

**Comment by koladka** [comment]
Kanaly swietna robota aktualizacja z dzisiaj! Tv smiga;) Warto bylo czekac Mr know.

**Comment by wojtas2323** [comment]
Koladka jak smiga jak nie smiga to cos ze mna nie tak caly czas to samo

**Comment by wojtas2323** [comment]
Robia kanaly tv na mrknow filmy on line

**Comment by wojtas2323** [comment]
Robia kanaly tv na mrknow filmy on line

**Comment by koladka** [comment]
Smiga wlasnie ogladam!;)

**Comment by wojtas2323** [comment]
Zwracam honor dzialaja canal+ tylko nie robi

**Comment by koladka** [comment]
Teraz na bajkach mam bo corka oglada

**Comment by mrknow** [comment]
E - filmy - planuje poprawić  jutro

**Comment by koladka** [comment]
Mr know niestety wiekszosc znow nie dziala , jutro rano napisze ktore szczegolowo!;)

**Comment by mrknow** [comment]
poprawiłem. powinno działać. Dajcie znać
