### ISSUE TITLE
FanFilm nie działa

### ISSUE THREAD

**Issue by hellboy2** [mrknow/filmkodi#796]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: _17____
- OS version: __android___

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [x ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [ ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

**Comment by hellboy2** [comment]
Czy na tych stronach co ogląda się zmieniają jakieś kodowanie czy blokują w jakiś sposób

**Comment by hellboy2** [comment]
Mrknow jesteś

**Comment by hellboy2** [comment]
Udało się coś naprawić

**Comment by hellboy2** [comment]
Dobra działa to chyba ja miałem jakieś błąd

**Comment by hellboy2** [comment]
Ale po tych poprawkach co zrobiłeś to już będzie dobrze działać

**Comment by hellboy2** [comment]
Mrknow zrobiła się aktualizacja i już nie działa FanFilm

**Comment by mrknow** [comment]
poprawiłem. Powinno działać prawidłowo
