### ISSUE TITLE
Openload znowu padł!!!! Android wersja kodi 16

### ISSUE THREAD

**Issue by rekin65** [mrknow/filmkodi#797]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: _____
- OS version: _____

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [ ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

**Comment by hellboy2** [comment]
Mrknow chyba czasu nie ma aby zająć się

**Comment by mrknow** [comment]
Przed chwilą puściłem aktualizację 
id="script.mrknow.urlresolver" name="Mrknow URLResolver" version="2017.03.13.1

Powinno działać po aktualizacji

**Comment by mrknow** [comment]
Teraz będę miał coraz więcej czasu na poprawki, więc powinno być coraz lepiej

**Comment by rekin65** [comment]
Nie ma jeszcze aktualizacji jest tylko wersja 2017.03.11

**Comment by rekin65** [comment]
Nadal nie ma aktualizacji do wersji 2017.03.13 jeżeli jest możliwość ręcznej aktualizacji proszę o opis jak to zrobić. Dziękuję

**Comment by rekin65** [comment]
Nadal nie działa openload, jak zaktualizowac mrknow skoro ostatnią aktualizacją jaką widzi jest 2017.03.11?

**Comment by mrknow** [comment]
Openload codziennie zmienia algorytmy 
Wersja z dzisiaj ponownie naprawia ten błąd http://kodi.filmkodi.com/script.mrknow.urlresolver/script.mrknow.urlresolver-2017.03.14.1.zip

**Comment by mrknow** [comment]
Aktualizacja automatyczna powinna zainstalować najnowszą wersję Mrknow Urlresolver

**Comment by rekin65** [comment]
Ok działa. Dzięki
