### ISSUE TITLE
pomysly na nowe serwisy

### ISSUE THREAD

**Issue by xxcriticxx** [mrknow/filmkodi#8]
http://www.olweb.tv/tv_channels/poland/
http://nowwatchtvlive.me/poland-tv-channels-live-stream-watch-polish-tv-online-channel-free/
http://streema.com/tv/country/Poland

**Comment by ip5d** [comment]
https://github.com/mrknow/filmkodi/issues/16#issuecomment-162817884

**Comment by xxcriticxx** [comment]
http://pure-cast.net/strona-glowna
http://www.telewizjada.net/
http://goldvod.tv/
http://yoy.tv/channels

**Comment by xxcriticxx** [comment]
http://filmykino.tv

**Comment by mar2016** [comment]
yoy.tv

**Comment by xxcriticxx** [comment]
http://pivotv.pl/telewizja/

**Comment by xxcriticxx** [comment]
https://www.horizon.tv/pl_pl/ogladaj-tv.html

**Comment by xxcriticxx** [comment]
http://looknij.tv

**Comment by xxcriticxx** [comment]
http://telewizjairadioprogramy.pl/tunertv.htm

**Comment by xxcriticxx** [comment]
http://vidtv.pl/

**Comment by xxcriticxx** [comment]
https://videostar.pl/tv

**Comment by xxcriticxx** [comment]
http://wkinie.tv/
http://www.tvseriesonline.pl/
http://kinofan.tv/
http://nocnyseans.pl/

**Comment by xxcriticxx** [comment]
http://www.films-online.pl/

**Comment by WerVa** [comment]
http://southparksite.pl/
