### ISSUE TITLE
nic nie robi zadna tv na mrknow filmy online wsio siadlo

### ISSUE THREAD

**Issue by wojtas2323** [mrknow/filmkodi#800]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: _____
- OS version: _____

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [ ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

**Comment by koladka** [comment]
Rowniez wszystko siadlo po aktualizacji

**Comment by mrknow** [comment]
a możecie wstawić logi

**Comment by koladka** [comment]
Niedziala iklub, sitomtv1, na tele miki 2 kanaly dzialaja ana tym ostatnim poprawionym caly dzial info niedziala i dzial nauka

**Comment by mrknow** [comment]
OK 
sitemtv1.rf.gd - poprawiłem przed chilą w wersji 2017.03.18.3. Zaktualizuj 

Jeżeli chodzi o iklub - to podaj kanał który działa na www, a nie działa w Kodi

**Comment by koladka** [comment]
Na Telewizja Polska z innej wtyczki  na Nadajemy Tv jest pare kanalow ktore chodza zawsze moze warto dodac! Na sitemtv1-- No stream avanable;( dalej nic! Ja dzis np.Ogladam z  ULTIMATE IPTV  z linku m3u z 16 marca caly pakiet dziala spoko

**Comment by koladka** [comment]
Co do iklub to ta telewizja przez wiekszosc dnia i wieczorem niedziala wiec niewidze sensu zeby ja podtrzymywac

**Comment by koladka** [comment]
Dzis na tej telewizyjnej wtyczce  na miki tv i reszcie --- NO STREAM AIVANABLE czy jakos tak

**Comment by mrknow** [comment]
Wszystkie strony padły (np iklub), lub działają przez maks 5 minut (jak  nowatvnet, telemaniakorg).  Będę starał się w tym tygodniu dodać więcej źrudeł w zgłoszeniu #830
