### ISSUE TITLE
CDA kodu 17, android tv

### ISSUE THREAD

**Issue by marqius2** [mrknow/filmkodi#803]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: 17
- OS version: _____

---
## Addon / Wtyczka
- [x ] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [ x] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [ x] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.
Od miesiąca nie jestem w stanie otworzyć żadnego filmu z CDA.  Teraz nawet nie mogę wejść w CDA.  Wyskakuje błąd

**Comment by marqius2** [comment]
Błąd dodatku. Wszystko co działało ok miesiąc temu,  już teraz nie działa.  De facto wszystko co jest powiązane z CDA i openload.

**Comment by marqius2** [comment]
http://paste.filmkodi.com/view/a787ca1f

Moje logi. Hasło sobie zmienię :-)  po wejściu w CDA wywala błąd

**Comment by souacz** [comment]
U mnie to samo

**Comment by mrknow** [comment]
Dzięki za info
Były 2 problemy:
openload - codziennie zmieniają sposób kodowania linków i czasami może nie działać 
FanFilm - poprawiłem aby prawidłowo odtwarzał źródła. Teraz będzie działał poprawnie

**Comment by souacz** [comment]
Ale cda nie działa nadal :( Pobrałem ponownie wtyczkę z repo i nic to nie dało.

**Comment by marqius2** [comment]
Również pre-instalowalem. Bez zmian. Ściągnąłem jakąś inną wtyczkę samego CDA i działa bez problemu. Wolę natomiast Twoja Mrknow :-)

**Comment by hellboy2** [comment]
A czemu trzeba wyczyścić dane i pobrać wtyczkę FanFilm i zacznie działać

**Comment by souacz** [comment]
@marqius2 też uzywam wtyczki cda od ramica ale u niego nie da się odtworzyć płatnych filmów a ja mam abonament cda.pl. Na MrKnow się dało ale teraz nie można w ogóle otworzyć cda.

@hellboy2 żeby działała wtyczka cda trzeba zainstalować FanFilm????

**Comment by borys76** [comment]
Juz po ramicu :(

**Comment by souacz** [comment]
dlaczego? jeszcze kilka dni temu poprawiał wtyczkę, coś się stało?

**Comment by borys76** [comment]
https://github.com/ramicspa/kodi
Juz update nie zrobisz

**Comment by souacz** [comment]
Kaszana.... szkoda bo miał fajne wtyczki. No to liczymy na @mrknow  ... Popraw Maestro tę wtyczkę z cda

**Comment by hellboy2** [comment]
FanFilm mam zainstalowany i po aktualizacji nie działa czasami, a po wykasowaniu danych i ponownym zainstalowaniu znacznie działać mowa o Android

**Comment by souacz** [comment]
Aha, myślałem, że ma to jakiś związek z cda.pl

**Comment by rekin65** [comment]
Nie działa openload!!!

**Comment by hellboy2** [comment]
Jak openload zmienia coś to nie działa

**Comment by mrknow** [comment]
@hellboy2 - u mnie działa 
Wykonaj aktualizację wtyczki (http://filmkodi.com/pl/aktualizacja-wtyczki-zrobic/) i sprawdź czy masz:
- Fanfilm w wersji 2017.03.18.1
- Mrknow Urlresolver w wersji 2017.03.15.3

**Comment by souacz** [comment]
@mrknow a wtyczkę z cda poprawisz?

**Comment by mrknow** [comment]
@hellboy2 - a dokładnie jaki jest problem z cda i w której wtyczce ? Poprawie - tylko napisz dokładnie co nie działa

**Comment by souacz** [comment]
FilmKodi - po wejściu w cda wywala błąd, powyżej ktoś wkleił logi więc nie będę powielać.

**Comment by yngbld** [comment]
@mrknow czy EKSTRAKLASA TV mozesz dodac?
PLS

**Comment by mrknow** [comment]
CDA premium. OK poprawiam

**Comment by souacz** [comment]
Dzieki

**Comment by hellboy2** [comment]
Mrknow działa dzięki

**Comment by hellboy2** [comment]
Filmy online wtyczka cdax.tv pisze może to chwilowa awaria spróbuj za jakiś czas

**Comment by souacz** [comment]
nie cdax tylko cda, to róznica

**Comment by mrknow** [comment]
Witam 
Za kilka minut na serwerach będzie nowa wersja 2017.03.18.2 wtyczki Filmy Online – mrknow

Konta premium powinny działać prawidłowo

**Comment by souacz** [comment]
Dzięki wielkie!

**Comment by mrknow** [comment]
Dobra. Jeszcze nie jest idealnie. Mogą się pokazywać komunikaty o nie zalogowaniu. Naprawię później

**Comment by souacz** [comment]
ok

**Comment by MrPonos** [comment]
https://logs.tvaddons.ag/pjsbelo75#line-1015
Openload nadal nie działa. 
Link łapie ale nie odtworzy. 

Pozdrawiam i liczę na pomoc.

**Comment by mrknow** [comment]
Logi to lubię - zaraz sprawdzę i naprawię.

**Comment by MrPonos** [comment]
Z góry dziękuję, bo świetnie działało a teraz nie ma co oglądać.

**Comment by hellboy2** [comment]
Fanfilm działa dobrze to na tym też można oglądać

**Comment by rafciu27** [comment]
Fanfilm nie wyłapuje materiałów z CDAOnline/cdax.tv. Gdy włącza się dany materiał z tego serwisu wyskakuje komunikat o braku strumienia, choć strumień na przeglądarce działa.

**Comment by hellboy2** [comment]
Że nie wyłapuje ale dany film jest i działa a jest różnica na czym dany film obejrzę

**Comment by MrPonos** [comment]
Właśnie chodzi o Fanfilm. Linki są ale openload w HD nie otwarza. Próbuje włączyć ale się wysypuje.

**Comment by hellboy2** [comment]
Ja włączyłem xxx reaktywacja i jakoś dział

**Comment by MrPonos** [comment]
Spróbuj włączyć serial LOST np odcinek 22

**Comment by hellboy2** [comment]
Sezon 1 to działa

**Comment by MrPonos** [comment]
Ale openload w HD?

**Comment by hellboy2** [comment]
HQ to widzę HD nie

**Comment by MrPonos** [comment]
To już teraz nie wiem co jest grane. Fanfilm zaktualizowałem do najnowszej wersji. Trzeba coś zrobić dodatkowo?

**Comment by hellboy2** [comment]
A na czym masz na Androidzie bo ja wyczyscilem dane i na nowo wgrałem wtyczkę

**Comment by MrPonos** [comment]
LibreELEC na boxie. Odinstalowałem wtyczkę i na nowo ale nadal nic. Znajduje link, próbuje zaczynać odtwarzać i crash

**Comment by hellboy2** [comment]
To nie wiem na pc i Androidzie mi działa

**Comment by souacz** [comment]
@mrknow na kodi 17 wtyczka się zaktualizowała i mimo wyskakującego powiadomienia "błąd logowania" - filmy płatne da się odtworzyć, wypróbowałem właśnie na filmie premium. Mam problem na SPMC 16.5: w repo widzi tylko poprzednią wersję wtyczki, jak to zaktualizować? Wolę SPMC bo na kodi 17 mam Cpu temp 80*C a na SPMC 55*C w czasie odtwarzania

**Comment by rafciu27** [comment]
A włączyłeś XXX reaktywacja hq z alltube czy cdaonline hd? HD nie działa mi na żadnej platformie; boxie, telefonie, komputerze, smart TV.

**Comment by marqius2** [comment]
U mnie teraz przy wyszukiwaniu w FanFILM w ogóle nie wyszukuje w CDA.  Ale samo CDA działa i to z premium.

**Comment by marqius2** [comment]
Ahhh..no i po wyszukaniu źródeł poza tym,że brak CDA to z "filmyto" nie idzie nic odtworzyć.  Tylko Hq z alltube.  Czyli HD brak

**Comment by MrPonos** [comment]
Wiadomo coś już co z tym openload? Z serwisu filmyto to w niektórych przypadkach w ogóle  nie odtwarza wersji w hq

**Comment by hellboy2** [comment]
Xxx reaktywacja na alltube openload bo jest też alltube/cda/napisy to też działa

**Comment by hellboy2** [comment]
FanFilm już nie działa bynajmniej openload

**Comment by rekin65** [comment]
Nie działa nadal openload, wyskakuje błąd.

**Comment by mrknow** [comment]
Z openload codziennie zmieniają kod do linków wideo. 

Dzisiaj wprowadziłem rozwiązanie które sprawdza czy link dekodowany jest prawidłowy. Jeżeli jest nieprawidłowy to  wykorzysta metodę z "pair"

**Comment by MrPonos** [comment]
Super. Tak w sumie działa exodus. Na kiedy można spodziewać się aktualizacji.

**Comment by mrknow** [comment]
Juz jest na serwerach 
name="Mrknow URLResolver" version="2017.03.18.3"

**Comment by marqius2** [comment]
Tak żeby zreasumować ten wątek bo w sumie go zacząłem.

Od zgłoszenia zmieniło się 👍 
# Mogę już wejść bezpośrednio w CDA przez wtycznę mkrknow film online.

CO nie działa 👍 
W FAN FILM jak wyszukiwało źródła było widoczne źródło CDA, filmyto etc.

Teraz po wyszukaniu (testuję cały czas na jednym filmie, oglądanym już + kilka innych tytułów)
nie wyświetla się źródło CDA , żadne . W sumie ,żadnego HD tylko HQ

**Comment by MrPonos** [comment]
Po aktualizacji Mrknow URLResolver zatrzymuje się na openload kręci ale nie odtwarza. Jak trzeba to mogę wrzucić loga jeszcze raz.

**Comment by MrPonos** [comment]
Podsumowując... Problem rozwiązany... Repo remica wróciło i zainstalowałem od niego iitv. Wszystko hula jak trza.

**Comment by souacz** [comment]
Taa... wiem, na tvaddons dał dzień po wywaleniu z githuba.

**Comment by MrPonos** [comment]
Wcześniej też tam miał ale teraz zaktualizował

**Comment by souacz** [comment]
na githubie ramica nadal brak, ja ciągnę z tvaddons ale jego plugin cda nie umożliwia odtwarzania premium a MrKnow tak więc cda od ramica wywaliłem. Płacę za cda i najbardziej zależy mi na premium

**Comment by MrPonos** [comment]
Może i tak, mnie zastanawia jedno... Czemu robi 5 wtyczek na raz zamiast jednej żeby działało.

**Comment by souacz** [comment]
Ale kto?

**Comment by MrPonos** [comment]
Mrknow

**Comment by souacz** [comment]
Do CDA Premium jest jedna i to uniwersalna, obsługująca też wielu innych dostawców treści - Filmy Online. To ramic się rozdrabnia, kilkanaście wtyczek zamiast zawrzeć wszystko w jednej, MrKnow ma raptem 4 i zobacz ile serwerów obsługują.

**Comment by MrPonos** [comment]
Może i ma kilka wtyczek ale działają. Mrknow robi 4 a każda ma problem. Czemu robi Fanfilm a później inna gdzie np jest CDA jak mogłoby to być na wzór exodusa. To już wolę kilka osobnych w prostych formach ale działające.

**Comment by souacz** [comment]
Tak ale z wtyczką ramica do cda też było kupę problemów, co chwilę poprawiał. A w końcu wyciął premium bo nie mógł sobie poradzić z zagadnieniem. Wtyczka Filmy Dokumentalne też co jakiś czas mi nawala. E-kabaret - to samo. Nie twierdzę, że u MrKnow jest lepiej, problemy są głównie z powodu mieszania przez dostawców ale przynajmniej cda premium da się oglądać. W sumie dziwię się CDA.pl, że nie wydali swojej aplikacji lub wtyczki do Kodi, w końcu właściciele Android Boxów to w tej chwili spory procent korzystających z takich serwisów.

**Comment by mrknow** [comment]
Mam w planach przygotowanie oddzielnej wtyczki dla cda premium (tylko nie wiem kiedy).

Od teraz mam więcej czasu na te zadania więc błędy powinny być rozwiązywane szybciej.
