### ISSUE TITLE
yoy.tv

### ISSUE THREAD

**Issue by marek2k** [mrknow/filmkodi#807]
## Kodi & OS
- Kodi verison: 17.1-RC1
- OS version: Xbuntu 16.04

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [ x] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: 2017.03.06.1

---
## Issue / Zgłoszenie
- [ x] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Mam wykupione konto premium w tym serwisie yoy.tv Problem polega na tym, że kanały aktualnie transmitowane na stronie yoy.tv nie pokrywają się z tymi, które wyświetla wtyczka. Nie pomaga opcja czyszczenia cache, a nawet ręczne kasowanie pliku .kodi/userdata/addon_plugin/plugin.video.mrknowtv/cache.db
Z tego co zauważyłem, to po wyczyszczeniu cache wtyczka ładuje aktualne numery kanałów ze strony, ale lista kanałów wyświetlanych się nie aktualizuje.
np kanał TVP1 ma id 5099 - w logach się pojawia, a na liście go nie mam.

`12:38:57.401 T:140501055526656  NOTICE: [MrknowTV]: ->----------                PARAMS: {}
12:39:00.037 T:140501055526656  NOTICE: [MrknowTV]: ->----------                PARAMS: {'action': 'tv', 'url': 'yoy'}
12:39:00.832 T:140501055526656  NOTICE: [MrknowTV]: YOY channel 5099
`

**Comment by marek2k** [comment]
Znalazłem problem. Kanały znikają z listy, bo mam ustawioną opcję, aby pokazywane były tylko filmy nieobejrzane w bibliotece. Gdy włączę pokazywanie wszystkich filmów, lista kanałów TV jest aktualna. 

Czy można zrobić tak, żeby włączenie kanału nie ustawiało znacznika na obejrzany?

**Comment by mrknow** [comment]
nie planuję tego na razie. Nie mam na to czasu. Może jak yoy wprowadzi api - to zrobię dedykowaną wtyczkę
