### ISSUE TITLE
iitv

### ISSUE THREAD

**Issue by s9215** [mrknow/filmkodi#809]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: _____
- OS version: _____

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [ ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ x] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

Czy jest szansa aby w Filmy Online - MrKnow.pl pojawiła się obsługa iitv.pl ?
Bo nie wiem jak to wygląda od strony technicznej 
Pytanie narodziło się gdyż serial mojej żony zniknął z Alltube (Grimm znaczy został tylko 6 sezon)

**Comment by koladka** [comment]
A probowales na wtyczce Telewizja Polska!?

**Comment by mrknow** [comment]
sprawdź wtyczkę fanfilm http://filmkodi.com/pl/wtyczka-fanfilm-kodi-trakt-tv/
