### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by karnage11** [mrknow/filmkodi#81]
i Can't install the repo , anyone else having that problem , I keep getting can't connect to Repo

**Comment by karnage11** [comment]
can't install new update

**Comment by romdogg** [comment]
same here

**Comment by lisalange79** [comment]
I have been unable to install since 2-6-16

**Comment by jewel22672** [comment]
I have tried to reinstal for two days  it gets stuck at 3 percent and after 10 minutes it says failed.  Any suggestions

**Comment by karnage11** [comment]
add the repo http://filmkodi.com/repository

**Comment by lisalange79** [comment]
We did that, it doesn't work :/

Sent from Yahoo Mail on Android 
 
  On Mon, Feb 8, 2016 at 3:45 PM, karnage11<notifications@github.com> wrote:   
add the repo http://filmkodi.com/repository

**Comment by karnage11** [comment]
Server can be down

**Comment by lisalange79** [comment]
FINALLY got it!! Kept trying for a few days and it finally worked today

Sent from Yahoo Mail on Android 
 
  On Tue, Feb 9, 2016 at 1:52 AM, karnage11<notifications@github.com> wrote:   
Server can be down

**Comment by karnage11** [comment]
yea there servers can't handle everyone trying to update it

**Comment by mrknow** [comment]
Tomorrow we'll buy some servers and see if this solves the problem

For now you can install add-ons manually, latest zip files:
[plugin.video.specto-2016.02.07.3.zip](https://github.com/mrknow/filmkodi/files/123826/plugin.video.specto-2016.02.07.3.zip)
