### ISSUE TITLE
yoy tv

### ISSUE THREAD

**Issue by peater52** [mrknow/filmkodi#811]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: _____
- OS version: _____

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [ ] MrknowTV x
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [ ] Bug report / Błąd x
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

Witam 

Mam wykupione konto premium na yoy tv i wszystko jest ok tylko programów TVN nie mam. Na windows mam te programy

Pozdrawiam

**Comment by talar666** [comment]
Potwierdzam, brak programów Tvn, tvn turbo

**Comment by iwan051772** [comment]
Nie bedzie tvn ale jest tv trwam i republika.Dobra zmiana
