### ISSUE TITLE
Openload fan film brak dostępnego strumienia danych. Mr Know pomożesz?

### ISSUE THREAD

**Issue by Jam55** [mrknow/filmkodi#812]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: _____
- OS version: _____

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [ ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.
Brak dostępnego strumienia danych na Openload  Fan Film. Możesz poóc Mr Know?

**Comment by Jam55** [comment]
Brak dostępnego strumienia danych na Openload Fan Film. Możesz poóc Mr Know?

**Comment by koladka** [comment]
Musisz wejsc na openload i wcisnac pair  wtedy sie odblokowuje na 3 godz.

**Comment by Jam55** [comment]
robie tak jak mowisz niestety to nie dziala

**Comment by koladka** [comment]
To  w takim razie wina wtyczki musi byc?!

**Comment by hellboy2** [comment]
Mi działa

**Comment by koladka** [comment]
Ta pewnie bo ty masz czarodziejski streaming

**Comment by hellboy2** [comment]
Nie wiem, ale działa

**Comment by koladka** [comment]
Ale chodzi mi o telewizje?

**Comment by hellboy2** [comment]
A to tego nie oglądam

**Comment by koladka** [comment]
No wlasnie filmy to ja mam inne wtyczki! Wiekszosci chodzi glownie o dzialajaca tv bo grono zagranica ma kodi poinstalowane do tv

**Comment by Jam55** [comment]
A mam pytanie na jakich działających wtyczkach można oglądać filmy i seriale? Jest teraz coś ala kinoman? Nic ciekawego nie mogę znaleźć. Z góry dziękuję za pomoc.

**Comment by koladka** [comment]
Na wtyczce ramica jest mnostwo wtyczek

**Comment by Jam55** [comment]
Masz racje ale niestety wiekszisc albo nie dziala jak np efilmy.tv mam konto premium u nich a na wtyczce jak wchodze nje wyswietla sie nic.Zero filmow zero seriali.Jest tylko lista a jak w nia wejde np w filmy to jest pusta strona to samo z serialami. Wydaje mi sie ze jest to jedyna sensowna strona z filmami i serialami po upadku kinomana ale niestety wtyczka nie dziala.

**Comment by koladka** [comment]
Ja ogladam seriale na wtyczce- iitv.info

**Comment by hellboy2** [comment]
Koladka a jakie wtyczki używasz do filmów

**Comment by koladka** [comment]
Zagranicznych i napisy np dotego z wtyczki

**Comment by hellboy2** [comment]
To podasz nazwy

**Comment by koladka** [comment]
SALTS stream All the sources
Supremacy
Vandetta
Yes Movies
Zem
Project M
ZEN
THE Players klub
Evolve
Silent Hunter
Bubbles
Exodus
GoodFellas 2.0
HEVC VideoClub
IceFilms
Jafma
M4U
Movie Echo
MovieMagic
Phoenix
    To kilka przykladowych wtyczek z video

**Comment by hellboy2** [comment]
A skąd je brać jakieś linki możesz na pocztę podesłać k1975@onet.pl

**Comment by koladka** [comment]
Na youtube  wpisuj pod filmami sa czasem linki i sciagasz lub wpisz nazwe danej wtyczki w google i tyle reszta to posciagac add-on, lub repo Ja mam tego w setkach

**Comment by hellboy2** [comment]
To się podziel
