### ISSUE TITLE
Filmy online nie działają

### ISSUE THREAD

**Issue by gujaq3** [mrknow/filmkodi#813]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: _16.1____
- OS version: _____

---
## Addon / Wtyczka
- [x ] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [x ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [ ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ x] Other / Inne

---
## Descryption / Opis
Po instalacji dostaje komunikat jest jest niekompatyblina.

Działa tylko MrknowTV reszta martwa

**Comment by hellboy2** [comment]
Tzn które nie działają
