### ISSUE TITLE
FanFilm - Openload - nie działają filmy HD

### ISSUE THREAD

**Issue by Wawrzor** [mrknow/filmkodi#815]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: _____krypton najnowszy 
- OS version: _____osmc rp3

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [ x] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [ x] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

Po ostatnim updacie url resolvera cześć filmów i seriali z openload po separowaniu na stronie działa ale tylko w HQ. Wszystkie linki opisane jako HD wyrzucają błąd że nie znaleziono strumienia danych.

Czy to jest problem wtyczki ? Czy komuś to działa ? A może ktoś miał taki problem i naprawił ?

**Comment by koladka** [comment]
Musisz zrobic peir na openload .

**Comment by Wawrzor** [comment]
Wiem - nie pomaga. Jak pisałem linki w HQ działają po separowaniu - linki w HD nadal wyrzucają brak strumienia danych

**Comment by koladka** [comment]
To wtakim razie bedzie blad wtyczki jak zawsze , czekamy na Mr know az naprawi

**Comment by hellboy2** [comment]
Mam pytanie dlaczego FanFilm wyszukuję tylko na openload a na innych już hostach nie

**Comment by koladka** [comment]
No coz Mr know ostatnio dziala moze i  w tym temacie zadziala;)

**Comment by hellboy2** [comment]
Poczekamy zobaczymy a co jest już coś nowego, a i nie wiem albo mi się zdaję FanFilm chyba nie uaktualnia nowych wstawek. A jak już to pisze że film trwa 1.33 minuty a jest to trailer

**Comment by kopernik1983** [comment]
Fanfilm juz dziala. zrobcie aktualizacje. na pierwszy rzut oka to i nowy serwis chyba widze szukajka.tv chyba go nie bylo ostatnio. openload chodzi bynajmniej na 4 serialach jakie wlaczylem . Takze Mr idzie do przodu

**Comment by Kubackjeee** [comment]
Mam ten sam problem. Kodi zaktualizowało mi się do 17,1. Wczesniej nigdy nie musiałem parowac mi boxa z openload a teraz wyskakuje że muszę, a to i tak nie działa. Jeden odcinek serialu mi się włączył, sam sparowal.po chwili chciałem go włączyć jescze raz i wyskakuje okno o parowaniu

**Comment by mrknow** [comment]
poprawiłem 
Teraz powinno działać prawidłowo
