### ISSUE TITLE
telewizjada.net nie działa

### ISSUE THREAD

**Issue by Swir** [mrknow/filmkodi#817]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: _____
- OS version: _____

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [x ] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [x ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

Witam problem jest że chociaż są podane dane logowania premium  to wtyczka woła o podanie lub sprawdzenie danych logowania

**Comment by mar2016** [comment]
Potwierdzam ze pomimo dobrego loginu. i. hasla nie. laczy i wola o poprawne haslo

**Comment by mrknow** [comment]
ja nie mam w swoich wtyczkach obsługi telewizjada.net. Napisz do nich na stronie
