### ISSUE TITLE
cda.pl przerwa techniczna

### ISSUE THREAD

**Issue by xxcriticxx** [mrknow/filmkodi#82]
Przerwa techniczna

Spróbuj ponownie za kilka sekund
Tymczasem zapraszamy na zaprzyjaźniony serwis e-programy.pl

**Comment by mrknow** [comment]
Witam
Też zauwazyłem że CDA w weekendy "nie daje rady". Trzeba do nich pisać, ja nie administruję serwisem cda.pl
