### ISSUE TITLE
Problem z wtyczką na Apple TV

### ISSUE THREAD

**Issue by kurnosek1226** [mrknow/filmkodi#820]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: _____
- OS version: _____

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [x ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [x] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Dlaczego na laptopie (OS X App) wtyczka FanFilm działa a na moim odtwarzaczu (Apple TV) ciągle "Brak strumienia danych"?

**Comment by mrknow** [comment]
nie wiem. może się nie aktualizuje. w wersji 2017.04.05.2 naprawiłem wysyłanie logów diagnostycznych. Wyślij logi
Wejdź do FanFilm->Narzędzia0> Diagnostic Log uploader. 
Wyślij adres do tych logów, popatrzymy na nie

**Comment by kurnosek1226** [comment]
Teraz rusza bez problemu o_O
