### ISSUE TITLE
Parowanie openload 

### ISSUE THREAD

**Issue by Kubackjeee** [mrknow/filmkodi#824]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: ___17.1__
- OS version: _____android tv 

---
## Addon / Wtyczka
- [ ] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [x ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [ ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [ ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

Czy da się jakoś rozwiązać problem parowania openload? Wcześniej po prostu klikalo się link na fanfilm i nic nie trzeba było parowac. Teraz co 4 godziny trzeba wchodzic w przeglądarkę i robić to powalone parowanie. 5 minut wciskania jakiś Gor, znaków, numerów po 10 Razy. Wszyscy teraz tak mają?

**Comment by hellboy2** [comment]
Tak i narazie musi tak być bo openload coś zmienia i nie działa potem FanFilm, więc Mrknow tak zrobił

**Comment by mrknow** [comment]
Zaktualizowałem script.mrknow.urlresolver.

Sprawdź czy problemy z parowaniem w openload  się rozwiązały
