### ISSUE TITLE
MrknowTV and more missing from "install from repository" ???

### ISSUE THREAD

**Issue by ChaoticSlacker** [mrknow/filmkodi#827]
## Please follow the guide below / Podążaj za przewodnikiem
- Put an "x" into all boxes [ ] relevant to your *issue* (Wstaw "x" w każde pole [ ], które dotyczy twojego zgłoszenia)
- Use *Preview* tab to see how your issue will actually look like (Użyj *Perview* aby sprawdzić, czy wszystko wygląda dobrze)

---
## Kodi & OS
- Kodi verison: ___16__
- OS version: __openELEC___

---
## Addon / Wtyczka
- [x ] Filmy online - Mrknow
- [x ] MrknowTV
- [x ] Specto
- [x ] FanFILM
- Version / Wersja: _____

---
## Issue / Zgłoszenie
- [x ] Bug report / Błąd
- [ ] Site request / Prośba o nową stronę
- [ ] Feature request / Prośba o nową funkcję
- [x ] Question / Pytanie
- [ ] Other / Inne

---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

After installing the repo and navigating to install from repo I can only find xbmcfilm.com? Where is MrknowTV, Specto, FanFILM etc? Am I missing something here? Hope you can help!

Thanks

**Comment by mrknow** [comment]
It's a performance issue with servers. Try to install again according to this manual http://filmkodi.com/en/specto-1080p-kodi-add/
