### ISSUE TITLE
cda - bardzo długie ładowanie

### ISSUE THREAD

**Issue by drrak** [mrknow/filmkodi#836]
## Kodi & Addon 
- Kodi verison: Kodi 16.1 (LibreELEC 7.0.3, RPi2)
- [x] Filmy online - Mrknow
- Version / Wersja: 2017.04.18.1
---
## Descryption / Opis
Na szczęście filmy działają normalnie, tyle że trzeba się naczekać zanim je wyszukam i uruchomię. Trwa to o wiele za długo.

## Donation / Darowizna
This addons are free, but you can always thank the author for ... / Te wtyczki są darmowe, ale zawsze możesz podziękować autorowi za jej stworzenie...

[![paypal](https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif)](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=HEV6TJY83S3Q4&lc=PL&item_name=Donation-Darowizna&currency_code=PLN&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted)

**Comment by drrak** [comment]
W wersji 2017.04.18.1 ciągle to samo:
[kodi.log](https://github.com/mrknow/filmkodi/files/936781/kodi.kopia.txt)

**Comment by rysson** [comment]
Sprawdź 2018.06.18.1, cda zostało poprawione.
