### ISSUE TITLE
telewizjada błędne hasło lub login

### ISSUE THREAD

**Issue by dariuszce** [mrknow/filmkodi#837]
## Please follow the guide below 
- Put an "x" into all boxes [ ] relevant to your *issue*
- Use *Preview* tab to see how your issue will actually look like
---
## Kodi & Addon 
- Kodi verison: _____
- [ ] Filmy online - Mrknow
- [x ] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: Kodi 16.1/MrknowTV 2017.03.06.1
---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
22:12:36 T:6160  NOTICE: [MrknowTV]: ->----------                PARAMS: {'action': 'play', 'meta': '{"plot": "axn", "name": "AXN", "service": "telewizjadanet", "title": "AXN", "poster": "http://www.telewizjada.net/media/stream/img/axn_big.png", "next": "", "id": 28}', 'name': 'AXN', 'service': 'telewizjadanet', 'title': 'AXN'}
22:12:36 T:6160  NOTICE: [MrknowTV]: >>>>  LOGIN()
22:12:36 T:6160  NOTICE: [MrknowTV]: Expire1:
22:12:38 T:6160  NOTICE: [MrknowTV]: >>>>  PARAMS {'username': 'dariuszce', 'password': '', 'return': 'aW5kZXgucGhwP29wdGlvbj1jb21fdXNlcnMmdmlldz1wcm9maWxl', 'remember': 'yes', 'd993e211defd642af0ac658aef7f7b40': '1'}
22:12:44 T:6160  NOTICE: [MrknowTV]: Exception telewizjada.net login Bledny login lub haslo.
22:12:44 T:6160  NOTICE: [MrknowTV]: Błędny login
22:12:44 T:6160  NOTICE: [MrknowTV]: Error telewizjada.net .getstream Błędny login
22:12:44 T:4368   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.mrknowtv/?action=play&name=AXN&title=AXN&service=telewizjadanet&meta=%7B%22plot%22%3A+%22axn%22%2C+%22name%22%3A+%22AXN%22%2C+%22service%22%3A+%22telewizjadanet%22%2C+%22title%22%3A+%22AXN%22%2C+%22poster%22%3A+%22http%3A%2F%2Fwww.telewizjada.net%2Fmedia%2Fstream%2Fimg%2Faxn_big.png%22%2C+%22next%22%3A+%22%22%2C+%22id%22%3A+28%7D]

## Donation / Darowizna
This addons are free, but you can always thank the author for ... / Te wtyczki są darmowe, ale zawsze możesz podziękować autorowi za jej stworzenie...

[![paypal](https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif)](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=HEV6TJY83S3Q4&lc=PL&item_name=Donation-Darowizna&currency_code=PLN&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted)

**Comment by mrknow** [comment]
Telewizjada została usunięta i na razie nie będzie  obsługiwana
