### ISSUE TITLE
Unable to Install SPECTO

### ISSUE THREAD

**Issue by lisalange79** [mrknow/filmkodi#84]
I had SPECTO installed on my system and it is no longer there for some reason and I have been unable to install since Saturday 2-6-16.  Any idea when this will be up and running again?? Is the server down???  It was running great until this happened.

**Comment by karnage11** [comment]
Just go to Genesis fork update fail one and download the zip there for now

**Comment by lisalange79** [comment]
I don't know how to do what you are saying. I am vwey new to this. Tnx though

Sent from Yahoo Mail on Android 
 
  On Sun, Feb 7, 2016 at 11:52 PM, karnage11<notifications@github.com> wrote:   
Just go to Genesis fork update fail one and download the zip there for now

**Comment by karnage11** [comment]
go here https://github.com/mrknow/filmkodi/issues/75 , and look for the zip , if you cant install from Kodi , but you should be able to now

**Comment by lisalange79** [comment]
I have an element streaming box so I don't know how to do this still with this link.  I assume the app is down again.  I will keep trying daily and hope it works eventually

Sent from Yahoo Mail on Android 
 
  On Mon, Feb 8, 2016 at 2:11 PM, karnage11<notifications@github.com> wrote:   
go here #75 , and look for the zip , if you cant install from Kodi , but you should be able to now

**Comment by karnage11** [comment]
if you can add sources , here is the repo - http://filmkodi.com/reposityory

**Comment by lisalange79** [comment]
Yes, we did all of that and went through the process but when we install and sticks at 3% and eventually says install failed.  

Sent from Yahoo Mail on Android 
 
  On Mon, Feb 8, 2016 at 3:54 PM, karnage11<notifications@github.com> wrote:   
if you can add sources , here is the repo - http://filmkodi.com/reposityory

**Comment by mrknow** [comment]
I added more servers to my CDN to serve files

**Comment by lisalange79** [comment]
We were finally able to get it working.  We've learned not to give up and it will eventually work out.  ;)

Sent from Yahoo Mail on Android 
 
  On Sat, Feb 20, 2016 at 2:07 PM, mrknow<notifications@github.com> wrote:   
I added more servers to my CDN to serve files
