### ISSUE TITLE
Zalukaj / Vshare Nie uruchamia filmów 

### ISSUE THREAD

**Issue by eko5** [mrknow/filmkodi#85]
Tak jak w temacie nie mogę odpalić na zalukaj żadnego filmu .  Zalukaj nie znajduje do Vshare linku .

http://xbmclogs.com/pygg2yl45

**Comment by xxcriticxx** [comment]
na ver 02.08 zalukaj dziala 

podaj link do jakiegos filmu

testuj ten sam link w firefox/ie czy dziala

**Comment by eko5** [comment]
http://zalukaj.tv/zalukaj-film/13979/czlowiek_na_krawedzi_man_on_a_ledge_2012_.html
http://zalukaj.tv/zalukaj-film/23305/lowca_czarownic_the_last_witch_hunter_2015_.html

Nie działa na Vshare , jak byś zajrzał do loga to byś widział 

> 11:38:26 T:3032540992   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.mrknow/?service=zalukaj&name=playSelectedMovie&category=None&title=Batman: Mroczne czasy / Batman: Bad Blood (..&url=http%3A%2F%2Fzalukaj.tv%2Fzalukaj-film%2F23669%2Fbatman_mroczne_czasy_batman_bad_blood_2016_.html&icon=http%3A%2F%2Fzalukaj.tv%2Fimage%2F23669.jpg&strona=]
> 11:38:26 T:2656041792  NOTICE: Thread BackgroundLoader start, auto delete: false

**Comment by xxcriticxx** [comment]
w sumie mi nic nie chodzi w dziale ostatio dodane plumers sprawdzisz please 

potwierdzam ze lowca czarownic nie dziale a dziala w firefox bez problemu

czlowiek na krawedzi tak samo

**Comment by mrknow** [comment]
W weekend się za to zabiorę ....

**Comment by xxcriticxx** [comment]
za piwo?

**Comment by mrknow** [comment]
Witam prawie wszystko działa. Na razie poprawiam wtyczki dla własnej satysfakcji :)
