### ISSUE TITLE
podzial forum

### ISSUE THREAD

**Issue by xxcriticxx** [mrknow/filmkodi#86]
proponuje podzial forum na polska wtyczke i na specto

otworz nowy master/branch czy jak to tam sie nazywa tylko na specto

zdejmij pliki specto z servera bo do konca sie sam wykonczy

plumers czy to nie zajebisty pomysł? dodasz cos?

**Comment by plumers** [comment]
No popieram - już są problemy z update -- a tak na marginesie czy tylko nas dwóch tutaj cokolwiek raportuje ??:)

Mr jak już znajdziesz dłuższa chwilę - to zrób wielki porządek we wtyczce - Nazwy serwisów itd itd - niepotrzebne info np że działa 15% linków w meczyki , bo to wiadome ,że jak nie nadają to większość nie udostępnia ( kilka osób nadaje a reszta się podpina i niby oni też pseudo portale a-la futbol coś tam piłkagol - bo im więcej reklam tym opłacalna transmisja :P serwisy można skopiować tak jak miał neoplacek TELEWIZJA - TRANSMISJE -DOKUMENTALNE - FILMY SERIALE itd :)

czekam na IPLA.TV od Ciebie szacun dla sdxbmc ale nie chce mi się skakać po wtyczkach i mieć all in one :) 

PS ktoś udostępnił listę m3u kanałów iptv INEA (w sumie klikałeś i od razu stream leciał ,tak jak w TV bo online serwis :) a tak pięknie miało być, aż tu WYKOPALI chłopakowi koniec kariery LoL ostrzegali go aby zbyt nie szalał , bo o to własnie POLSKI RÓD :) daj im palec zrobią SMRÓD :) 

czas na relax pozdro 4 all

**Comment by xxcriticxx** [comment]
skladke na server moze zrobimy? donation button

animi mozna dodac / rozrywke rozbudowac / sub system dopiac / 4k sekcje 

popieram plumers pomysl zeby zrobic wiosene porzadki

**Comment by xxcriticxx** [comment]
mrknow da sie rade cos stym zrobic?

bo sie pierdoli mi sie w oczach pomiendzy specto i tv wtyczka

**Comment by xxcriticxx** [comment]
napisalem email 3 tygodnie temu tak jak prosiles hyba nie dostales zobacz moze spam
