### ISSUE TITLE
Nieudane wykonanie skryptu!

### ISSUE THREAD

**Issue by drrak** [mrknow/filmkodi#87]
Taką informacje otrzymuje przy próbie włączenia wtyczki mrknow. Jeszcze wczoraj działała, ale w nocy przestała.

Przy okazji chciałem podziękować za mrknow, to moja główna, najczęściej używana wtyczka.

---

Ręczne zainstalowanie też nie pomogło. Mam ten sam błąd.

---

Po kilku próbach automatycznej aktualizacji zaskoczyło i znów działa. Jestem szczęśliwy :)

Dzięki raz jeszcze za super wtyczkę.

**Comment by xxcriticxx** [comment]
przeciążony serwer

**Comment by mrknow** [comment]
Pliki do instalacji ręcznej 
[plugin.video.specto-2016.02.07.3.zip](https://github.com/mrknow/filmkodi/files/123828/plugin.video.specto-2016.02.07.3.zip)
[plugin.video.mrknow-2016.02.08.1.zip](https://github.com/mrknow/filmkodi/files/123829/plugin.video.mrknow-2016.02.08.1.zip)
[script.module.xbmcfilm-2016.02.08.1.zip](https://github.com/mrknow/filmkodi/files/123830/script.module.xbmcfilm-2016.02.08.1.zip)
