### ISSUE TITLE
Update Failed

### ISSUE THREAD

**Issue by techionltd** [mrknow/filmkodi#88]
First off, thank you for the great work.

While you are investigating new servers/deployment, might I suggest you post a download link to the latest zip file when there is a new update.

At least then it would be possible for everyone to benefit from improvements in Specto without waiting for the server upgrades

**Comment by mrknow** [comment]
Latest zip files:

[plugin.video.specto-2016.02.07.3.zip](https://github.com/mrknow/filmkodi/files/123826/plugin.video.specto-2016.02.07.3.zip)
