### ISSUE TITLE
Trakt

### ISSUE THREAD

**Issue by redfox1** [mrknow/filmkodi#90]
Trakt won't work it was working before the last update.

**Comment by ECKoBASE** [comment]
Experiencing the Same issue, Ever since the **2016.02.07.3** Version

**Comment by Duifje** [comment]
Same issue here. Was syncing with Trakt and it stopped.

**Comment by Justawebguy** [comment]
I'm having the same problem

**Comment by mrknow** [comment]
OK thanks. I'm working on it.

**Comment by Duifje** [comment]
Excellent. Thanks.

**Comment by ECKoBASE** [comment]
Thanks @mrknow you da best Yo!!! 

FYI I think you should change the name, completely to Specto, if you want help with images and stuff message me and I can whip something up for you!

**Comment by mrknow** [comment]
In my development version i have working properly authentication using a pin code. Keep working on it.

**Comment by Duifje** [comment]
Ok.  Looking forward to completion of it.

**Comment by Duifje** [comment]
Ok.  Looking forward to completion of it.

**Comment by ECKoBASE** [comment]
Noice!

**Comment by mrknow** [comment]
Right now i change api of trakt.tv  to v2. I'm going to finish this change to 22-02-2016.

**Comment by ECKoBASE** [comment]
Thanks @mrknow

**Comment by Duifje** [comment]
Noticed new update came through.  Progress seems to work.  Thanks

**Comment by redfox1** [comment]
Trakt working great now thanks for the fix.

**Comment by ECKoBASE** [comment]
Getting an issue with Trakt setup, once I've Authorized SPECTO then enter the Pin, I get a Trakt 504 Error. I even removed Specto and deleted any of its folders and installed it again. Same issue! Even when selecting Remind me later won't respond to the key press. I have to push pack on my remote. 

Mind you I am using the Arctic:Zypher skin, I'll try it again with the Default skin

**Comment by gator48** [comment]
I am also getting the TrakT 504 error

**Comment by Justawebguy** [comment]
Trakt is having API issues today

**Comment by ECKoBASE** [comment]
@Justawebguy & @gator48 Trakt API are back online! Just signed into Spectro successfully

**Comment by Leuthil** [comment]
Trakt integration seems to be working perfectly for me since I updated Specto yesterday. Cheers.
