### ISSUE TITLE
Real-Derbrid links issue + Movie Artwork & Thumbnails issue

### ISSUE THREAD

**Issue by noor666** [mrknow/filmkodi#901]
## Please follow the guide below 
- Put an "x" into all boxes [ ] relevant to your *issue*
- Use *Preview* tab to see how your issue will actually look like
---
## Kodi & Addon 
- Kodi verison: 17.3
- [ ] Filmy online - Mrknow
- [ ] MrknowTV
- [ x] Specto
- [ ] FanFILM
- Version / Wersja: 2017.06.10.1
---
## Descryption / Opis

I have Kodi 17.3 and Specto Fork version 2017.06.10.1

I recently got a premium subscription for Real-Debrid, cause both my main addons for TV&Movies Exodus and (Your) Specto Fork weren't working properly especially Exodus. I wasn't getting any HD links let alone 1080p links. So I went for Real-Debrid and It Havw me so many 1080 and HD links, but on Exodus. 

Ill give you the example of Fargo. I am on S3E7 now and when I open with exodus I get 8 1080p links and 38-39 HD links from Real-Debrid

Source links consist of: 

(OBOOM, UPLOADED, FILEFACTORY, RAPIDGATOR, NITROFLARE, USERCLOUD, UPLOADX, UPLOAD, OPENLOAD, UPLOADROCKET & UL)

When I open the same episode on Specto Fork I get only HQ links from Real-Debrid ( for OPENLOAD only) which makes no sense cause its not like the other links don't exist. When I Clear Cache and Sources from the tools options within Specto Frok, then I get HD links from Real-Debrid (again OPENLOAD only) which don't open mostly.

There is something wrong with the Real-Debrid integration within Specto Fork, and it would be amazing if this could be fixed. Please make Real-Debrid work the same way that it works with exodus. Specto works amazingly for non Real-Debrid links but the down side is not many come up for recent stuff or very old stuff. GVIDEO links work too but they don't pop up as much as they used to. Thus Real-Debrid is the solution. 
[Kodi Log.txt](https://github.com/mrknow/filmkodi/files/1066031/Kodi.Log.txt)

Another minor issue is that the movie art and thumbnails take a lot longer than they used to, some don't load at all.

Thanking you in advance

Regards,

S.Sangeen.Noor

## Donation / Darowizna
This addons are free, but you can always thank the author for ... / Te wtyczki są darmowe, ale zawsze możesz podziękować autorowi za jej stworzenie...

[![paypal](https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif)](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=HEV6TJY83S3Q4&lc=PL&item_name=Donation-Darowizna&currency_code=PLN&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted)

**Comment by zemely** [comment]
I got exactly the same thing. Today I got an update of the addon, marked 2017.06.11, which is yesterday and Real-Debrid is not fixed. Very sad, used to be one of the best addons.

**Comment by noor666** [comment]
I think I know what the issue might be. When I went to configure Specto Fork, I noticed that in the list of hosts, OBOOM, UPLOADED, FILEFACTORY, RAPIDGATOR, NITROFLARE, USERCLOUD, OPENLOAD, UPLOADROCKET & UL and many others that work with Real-Debrid weren't listed. Thus the reason for only getting OPENLOAD links. Cause most of the links I get on exodus are the ones mentioned above and the aren't integrated into Specto as of now. Please add them so the links with proper HD sources get listed. It would be awesome cause Exodus is causing many issues as well. After a while the links stop opening  on that untill I restart Kodi, which is super annoying.


Regards.

Sangeen

**Comment by zemely** [comment]
What Specto link? Where is this link? I thought it is Specto link

**Comment by noor666** [comment]
This is the page for the filmkodi addon. The specto page is a different page as it's a different add on. Apparently this has been an on going issue since August 2016. Come join the petition for an update that fixes this as exodus is an assessment these days. 

Link below: 

https://github.com/mrknow/specto/issues/3

**Comment by BankruptEd** [comment]
When was the last time MrKnow responded to anything?

**Comment by BankruptEd** [comment]
I mean I assume he's listening cause the movie poster issue is fixed, but
he doesn't seem to say much these days.

On Jun 14, 2017 8:18 PM, "Bankrupt B" <ddobry21@gmail.com> wrote:

When was the last time MrKnow responded to anything?

**Comment by zemely** [comment]
Maybe there is something we don't know. Maybe that's related to the KODI switching to https? Also, Exodus use to have it's own RED settings and not it switch to the URLResolver settings on KODI, like SALTS, maybe that's the problem? But the point from noor666 about missing scrappers looks exactly what's wrong. Man, we are talking on the closed thread, we have to stop it

**Comment by noor666** [comment]
BankruptEd please join us on the specto link. So mrknow takes notice.

Come join 

https://github.com/mrknow/specto/issues/3
