### ISSUE TITLE
repository.ramic & URLResolver both not updating...Specto doesn't want to update also.

### ISSUE THREAD

**Issue by Huero23** [mrknow/filmkodi#903]
## Please follow the guide below 
- Put an "x" into all boxes [ ] relevant to your *issue*
- Use *Preview* tab to see how your issue will actually look like
---
## Kodi & Addon 
- Kodi verison: 16.1
- [ ] Filmy online - Mrknow
- [ ] MrknowTV
- [X] Specto
- [ ] FanFILM
- Version / Wersja: _____
---
## Descryption / Opis
Put here every imported thing such logs, how to reproduce etc. <br/>
Wstaw tutaj każdą ważna rzecz, taką jak logi, jak wywołać błąd itp.

## Donation / Darowizna
This addons are free, but you can always thank the author for ... / Te wtyczki są darmowe, ale zawsze możesz podziękować autorowi za jej stworzenie...

[![paypal](https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif)](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=HEV6TJY83S3Q4&lc=PL&item_name=Donation-Darowizna&currency_code=PLN&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted)

**Comment by kopernik1983** [comment]
There are server problems and many addons are not working. For future write to author https://github.com/ramicspa/kodi. There is a new ramicspa repository to download. You should manually download the zip and update. Extras are already on another server. Everything should already work properly.

**Comment by koladka** [comment]
Walka z 3 part adoons trwa;) Mr know co ze spekto zdjeli:( Jak batalia sadowa? Wychodzi na to ze to ostatnie podrygi kodi ja przechodze na apki iptv;)

**Comment by rysson** [comment]
New resolver is used. Since 2018.06.18.1.
