### ISSUE TITLE
Nowy serwis Telewizja / Filmy / do sprawdzenia .

### ISSUE THREAD

**Issue by eko5** [mrknow/filmkodi#92]
Znalazłem nowy serwis przejrzał by ktoś czy to nie jest następna kopia linków z telewizjada.net . Oferta wydaje się być ciekawa .

http://telewizjairadioprogramy.pl/xbmc.php

**Comment by plumers** [comment]
płatne gówno, zaczyna być tego plaga ludzie zamiast zrobić coś normalnego , to ładują internetowe tv , które padają jak muchy jedna po drugiej --- pozdro

**Comment by xxcriticxx** [comment]
plumers sprawdz telezon.tv

**Comment by mrknow** [comment]
403
Forbidden
