### ISSUE TITLE
Specto- wrong movies and No Sources  - add movies here that have the Wrong Source or no Source

### ISSUE THREAD

**Issue by karnage11** [mrknow/filmkodi#93]
alot of issues when alot of movies have the wrong movie , anyway to get that fixed ?

**Comment by mrknow** [comment]
Please give an example movi name

**Comment by karnage11** [comment]
The Boy 2016 , Entity 2012 - shows up as Hostage  , Krampus 2015.. if I can think of more I will contact you again .. Thanks for your Help

**Comment by karnage11** [comment]
The Hunger Games: Mockingjay Part 2 - No Source , Pride and Prejudice and Zombies - No Source ,

**Comment by karnage11** [comment]
The 5th Wave 2016

**Comment by donr1961** [comment]
Daddys Home With Mark Wahlberg

**Comment by karnage11** [comment]
The Forest 2016

**Comment by karnage11** [comment]
Pride+Prejudice=Zombies 2016 - No source

**Comment by karnage11** [comment]
if you can from this post add these Sources - https://github.com/mrknow/filmkodi/issues/98

**Comment by karnage11** [comment]
The Boy 2016 still showing the wrong movie

**Comment by karnage11** [comment]
Any way you can add in Theatre links so it will update
