### ISSUE TITLE
Alltube nie dziala

### ISSUE THREAD

**Issue by mrrumcajz** [mrknow/filmkodi#942]
## Please follow the guide below 
- Put an "x" into all boxes [ ] relevant to your *issue*
- Use *Preview* tab to see how your issue will actually look like
---
## Kodi & Addon 
- Kodi verison: _____
- [ x] Filmy online - Mrknow
- [ ] MrknowTV
- [ ] Specto
- [ ] FanFILM
- Version / Wersja: _____
---
## Descryption / Opis
Alltube przestalo dzialac.  A tak z ciekawosci doczytalem sie ze MrKnow zmarl, ile w tym prawdy nie wiem ale jest czisza na tym koncie, i wszystkie pull request czekaja.  Czy ktos cos o tym wie?

## Donation / Darowizna
This addons are free, but you can always thank the author for ... / Te wtyczki są darmowe, ale zawsze możesz podziękować autorowi za jej stworzenie...

[![paypal](https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif)](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=HEV6TJY83S3Q4&lc=PL&item_name=Donation-Darowizna&currency_code=PLN&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted)

**Comment by rysson** [comment]
Czołem.

No nie wiem co się z nim stało, zero kontaktu. Ani maile, ani telefon.
A z alltube to problem, postaram się zajrzeć w ciągu paru dni.

O ile jeszcze próba podniesienia tego projektu ma jakikolwiek sens...

**Comment by rysson** [comment]
Dobra, pogrzebałem chwilę i samo Alltube działa, ale większość strumieni jeszcze nie.
W sumie da się cokolwiek zobaczyć. Na razie zamykam. 

Ha pierwszy ze 217 :-)

**Comment by rysson** [comment]
Zapomniałem: paczki są zbudowane w nowym miejscu: http://kodi.sharkbits.com.
Trzeba od nowa repo zainstalować. Albo ręcznie wydłubać z serwera zipy.
