### ISSUE TITLE
outdated addon?

### ISSUE THREAD

**Issue by dilldogs** [mrknow/filmkodi#95]
I am getting this error: You are using outdated addon. To View filepup stream please use SALTS or another  up-to-date Kodi addon.

any fix for this?

**Comment by karnage11** [comment]
just add this repo , http://filmkodi.com/repository , you should get the new update for Specto

**Comment by karnage11** [comment]
ohh yeah make sure , you clean out your caches , and purge files , if you have the old genesis installed uninstall it

**Comment by karnage11** [comment]
or you can get the zip from here https://github.com/mrknow/filmkodi/issues/81 at the bottom of it

**Comment by dilldogs** [comment]
I have don't all that and even a fresh install of kodi. And I am still getting the same error

**Comment by dilldogs** [comment]
Everything was fine earlier today

**Comment by karnage11** [comment]
weird , try that zip - http://filmkodi.com/pl/problemy-z-serwerem/ .. mine is working fine

**Comment by dilldogs** [comment]
I have the updated version installed for a few days and it has worked fine til about 2pm today

**Comment by karnage11** [comment]
try the zip again , just make sure you unintall what you have now

**Comment by karnage11** [comment]
try the new zip scroll all the way down https://github.com/mrknow/filmkodi/issues/81

**Comment by karnage11** [comment]
plugin.video.specto-2016.02.07.3.zip , you will see that

**Comment by karnage11** [comment]
unless , he blocked the servers in the US again , do to an overload

**Comment by dilldogs** [comment]
Ok, so this is what I did. I Uninstaller what I had. Cleared data from kodi, the download the file you posted and still getting the same thing. It's not just happening on mine. It's happening  on several others

**Comment by karnage11** [comment]
yeah I don't know , I am on Kodi Javis  and I am up to date with Specto

**Comment by karnage11** [comment]
what maintenance's tool you have installed ?

**Comment by dilldogs** [comment]
I don't understand stand it but I was on the movie Revenant and it like the 4th or 5th link down and that's what I am getting. Now, about 11 am or 12 pm today I went to that movie and clickEd on the first like and it popped right up and now somethings changed someplace, lol. 


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by karnage11** [comment]
yea I don't know whats wrong

**Comment by dilldogs** [comment]
I am using TV addon maint.


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by karnage11** [comment]
ohhh Genesis is still on there and doesn't work anymore

**Comment by karnage11** [comment]
it might be Enabled

**Comment by dilldogs** [comment]
Nope, no Genesis. Took it off when spectro took over.

**Comment by karnage11** [comment]
ah ok , yea I don't use tvaddons.ag repo I just install each repo on its own

**Comment by dilldogs** [comment]
Like I said, it worked fine until earlier today.

**Comment by karnage11** [comment]
yea sorry buddy I don't know what it would be

**Comment by dilldogs** [comment]
15 hrs ago someone in the UK had the same problem

**Comment by karnage11** [comment]
ohh ok , could just be the servers , I know they are getting new ones and , I think Mrknow is going to update the repop again

**Comment by dilldogs** [comment]
I will keep messing and see what I can figure out. Nothing major or anything to get excited about, lol. It always works out

**Comment by karnage11** [comment]
yeah , this repop will be fixed , just have to wait for the new servers and and a new update.....

**Comment by dilldogs** [comment]
I like spectro and what he has done with it.

**Comment by karnage11** [comment]
yea Same here , it will get better

**Comment by dilldogs** [comment]
Thanks for the help and look forward to seeing what the future brings for this app. Take care and again thanks

**Comment by karnage11** [comment]
I am always around here , anytime ... Hope you get it working

**Comment by dilldogs** [comment]
Ok, don't want to be a pain but wanted to give a heads up and keep you updated. This morning it even worse. More and more links are saying the same thing.
I figure if I keep you all updated.

**Comment by dilldogs** [comment]
https://www.youtube.com/watch?v=p5-mRcUB2Ow
Here is a video of my problem

**Comment by dilldogs** [comment]
If you are getting this error:
 "you are using an outdated addon. to view filepup streams please use salts or another up to date Kodi addon."
 Go into sprectro settings and Disable movienight in sources and it will work.

**Comment by donr1961** [comment]
If you are getting this error:
 "you are using an outdated addon. to view filepup streams please use salts or another up to date Kodi addon."
 Go into sprectro settings and Disable movienight in sources and it will work.

**Comment by dilldogs** [comment]
That did it.

**Comment by lulugoose** [comment]
Hi there. I'm a complete novice with these things. I am getting the same error message from my raspberry pi when trying to stream from Genesis. I don't know how to access spectro settings. Please could you help me? Thanks very much

**Comment by Nusadua** [comment]
I looked fro the spectro settings and I couldn't find it. Would you please help?

**Comment by donr1961** [comment]
lulugoose, Go into settings > Config >at the top you will see tabs and the third tab over you will see Movie Click on it and scroll Down until you get to movienight and deselect it by clicking on it. then at the bottom click OK then your done.
Nusadua, its called Addon Information > Config

**Comment by radders631** [comment]
this might be a dumb question but how do i get too add on info?

**Comment by dilldogs** [comment]
Lol, no question is dumb. On the home page of kodi under Videos you will see, Add-ons > you will see specto- fork  right click ( If on the computer) or if fire stick or android box on the remote click the button with the lines.

**Comment by dctg1971** [comment]
Where do you find homepage of kodi

**Comment by dilldogs** [comment]
When you first turn your kodi on.

**Comment by kazzamct** [comment]
Hi
I'm trying to sort Genesis out to. Just trying to follow your instruction of where to find specto- fork

**Comment by karnage11** [comment]
Here is The repo http://filmkodi.com/repository , that's here you can get specto

**Comment by kazzamct** [comment]
Thank you 

Karyn

**Comment by ajjohnson10** [comment]
Please help! I read all of the comments however, I still can't find specto. I uninstalled kodi and now I'm looking for specto but can't find it.

**Comment by karnage11** [comment]
ajjohnson10 add this Repo http://Filmkodi.com/repository ... it has nothing to do with tvaddons.ag or anything

**Comment by ajjohnson10** [comment]
I am clicking on the link from my tv. It's telling me that the download is successful but when I go to open folder I can't get anywhere. I went back to apps and still nothing.

**Comment by ajjohnson10** [comment]
Thanks for responding by the way

**Comment by karnage11** [comment]
in kodi , add a source

**Comment by karnage11** [comment]
what Kodi version you on ?

**Comment by ajjohnson10** [comment]
Geesh! Instead of deleting genesis, I deleted kodi. I guess I'm screwed now. Thanks anyway

**Comment by karnage11** [comment]
well reinstall Kodi , get Kodi 16 works good , add a source - http://kodifilm.com/repository and you will get Specto

**Comment by ajjohnson10** [comment]
Where do I go to get kodi 16?

**Comment by karnage11** [comment]
www.kodi.tv/downloads

**Comment by lulugoose** [comment]
Hi I am not on a computer... I am using a raspberry pi with wireless remote. Is spectro an app? I haven't got an option for spectro at all. When I click on Videos> add ons> I get the available apps and Get more option... 

Please can you advise further? Thanks so much

**Comment by karnage11** [comment]
lulugoose and ajjohnson10 follow this http://filmkodi.com/en/addon-xbmcfilm-com/

**Comment by lulugoose** [comment]
Hi having real trouble with locating specto-fork. When I go to videos>add ons.   There is no specto option. 

I'm on raspberry pi with a wireless remote so don't know if that makes a difference. Is specto fork an app? Thanks so much for the help and advice.

**Comment by lulugoose** [comment]
Sorry for repeat message

**Comment by karnage11** [comment]
it wont be in the video addons , you have to add the source in kodi to get it

**Comment by lulugoose** [comment]
Ok cool do I do that in system?

**Comment by karnage11** [comment]
yes just add that source I gave you and then you will get it

**Comment by lulugoose** [comment]
Can I access the link you sent me from my raspberry pi as I am writing to you on ipad

**Comment by lulugoose** [comment]
Ok am trying that now.

**Comment by karnage11** [comment]
go to system - File Manager .... lick on add source and then type in http://filmkodi.com/repository

**Comment by karnage11** [comment]
after you add that , go to addons - click on install from zip - open it up until you see the repo and install that

**Comment by karnage11** [comment]
then when you go to Video-addons you should see Specto

**Comment by lulugoose** [comment]
Which repo shall I install? I got to repository and there are 3 options

I am clicking on repository.filmkodi.com.zip to try to install

**Comment by karnage11** [comment]
yea that's the one sorry forgot to tell you repository.filmkodi.com.zip

**Comment by lulugoose** [comment]
There is a message checking for add on updates in the corner of screen. Then Phoenix update fails

**Comment by lulugoose** [comment]
Specto still fails to appear in add ons under video

**Comment by lulugoose** [comment]
Should I install from repository rather than. Zip file

**Comment by karnage11** [comment]
ok , go to install from repo and choose filmkodi

**Comment by karnage11** [comment]
you should see specto

**Comment by lulugoose** [comment]
We seem to have found it. Downloading now

**Comment by lulugoose** [comment]
Seems to be working... Should that sort it? Thanks so much for your patience with the special needs perosn

**Comment by lulugoose** [comment]
Sorry no offence. So specto is the new genesis

**Comment by karnage11** [comment]
yea another Dev took the source and started to update it

**Comment by lulugoose** [comment]
Do I need to turn anything off now?

**Comment by lulugoose** [comment]
Remove genesis

**Comment by karnage11** [comment]
you can if you want too

**Comment by lulugoose** [comment]
Any other recommendations for movie or sport apps? Thanks

**Comment by karnage11** [comment]
you can get SportsDevil ...if you want to watch sports and get Live PPV's for free

**Comment by lulugoose** [comment]
Great any other for movies than specto?

**Comment by karnage11** [comment]
Salts , The Royal We

**Comment by lulugoose** [comment]
Great thanks so much. So new to this. Really appreciate all your help

**Comment by karnage11** [comment]
anytime , I am always on

**Comment by karnage11** [comment]
Mrknow is always updating the Specto addon

**Comment by ajjohnson10** [comment]
I have the 4.4.2 version. Once I download the link, it gives me the option to open the file. I can see my downloads but I can't do anything from this step.

**Comment by kazzamct** [comment]
I'm still struggling. I forgot to mention I'm trying to get specto on the Amazon box

Karyn

**Comment by kwood2287** [comment]
I am new to the fire stick so still learning the ropes. I had the same problem with every single link on every video I clicked on saying no stream available and the message re download salts appear. I've followed the instructions as above and now downloaded specto and it's now playing hoorah! How do I 1) remove Genesis from homescreen of kodi under videos? And 2) replace with the new specto add on image? Sorry if this doesn't make much sense thank you

**Comment by kazzamct** [comment]
Can you clue me in on how you managed to download specto on the fire stick?

Karyn

**Comment by karnage11** [comment]
from the fire stick on kodi , open kodi .. go to file Manager .. click on add source .. add http://filmkodi.com/repository , after you add that , go to add ones and click on install from Zip ..open that and click on repository.filmkodi.com.zip and install it , after that go to install from Repository and click on Filmkodi and go to video and you should see Specto

**Comment by camtheman88** [comment]
Hey everyone I'm struggling very much, long story short I had a problem with storage and nothing I did would free it up some started fresh! I re downloaded kodi 15.2! Then I downloaded Genesis 5.1.4! I went into system and found the update option which is not available! When I try to play movies it states ( you are using an outdated add on, to view file pup streams please use s.a.l.t.s. Or another up to date add on! Ps I don't have a computer and have to do everything threw the tv! Any advice would be really appreciated!!!

**Comment by camtheman88** [comment]
Shoot man it worked!!!! Thanks allot guys I just had trouble navigating my way around this thing is all! So hey! One last thing, well 2! My Genesis disappeared one day off my recent list so I have to open it manually which is a nusence! Any ideas on how to bring it back?
 Secondly I have a major memory problem! I wish we could post pics to make it easier! But basically all I have to delete is YouTube, I don't have anything installed, I just redoenloaded the app so it can't possibly be bunched up I don't think! But I prefer downloading movies in the am as the afternoon streaming can be an issue? But I no longer have the memory! Any clean up advise?

**Comment by camtheman88** [comment]
Should I reset to factory default maybe?

**Comment by karnage11** [comment]
Genesis 5.1.4 is out dated and no longer being updated

**Comment by karnage11** [comment]
you have to install Specto

**Comment by camtheman88** [comment]
I did! And it's working great! Any ideas on there cleanup and recents lists tho?

**Comment by Adam-po** [comment]
mrknow polecam super stronke Nasze-Kino.eu może taką wtyczkę....szło by wkleic

**Comment by karnage11** [comment]
just install a maintenance tool

**Comment by camtheman88** [comment]
What is Adam even saying exactly? and what should I search the web for to find the maintenance tool?

**Comment by kwood2287** [comment]
What is a maintenance tool or how do I install this also? 
Also on kodi homescreen.... Under videos.... It shows the thumbnails of the apps like Phoenix etc how do I add more so they appear here?

**Comment by karnage11** [comment]
install this addon 
[plugin.video.xbmchubmaintenance-2.1.3.zip](https://github.com/mrknow/filmkodi/files/133164/plugin.video.xbmchubmaintenance-2.1.3.zip)

**Comment by karnage11** [comment]
you guys can message me if you like , on Skype (Karnage11) ... if you need help , I wont be at the pc yet , give me till 4 or 5pm Eastern Standerd time

**Comment by kwood2287** [comment]
I was unable to download the maintenance tool link it said path Unknown I did as instructed :-/

**Comment by karnage11** [comment]
Message me on my chat room - http://chatwing.com/vamgothic69-797

**Comment by karnage11** [comment]
I am on there right now

**Comment by karnage11** [comment]
trying to create a chat room , so it is easy to help people

**Comment by karnage11** [comment]
http://chatwing.com/Karnage11 anyone need help join now I will be here for alittle

**Comment by kazzamct** [comment]
Where's instal from repository?

Karyn

**Comment by karnage11** [comment]
join the chat would be better to help you if you like

**Comment by Lcnation** [comment]
Hello and Thanks in advance
 Im also having the old version error. As I try to install the HTTP://filmkodi.com/repository fix the screen freezes when I try to install from zip file. What would cause this ?

**Comment by karnage11** [comment]
try updating thru your addons

**Comment by karnage11** [comment]
Join the chat if you want to chat and i can Help

**Comment by Lcnation** [comment]
Thank you, I had to installed from repository. It's working perfectly. I take it I'll need to configure ? I see there's no contents Movie home page.

**Comment by karnage11** [comment]
you should be on version 2016.02.15.01

**Comment by Lcnation** [comment]
I apologize, I am learning this as we speak 😃. Where do find my current version ?

**Comment by karnage11** [comment]
on your kodi , go to system , addons video and go to specto and check to see what version your on

**Comment by Lcnation** [comment]
Yes that's the version I have. And I can access the video files this way and it works great. Specto just isn't located on the shortcut I guess you would call it on the home page. Is there someway to configure this so it is ?

**Comment by karnage11** [comment]
ok go to system , appearance , under skin click settings , the add-on shortcut

**Comment by Lcnation** [comment]
Thank you very much for all your help

**Comment by karnage11** [comment]
your welcome

**Comment by karnage11** [comment]
Join Chat if anyone needs Help - http://chatwing.com/Karnage11

**Comment by Lcnation** [comment]
Sorry it's me again.
I'm now seeing that I have several add-ons that fail to update.Along with video errors. Here is just a few. Again thank you for your patience as this is all all very new to me
Zeus video error
HALOW Repository
1channel
Phoenix
Stream All The Sources
UK Turk Playlist

**Comment by karnage11** [comment]
Join the Chat , so we can chat

**Comment by karnage11** [comment]
if anyone needs Help Join the chat room please , makes it easier on me

**Comment by mystico29** [comment]
could you also fix the problems with list that happened today please it is code cosmetics

**Comment by camtheman88** [comment]
Well I can't get in the dam chat for some reason! Bummer! Ahh well! My newest issue in Spectro is when I go to movies I clicking some
Like adventure and such and they won't even load any movies on multiple pages! Odd

**Comment by karnage11** [comment]
you can join the chat now

**Comment by karnage11** [comment]
if anyone joins , give me about 10 mins

**Comment by camtheman88** [comment]
Sucks man it won't let
Me do it
On my phone and I'm computer less
Lol!

**Comment by karnage11** [comment]
try that 
http://chatwing.com/chatbox/4f433060-d4e9-11e5-b1fb-3b967afb188d

**Comment by karnage11** [comment]
trying to get things working

**Comment by Lcnation** [comment]
Yes I did, it's working perfectly. Thank you for everything

**Comment by karnage11** [comment]
i am in there now sorry

**Comment by camtheman88** [comment]
I have a second phone line I could give out for some help I guess if ya ever have some free time,
I don't care about putting it public it's just a text app and I can just change it if some moron gets ahold of it! For some reason my phone won't open the page at all I tried it a couple different ways and it just rings up a black page with a sand timer on it that never changes!

**Comment by camtheman88** [comment]
I got an interesting one! I found online how to install specto and noticed when done there's said Specto Genesis fork and I didn't know ya still needed Genesis so I deleted it dominate download it now? Wtf

**Comment by karnage11** [comment]
you dont need Genesis for it , Specto is Genesis just remade and Mrknow took over and renamed it

**Comment by camtheman88** [comment]
Ok I got mad deleated everything!!! Wiped it clean, downloaded kodi! Went to settings memory, it's using 75% of the memory inside Kodi app, go back to home page and manage apps, fire stick has 4.6 of 5.7 gb available???? Wtf

**Comment by mrknow** [comment]
I think this is  your hardware issue
