### ISSUE TITLE
Fix for outdated addon error

### ISSUE THREAD

**Issue by donr1961** [mrknow/filmkodi#96]
If you are getting this error:
"you are using an outdated addon. to view filepup streams please use salts or another up to date Kodi addon."
Go into sprectro settings and Disable movienight in sources and it will work.

Thanks to Matt on Facebook

**Comment by mrknow** [comment]
Yes, thx

Important bugs to fix in this week :
    watch1080p - cloudflare
    Pubfilm
    trakt.tv api v2

 Important bugs to fix in next week :
    realdebrid api v3

**Comment by mrknow** [comment]
Fixed in 2016.02.20.2
