### ISSUE TITLE
Only getting sources from 2 scrapers.

### ISSUE THREAD

**Issue by derekramirez** [mrknow/filmkodi#97]
Hello Mr. Know,

Thank you for updating our beloved Genesis! More power to you. However, with much power comes great responsibility! Just kidding you don't owe anyone anything. My issue:  Specto was working perfecto a few days ago. Yesterday, I noticed Pubfilm scraper links showing at the top which all have been working flawlessly. Now, I only see links from 2 scrapers (Primewire and Watchfree). Sometimes Movienight which we know gives us the outdated error to use S.A.L.T.S. Is there an issue with the scrapers? Will there be a new update coming? Probably not today? It's Valentines day! Going out with the significant other to spend $40 on a movie lol. Anyway, please let me (us) know if there will be any fixes coming in the future for this fantastic Add-on. 

Best regards,
Durex

**Comment by mrknow** [comment]
Today i will push new update. 
This update  will fix: 
- openload resolver
- iwatchonline


Important bugs to fix in this week :
- watch1080p - cloudflare
- Pubfilm
- trakt.tv api v2
Important bugs to fix in next week :
- realdebrid api v3

**Comment by karnage11** [comment]
Hey when is the update ? Thanks Mrknow

**Comment by derekramirez** [comment]
Nice. Thank you Mr. Know!
