### ISSUE TITLE
Add the following super fast HD sources to Specto

### ISSUE THREAD

**Issue by bryan3r3** [mrknow/filmkodi#98]
Please add the following super fast HD sources to Specto:

http://123movies.to
http://sezonlukdizi.com
http://www.izlemeyedeger.com
http://9movies.to
http://xmovies8.tv

**Comment by karnage11** [comment]
that would be awesome

**Comment by Delwashy** [comment]
I have Specto version 2016.02.06.1  running on my Android box using Helix 14.2 iv'e just got an update for specto version 2016.02.15.1  it will not update as it is saying Add-on is incompatibleor has been marked broken in repository  dependencies not met.Please contact Add-on author. My Specto is still working but i will not be able to update it any feed back or advice would be greatly appreciated is there a new plugin i can use or is there a problem as it seems i've missed an update as on my other device it's version 2016.02.07.3 any help please

**Comment by bryan3r3** [comment]
I've updated the list, I am 100% sure that this addon will be #1 to look for and will be in every single build if that list of sources get added.

**Comment by mrknow** [comment]
OK, I will try to add this as soon as possible, Give me max 2 weeks.

**Comment by karnage11** [comment]
Mrknow , you think you can see if the updating episodes , the library is working ?

**Comment by mrknow** [comment]
all addet to specto
